import { createHash } from "node:crypto";
import {
  campaignContentApplyRequestSchema, campaignContentApplyResponseSchema, campaignContentDraftViewSchema,
  campaignContentGenerationRequestSchema, campaignGeneratedFoundationSchema, campaignGeneratedPlanningSchema,
  campaignMaterialPublishRequestSchema, campaignMaterialPublishResponseSchema, campaignPublishedMaterialsSchema, generatedCampaignContentProviderSchema,
  resourceIdSchema, stagedCampaignContentGenerationSchema, type GeneratedCampaignContentProvider, type PrivateGenerationDraft,
} from "@velvet/contracts";
import type { FastifyPluginAsync } from "fastify";
import { z } from "zod";
import { completeWithProvider } from "../../../provider/index.js";
import { defaultHarnessSettings } from "../../../defaults.js";
import { getPromptPreset } from "../../../presets.js";
import { readRpgFeatureFlags } from "../../../features.js";
import { sendApiProblem } from "../../../http/problem.js";
import { AdventureTurnAuthorizationError, AdventureTurnConflictError, AdventureTurnStaleError, AdventureTurnUnavailableError, getProviderSettings, type Repository } from "../../../repo/index.js";
import type { ProviderSettings } from "../../../types.js";

const OWNER="local-owner",JSON_TYPE=/^application\/json(?:\s*;.*)?$/i;
const enabled=()=>{const flags=readRpgFeatureFlags();return flags.campaign&&flags.mechanics&&flags.combat;};
const digest=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const sleep=(ms:number)=>new Promise((resolve)=>setTimeout(resolve,ms));
type Repo=Pick<Repository,"createGenerationDraft"|"getGenerationDraft"|"getGenerationDraftByIdempotencyKey"|"applyCampaignContentGenerationDraftAtomically"|"getCampaign"|"getCampaignAdministration"|"beginCampaignGenerationCall"|"getCampaignGenerationCall"|"finishCampaignGenerationCall"|"getCampaignGenerationContext"|"recordCampaignGenerationCandidate"|"getCampaignGeneratedFoundation"|"getCampaignGeneratedPlanning"|"getCampaignPublishedMaterials"|"publishCampaignMaterial">;
export interface CampaignContentGenerationOptions {generationDraftRepositoryAccessor:()=>Repo;generateCampaignContent?:(prompt:unknown,signal:AbortSignal)=>Promise<unknown>;}
function privateDraft(value:ReturnType<Repo["getGenerationDraft"]>):PrivateGenerationDraft{if(!value||!("stagedContent" in value))throw new AdventureTurnUnavailableError();return value;}
function view(draft:PrivateGenerationDraft){const staged=stagedCampaignContentGenerationSchema.parse(draft.stagedContent);const {kind:_kind,requestDigest:_digest,baseContentRevision:_base,dependencyDigests:_dependencies,npcs,factions,...preview}=staged;return campaignContentDraftViewSchema.parse({draft:{draftId:draft.draftId,campaignId:draft.campaignId,kind:"campaign-content",state:draft.state,revision:draft.revision,createdAt:draft.createdAt,updatedAt:draft.updatedAt},preview:{...preview,factions:factions.map(({gmNotes:_private,...item})=>item),npcs:npcs.map(({privateGoals:_private,...item})=>item),npcStats:{body:10,mind:10,presence:10,source:"generated-deterministic-baseline"}},validationIssues:draft.validation.issues.map((issue)=>issue.message)});}

const sectionFields:Record<string,string[]>={outline:["outlines"],arcs:["arcs"],locations:["locations","connections"],factions:["factions"],npcs:["npcs"],quests:["quests"],encounters:["encounters"],clues:["clues"],story:["storyNodes","storyRelationships"],handouts:["handouts"],"scene-prompts":["scenePrompts"]};
function validateContent(content:GeneratedCampaignContentProvider,sections:string[],dependencyKeys:Set<string>):GeneratedCampaignContentProvider{
  const enabledFields=new Set(sections.flatMap((section)=>sectionFields[section]??[]));
  for(const fields of Object.values(sectionFields))for(const field of fields)if(!enabledFields.has(field)&&(content as any)[field].length)throw new Error(`provider returned unrequested ${field}`);
  const all=[...content.outlines,...content.arcs,...content.locations,...content.connections,...content.factions,...content.npcs,...content.quests,...content.encounters,...content.clues,...content.storyNodes,...content.storyRelationships,...content.handouts,...content.scenePrompts];
  if(!all.length)throw new Error("provider returned no candidates");const keys=new Set(all.map(({key})=>key));if(keys.size!==all.length||[...keys].some((key)=>dependencyKeys.has(key)))throw new Error("generated keys must be unique and additive");
  const available=(key:string)=>keys.has(key)||dependencyKeys.has(key),references:string[]=[];
  for(const value of content.outlines)if(value.startLocationKey)references.push(value.startLocationKey);
  for(const value of content.locations)references.push(...value.factionKeys);
  for(const value of content.connections)references.push(value.fromLocationKey,value.toLocationKey);
  for(const value of content.npcs)references.push(...value.factionKeys,...(value.locationKey?[value.locationKey]:[]));
  for(const value of content.quests)references.push(...value.locationKeys,...(value.arcKey?[value.arcKey]:[]));
  for(const value of content.encounters)references.push(...value.participantNpcKeys,...(value.locationKey?[value.locationKey]:[]));
  for(const value of content.clues)references.push(...(value.locationKey?[value.locationKey]:[]),...(value.revealsStoryNodeKey?[value.revealsStoryNodeKey]:[]));
  for(const value of content.storyRelationships)references.push(value.fromStoryNodeKey,value.toStoryNodeKey);
  for(const value of content.scenePrompts)references.push(...value.npcKeys,...(value.locationKey?[value.locationKey]:[]));
  if(references.some((key)=>!available(key)))throw new Error("generated reference is unavailable");return content;
}
type GenerationResult={content:GeneratedCampaignContentProvider;usage:{promptTokens:number;completionTokens:number;totalTokens:number}|null;responseModel:string|null};
async function generate(input:ReturnType<typeof campaignContentGenerationRequestSchema.parse>,safeCanon:unknown,options:CampaignContentGenerationOptions,signal:AbortSignal,providerSettings:ProviderSettings):Promise<GenerationResult>{
  const safe={brief:input.brief,tone:input.tone,exclusions:input.exclusions,sections:input.sections,expandArtifactKeys:input.expandArtifactKeys,revisionFeedback:input.revisionFeedback,acceptedPublicCanon:safeCanon,instructions:"Return one sparse strict JSON candidate. Populate only requested section arrays. Stable lowercase-hyphen keys must be new. References may target another candidate key or an accepted key supplied here. Do not emit credentials, principals, permissions, statistics, powers, effects, prompts, player characters, or private goals outside the dedicated privateGoals/gmNotes fields."};
  if(options.generateCampaignContent){const raw=await options.generateCampaignContent(safe,signal);if(raw&&typeof raw==="object"&&"content" in raw){const envelope=raw as any,usage=envelope.usage;if(usage!==null&&(!usage||![usage.promptTokens,usage.completionTokens,usage.totalTokens].every((value)=>Number.isInteger(value)&&value>=0)||usage.totalTokens!==usage.promptTokens+usage.completionTokens))throw new Error("invalid provider usage");return {content:generatedCampaignContentProviderSchema.parse(envelope.content),usage,responseModel:typeof envelope.responseModel==="string"&&envelope.responseModel.trim()?envelope.responseModel:null};}return {content:generatedCampaignContentProviderSchema.parse(raw),usage:null,responseModel:providerSettings.model.trim()||"unconfigured"};}
  const result=await completeWithProvider({provider:providerSettings,harness:await Promise.resolve(defaultHarnessSettings()),preset:getPromptPreset("default"),toolChoice:"none",jsonSchema:{name:"campaign_content_candidate_v3",description:"Sparse additive campaign section candidates",schema:z.toJSONSchema(generatedCampaignContentProviderSchema) as any},signal,messages:[{role:"system",content:"Create bounded additive RPG campaign section candidates. Return JSON only and obey the requested sparse schema."},{role:"user",content:JSON.stringify(safe)}]});
  if(result.message.toolCalls?.length||typeof result.message.content!=="string")throw new Error("invalid provider response");return {content:generatedCampaignContentProviderSchema.parse(JSON.parse(result.message.content)),usage:result.usage,responseModel:result.model.responseModel};
}
function problem(request:any,reply:any,error:unknown,commitMayHaveOccurred=false){if(error instanceof AdventureTurnUnavailableError||error instanceof AdventureTurnAuthorizationError)return sendApiProblem(request,reply,404,"RPG_GENERATION_DRAFT_NOT_FOUND","Campaign content draft not found");if(error instanceof AdventureTurnConflictError||error instanceof AdventureTurnStaleError)return sendApiProblem(request,reply,409,"RPG_GENERATION_DRAFT_CONFLICT","Campaign content draft conflicts with durable state");request.log.error({operation:"campaign-content-generation"},"campaign content generation failed");return sendApiProblem(request,reply,503,"RPG_GENERATION_UNAVAILABLE",commitMayHaveOccurred?"Campaign content outcome could not be confirmed; reconcile authoritative state and do not automatically retry":"Campaign content generation is unavailable; no content was applied");}

export const campaignContentGenerationHttpRoutes:FastifyPluginAsync<CampaignContentGenerationOptions>=async(app,options)=>{
  const gate=(request:any,reply:any,body=true)=>{reply.header("cache-control","no-store");if(!enabled())return sendApiProblem(request,reply,404,"RPG_ROUTE_NOT_FOUND","RPG route not found");if((request.raw.url??request.url).includes("?"))return sendApiProblem(request,reply,400,"RPG_INVALID_REQUEST","Campaign content generation does not accept query parameters");if(body&&(typeof request.headers["content-type"]!=="string"||!JSON_TYPE.test(request.headers["content-type"])))return sendApiProblem(request,reply,415,"RPG_UNSUPPORTED_MEDIA_TYPE","Campaign content generation requires application/json");};
  app.post("/campaign-content-drafts",{onRequest:async(r,p)=>gate(r,p)},async(request,reply)=>{const parsed=campaignContentGenerationRequestSchema.safeParse(request.body);if(!parsed.success)return sendApiProblem(request,reply,400,"RPG_INVALID_REQUEST","Campaign content generation request is invalid");
    const logical={...parsed.data,retryFailedAttempt:undefined},requestDigest=digest(logical);let repo:Repo|undefined,owned:{attempt:number;startedAt:number}|null=null;
    try{repo=options.generationDraftRepositoryAccessor();const existing=repo.getGenerationDraftByIdempotencyKey(OWNER,parsed.data.campaignId,parsed.data.idempotencyKey);if(existing){const draft=privateDraft(existing);if(stagedCampaignContentGenerationSchema.parse(draft.stagedContent).requestDigest!==requestDigest)throw new AdventureTurnConflictError();return reply.code(201).send(view(draft));}
      const campaign=repo.getCampaign(OWNER,parsed.data.campaignId),administration=repo.getCampaignAdministration(OWNER,parsed.data.campaignId),context=repo.getCampaignGenerationContext(OWNER,parsed.data.campaignId,parsed.data.expandArtifactKeys);if(!campaign||!administration||!context)throw new AdventureTurnUnavailableError();
      const provider=await getProviderSettings(),jobId=`campaign-generation-${digest(`${parsed.data.campaignId}:${parsed.data.idempotencyKey}`).slice(0,40)}`,startedAt=Date.now();const call=repo.beginCampaignGenerationCall(parsed.data.campaignId,parsed.data.idempotencyKey,requestDigest,{provider:provider.providerType||"openai-compatible",model:provider.model.trim()||"unconfigured",operation:"campaign-generation",stage:"candidate",promptVersion:"campaign-content-v3",schemaVersion:"campaign-content-v3",jobId},parsed.data.retryFailedAttempt?.failedAttempt??null);
      if(call.state==="succeeded"&&call.draftId)return reply.code(201).send(view(privateDraft(repo.getGenerationDraft(OWNER,call.draftId))));
      if(!call.acquired){for(let index=0;index<40&&call.state==="running";index++){await sleep(25);const winner=repo.getCampaignGenerationCall(parsed.data.campaignId,parsed.data.idempotencyKey,requestDigest);if(winner?.state==="succeeded"&&winner.draftId)return reply.code(201).send(view(privateDraft(repo.getGenerationDraft(OWNER,winner.draftId))));if(winner?.state==="failed")throw new AdventureTurnConflictError("the acknowledged provider attempt failed");}throw new AdventureTurnConflictError("generation call is still in progress");}
      owned={attempt:call.attempt,startedAt};const safeCanon=context.artifacts.filter((item)=>item.visibility==="public").map((item)=>({key:item.key,kind:item.kind,content:item.canonical}));const abort=new AbortController();request.raw.once("aborted",()=>abort.abort());const generated=await generate(parsed.data,safeCanon,options,abort.signal,provider),content=validateContent(generated.content,parsed.data.sections,new Set(context.artifacts.map((item)=>item.key)));
      const draft=repo.createGenerationDraft(OWNER,{campaignId:parsed.data.campaignId,timelineId:campaign.activeTimelineId,kind:"content-pack",stagedContent:{kind:"campaign-content",requestDigest,baseContentRevision:context.revision,dependencyDigests:Object.fromEntries(context.artifacts.map((item)=>[item.key,item.digest])),...content},validation:{valid:true,issues:[],validatedAt:new Date().toISOString()},expectedCampaignRevision:administration.revision,idempotencyKey:parsed.data.idempotencyKey});repo.recordCampaignGenerationCandidate(draft.draftId,content,context.artifacts);
      const usage=generated.usage,pricing=provider.pricing,estimatedCostUsd=usage&&pricing.promptPerMillion!==null&&pricing.completionPerMillion!==null?(usage.promptTokens*pricing.promptPerMillion+usage.completionTokens*pricing.completionPerMillion)/1_000_000:null;repo.finishCampaignGenerationCall(parsed.data.campaignId,parsed.data.idempotencyKey,call.attempt,draft.draftId,"ok",{responseModel:generated.responseModel,promptTokens:usage?.promptTokens??null,completionTokens:usage?.completionTokens??null,totalTokens:usage?.totalTokens??null,latencyMs:Date.now()-startedAt,estimatedCostUsd});owned=null;return reply.code(201).send(view(draft));
    }catch(error){if(repo&&owned){try{repo.finishCampaignGenerationCall(parsed.data.campaignId,parsed.data.idempotencyKey,owned.attempt,null,"generation-failed",{responseModel:null,promptTokens:null,completionTokens:null,totalTokens:null,latencyMs:Date.now()-owned.startedAt,estimatedCostUsd:null});}catch{}}return problem(request,reply,error);}});
  app.get("/campaign-content-drafts/:draftId",{onRequest:async(r,p)=>gate(r,p,false)},async(request:any,reply)=>{const id=resourceIdSchema.safeParse(request.params.draftId);if(!id.success)return sendApiProblem(request,reply,404,"RPG_GENERATION_DRAFT_NOT_FOUND","Campaign content draft not found");try{return reply.send(view(privateDraft(options.generationDraftRepositoryAccessor().getGenerationDraft(OWNER,id.data))));}catch(error){return problem(request,reply,error);}});
  app.get("/campaigns/:campaignId/generated-foundation",{onRequest:async(r,p)=>gate(r,p,false)},async(request:any,reply)=>{const id=resourceIdSchema.safeParse(request.params.campaignId);if(!id.success)return sendApiProblem(request,reply,404,"RPG_CAMPAIGN_NOT_FOUND","Campaign not found");try{const result=options.generationDraftRepositoryAccessor().getCampaignGeneratedFoundation(OWNER,id.data);if(!result)return sendApiProblem(request,reply,404,"RPG_CAMPAIGN_NOT_FOUND","Campaign not found");const response=campaignGeneratedFoundationSchema.parse(result);if(response.campaignId!==id.data)throw new Error("campaign foundation binding is invalid");return reply.send(response);}catch{request.log.error({operation:"campaign-generated-foundation"},"campaign generated foundation read failed");return sendApiProblem(request,reply,500,"RPG_INTERNAL_ERROR","Campaign generated foundation could not be loaded");}});
  app.get("/campaigns/:campaignId/generated-planning",{onRequest:async(r,p)=>gate(r,p,false)},async(request:any,reply)=>{const id=resourceIdSchema.safeParse(request.params.campaignId);if(!id.success)return sendApiProblem(request,reply,404,"RPG_CAMPAIGN_NOT_FOUND","Campaign not found");if(request.body!==undefined)return sendApiProblem(request,reply,400,"RPG_INVALID_REQUEST","Campaign generated planning does not accept a request body");try{const result=options.generationDraftRepositoryAccessor().getCampaignGeneratedPlanning(OWNER,id.data);if(!result)return sendApiProblem(request,reply,404,"RPG_CAMPAIGN_NOT_FOUND","Campaign not found");const response=campaignGeneratedPlanningSchema.parse(result);if(response.campaignId!==id.data)throw new Error("campaign planning binding is invalid");return reply.send(response);}catch{request.log.error({operation:"campaign-generated-planning"},"campaign generated planning read failed");return sendApiProblem(request,reply,500,"RPG_INTERNAL_ERROR","Campaign generated planning could not be loaded");}});
  app.get("/campaigns/:campaignId/published-materials",{onRequest:async(r,p)=>gate(r,p,false)},async(request:any,reply)=>{const id=resourceIdSchema.safeParse(request.params.campaignId);if(!id.success)return sendApiProblem(request,reply,404,"RPG_CAMPAIGN_NOT_FOUND","Campaign not found");if(request.body!==undefined)return sendApiProblem(request,reply,400,"RPG_INVALID_REQUEST","Campaign published materials do not accept a request body");try{const result=options.generationDraftRepositoryAccessor().getCampaignPublishedMaterials(OWNER,id.data);if(!result)return sendApiProblem(request,reply,404,"RPG_CAMPAIGN_NOT_FOUND","Campaign not found");const response=campaignPublishedMaterialsSchema.parse(result);if(response.campaignId!==id.data)throw new Error("published materials binding is invalid");return reply.send(response);}catch{request.log.error({operation:"campaign-published-materials"},"campaign published materials read failed");return sendApiProblem(request,reply,500,"RPG_INTERNAL_ERROR","Campaign published materials could not be loaded");}});
  app.post("/campaigns/:campaignId/material-publications",{onRequest:async(r,p)=>gate(r,p)},async(request:any,reply)=>{const id=resourceIdSchema.safeParse(request.params.campaignId),body=campaignMaterialPublishRequestSchema.safeParse(request.body);if(!id.success||!body.success)return sendApiProblem(request,reply,400,"RPG_INVALID_REQUEST","Campaign material publication request is invalid");try{const response=campaignMaterialPublishResponseSchema.parse(options.generationDraftRepositoryAccessor().publishCampaignMaterial(OWNER,id.data,body.data));if(response.material.artifactKey!==body.data.artifactKey||response.receipt.idempotencyKey!==body.data.idempotencyKey||response.receipt.revisionBefore!==body.data.expectedRevision)throw new Error("campaign publication binding is invalid");return reply.send(response);}catch(error){return problem(request,reply,error,true);}});
  app.post("/campaign-content-drafts/:draftId/apply",{onRequest:async(r,p)=>gate(r,p)},async(request:any,reply)=>{const id=resourceIdSchema.safeParse(request.params.draftId),body=campaignContentApplyRequestSchema.safeParse(request.body);if(!id.success||!body.success)return sendApiProblem(request,reply,400,"RPG_INVALID_REQUEST","Campaign content apply request is invalid");try{const repo=options.generationDraftRepositoryAccessor(),prior=privateDraft(repo.getGenerationDraft(OWNER,id.data)),draft=repo.applyCampaignContentGenerationDraftAtomically(OWNER,{draftId:id.data,expectedDraftRevision:body.data.expectedRevision,expectedCampaignRevision:prior.campaignRevision,idempotencyKey:body.data.idempotencyKey,selectedArtifactKeys:body.data.selectedArtifactKeys}),receipt=draft.applyReceipt,result=receipt?.result as {scope?:unknown;selectedArtifactKeys?:unknown}|undefined;if(!receipt||draft.draftId!==id.data||draft.campaignId!==prior.campaignId||draft.state!=="applied"||receipt.draftId!==id.data||result?.scope!=="campaign-content"||JSON.stringify(result.selectedArtifactKeys)!==JSON.stringify(body.data.selectedArtifactKeys))throw new Error("campaign apply binding is invalid");return reply.send(campaignContentApplyResponseSchema.parse({draft:view(draft).draft,application:{scope:"campaign-content",campaignDomainMutated:true,appliedAt:receipt.appliedAt},receipts:[{receiptId:receipt.receiptId,scope:"campaign-content",appliedAt:receipt.appliedAt}]}));}catch(error){return problem(request,reply,error,true);}});
};
