import { createHash } from "node:crypto";
import { campaignContentApplyRequestSchema, campaignContentApplyResponseSchema, campaignContentDraftViewSchema, campaignContentGenerationRequestSchema, generatedCampaignContentProviderSchema, resourceIdSchema, stagedCampaignContentGenerationSchema, type PrivateGenerationDraft } from "@velvet/contracts";
import type { FastifyPluginAsync } from "fastify";
import { completeWithProvider } from "../../../provider/index.js";
import { defaultHarnessSettings, defaultProviderSettings } from "../../../defaults.js";
import { getPromptPreset } from "../../../presets.js";
import { readRpgFeatureFlags } from "../../../features.js";
import { sendApiProblem } from "../../../http/problem.js";
import { AdventureTurnAuthorizationError, AdventureTurnConflictError, AdventureTurnStaleError, AdventureTurnUnavailableError, type AdventureTurnRepository } from "../../../repo/index.js";

const OWNER = "local-owner", JSON_TYPE = /^application\/json(?:\s*;.*)?$/i;
const enabled = () => { const flags = readRpgFeatureFlags(); return flags.campaign && flags.mechanics && flags.combat; };
const digest = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");
type Repo = Pick<AdventureTurnRepository, "createGenerationDraft" | "getGenerationDraft" | "getGenerationDraftByIdempotencyKey" | "applyCampaignContentGenerationDraftAtomically"> & { getCampaign(actor: string, campaign: string): { activeTimelineId: string } | null; getCampaignAdministration(actor: string, campaign: string): { revision: number } | null };
export interface CampaignContentGenerationOptions { generationDraftRepositoryAccessor: () => Repo; generateCampaignContent?: (prompt: unknown, signal: AbortSignal) => Promise<unknown>; }
function privateDraft(value: ReturnType<Repo["getGenerationDraft"]>): PrivateGenerationDraft { if (!value || !("stagedContent" in value)) throw new AdventureTurnUnavailableError(); return value; }
function view(draft: PrivateGenerationDraft) { const staged = stagedCampaignContentGenerationSchema.parse(draft.stagedContent); const { kind: _kind, requestDigest: _requestDigest, npcs, ...preview } = staged; return campaignContentDraftViewSchema.parse({ draft: { draftId: draft.draftId, campaignId: draft.campaignId, kind: "campaign-content", state: draft.state, revision: draft.revision, createdAt: draft.createdAt, updatedAt: draft.updatedAt }, preview: { ...preview, npcs: npcs.map(({ name, archetype }) => ({ name, archetype })), npcStats: { body: 10, mind: 10, presence: 10, source: "generated-deterministic-baseline" } }, validationIssues: draft.validation.issues }); }
async function generate(input: ReturnType<typeof campaignContentGenerationRequestSchema.parse>, options: CampaignContentGenerationOptions, signal: AbortSignal) {
  const safe = { brief: input.brief, tone: input.tone, exclusions: input.exclusions, instructions: "Return JSON only: opening, premise, locations [{name,description}], factions [{name,description}], quests [{title,description}], npcs [{name,archetype,goals}]. Do not include secrets, relationships, statistics, powers, effects, IDs, permissions, player characters, or hidden state." };
  if (options.generateCampaignContent) return generatedCampaignContentProviderSchema.parse(await options.generateCampaignContent(safe, signal));
  const result = await completeWithProvider({ provider: await Promise.resolve(defaultProviderSettings()), harness: await Promise.resolve(defaultHarnessSettings()), preset: getPromptPreset("default"), toolChoice: "none", signal, messages: [{ role: "system", content: "Create bounded RPG campaign content. Follow the JSON instruction exactly." }, { role: "user", content: JSON.stringify(safe) }] });
  if (result.message.toolCalls?.length || typeof result.message.content !== "string") throw new Error("invalid provider response");
  return generatedCampaignContentProviderSchema.parse(JSON.parse(result.message.content));
}
function problem(request: any, reply: any, error: unknown) { if (error instanceof AdventureTurnUnavailableError || error instanceof AdventureTurnAuthorizationError) return sendApiProblem(request, reply, 404, "RPG_GENERATION_DRAFT_NOT_FOUND", "Campaign content draft not found"); if (error instanceof AdventureTurnConflictError || error instanceof AdventureTurnStaleError) return sendApiProblem(request, reply, 409, "RPG_GENERATION_DRAFT_CONFLICT", "Campaign content draft conflicts with durable state"); request.log.error({ operation: "campaign-content-generation" }, "campaign content generation failed"); return sendApiProblem(request, reply, 503, "RPG_GENERATION_UNAVAILABLE", "Campaign content generation is unavailable; no content was applied"); }
/** Provider work is bounded and outside SQLite; application is one repository transaction. */
export const campaignContentGenerationHttpRoutes: FastifyPluginAsync<CampaignContentGenerationOptions> = async (app, options) => {
  const guard = (request: any, reply: any) => { reply.header("cache-control", "no-store"); if (!enabled()) return sendApiProblem(request, reply, 404, "RPG_ROUTE_NOT_FOUND", "RPG route not found"); if ((request.raw.url ?? request.url).includes("?")) return sendApiProblem(request, reply, 400, "RPG_INVALID_REQUEST", "Campaign content generation does not accept query parameters"); if (typeof request.headers["content-type"] !== "string" || !JSON_TYPE.test(request.headers["content-type"])) return sendApiProblem(request, reply, 415, "RPG_UNSUPPORTED_MEDIA_TYPE", "Campaign content generation requires application/json"); };
  app.post("/campaign-content-drafts", { onRequest: async (r, p) => guard(r, p) }, async (request, reply) => { const parsed = campaignContentGenerationRequestSchema.safeParse(request.body); if (!parsed.success) return sendApiProblem(request, reply, 400, "RPG_INVALID_REQUEST", "Campaign content generation request is invalid"); try { const repo = options.generationDraftRepositoryAccessor(), existing = repo.getGenerationDraftByIdempotencyKey(OWNER, parsed.data.campaignId, parsed.data.idempotencyKey); if (existing) { const draft = privateDraft(existing); if (stagedCampaignContentGenerationSchema.parse(draft.stagedContent).requestDigest !== digest(parsed.data)) throw new AdventureTurnConflictError(); return reply.code(201).send(view(draft)); } const campaign = repo.getCampaign(OWNER, parsed.data.campaignId), administration = repo.getCampaignAdministration(OWNER, parsed.data.campaignId); if (!campaign || !administration) throw new AdventureTurnUnavailableError(); const content = await generate(parsed.data, options, new AbortController().signal); const draft = repo.createGenerationDraft(OWNER, { campaignId: parsed.data.campaignId, timelineId: campaign.activeTimelineId, /* v35's immutable CHECK has no campaign-content value; content-pack is its compatible durable envelope. */ kind: "content-pack", stagedContent: { kind: "campaign-content", requestDigest: digest(parsed.data), ...content }, validation: { valid: true, issues: [], validatedAt: new Date().toISOString() }, expectedCampaignRevision: administration.revision, idempotencyKey: parsed.data.idempotencyKey }); return reply.code(201).send(view(draft)); } catch (error) { return problem(request, reply, error); } });
  app.get("/campaign-content-drafts/:draftId", async (request: any, reply) => { if (!enabled()) return sendApiProblem(request, reply, 404, "RPG_ROUTE_NOT_FOUND", "RPG route not found"); const id = resourceIdSchema.safeParse(request.params.draftId); if (!id.success) return sendApiProblem(request, reply, 404, "RPG_GENERATION_DRAFT_NOT_FOUND", "Campaign content draft not found"); try { return reply.send(view(privateDraft(options.generationDraftRepositoryAccessor().getGenerationDraft(OWNER, id.data)))); } catch (error) { return problem(request, reply, error); } });
  app.post("/campaign-content-drafts/:draftId/apply", { onRequest: async (r, p) => guard(r, p) }, async (request: any, reply) => { const id = resourceIdSchema.safeParse(request.params.draftId), body = campaignContentApplyRequestSchema.safeParse(request.body); if (!id.success || !body.success) return sendApiProblem(request, reply, 400, "RPG_INVALID_REQUEST", "Campaign content apply request is invalid"); try { const draft = options.generationDraftRepositoryAccessor().applyCampaignContentGenerationDraftAtomically(OWNER, { draftId: id.data, expectedDraftRevision: body.data.expectedRevision, expectedCampaignRevision: privateDraft(options.generationDraftRepositoryAccessor().getGenerationDraft(OWNER, id.data)).campaignRevision, idempotencyKey: body.data.idempotencyKey }); if (!draft.applyReceipt) throw new Error("missing receipt"); return reply.send(campaignContentApplyResponseSchema.parse({ draft: view(draft).draft, application: { scope: "campaign-content", campaignDomainMutated: true, appliedAt: draft.applyReceipt.appliedAt }, receipts: [{ receiptId: draft.applyReceipt.receiptId, scope: "campaign-content", appliedAt: draft.applyReceipt.appliedAt }] })); } catch (error) { return problem(request, reply, error); } });
};
