import { directCombatPowerCandidatesResponseSchema,directCombatPowerCommandRequestSchema,directCombatPowerCommandResponseSchema,idempotencyKeySchema,resourceIdSchema } from "@velvet/contracts";
import type { FastifyPluginAsync,FastifyRequest } from "fastify";
import { readRpgFeatureFlags } from "../../../features.js";
import { sendApiProblem } from "../../../http/problem.js";
import { EncounterAuthorizationError,EncounterConflictError,EncounterStaleError,EncounterTurnError,type EncounterRepository } from "../../../repo/index.js";
const OWNER="local-owner",json=/^application\/json(?:\s*;.*)?$/i;
type Repository=Pick<EncounterRepository,"getCombatPowerLegalActions"|"useCombatPower"|"getCombatPowerResultByKey">;
export interface CombatPowersHttpOptions{combatPowerRepositoryAccessor:()=>Repository;}
const enabled=()=>{const flags=readRpgFeatureFlags();return flags.campaign&&flags.mechanics&&flags.combat;};
const missing=(request:FastifyRequest,reply:Parameters<typeof sendApiProblem>[1])=>sendApiProblem(request,reply,404,"RPG_COMBAT_POWER_NOT_FOUND","Combat power not found");
const clean=(request:FastifyRequest)=>!(request.raw.url??request.url).includes("?")&&Object.keys(request.query as object).length===0;
export const combatPowersHttpRoutes:FastifyPluginAsync<CombatPowersHttpOptions>=async(app,options)=>{
  app.get<{Params:{combatId:string};Querystring:Record<string,unknown>}>("/combats/:combatId/power-actions",{exposeHeadRoute:false},async(request,reply)=>{reply.header("cache-control","no-store");if(!enabled())return sendApiProblem(request,reply,404,"RPG_ROUTE_NOT_FOUND","RPG route not found");const combatId=resourceIdSchema.safeParse(request.params.combatId);if(!combatId.success)return missing(request,reply);if(!clean(request))return sendApiProblem(request,reply,400,"RPG_INVALID_REQUEST","Combat power actions do not accept query parameters");try{const candidates=options.combatPowerRepositoryAccessor().getCombatPowerLegalActions(OWNER,combatId.data).map(action=>({legalActionId:action.legalActionId,powerName:action.definition.name,targetCombatantId:action.targetCombatantId,target:"Legal target",powerRef:action.powerRef,cost:action.cost?.kind==="slot"?`Level ${action.cost.id.slice(5)} spell slot`:action.cost?.kind==="ability-use"?"Power use":null,revisions:action.revisions}));return reply.send(directCombatPowerCandidatesResponseSchema.parse({candidates}));}catch(error){if(error instanceof EncounterAuthorizationError)return missing(request,reply);return sendApiProblem(request,reply,500,"RPG_INTERNAL_ERROR","Combat power actions could not be loaded");}});
  app.get<{Params:{combatId:string;idempotencyKey:string};Querystring:Record<string,unknown>}>("/combats/:combatId/power-actions/results/:idempotencyKey",{exposeHeadRoute:false},async(request,reply)=>{reply.header("cache-control","no-store");const combatId=resourceIdSchema.safeParse(request.params.combatId),key=idempotencyKeySchema.safeParse(request.params.idempotencyKey);if(!enabled())return sendApiProblem(request,reply,404,"RPG_ROUTE_NOT_FOUND","RPG route not found");if(!combatId.success||!key.success)return missing(request,reply);if(!clean(request))return sendApiProblem(request,reply,400,"RPG_INVALID_REQUEST","Combat power result does not accept query parameters");const value=options.combatPowerRepositoryAccessor().getCombatPowerResultByKey(OWNER,combatId.data,key.data);if(!value)return missing(request,reply);const {powerRef:_,targetCombatantId:__,...requestBody}=value.request;return reply.send(directCombatPowerCommandResponseSchema.parse({request:requestBody,result:value.result}));});
  app.post<{Params:{combatId:string};Querystring:Record<string,unknown>;Body:unknown}>("/combats/:combatId/power-actions/commands",{errorHandler:(_e,request,reply)=>sendApiProblem(request,reply,400,"RPG_INVALID_REQUEST","Combat power command is invalid")},async(request,reply)=>{reply.header("cache-control","no-store");if(!enabled())return sendApiProblem(request,reply,404,"RPG_ROUTE_NOT_FOUND","RPG route not found");const combatId=resourceIdSchema.safeParse(request.params.combatId),body=directCombatPowerCommandRequestSchema.safeParse(request.body);if(!combatId.success)return missing(request,reply);if(!clean(request)||typeof request.headers["content-type"]!=="string"||!json.test(request.headers["content-type"]))return sendApiProblem(request,reply,400,"RPG_INVALID_REQUEST","Combat power command requires JSON without query parameters");if(!body.success)return sendApiProblem(request,reply,400,"RPG_INVALID_REQUEST","Combat power command is invalid");try{const repository=options.combatPowerRepositoryAccessor(),prior=repository.getCombatPowerResultByKey(OWNER,combatId.data,body.data.idempotencyKey);if(prior){const {powerRef:_,targetCombatantId:__,...priorRequest}=prior.request;if(JSON.stringify(priorRequest)!==JSON.stringify(body.data))throw new EncounterConflictError("idempotency key was reused");return reply.send(directCombatPowerCommandResponseSchema.parse({request:body.data,result:prior.result}));}const action=repository.getCombatPowerLegalActions(OWNER,combatId.data).find(value=>value.legalActionId===body.data.legalActionId);if(!action)return missing(request,reply);const result=repository.useCombatPower(OWNER,{legalActionId:body.data.legalActionId,powerRef:action.powerRef,targetCombatantId:action.targetCombatantId,expectedCombatRevision:body.data.expectedCombatRevision,expectedSourceM15Revision:body.data.expectedSourceM15Revision,expectedSourceM16Revision:body.data.expectedSourceM16Revision,expectedTargetM15Revision:body.data.expectedTargetM15Revision,expectedTargetM16Revision:body.data.expectedTargetM16Revision,idempotencyKey:body.data.idempotencyKey});return reply.send(directCombatPowerCommandResponseSchema.parse({request:body.data,result}));}catch(error){if(error instanceof EncounterAuthorizationError)return missing(request,reply);if(error instanceof EncounterStaleError)return sendApiProblem(request,reply,409,"RPG_COMBAT_STALE","Combat power state is stale; refresh before trying again");if(error instanceof EncounterConflictError||error instanceof EncounterTurnError)return sendApiProblem(request,reply,409,"RPG_COMBAT_POWER_CONFLICT","Combat power conflicts with current state");return sendApiProblem(request,reply,500,"RPG_INTERNAL_ERROR","Combat power outcome is uncertain. Do not retry POST; read the exact result and refresh");}});
};
