import { expect, test } from "@playwright/test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { buildApp } from "../../server/src/app.js";
import { closeRepo } from "../../server/src/repo/index.js";
import { defaultHarnessSettings, defaultProviderSettings } from "../../server/src/defaults.js";
import { createReviewedAdventure, REVIEWED_ADVENTURE_NAME, REVIEWED_ADVENTURE_PRIVATE_SENTINEL } from "../../server/test/fixtures/reviewedAdventure.js";

const completion = (name: string, value: unknown) => ({ message: { role: "assistant" as const, content: null, toolCalls: [{ id: name, name, arguments: JSON.stringify(value) }] }, usage: { promptTokens: 1, completionTokens: 1, totalTokens: 2 }, model: { requestedModel: "reviewed-e2e", responseModel: "reviewed-e2e" } });

test("reviewed harbor human controls accept at Quay and travel once", async ({ page }) => {
  test.setTimeout(90_000);
  const dataDir = mkdtempSync(path.join(tmpdir(), "velvet-e2e-reviewed-"));
  const previous = { VELVET_DATA_DIR: process.env.VELVET_DATA_DIR, NODE_ENV: process.env.NODE_ENV, FEATURE_RPG_CAMPAIGN: process.env.FEATURE_RPG_CAMPAIGN, FEATURE_RPG_MECHANICS: process.env.FEATURE_RPG_MECHANICS, FEATURE_RPG_COMBAT: process.env.FEATURE_RPG_COMBAT };
  Object.assign(process.env, { VELVET_DATA_DIR: dataDir, NODE_ENV: "test", FEATURE_RPG_CAMPAIGN: "true", FEATURE_RPG_MECHANICS: "true", FEATURE_RPG_COMBAT: "true" });
  closeRepo(); let fixture: any; let app: any; let dispatches = 0; let instant = Date.parse("2036-01-01T00:00:00.000Z"); const now = () => new Date(instant += 1_000); const advance = () => { instant += 60_000; }; let planningCandidates: Array<{ action: string; label: string }> = []; let providerFailure = ""; let director: { action: "reveal-node" | "resolve-node"; title: string } | null = null; let declarationIntent: "accept" | "hear-keeper" | "secure-lens" | "relight" | "claim" = "accept";
  try {
    fixture = await createReviewedAdventure(dataDir, { prepareOptionalEncounter: false, clock: { now } });
    app = buildApp({ campaignRepositoryFactory: () => fixture.repo, adventureAgentDependencies: { complete: async (input: any) => {
      dispatches += 1;
      if (input.promptVersion === "campaign-dm-v1") {
        const candidates = JSON.parse(input.messages[1].content).candidates;
        planningCandidates = candidates.map((item: any) => ({ action: item.action, label: item.label }));
        if (!director) return completion("select_dm_beat", { selection: null });
        const candidate = candidates.find((item: any) => item.action === director!.action && item.label === `${director!.action === "resolve-node" ? "Resolve bound scene" : "Reveal scene"}: ${director!.title}`);
        if (!candidate) { providerFailure = `reviewed ${director.action} ${director.title} control unavailable: ${JSON.stringify(planningCandidates)}`; throw new Error(providerFailure); }
        return completion("select_dm_beat", { selection: { candidateId: candidate.candidateId, digest: candidate.digest } });
      }
      if (input.promptVersion === "campaign-dm-narration-v1") return completion("submit_dm_scene", { atmosphere: "Harbor lights.", dialogue: [], question: "What do you do?" });
      if (input.promptVersion === "adventure-narration-v1") return completion("submit_adventure_narration", { narration: "The authoritative harbor record is clear." });
      const message = input.messages.find((entry: any) => typeof entry.content === "string" && entry.content.startsWith("UNTRUSTED CURRENT EXACT CANDIDATE TABLE"));
      const candidates = JSON.parse(message.content.slice(message.content.indexOf("{"))).candidateOptions;
      const candidate = declarationIntent === "accept"
        ? candidates.find((item: any) => item.toolName === "exact_quest_lifecycle.select" && item.label.action === "accept" && item.label.source === "Restore the Harbor Light")
        : declarationIntent === "claim"
          ? candidates.find((item: any) => item.toolName === "exact_quest_lifecycle.select" && item.label.action === "claim-reward" && item.label.source === "Restore the Harbor Light")
        : candidates.find((item: any) => item.toolName === "exact_quest_objective.select" && item.label.action === "Advance quest objective" && typeof item.label.target === "string" && item.label.target.toLowerCase().includes(declarationIntent === "hear-keeper" ? "keeper" : declarationIntent === "secure-lens" ? "lens" : "beacon"));
      if (!candidate) throw new Error(`reviewed ${declarationIntent} declaration control unavailable`);
      return completion(candidate.toolName, candidate.arguments);
    }, getProvider: async () => ({ ...defaultProviderSettings(), model: "reviewed-e2e" }), getHarness: async () => defaultHarnessSettings(), now } });
    const origin = await app.listen({ host: "127.0.0.1", port: 0 });
    await page.route("**/api/**", async route => { const url = new URL(route.request().url()); await route.fulfill({ response: await route.fetch({ url: `${origin}${url.pathname}${url.search}` }) }); });
    const writes: string[] = []; page.on("request", request => { if (["POST", "PATCH"].includes(request.method())) writes.push(new URL(request.url()).pathname); });
    await page.goto("/"); await page.getByRole("button", { name: `Open campaign ${REVIEWED_ADVENTURE_NAME}`, exact: true }).click();
    await page.getByRole("navigation", { name: "Campaign destinations", exact: true }).getByRole("button", { name: "Play workspace", exact: true }).click();
    await page.getByRole("button", { name: "Check room readiness", exact: true }).click(); await page.getByRole("button", { name: "Enter adventure", exact: true }).click();
    const composer = page.getByRole("textbox", { name: "What do you do?", exact: true });
    await composer.fill("I accept Restore the Harbor Light."); await page.getByRole("button", { name: "Declare action", exact: true }).click();
    await page.getByRole("button", { name: "Approve selected batch", exact: true }).click(); await expect(composer).toBeEnabled();
    const map = await page.getByRole("region", { name: "Campaign maps", exact: true }).elementHandle();
    await composer.fill("Retained Harbor draft"); await page.getByRole("button", { name: "Director", exact: true }).click(); director = { action: "reveal-node", title: "Lens Recovered" };
    await page.getByRole("button", { name: "Open scene", exact: true }).click(); await page.getByRole("button", { name: "Approve exact proposal", exact: true }).click();
    await page.getByRole("button", { name: "Close Director", exact: true }).click(); await expect(composer).toHaveValue("Retained Harbor draft"); expect(await map!.evaluate(node => node.isConnected)).toBe(true);
    declarationIntent = "hear-keeper";
    const hearStream = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/adventure-turns/stream"));
    await composer.fill("I hear Keeper Maren's request."); await page.getByRole("button", { name: "Declare action", exact: true }).click(); expect((await hearStream).status()).toBe(200); await expect(composer).toBeEnabled();
    await page.setViewportSize({ width: 390, height: 844 }); await page.locator('[data-atlas-tool="travel"]').click(); await expect(page.getByRole("heading", { name: "World explorer", exact: true })).toBeVisible();
    await page.getByRole("combobox", { name: "Eligible route", exact: true }).selectOption({ label: "Lantern Quay → Keeper House" }); await page.getByRole("button", { name: "Review", exact: true }).click(); await page.getByRole("button", { name: "Confirm travel", exact: true }).click();
    await page.getByRole("button", { name: "Close Travel", exact: true }).click(); expect(await map!.evaluate(node => node.isConnected)).toBe(true);
    advance();
    declarationIntent = "secure-lens";
    const objectiveStream = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/adventure-turns/stream"));
    await composer.fill("I secure the harbor lens."); await page.getByRole("button", { name: "Declare action", exact: true }).click();
    const objectiveResponse = await objectiveStream; expect(objectiveResponse.status()).toBe(200); await expect(composer).toBeEnabled();
    director = { action: "resolve-node", title: "Lens Recovered" };
    const continueRequest = page.waitForRequest(request => request.method() === "POST" && new URL(request.url()).pathname.endsWith("/beat-commands"));
    const continueResponse = page.waitForResponse(response => response.request().method() === "POST" && new URL(response.url()).pathname.endsWith("/beat-commands"));
    await page.getByRole("button", { name: "Director", exact: true }).click(); await page.getByRole("button", { name: "Continue scene", exact: true }).click();
    const continuePayload = (await continueRequest).postDataJSON(); expect(continuePayload.evidenceTurnId).toBeTruthy();
    expect((await continueResponse).status()).toBe(200);
    const historyResponse = await app.inject({ method: "GET", url: `/api/rpg/v1/campaigns/${fixture.campaignId}/rooms/${fixture.sessionId}/dm` }); expect(historyResponse.statusCode).toBe(200);
    const latestRun = historyResponse.json().runs.at(-1); expect(latestRun).toMatchObject({ intent: "continue", state: "awaiting-approval" }); expect(providerFailure).toBe(""); expect(planningCandidates).toContainEqual({ action: "resolve-node", label: "Resolve bound scene: Lens Recovered" });
    await page.getByRole("button", { name: "Approve exact proposal", exact: true }).click(); await expect(page.getByRole("region", { name: "DM chronicle", exact: true })).toContainText("Committed:");
    director = { action: "reveal-node", title: "Harbor Finale" }; await page.getByRole("button", { name: "Continue scene", exact: true }).click(); await page.getByRole("button", { name: "Approve exact proposal", exact: true }).click();
    advance(); declarationIntent = "relight"; const relightStream = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/adventure-turns/stream")); await page.getByRole("button", { name: "Close Director", exact: true }).click(); await composer.fill("I relight the harbor beacon."); await page.getByRole("button", { name: "Declare action", exact: true }).click(); expect((await relightStream).status()).toBe(200); await expect(composer).toBeEnabled();
    director = { action: "resolve-node", title: "Harbor Finale" }; await page.getByRole("button", { name: "Director", exact: true }).click(); await page.getByRole("button", { name: "Continue scene", exact: true }).click(); await page.getByRole("button", { name: "Approve exact proposal", exact: true }).click(); await expect(page.getByRole("region", { name: "DM chronicle", exact: true })).toContainText("Committed:");
    await page.getByRole("button", { name: "Close Director", exact: true }).click(); declarationIntent = "claim"; await composer.fill("I claim Keeper's acknowledgment."); await page.getByRole("button", { name: "Declare action", exact: true }).click(); await page.getByRole("button", { name: "Approve selected batch", exact: true }).click(); await expect(composer).toBeEnabled(); await expect(page.getByRole("heading", { name: "Committed mechanics", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Back to campaign", exact: true }).click(); await expect(page.getByRole("region", { name: "Campaign maps", exact: true })).toHaveCount(0); await page.getByRole("navigation", { name: "Campaign destinations", exact: true }).getByRole("button", { name: "Overview workspace", exact: true }).click(); await page.getByRole("button", { name: "Continue preparation", exact: true }).click(); await page.getByRole("button", { name: /3\. Publication/ }).click(); await page.getByRole("checkbox", { name: "I confirm that this published campaign is complete.", exact: true }).check(); await page.getByRole("button", { name: "Mark campaign complete", exact: true }).click(); await expect(page.getByRole("status")).toContainText("Campaign marked completed. Receipt confirmed");
    const beforeReload = dispatches, writesBeforeReload = [...writes]; await page.setViewportSize({ width: 390, height: 844 }); await page.reload(); await expect(page.getByRole("main")).toBeVisible(); expect(dispatches).toBe(beforeReload); expect(writes).toEqual(writesBeforeReload);
    expect(writes.filter(path => path.includes("travel-commands"))).toHaveLength(1); expect(writes.filter(path => path.endsWith("/confirm"))).toHaveLength(2); expect(await page.locator("body").innerText()).not.toContain(REVIEWED_ADVENTURE_PRIVATE_SENTINEL);
  } finally { await page.goto("about:blank").catch(() => {}); await page.unrouteAll({ behavior: "wait" }).catch(() => {}); await app?.close(); fixture?.repo.close(); closeRepo(); rmSync(dataDir, { recursive: true, force: true }); if (previous.VELVET_DATA_DIR === undefined) delete process.env.VELVET_DATA_DIR; else process.env.VELVET_DATA_DIR = previous.VELVET_DATA_DIR; if (previous.NODE_ENV === undefined) delete process.env.NODE_ENV; else process.env.NODE_ENV = previous.NODE_ENV; if (previous.FEATURE_RPG_CAMPAIGN === undefined) delete process.env.FEATURE_RPG_CAMPAIGN; else process.env.FEATURE_RPG_CAMPAIGN = previous.FEATURE_RPG_CAMPAIGN; if (previous.FEATURE_RPG_MECHANICS === undefined) delete process.env.FEATURE_RPG_MECHANICS; else process.env.FEATURE_RPG_MECHANICS = previous.FEATURE_RPG_MECHANICS; if (previous.FEATURE_RPG_COMBAT === undefined) delete process.env.FEATURE_RPG_COMBAT; else process.env.FEATURE_RPG_COMBAT = previous.FEATURE_RPG_COMBAT; }
});

test("reviewed harbor AI controls accept at Quay and travel once", async ({ page }) => {
  test.setTimeout(90_000);
  const dataDir = mkdtempSync(path.join(tmpdir(), "velvet-e2e-reviewed-ai-"));
  const previous = { VELVET_DATA_DIR: process.env.VELVET_DATA_DIR, NODE_ENV: process.env.NODE_ENV, FEATURE_RPG_CAMPAIGN: process.env.FEATURE_RPG_CAMPAIGN, FEATURE_RPG_MECHANICS: process.env.FEATURE_RPG_MECHANICS, FEATURE_RPG_COMBAT: process.env.FEATURE_RPG_COMBAT };
  Object.assign(process.env, { VELVET_DATA_DIR: dataDir, NODE_ENV: "test", FEATURE_RPG_CAMPAIGN: "true", FEATURE_RPG_MECHANICS: "true", FEATURE_RPG_COMBAT: "true" });
  closeRepo(); let fixture: any; let app: any; let dispatches = 0; let instant = Date.parse("2036-01-01T00:00:00.000Z"); const now = () => new Date(instant += 1_000); const advance = () => { instant += 60_000; }; let director: { action: "reveal-node" | "resolve-node"; title: string } | null = null; let intent: "accept" | "hear" | "secure" | "relight" | "claim" = "accept";
  try {
    fixture = await createReviewedAdventure(dataDir, { prepareOptionalEncounter: false, clock: { now } });
    app = buildApp({ campaignRepositoryFactory: () => fixture.repo, adventureAgentDependencies: { complete: async (input: any) => {
      dispatches += 1;
      if (input.promptVersion === "campaign-dm-v1") { const candidates = JSON.parse(input.messages[1].content).candidates; if (!director) return completion("select_dm_beat", { selection: null }); const candidate = candidates.find((item: any) => item.action === director!.action && item.label === `${director!.action === "resolve-node" ? "Resolve bound scene" : "Reveal scene"}: ${director!.title}`); if (!candidate) throw new Error(`AI director candidate unavailable: ${director.action} ${director.title}`); return completion("select_dm_beat", { selection: { candidateId: candidate.candidateId, digest: candidate.digest } }); }
      if (input.promptVersion === "campaign-dm-narration-v1") return completion("submit_dm_scene", { atmosphere: "Harbor lights.", dialogue: [], question: "What do you do?" });
      if (input.promptVersion === "adventure-narration-v1") return completion("submit_adventure_narration", { narration: "The authoritative harbor record is clear." });
      const message = input.messages.find((entry: any) => typeof entry.content === "string" && entry.content.startsWith("UNTRUSTED CURRENT EXACT CANDIDATE TABLE"));
      const candidate = JSON.parse(message.content.slice(message.content.indexOf("{"))).candidateOptions.find((item: any) => intent === "accept" || intent === "claim" ? item.toolName === "exact_quest_lifecycle.select" && item.label.action === (intent === "claim" ? "claim-reward" : "accept") && item.label.source === "Restore the Harbor Light" : item.toolName === "exact_quest_objective.select" && item.label.action === "Advance quest objective" && typeof item.label.target === "string" && item.label.target.toLowerCase().includes(intent === "hear" ? "keeper" : intent === "secure" ? "lens" : "beacon"));
      if (!candidate) throw new Error(`reviewed AI ${intent} control unavailable`);
      return completion(candidate.toolName, candidate.arguments);
    }, getProvider: async () => ({ ...defaultProviderSettings(), model: "reviewed-e2e" }), getHarness: async () => defaultHarnessSettings(), now } });
    const origin = await app.listen({ host: "127.0.0.1", port: 0 });
    await page.route("**/api/**", async route => { const url = new URL(route.request().url()); await route.fulfill({ response: await route.fetch({ url: `${origin}${url.pathname}${url.search}` }) }); });
    const writes: string[] = []; page.on("request", request => { if (["POST", "PATCH"].includes(request.method())) writes.push(new URL(request.url()).pathname); });
    await page.goto("/"); await page.getByRole("button", { name: `Open campaign ${REVIEWED_ADVENTURE_NAME}`, exact: true }).click(); await page.getByRole("navigation", { name: "Campaign destinations", exact: true }).getByRole("button", { name: "Play workspace", exact: true }).click(); await page.getByRole("button", { name: "Check room readiness", exact: true }).click(); await page.getByRole("button", { name: "Enter adventure", exact: true }).click();
    const composer = page.getByRole("textbox", { name: "What do you do?", exact: true }); await composer.fill("I accept Restore the Harbor Light."); await page.getByRole("button", { name: "Declare action", exact: true }).click(); await page.getByRole("button", { name: "Approve selected batch", exact: true }).click(); await expect(composer).toBeEnabled();
    const map = await page.getByRole("region", { name: "Campaign maps", exact: true }).elementHandle(); await composer.fill("Retained AI Harbor draft"); await page.getByRole("button", { name: "Director", exact: true }).click(); await page.getByRole("button", { name: "Review AI delegation", exact: true }).click(); await page.getByRole("button", { name: "Confirm AI delegation", exact: true }).click(); director = { action: "reveal-node", title: "Lens Recovered" }; await page.getByRole("button", { name: "Open scene", exact: true }).click(); await page.getByRole("button", { name: "Close Director", exact: true }).click(); await expect(composer).toHaveValue("Retained AI Harbor draft"); expect(await map!.evaluate(node => node.isConnected)).toBe(true);
    advance(); intent = "hear"; await composer.fill("I hear Keeper Maren's request."); await page.getByRole("button", { name: "Declare action", exact: true }).click(); await expect(composer).toBeEnabled();
    await page.setViewportSize({ width: 390, height: 844 }); await page.locator('[data-atlas-tool="travel"]').click(); await page.getByRole("combobox", { name: "Eligible route", exact: true }).selectOption({ label: "Lantern Quay → Keeper House" }); await page.getByRole("button", { name: "Review", exact: true }).click(); await page.getByRole("button", { name: "Confirm travel", exact: true }).click(); await page.getByRole("button", { name: "Close Travel", exact: true }).click(); expect(await map!.evaluate(node => node.isConnected)).toBe(true);
    advance(); intent = "secure"; await composer.fill("I secure the harbor lens."); await page.getByRole("button", { name: "Declare action", exact: true }).click(); await expect(composer).toBeEnabled(); director = { action: "resolve-node", title: "Lens Recovered" }; const lensContinue = page.waitForRequest(request => request.method() === "POST" && new URL(request.url()).pathname.endsWith("/beat-commands")); await page.getByRole("button", { name: "Director", exact: true }).click(); await page.getByRole("button", { name: "Continue scene", exact: true }).click(); expect((await lensContinue).postDataJSON().evidenceTurnId).toBeTruthy(); director = { action: "reveal-node", title: "Harbor Finale" }; await page.getByRole("button", { name: "Continue scene", exact: true }).click(); await page.getByRole("button", { name: "Close Director", exact: true }).click();
    advance(); intent = "relight"; await composer.fill("I relight the harbor beacon."); await page.getByRole("button", { name: "Declare action", exact: true }).click(); await expect(composer).toBeEnabled(); director = { action: "resolve-node", title: "Harbor Finale" }; const finaleContinue = page.waitForRequest(request => request.method() === "POST" && new URL(request.url()).pathname.endsWith("/beat-commands")); await page.getByRole("button", { name: "Director", exact: true }).click(); await page.getByRole("button", { name: "Continue scene", exact: true }).click(); expect((await finaleContinue).postDataJSON().evidenceTurnId).toBeTruthy(); await page.getByRole("button", { name: "Close Director", exact: true }).click();
    intent = "claim"; await composer.fill("I claim Keeper's acknowledgment."); await page.getByRole("button", { name: "Declare action", exact: true }).click(); await page.getByRole("button", { name: "Approve selected batch", exact: true }).click(); await expect(composer).toBeEnabled(); await expect(page.getByRole("heading", { name: "Committed mechanics", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Back to campaign", exact: true }).click(); await expect(page.getByRole("region", { name: "Campaign maps", exact: true })).toHaveCount(0); await page.getByRole("navigation", { name: "Campaign destinations", exact: true }).getByRole("button", { name: "Overview workspace", exact: true }).click(); await page.getByRole("button", { name: "Continue preparation", exact: true }).click(); await page.getByRole("button", { name: /3\. Publication/ }).click(); await page.getByRole("checkbox", { name: "I confirm that this published campaign is complete.", exact: true }).check(); await page.getByRole("button", { name: "Mark campaign complete", exact: true }).click(); await expect(page.getByRole("status")).toContainText("Campaign marked completed. Receipt confirmed");
    const beforeReload = dispatches, writesBeforeReload = [...writes]; await page.setViewportSize({ width: 390, height: 844 }); await page.reload(); await expect(page.getByRole("main")).toBeVisible(); expect(dispatches).toBe(beforeReload); expect(writes).toEqual(writesBeforeReload); expect(writes.filter(path => path.includes("travel-commands"))).toHaveLength(1); expect(writes.filter(path => path.endsWith("/confirm"))).toHaveLength(2); expect(await page.locator("body").innerText()).not.toContain(REVIEWED_ADVENTURE_PRIVATE_SENTINEL);
  } finally { await page.goto("about:blank").catch(() => {}); await page.unrouteAll({ behavior: "wait" }).catch(() => {}); await app?.close(); fixture?.repo.close(); closeRepo(); rmSync(dataDir, { recursive: true, force: true }); if (previous.VELVET_DATA_DIR === undefined) delete process.env.VELVET_DATA_DIR; else process.env.VELVET_DATA_DIR = previous.VELVET_DATA_DIR; if (previous.NODE_ENV === undefined) delete process.env.NODE_ENV; else process.env.NODE_ENV = previous.NODE_ENV; if (previous.FEATURE_RPG_CAMPAIGN === undefined) delete process.env.FEATURE_RPG_CAMPAIGN; else process.env.FEATURE_RPG_CAMPAIGN = previous.FEATURE_RPG_CAMPAIGN; if (previous.FEATURE_RPG_MECHANICS === undefined) delete process.env.FEATURE_RPG_MECHANICS; else process.env.FEATURE_RPG_MECHANICS = previous.FEATURE_RPG_MECHANICS; if (previous.FEATURE_RPG_COMBAT === undefined) delete process.env.FEATURE_RPG_COMBAT; else process.env.FEATURE_RPG_COMBAT = previous.FEATURE_RPG_COMBAT; }
});
