import type { CreateCampaignFactionHttpRequest, FactionReputationCommandHttpRequest, GmCampaignFactionsHttpResponse, PlayerCampaignFactionsHttpResponse } from "@velvet/contracts";
import { FormEvent, useState } from "react";
import type { NamedChoice } from "../world/useWorldbuildingChoices";
import { createClientId } from "../../../utils/clientId";

export function FactionStandingPanel({ data, revision, isGm, locked, onCreate, onReputation, onPreview, actors = [], editing = true }: {
  data: GmCampaignFactionsHttpResponse | PlayerCampaignFactionsHttpResponse; revision: number; isGm: boolean; locked: boolean;
  onCreate: (input: CreateCampaignFactionHttpRequest) => Promise<void>; onReputation: (factionId: string, input: FactionReputationCommandHttpRequest) => Promise<void>;
  onPreview: (input: CreateCampaignFactionHttpRequest) => void;
  actors?: NamedChoice[]; editing?: boolean;
}) {
  const [name,setName]=useState(""),[description,setDescription]=useState(""),[notes,setNotes]=useState(""),[visibility,setVisibility]=useState<"public"|"gm">("public"),[previewRequest,setPreviewRequest]=useState<CreateCampaignFactionHttpRequest|null>(null);
  const [selected,setSelected]=useState(""),[actor,setActor]=useState(""),[delta,setDelta]=useState("1"),[reason,setReason]=useState("");
  const changed=()=>setPreviewRequest(null);
  const build=():CreateCampaignFactionHttpRequest=>({name,publicState:{description},privateState:{gmNotes:notes,visibility},expectedRevision:revision,idempotencyKey:`faction-ui-${createClientId()}`});
  function preview(){const input=build();setPreviewRequest(input);onPreview(input);}
  function create(event:FormEvent){event.preventDefault();if(!locked&&isGm&&previewRequest&&previewRequest.expectedRevision===revision)void onCreate(previewRequest);}
  function reputation(event:FormEvent){event.preventDefault();if(locked||!isGm)return;void onReputation(selected,{subjectActorId:actor,delta:Number(delta),reason,expectedRevision:revision,idempotencyKey:`reputation-ui-${createClientId()}`});}
  return <section className="studio-panel" aria-labelledby="factions-heading"><h2 id="factions-heading">Factions & standings</h2><p className="field-help">Persisted faction definitions are read-only; current routes support creation and reputation commands.</p>
    {data.factions.length ? <ul className="cast-list">{data.factions.map(faction => <li key={faction.factionId}>
      <h3><bdi dir="auto">{faction.name}</bdi></h3><p><bdi dir="auto">{faction.publicState.description}</bdi></p>
      {isGm && "privateState" in faction && <details className="worldbuilding-details"><summary>Visibility & private notes for {faction.name}</summary><dl className="private-record"><dt>Visibility</dt><dd>{faction.privateState.visibility}</dd><dt>GM notes</dt><dd><bdi dir="auto">{faction.privateState.gmNotes || "None"}</bdi></dd></dl></details>}
      <ul aria-label={`Standings for ${faction.name}`}>{data.standings.filter(item => item.factionId === faction.factionId).map(standing => <li key={standing.subjectActorId}>{actors.find(actor => actor.id === standing.subjectActorId)?.name ?? "Campaign actor"}: Reputation {standing.reputation}</li>)}</ul>
    </li>)}</ul> : <p>No visible factions.</p>}
    {isGm&&editing&&<><details className="worldbuilding-details"><summary>Create a faction</summary><form className="studio-form" onSubmit={create}><h3>Create faction definition</h3><p>GM-only factions and their standings are absent from the player projection. Visibility cannot be edited here after creation.</p><label>Name<input required value={name} onChange={e=>{setName(e.target.value);changed()}} /></label><label>Player description<textarea value={description} onChange={e=>{setDescription(e.target.value);changed()}} /></label><label>Private GM notes<textarea value={notes} onChange={e=>{setNotes(e.target.value);changed()}} /></label><label>Visibility<select value={visibility} onChange={e=>{setVisibility(e.target.value as "public"|"gm");changed()}}><option value="public">Public</option><option value="gm">GM only</option></select></label><div className="button-row"><button type="button" className="ghost" disabled={locked||!name.trim()} onClick={preview}>Preview exact player projection</button><button className="primary" disabled={locked||!previewRequest||previewRequest.expectedRevision!==revision}>Create exact previewed definition</button></div></form></details>
      <details className="worldbuilding-details"><summary>Change faction reputation</summary><form className="studio-form" onSubmit={reputation}><h3>Change reputation</h3><label>Faction<select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose faction</option>{data.factions.map(item=><option value={item.factionId} key={item.factionId}>{item.name}</option>)}</select></label><label>Subject actor<select required value={actor} onChange={e=>setActor(e.target.value)}><option value="">Choose an available campaign actor</option>{actors.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><p className="field-help">Choices include healthy actors outside preparing or active encounters. If choices are unavailable, reauthorize & refresh.</p><label>Exact reputation delta<input required type="number" value={delta} onChange={e=>setDelta(e.target.value)} /></label><label>Reason<input required value={reason} onChange={e=>setReason(e.target.value)} /></label><button className="primary" disabled={locked||!selected||!actor||!reason||Number(delta)===0}>Apply exact reputation command</button></form></details></>}
  </section>;
}
