import type { ActorFactionMembershipCommandHttpRequest, CreateCampaignFactionHttpRequest, FactionReactionCommandHttpRequest, FactionRelationCommandHttpRequest, FactionReputationCommandHttpRequest, GmCampaignFactionsHttpResponse, NpcFactionMembershipCommandHttpRequest, PlayerCampaignFactionsHttpResponse } from "@velvet/contracts";
import { FormEvent, useState } from "react";
import type { NamedChoice } from "../world/useWorldbuildingChoices";
import { createClientId } from "../../../utils/clientId";

const memberLabel = (membership: { actorId?: string; npcId?: string }, actors: NamedChoice[], npcs: NamedChoice[]) =>
  "actorId" in membership && membership.actorId !== undefined
    ? actors.find((entry) => entry.id === membership.actorId)?.name ?? "Campaign actor"
    : memberNpcLabel(membership.npcId, npcs);
const memberNpcLabel = (npcId: string | undefined, npcs: NamedChoice[]) =>
  npcs.find((entry) => entry.id === npcId)?.name ?? "Campaign character";

export function FactionStandingPanel({ data, revision, isGm, locked, onCreate, onReputation, onRelation, onActorMembership, onNpcMembership, onReaction, onPreview, actors = [], npcs = [], editing = true }: {
  data: GmCampaignFactionsHttpResponse | PlayerCampaignFactionsHttpResponse; revision: number; isGm: boolean; locked: boolean;
  onCreate: (input: CreateCampaignFactionHttpRequest) => Promise<void>; onReputation: (factionId: string, input: FactionReputationCommandHttpRequest) => Promise<void>;
  onRelation?: (factionId: string, input: FactionRelationCommandHttpRequest) => Promise<void>;
  onActorMembership?: (factionId: string, input: ActorFactionMembershipCommandHttpRequest) => Promise<void>;
  onNpcMembership?: (factionId: string, input: NpcFactionMembershipCommandHttpRequest) => Promise<void>;
  onReaction?: (factionId: string, input: FactionReactionCommandHttpRequest) => Promise<void>;
  onPreview: (input: CreateCampaignFactionHttpRequest) => void;
  actors?: NamedChoice[]; npcs?: NamedChoice[]; editing?: boolean;
}) {
  const [name,setName]=useState(""),[description,setDescription]=useState(""),[notes,setNotes]=useState(""),[visibility,setVisibility]=useState<"public"|"gm">("public"),[previewRequest,setPreviewRequest]=useState<CreateCampaignFactionHttpRequest|null>(null);
  const [selected,setSelected]=useState(""),[actor,setActor]=useState(""),[delta,setDelta]=useState("1"),[reason,setReason]=useState("");
  const [fromFaction,setFromFaction]=useState(""),[toFaction,setToFaction]=useState(""),[disposition,setDisposition]=useState<"allied"|"neutral"|"hostile">("neutral");
  const [memberFaction,setMemberFaction]=useState(""),[memberActor,setMemberActor]=useState(""),[memberRole,setMemberRole]=useState<"leader"|"member"|"associate"|"enemy">("member");
  const [npcFaction,setNpcFaction]=useState(""),[npcMember,setNpcMember]=useState(""),[npcRole,setNpcRole]=useState<"leader"|"member"|"associate"|"enemy">("member");
  const [reactionFaction,setReactionFaction]=useState(""),[reactionActor,setReactionActor]=useState(""),[reactionDelta,setReactionDelta]=useState("-1"),[reactionReason,setReactionReason]=useState(""),[reactionSource,setReactionSource]=useState("");
  const changed=()=>setPreviewRequest(null);
  const build=():CreateCampaignFactionHttpRequest=>({name,publicState:{description},privateState:{gmNotes:notes,visibility},expectedRevision:revision,idempotencyKey:`faction-ui-${createClientId()}`});
  function preview(){const input=build();setPreviewRequest(input);onPreview(input);}
  function create(event:FormEvent){event.preventDefault();if(!locked&&isGm&&previewRequest&&previewRequest.expectedRevision===revision)void onCreate(previewRequest);}
  function reputation(event:FormEvent){event.preventDefault();if(locked||!isGm)return;void onReputation(selected,{subjectActorId:actor,delta:Number(delta),reason,expectedRevision:revision,idempotencyKey:`reputation-ui-${createClientId()}`});}
  function relation(event:FormEvent){event.preventDefault();if(locked||!isGm||!onRelation||!fromFaction||!toFaction)return;void onRelation(fromFaction,{toFactionId:toFaction,disposition,expectedRevision:revision,idempotencyKey:`relation-ui-${createClientId()}`});}
  function actorMembership(event:FormEvent){event.preventDefault();if(locked||!isGm||!onActorMembership||!memberFaction||!memberActor)return;void onActorMembership(memberFaction,{actorId:memberActor,role:memberRole,expectedRevision:revision,idempotencyKey:`actor-membership-ui-${createClientId()}`});}
  function npcMembership(event:FormEvent){event.preventDefault();if(locked||!isGm||!onNpcMembership||!npcFaction||!npcMember)return;void onNpcMembership(npcFaction,{npcId:npcMember,role:npcRole,expectedRevision:revision,idempotencyKey:`npc-membership-ui-${createClientId()}`});}
  function reaction(event:FormEvent){event.preventDefault();if(locked||!isGm||!onReaction||!reactionFaction||!reactionActor||!reactionSource||Number(reactionDelta)===0)return;void onReaction(reactionFaction,{subjectActorId:reactionActor,delta:Number(reactionDelta),reason:reactionReason,sourceCommandId:reactionSource,expectedRevision:revision,idempotencyKey:`reaction-ui-${createClientId()}`});}
  const factionName=(factionId:string)=>data.factions.find((faction)=>faction.factionId===factionId)?.name??factionId;
  return <section className="studio-panel" aria-labelledby="factions-heading"><h2 id="factions-heading">Factions & standings</h2><p className="field-help">Persisted faction definitions are read-only; current routes support creation, reputation, relations, membership, and reaction commands.</p>
    {data.factions.length ? <ul className="cast-list">{data.factions.map(faction => <li key={faction.factionId}>
      <h3><bdi dir="auto">{faction.name}</bdi></h3><p><bdi dir="auto">{faction.publicState.description}</bdi></p>
      {isGm && "privateState" in faction && <details className="worldbuilding-details"><summary>Visibility & private notes for {faction.name}</summary><dl className="private-record"><dt>Visibility</dt><dd>{faction.privateState.visibility}</dd><dt>GM notes</dt><dd><bdi dir="auto">{faction.privateState.gmNotes || "None"}</bdi></dd></dl></details>}
      <ul aria-label={`Standings for ${faction.name}`}>{data.standings.filter(item => item.factionId === faction.factionId).map(standing => <li key={standing.subjectActorId}>{actors.find(actor => actor.id === standing.subjectActorId)?.name ?? "Campaign actor"}: Reputation {standing.reputation}</li>)}</ul>
      <ul aria-label={`Memberships for ${faction.name}`}>{data.memberships.filter(membership => membership.factionId === faction.factionId).map(membership => <li key={"actorId" in membership ? `actor:${membership.actorId}` : `npc:${membership.npcId}`}>{memberLabel(membership, actors, npcs)}: {membership.role}</li>)}</ul>
    </li>)}</ul> : <p>No visible factions.</p>}
    {data.relations.length>0 && <div><h3>Relations</h3><ul aria-label="Faction relations">{data.relations.map(relation=><li key={`${relation.fromFactionId}:${relation.toFactionId}`}><bdi dir="auto">{factionName(relation.fromFactionId)}</bdi> is <b>{relation.disposition}</b> toward <bdi dir="auto">{factionName(relation.toFactionId)}</bdi></li>)}</ul></div>}
    {isGm&&editing&&<><details className="worldbuilding-details"><summary>Create a faction</summary><form className="studio-form" onSubmit={create}><h3>Create faction definition</h3><p>GM-only factions and their standings are absent from the player projection. Visibility cannot be edited here after creation.</p><label>Name<input required value={name} onChange={e=>{setName(e.target.value);changed()}} /></label><label>Player description<textarea value={description} onChange={e=>{setDescription(e.target.value);changed()}} /></label><label>Private GM notes<textarea value={notes} onChange={e=>{setNotes(e.target.value);changed()}} /></label><label>Visibility<select value={visibility} onChange={e=>{setVisibility(e.target.value as "public"|"gm");changed()}}><option value="public">Public</option><option value="gm">GM only</option></select></label><div className="button-row"><button type="button" className="ghost" disabled={locked||!name.trim()} onClick={preview}>Preview exact player projection</button><button className="primary" disabled={locked||!previewRequest||previewRequest.expectedRevision!==revision}>Create exact previewed definition</button></div></form></details>
      <details className="worldbuilding-details"><summary>Change faction reputation</summary><form className="studio-form" onSubmit={reputation}><h3>Change reputation</h3><label>Faction<select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose faction</option>{data.factions.map(item=><option value={item.factionId} key={item.factionId}>{item.name}</option>)}</select></label><label>Subject actor<select required value={actor} onChange={e=>setActor(e.target.value)}><option value="">Choose an available campaign actor</option>{actors.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><p className="field-help">Choices include healthy actors outside preparing or active encounters. If choices are unavailable, reauthorize & refresh.</p><label>Exact reputation delta<input required type="number" value={delta} onChange={e=>setDelta(e.target.value)} /></label><label>Reason<input required value={reason} onChange={e=>setReason(e.target.value)} /></label><button className="primary" disabled={locked||!selected||!actor||!reason||Number(delta)===0}>Apply exact reputation command</button></form></details>
      {onRelation&&<details className="worldbuilding-details"><summary>Set a faction relation</summary><form className="studio-form" onSubmit={relation}><h3>Set faction relation</h3><label>Source faction<select required value={fromFaction} onChange={e=>setFromFaction(e.target.value)}><option value="">Choose source</option>{data.factions.map(item=><option value={item.factionId} key={item.factionId}>{item.name}</option>)}</select></label><label>Target faction<select required value={toFaction} onChange={e=>setToFaction(e.target.value)}><option value="">Choose target</option>{data.factions.filter(item=>item.factionId!==fromFaction).map(item=><option value={item.factionId} key={item.factionId}>{item.name}</option>)}</select></label><label>Disposition<select value={disposition} onChange={e=>setDisposition(e.target.value as "allied"|"neutral"|"hostile")}><option value="allied">Allied</option><option value="neutral">Neutral</option><option value="hostile">Hostile</option></select></label><button className="primary" disabled={locked||!fromFaction||!toFaction||fromFaction===toFaction}>Apply exact relation command</button></form></details>}
      {onActorMembership&&<details className="worldbuilding-details"><summary>Set an actor membership</summary><form className="studio-form" onSubmit={actorMembership}><h3>Actor faction membership</h3><label>Membership faction<select required value={memberFaction} onChange={e=>setMemberFaction(e.target.value)}><option value="">Choose faction</option>{data.factions.map(item=><option value={item.factionId} key={item.factionId}>{item.name}</option>)}</select></label><label>Campaign actor<select required value={memberActor} onChange={e=>setMemberActor(e.target.value)}><option value="">Choose an available campaign actor</option>{actors.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Actor role<select value={memberRole} onChange={e=>setMemberRole(e.target.value as typeof memberRole)}><option value="leader">Leader</option><option value="member">Member</option><option value="associate">Associate</option><option value="enemy">Enemy</option></select></label><button className="primary" disabled={locked||!memberFaction||!memberActor}>Apply exact actor membership command</button></form></details>}
      {onNpcMembership&&<details className="worldbuilding-details"><summary>Set a character membership</summary><form className="studio-form" onSubmit={npcMembership}><h3>Character faction membership</h3><label>Character faction<select required value={npcFaction} onChange={e=>setNpcFaction(e.target.value)}><option value="">Choose faction</option>{data.factions.map(item=><option value={item.factionId} key={item.factionId}>{item.name}</option>)}</select></label><label>Campaign character<select required value={npcMember} onChange={e=>setNpcMember(e.target.value)}><option value="">Choose a character</option>{npcs.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Character role<select value={npcRole} onChange={e=>setNpcRole(e.target.value as typeof npcRole)}><option value="leader">Leader</option><option value="member">Member</option><option value="associate">Associate</option><option value="enemy">Enemy</option></select></label><button className="primary" disabled={locked||!npcFaction||!npcMember}>Apply exact character membership command</button></form></details>}
      {onReaction&&<details className="worldbuilding-details"><summary>Resolve a faction reaction</summary><form className="studio-form" onSubmit={reaction}><h3>Faction reaction</h3><p className="field-help">A reaction is accepted only when the faction already holds an observation for the named source command.</p><label>Faction<select required value={reactionFaction} onChange={e=>setReactionFaction(e.target.value)}><option value="">Choose faction</option>{data.factions.map(item=><option value={item.factionId} key={item.factionId}>{item.name}</option>)}</select></label><label>Subject actor<select required value={reactionActor} onChange={e=>setReactionActor(e.target.value)}><option value="">Choose an available campaign actor</option>{actors.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Exact reputation delta<input required type="number" value={reactionDelta} onChange={e=>setReactionDelta(e.target.value)} /></label><label>Reason<input required value={reactionReason} onChange={e=>setReactionReason(e.target.value)} /></label><label>Observation source command<input required value={reactionSource} onChange={e=>setReactionSource(e.target.value)} /></label><button className="primary" disabled={locked||!reactionFaction||!reactionActor||!reactionSource||!reactionReason||Number(reactionDelta)===0}>Apply exact reaction command</button></form></details>}
    </>}
  </section>;
}
