import type { CreateCampaignFactionHttpRequest, FactionReputationCommandHttpRequest } from "@velvet/contracts";
import type { CampaignFactionsHttpResponse } from "../../../api";
import { FormEvent, useState } from "react";

export function FactionStandingPanel({ data, revision, isGm, locked, onCreate, onReputation, onPreview }: { data:CampaignFactionsHttpResponse;revision:number;isGm:boolean;locked:boolean;onCreate:(input:CreateCampaignFactionHttpRequest)=>Promise<void>;onReputation:(factionId:string,input:FactionReputationCommandHttpRequest)=>Promise<void>;onPreview:(input:CreateCampaignFactionHttpRequest)=>void }) {
  const [name,setName]=useState(""),[description,setDescription]=useState(""),[notes,setNotes]=useState(""),[visibility,setVisibility]=useState<"public"|"gm">("public"),[previewed,setPreviewed]=useState(false);
  const [selected,setSelected]=useState(""),[actor,setActor]=useState(""),[delta,setDelta]=useState("1"),[reason,setReason]=useState("");
  const createInput=():CreateCampaignFactionHttpRequest=>({name,publicState:{description},privateState:{gmNotes:notes,visibility},expectedRevision:revision,idempotencyKey:`faction-ui-${crypto.randomUUID()}`});
  const create=(event:FormEvent)=>{event.preventDefault();if(!previewed)return;void onCreate(createInput()).then(()=>{setName("");setDescription("");setNotes("");setPreviewed(false);});};
  const reputation=(event:FormEvent)=>{event.preventDefault();void onReputation(selected,{subjectActorId:actor,delta:Number(delta),reason,expectedRevision:revision,idempotencyKey:`reputation-ui-${crypto.randomUUID()}`});};
  const names=new Map(data.factions.map((item)=>[item.factionId,item.name]));
  return <section className="studio-panel" aria-labelledby="factions-heading"><h2 id="factions-heading">Factions & standings</h2>{data.factions.length?<ul className="cast-list">{data.factions.map((faction)=><li key={faction.factionId}><h3><bdi dir="auto">{faction.name}</bdi></h3><p><bdi dir="auto">{faction.publicState.description}</bdi></p>{isGm&&faction.privateState&&<dl className="private-record"><div><dt>Visibility</dt><dd>{faction.privateState.visibility}</dd></div><div><dt>GM notes</dt><dd><bdi dir="auto">{faction.privateState.gmNotes||"None"}</bdi></dd></div></dl>}<ul aria-label={`Standings for ${faction.name}`}>{data.standings.filter((item)=>item.factionId===faction.factionId).map((standing)=><li key={`${standing.factionId}:${standing.subjectActorId}`}>Reputation {standing.reputation}</li>)}</ul></li>)}</ul>:<p>No visible factions.</p>}
    {isGm&&<><form className="studio-form" onSubmit={create}><h3>Create faction</h3><label>Name<input required value={name} onChange={(e)=>{setName(e.target.value);setPreviewed(false);}} /></label><label>Player description<textarea value={description} onChange={(e)=>{setDescription(e.target.value);setPreviewed(false);}} /></label><label>GM notes<textarea value={notes} onChange={(e)=>{setNotes(e.target.value);setPreviewed(false);}} /></label><label>Visibility<select value={visibility} onChange={(e)=>{setVisibility(e.target.value as "public"|"gm");setPreviewed(false);}}><option value="public">Public</option><option value="gm">GM only</option></select></label><div className="button-row"><button type="button" className="ghost" disabled={locked||!name.trim()} onClick={()=>{const input=createInput();onPreview(input);setPreviewed(true);}}>Preview player projection</button><button className="primary" disabled={locked||!previewed}>Create after preview</button></div></form>
    <form className="studio-form" onSubmit={reputation}><h3>Change reputation</h3><label>Faction<select required value={selected} onChange={(e)=>setSelected(e.target.value)}><option value="">Choose faction</option>{data.factions.map((item)=><option value={item.factionId} key={item.factionId}>{names.get(item.factionId)}</option>)}</select></label><label>Subject actor ID<input required value={actor} onChange={(e)=>setActor(e.target.value)} /></label><label>Change<input required type="number" value={delta} onChange={(e)=>setDelta(e.target.value)} /></label><label>Reason<input required value={reason} onChange={(e)=>setReason(e.target.value)} /></label><button className="primary" disabled={locked||!selected||!actor||!reason||Number(delta)===0}>Review & apply reputation</button></form></>}
  </section>;
}
