import type { CreateCampaignFactionHttpRequest, CreateCampaignNpcHttpRequest, FactionReputationCommandHttpRequest, GmCampaignFactionsHttpResponse, GmCampaignNpcsHttpResponse, NpcRelationshipCommandHttpRequest, PlayerCampaignFactionsHttpResponse, PlayerCampaignNpcsHttpResponse } from "@velvet/contracts";
import { useCallback, useEffect, useRef, useState } from "react";
import type { CampaignFactionsHttpResponse, CampaignNpcsHttpResponse } from "../../../api";
import { isDefiniteNarrativeRejection, NarrativeMutationStatus, receiptFrom } from "../NarrativeMutationStatus";
import { beginNarrativeMutation, blocksNarrativeMutation, clearNarrativeMutation, consumeNarrativeConfirmed, markNarrativeAmbiguous, markNarrativeConfirmed, markNarrativePartial, useNarrativeMutation, type NarrativeLane } from "../narrativeMutationRegistry";
import type { StudioAuthorization } from "../StudioAuthorization";
import { FactionStandingPanel } from "./FactionStandingPanel";
import { WorldbuildingNavigation } from "../world/WorldbuildingNavigation";
import { useWorldbuildingChoices } from "../world/useWorldbuildingChoices";
import { createClientId } from "../../../utils/clientId";

export interface CastStudioApi {
  listNpcs:(id:string,audience:"gm"|"player")=>Promise<{data:CampaignNpcsHttpResponse;revision:number}>; listFactions:(id:string,audience:"gm"|"player")=>Promise<{data:CampaignFactionsHttpResponse;revision:number}>;
  createNpc:(id:string,input:CreateCampaignNpcHttpRequest)=>Promise<unknown>; relationship:(id:string,input:NpcRelationshipCommandHttpRequest)=>Promise<unknown>;
  createFaction:(id:string,input:CreateCampaignFactionHttpRequest)=>Promise<unknown>; reputation:(id:string,input:FactionReputationCommandHttpRequest)=>Promise<unknown>;
  previewNpcs:(data:GmCampaignNpcsHttpResponse)=>PlayerCampaignNpcsHttpResponse; previewFactions:(data:GmCampaignFactionsHttpResponse)=>PlayerCampaignFactionsHttpResponse;
}
export function NpcRosterPage(props: React.ComponentProps<typeof NpcRosterWorkspace>) {
  return <NpcRosterWorkspace key={`${props.campaignId}:${props.authorization.role}:${props.authorization.audience}:${props.authorization.generation}`} {...props} />;
}
function NpcRosterWorkspace({campaignId,authorization,api,onBack,focusHeadingRequest}:{campaignId:string;authorization:StudioAuthorization;api:CastStudioApi;onBack:()=>void;focusHeadingRequest?:number}){
  const isGm=authorization.audience==="gm",npcMutation=useNarrativeMutation(campaignId,"npc"),factionMutation=useNarrativeMutation(campaignId,"faction");
  const [npcs,setNpcs]=useState<CampaignNpcsHttpResponse|null>(null),[factions,setFactions]=useState<CampaignFactionsHttpResponse|null>(null),[revision,setRevision]=useState(0),[phase,setPhase]=useState<"loading"|"ready"|"failed">("loading"),[consistent,setConsistent]=useState(false),[status,setStatus]=useState(""),[preview,setPreview]=useState<unknown>(null);
  const [persona,setPersona]=useState(""),[npcName,setNpcName]=useState(""),[goals,setGoals]=useState(""),[notes,setNotes]=useState(""),[merchantJson,setMerchantJson]=useState(""),[npcPreviewRequest,setNpcPreviewRequest]=useState<CreateCampaignNpcHttpRequest|null>(null);
  const [selectedNpc,setSelectedNpc]=useState(""),[actor,setActor]=useState(""),[affinity,setAffinity]=useState("0"),[trust,setTrust]=useState("0"),[fear,setFear]=useState("0"),[reason,setReason]=useState("");
  const mounted=useRef(true),generation=useRef(0),heading=useRef<HTMLHeadingElement>(null);
  const personas = useWorldbuildingChoices(campaignId, authorization, "personas"), actors = useWorldbuildingChoices(campaignId, authorization, "actors");
  const [task, setTask] = useState<"browse" | "npc" | "relationship" | "faction">("browse");
  const load=useCallback(async(audience=authorization.audience,focus=false)=>{const token=++generation.current;setPhase("loading");const [npcRead,factionRead]=await Promise.allSettled([api.listNpcs(campaignId,audience),api.listFactions(campaignId,audience)]);if(!mounted.current||token!==generation.current)return false;if(npcRead.status!=="fulfilled"||factionRead.status!=="fulfilled"){setPhase(npcRead.status==="fulfilled"||factionRead.status==="fulfilled"?"ready":"failed");setConsistent(false);setStatus("Cast refresh was partial. Existing records and confirmed receipts are preserved; writes are blocked.");return false}if(npcRead.value.revision!==factionRead.value.revision){setPhase("ready");setConsistent(false);setStatus("NPC and faction revisions disagree. No mixed snapshot was published; writes are blocked until refetch.");return false}setNpcs(npcRead.value.data);setFactions(factionRead.value.data);setRevision(npcRead.value.revision);setConsistent(true);setPhase("ready");setStatus("");if(focus)queueMicrotask(()=>heading.current?.focus());return npcRead.value.revision},[api,campaignId,authorization.audience]);
  useEffect(()=>{mounted.current=true;void load().then((fresh)=>{for(const mutation of [npcMutation,factionMutation])if(fresh!==false&&mutation?.phase==="confirmed"){fresh===mutation.resultingRevision?consumeNarrativeConfirmed(mutation):markNarrativePartial(mutation)}});return()=>{mounted.current=false;generation.current+=1}},[load]);
  useEffect(()=>{if(focusHeadingRequest!==undefined&&phase!=="loading")heading.current?.focus()},[focusHeadingRequest,phase]);
  async function refreshAuthorized(){try{const auth=await authorization.reauthorize();if(!mounted.current||auth.audience!==authorization.audience||auth.role!==authorization.role)return;const fresh=await load(auth.audience);for(const mutation of [npcMutation,factionMutation])if(fresh!==false&&mutation?.phase==="confirmed"){fresh===mutation.resultingRevision?consumeNarrativeConfirmed(mutation):markNarrativePartial(mutation)}}catch{/* gate renders the authorized fallback */}}
  async function mutate(lane:NarrativeLane,operation:string,request:{idempotencyKey:string;expectedRevision:number},write:()=>Promise<unknown>){let auth;try{auth=await authorization.reauthorize()}catch{return}if(auth.audience!=="gm"){setStatus("GM authority is required for this command.");return}const pending=beginNarrativeMutation(campaignId,lane,operation,{idempotencyKey:request.idempotencyKey,expectedRevision:request.expectedRevision});if(!pending)return;try{const result=await write(),receipt=receiptFrom(result);markNarrativeConfirmed(pending,result,receipt);const reads=await Promise.allSettled([api.listNpcs(campaignId,auth.audience),api.listFactions(campaignId,auth.audience)]);const confirmed={...pending,phase:"confirmed" as const,memoryResult:result,receipt,resultingRevision:receipt?.revisionAfter,refresh:"required" as const};if(reads[0].status==="fulfilled"&&reads[1].status==="fulfilled"&&reads[0].value.revision===reads[1].value.revision&&receipt!==undefined&&reads[0].value.revision===receipt.revisionAfter){if(mounted.current){setNpcs(reads[0].value.data);setFactions(reads[1].value.data);setRevision(reads[0].value.revision);setConsistent(true);setPhase("ready");}consumeNarrativeConfirmed(confirmed)}else markNarrativePartial(confirmed)}catch(error){if(isDefiniteNarrativeRejection(error)){clearNarrativeMutation(campaignId,lane);setStatus(`${operation} was definitely rejected as stale or conflicting. Refresh before retrying.`)}else markNarrativeAmbiguous(pending)}}
  function npcInput(idempotencyKey=`npc-ui-${createClientId()}`):CreateCampaignNpcHttpRequest|null{let merchantState:CreateCampaignNpcHttpRequest["privateState"]["merchantState"]=null;try{merchantState=merchantJson.trim()?JSON.parse(merchantJson) as NonNullable<typeof merchantState>:null}catch{return null}return{personaId:persona,publicState:{name:npcName},privateState:{goals,gmNotes:notes,merchantState},expectedRevision:revision,idempotencyKey}}
  const locked=!consistent||blocksNarrativeMutation(npcMutation)||blocksNarrativeMutation(factionMutation);
  return <main className="studio-page" aria-labelledby="cast-heading"><div className="studio-shell"><header className="studio-header"><div><button className="back-link" onClick={onBack}>← Campaign</button><p className="eyebrow">{isGm?"GM CAST STUDIO":"VISIBLE CAST"}</p><h1 ref={heading} tabIndex={-1} id="cast-heading">Cast & factions</h1></div><button className="ghost" onClick={()=>void refreshAuthorized()}>Reauthorize & refresh</button></header><NarrativeMutationStatus mutation={npcMutation} onRefresh={()=>void refreshAuthorized()}/><NarrativeMutationStatus mutation={factionMutation} onRefresh={()=>void refreshAuthorized()}/>{status&&<p role="status">{status}</p>}{phase==="failed"&&<p role="alert">Cast could not be loaded.</p>}
    <WorldbuildingNavigation current="cast" authorization={authorization} />
    {isGm && <nav className="button-row" aria-label="Cast preparation tasks">{([{id:"browse",label:"Browse cast"},{id:"npc",label:"Create an NPC"},{id:"relationship",label:"Change a relationship"},{id:"faction",label:"Prepare a faction"}] as const).map(item => <button key={item.id} aria-pressed={task===item.id} onClick={()=>setTask(item.id)}>{item.label}</button>)}</nav>}
    <div className="studio-grid">{npcs&&<section className="studio-panel"><h2>NPC roster</h2><p className="field-help">NPC names are public. Goals, notes and merchant data are GM-only. Definitions are read-only; creation does not place an NPC in a room.</p>
      {npcs.npcs.length ? <ul className="cast-list">{npcs.npcs.map(npc => <li key={npc.npcId}>
        <h3><bdi dir="auto">{npc.publicState.name}</bdi></h3>{npc.publicState.description && <p>{npc.publicState.description}</p>}
        {isGm && "privateState" in npc && <details className="worldbuilding-details"><summary>Private preparation for {npc.publicState.name}</summary><dl className="private-record"><dt>Goals</dt><dd>{npc.privateState.goals || "None"}</dd><dt>GM notes</dt><dd>{npc.privateState.gmNotes || "None"}</dd><dt>Merchant data</dt><dd>{npc.privateState.merchantState ? JSON.stringify(npc.privateState.merchantState) : "None"}</dd></dl></details>}
        <ul aria-label={`Relationships for ${npc.publicState.name}`}>{npcs.relationships.filter(item => item.npcId === npc.npcId).map(item => <li key={item.subjectActorId}>{actors.choices.find(choice => choice.id === item.subjectActorId)?.name ?? "Campaign actor"}: Affinity {item.affinity}; trust {item.trust}; fear {item.fear}</li>)}</ul>
        {isGm && <button onClick={() => { setSelectedNpc(npc.npcId); setTask("relationship"); }}>Change relationship with {npc.publicState.name}</button>}
      </li>)}</ul> : <p>No visible NPCs.</p>}
      {isGm&&task==="npc"&&<form className="studio-form" onSubmit={e=>{e.preventDefault();if(!locked&&npcPreviewRequest)void mutate("npc","NPC creation",npcPreviewRequest,()=>api.createNpc(campaignId,npcPreviewRequest))}}><h3>Create NPC definition</h3><label>Persona<select required value={persona} onChange={e=>{setPersona(e.target.value);setNpcName(personas.choices.find(item=>item.id===e.target.value)?.name??"");setNpcPreviewRequest(null)}}><option value="">Choose a library persona</option>{personas.choices.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{personas.failed&&<p role="alert">Persona choices could not be loaded. Reauthorize & refresh before creating.</p>}<label>Public name<input required value={npcName} onChange={e=>{setNpcName(e.target.value);setNpcPreviewRequest(null)}} /></label><label>Private goals<textarea value={goals} onChange={e=>{setGoals(e.target.value);setNpcPreviewRequest(null)}} /></label><label>Private GM notes<textarea value={notes} onChange={e=>{setNotes(e.target.value);setNpcPreviewRequest(null)}} /></label><details className="worldbuilding-details"><summary>Advanced merchant data</summary><label>Private merchant JSON<textarea value={merchantJson} onChange={e=>{setMerchantJson(e.target.value);setNpcPreviewRequest(null)}} /></label></details><div className="button-row"><button type="button" disabled={locked||!persona||!npcName||!npcInput("review-only")} onClick={()=>{const input=npcInput();if(!input)return;setPreview(api.previewNpcs({npcs:[{npcId:"preview-npc",personaId:input.personaId,publicState:input.publicState,privateState:input.privateState,createdAt:new Date().toISOString()}],relationships:[]}));setNpcPreviewRequest(input)}}>Preview exact player projection</button><button className="primary" disabled={locked||!npcPreviewRequest||npcPreviewRequest.expectedRevision!==revision}>Create exact previewed NPC</button></div></form>}
      {isGm&&task==="relationship"&&<form className="studio-form" onSubmit={e=>{e.preventDefault();if(locked)return;const request:NpcRelationshipCommandHttpRequest={subjectActorId:actor,affinityDelta:Number(affinity),trustDelta:Number(trust),fearDelta:Number(fear),reason,expectedRevision:revision,idempotencyKey:`relationship-ui-${createClientId()}`};void mutate("npc","NPC relationship command",request,()=>api.relationship(selectedNpc,request))}}><h3>Change relationship</h3><label>NPC<select required value={selectedNpc} onChange={e=>setSelectedNpc(e.target.value)}><option value="">Choose NPC</option>{npcs.npcs.map(npc=><option key={npc.npcId} value={npc.npcId}>{npc.publicState.name}</option>)}</select></label><label>Subject actor<select required value={actor} onChange={e=>setActor(e.target.value)}><option value="">Choose an available campaign actor</option>{actors.choices.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><p className="field-help">Actor choices use the existing setup-candidate read: healthy actors outside preparing or active encounters. Missing actors cannot be selected here.</p>{actors.failed&&<p role="alert">Actor choices are unavailable. Reauthorize & refresh; no IDs need to be entered.</p>}<label>Affinity delta<input type="number" min="-100" max="100" value={affinity} onChange={e=>setAffinity(e.target.value)} /></label><label>Trust delta<input type="number" min="-100" max="100" value={trust} onChange={e=>setTrust(e.target.value)} /></label><label>Fear delta<input type="number" min="-100" max="100" value={fear} onChange={e=>setFear(e.target.value)} /></label><label>Exact reason<input required value={reason} onChange={e=>setReason(e.target.value)} /></label><button className="primary" disabled={locked||!selectedNpc||!actor||!reason||(Number(affinity)===0&&Number(trust)===0&&Number(fear)===0)}>Apply exact relationship command</button></form>}</section>}
      {factions&&<FactionStandingPanel data={factions} revision={revision} isGm={isGm} editing={task==="faction"} actors={actors.choices} locked={locked} onPreview={input=>{setPreview(api.previewFactions({factions:[{factionId:"preview-faction",name:input.name,publicState:input.publicState,privateState:input.privateState,createdAt:new Date().toISOString()}],standings:[]}))}} onCreate={input=>mutate("faction","Faction creation",input,()=>api.createFaction(campaignId,input))} onReputation={(id,input)=>mutate("faction","Faction reputation command",input,()=>api.reputation(id,input))}/>}</div>
    {isGm&&Boolean(preview)&&<section className="projection-preview"><h2>Exact player projection preview</h2><p>Private fields are structurally absent.</p><pre>{JSON.stringify(preview,null,2)}</pre></section>}</div></main>;
}
