import type { CreateCampaignFactionHttpRequest, CreateCampaignNpcHttpRequest, FactionReputationCommandHttpRequest, NpcRelationshipCommandHttpRequest } from "@velvet/contracts";
import type { CampaignFactionsHttpResponse, CampaignNpcsHttpResponse } from "../../../api";
import { useCallback, useEffect, useRef, useState } from "react";
import { FactionStandingPanel } from "./FactionStandingPanel";

export interface CastStudioApi { listNpcs:(id:string)=>Promise<{data:CampaignNpcsHttpResponse;revision:number}>;listFactions:(id:string)=>Promise<{data:CampaignFactionsHttpResponse;revision:number}>;createNpc:(id:string,input:CreateCampaignNpcHttpRequest)=>Promise<unknown>;relationship:(id:string,input:NpcRelationshipCommandHttpRequest)=>Promise<unknown>;createFaction:(id:string,input:CreateCampaignFactionHttpRequest)=>Promise<unknown>;reputation:(id:string,input:FactionReputationCommandHttpRequest)=>Promise<unknown>;previewNpcs:(data:CampaignNpcsHttpResponse)=>CampaignNpcsHttpResponse;previewFactions:(data:CampaignFactionsHttpResponse)=>CampaignFactionsHttpResponse }
type Lock={kind:string;phase:"ambiguous"|"confirmed";receipt?:unknown};const lockKey=(id:string)=>`velvet.cast-command.v1:${id}`;const readLock=(id:string):Lock|null=>{try{return JSON.parse(localStorage.getItem(lockKey(id))??"null") as Lock|null}catch{return null}};const writeLock=(id:string,value:Lock|null)=>{try{value?localStorage.setItem(lockKey(id),JSON.stringify(value)):localStorage.removeItem(lockKey(id))}catch{/* durable best effort */}};
export function NpcRosterPage({campaignId,isGm,api,onBack,focusHeadingRequest}:{campaignId:string;isGm:boolean;api:CastStudioApi;onBack:()=>void;focusHeadingRequest?:number}){
  const [npcs,setNpcs]=useState<CampaignNpcsHttpResponse|null>(null),[factions,setFactions]=useState<CampaignFactionsHttpResponse|null>(null),[revision,setRevision]=useState(0),[phase,setPhase]=useState<"loading"|"ready"|"failed">("loading"),[lock,setLock]=useState<Lock|null>(()=>readLock(campaignId)),[status,setStatus]=useState(""),[preview,setPreview]=useState<unknown>(null);
  const [persona,setPersona]=useState(""),[npcName,setNpcName]=useState(""),[goals,setGoals]=useState(""),[notes,setNotes]=useState(""),[previewed,setPreviewed]=useState(false),[selectedNpc,setSelectedNpc]=useState(""),[actor,setActor]=useState(""),[reason,setReason]=useState("");
  const mounted=useRef(true),generation=useRef(0),heading=useRef<HTMLHeadingElement>(null);
  const load=useCallback(async(focus=false)=>{const token=++generation.current;setPhase("loading");const [npcRead,factionRead]=await Promise.allSettled([api.listNpcs(campaignId),api.listFactions(campaignId)]);if(!mounted.current||token!==generation.current)return false;if(npcRead.status==="fulfilled")setNpcs(npcRead.value.data);if(factionRead.status==="fulfilled")setFactions(factionRead.value.data);if(npcRead.status==="fulfilled"&&factionRead.status==="fulfilled"){setRevision(Math.max(npcRead.value.revision,factionRead.value.revision));setPhase("ready");if(focus)queueMicrotask(()=>heading.current?.focus());return true;}setPhase(npcs||factions?"ready":"failed");setStatus("Cast refresh was partial; existing records are preserved.");return false;},[api,campaignId,npcs,factions]);
  useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;generation.current+=1}},[load]);useEffect(()=>{if(focusHeadingRequest!==undefined&&phase!=="loading")heading.current?.focus()},[focusHeadingRequest,phase]);
  async function mutate(kind:string,write:()=>Promise<unknown>){if(lock)return;const pending:Lock={kind,phase:"ambiguous"};writeLock(campaignId,pending);setLock(pending);setStatus(`${kind} submitted once; no automatic replay.`);try{const receipt=await write();const confirmed:Lock={kind,phase:"confirmed",receipt};writeLock(campaignId,confirmed);if(!mounted.current)return;setLock(confirmed);const fresh=await load();if(fresh){writeLock(campaignId,null);setLock(null);setStatus(`${kind} confirmed; authoritative cast refreshed.`);}else setStatus(`${kind} confirmed, but refresh was partial. Receipt and lock are preserved.`);}catch{if(mounted.current)setStatus(`${kind} outcome is ambiguous or stale. It will not be replayed.`);}}
  const npcInput=():CreateCampaignNpcHttpRequest=>({personaId:persona,publicState:{name:npcName},privateState:{goals,gmNotes:notes,merchantState:null},expectedRevision:revision,idempotencyKey:`npc-ui-${crypto.randomUUID()}`});
  const playerNpcs=npcs?api.previewNpcs(npcs):null, playerFactions=factions?api.previewFactions(factions):null;
  return <main className="studio-page" aria-labelledby="cast-heading"><div className="studio-shell"><header className="studio-header"><div><button className="back-link" onClick={onBack}>← Campaign</button><p className="eyebrow">{isGm?"GM CAST STUDIO":"VISIBLE CAST"}</p><h1 ref={heading} tabIndex={-1} id="cast-heading">Cast & factions</h1></div><button className="ghost" onClick={()=>void load(true)}>Refresh</button></header>{lock&&<section className="studio-lock" role="alert"><strong>{lock.phase==="confirmed"?"Confirmed command awaiting full refresh":"Command outcome unresolved"}</strong><p>Duplicate commands and automatic replay are blocked across reload.</p></section>}{status&&<p role="status">{status}</p>}{phase==="failed"&&<p role="alert">Cast could not be loaded.</p>}
    <div className="studio-grid">{npcs&&<section className="studio-panel"><h2>NPC roster</h2>{npcs.npcs.length?<ul className="cast-list">{npcs.npcs.map((npc)=><li key={npc.npcId}><h3><bdi dir="auto">{npc.publicState.name}</bdi></h3>{isGm&&npc.privateState&&<dl className="private-record"><div><dt>Goals</dt><dd><bdi dir="auto">{npc.privateState.goals||"None"}</bdi></dd></div><div><dt>GM notes</dt><dd><bdi dir="auto">{npc.privateState.gmNotes||"None"}</bdi></dd></div></dl>}<ul aria-label={`Relationships for ${npc.publicState.name}`}>{npcs.relationships.filter((item)=>item.npcId===npc.npcId).map((item)=><li key={`${item.npcId}:${item.subjectActorId}`}>Affinity {item.affinity}; trust {item.trust}; fear {item.fear}</li>)}</ul></li>)}</ul>:<p>No visible NPCs.</p>}
      {isGm&&<><form className="studio-form" onSubmit={(e)=>{e.preventDefault();if(previewed)void mutate("NPC creation",()=>api.createNpc(campaignId,npcInput()));}}><h3>Create NPC</h3><label>Persona ID<input required value={persona} onChange={(e)=>{setPersona(e.target.value);setPreviewed(false)}} /></label><label>Public name<input required value={npcName} onChange={(e)=>{setNpcName(e.target.value);setPreviewed(false)}} /></label><label>Private goals<textarea value={goals} onChange={(e)=>{setGoals(e.target.value);setPreviewed(false)}} /></label><label>GM notes<textarea value={notes} onChange={(e)=>{setNotes(e.target.value);setPreviewed(false)}} /></label><div className="button-row"><button type="button" className="ghost" disabled={Boolean(lock)||!npcName||!persona} onClick={()=>{const candidate:CampaignNpcsHttpResponse={npcs:[{npcId:"preview",publicState:{name:npcName},createdAt:new Date().toISOString(),personaId:persona,privateState:{goals,gmNotes:notes,merchantState:null}}],relationships:[]};setPreview(api.previewNpcs(candidate));setPreviewed(true)}}>Preview player projection</button><button className="primary" disabled={Boolean(lock)||!previewed}>Create after preview</button></div></form>
      <form className="studio-form" onSubmit={(e)=>{e.preventDefault();void mutate("NPC relationship command",()=>api.relationship(selectedNpc,{subjectActorId:actor,affinityDelta:1,trustDelta:0,fearDelta:0,reason,expectedRevision:revision,idempotencyKey:`relationship-ui-${crypto.randomUUID()}`}));}}><h3>Change relationship</h3><label>NPC<select required value={selectedNpc} onChange={(e)=>setSelectedNpc(e.target.value)}><option value="">Choose NPC</option>{npcs.npcs.map((npc)=><option key={npc.npcId} value={npc.npcId}>{npc.publicState.name}</option>)}</select></label><label>Subject actor ID<input required value={actor} onChange={(e)=>setActor(e.target.value)} /></label><label>Reason<input required value={reason} onChange={(e)=>setReason(e.target.value)} /></label><button className="primary" disabled={Boolean(lock)||!selectedNpc||!actor||!reason}>Apply +1 affinity</button></form></>}</section>}{factions&&<FactionStandingPanel data={factions} revision={revision} isGm={isGm} locked={Boolean(lock)} onPreview={(input)=>{const candidate:CampaignFactionsHttpResponse={factions:[{factionId:"preview",name:input.name,publicState:input.publicState,privateState:input.privateState,createdAt:new Date().toISOString()}],standings:[]};setPreview(api.previewFactions(candidate));}} onCreate={(input)=>mutate("Faction creation",()=>api.createFaction(campaignId,input))} onReputation={(id,input)=>mutate("Faction reputation command",()=>api.reputation(id,input))}/>}</div>
    {isGm&&Boolean(preview)&&<section className="projection-preview"><h2>Player projection preview</h2><p>This structure was rebuilt through the public contract. Private fields are absent.</p><pre>{JSON.stringify(preview,null,2)}</pre></section>}{!isGm&&Boolean(playerNpcs||playerFactions)&&<p className="sr-only">Player projection loaded.</p>}</div></main>;
}
