/** Quest repository composition boundary. */
export {
  createQuestReadRepository,
  getQuest,
  getStoryline,
  listClues,
  listObjectiveCompletions,
  listQuests,
  listRewards,
  listStorylines,
  QuestUnavailableError,
  type CreateQuestInput,
  type CreateRewardInput,
  type CreateStorylineInput,
  type Quest,
  type QuestClue,
  type QuestDetail,
  type QuestObjectiveCompletion,
  type QuestReadRepository,
  type QuestReward,
  type Storyline,
  type UpdateQuestInput,
  type UpdateStorylineInput,
} from "./questReadRepo.js";
export {
  addClue,
  addReward,
  completeObjective,
  createQuest,
  createQuestWriteRepository,
  createStoryline,
  grantReward,
  markClueDiscovered,
  reorderQuests,
  updateQuestStatus,
  updateStorylineStatus,
  type QuestWriteRepository,
} from "./questWriteRepo.js";
