import { createHash } from "node:crypto";
import type DatabaseDriver from "better-sqlite3";
import { adventureCommerceCandidateSchema, adventureCommercePublicReceiptSchema, adventureCommerceSelectionSchema,
  canonicalAgentJson, resourceIdSchema, utcIsoTimestampSchema, type AdventureCommerceCandidate,
  type AdventureCommercePublicReceipt } from "@velvet/contracts";
import { getM15ActorRevision, m15Authorized, type M15Dependencies } from "./actorResourceRepo.js";
import type { EconomyRepository } from "./economyRepo.js";

const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
type Scope={campaignId:string;turnId:string;sessionId:string;actorId:string;principalId:string;revision:number};
type Public=Omit<AdventureCommerceCandidate,"candidateId"|"digest">;
type Plan={quoteId:string;shopId:string;stockId:string;entryId:string|null;currencyCode:string;priceMinorUnits:number;sourceRevision:number;expiresAt:string};

export type VendorShopAssociation={campaignId:string;npcId:string;vendorLabel:string;shopId:string;shopLabel:string};
/** An exact vendor sale quote bound to one inventory revision and one visible vendor's buy policy. */
export interface VendorSaleQuote {
  quoteId:string;shopId:string;entryId:string;quantity:number;
  payout:{currency:{kind:"currency";packId:string;packVersion:string;definitionId:string};minorUnits:number};
  expiresAt:string;expectedRevision:number;
}
export interface AdventureCommerceRepository {
  associateNpcShop(principalId:string,campaignId:string,npcId:string,shopId:string):VendorShopAssociation;
  setShopBuyPolicy(principalId:string,campaignId:string,shopId:string,stockId:string,payoutUnitMinor:number):void;
  getNpcShop(principalId:string,campaignId:string,npcId:string):VendorShopAssociation|null;
  /** Creates a vendor sale quote a player can then sell against through the economy command lane. */
  requestVendorSaleQuote(principalId:string,campaignId:string,actorId:string,input:{entryId:string;quantity:number}):VendorSaleQuote|null;
  generateAdventureCommerceCandidates(principalId:string,turnId:string):AdventureCommerceCandidate[];
  executeAdventureCommerceProposal(principalId:string,turnId:string,proposalId:string):{commandId:string;receipt:AdventureCommercePublicReceipt};
  getAdventureCommercePublicReceipt(principalId:string,campaignId:string,commandId:string):AdventureCommercePublicReceipt|null;
  getAdventureCommerceNarrationReceipt(principalId:string,turnId:string,commandId:string):AdventureCommercePublicReceipt|null;
}

function scope(db:DatabaseDriver.Database,principal:string,turnId:string):Scope|null{const row=db.prepare(`SELECT turn.campaign_id campaignId,turn.id turnId,turn.session_id sessionId,turn.actor_id actorId,turn.principal_id principalId
  FROM adventure_turns turn JOIN campaigns campaign ON campaign.id=turn.campaign_id AND campaign.active_timeline_id=turn.timeline_id
  JOIN campaign_sessions attached ON attached.campaign_id=turn.campaign_id AND attached.session_id=turn.session_id
  JOIN sessions session ON session.id=attached.session_id AND session.state='active' AND session.stopped_at IS NULL
  JOIN campaign_memberships member ON member.campaign_id=turn.campaign_id AND member.principal_id=?
  WHERE turn.id=? AND turn.principal_id=? AND turn.mode='original' AND member.role<>'observer'`).get(principal,turnId,principal)as Omit<Scope,"revision">|undefined;
  return row&&m15Authorized(db,principal,row.campaignId,row.actorId)?{...row,revision:getM15ActorRevision(db,row.campaignId,row.actorId)}:null;}
function definitionLabel(db:DatabaseDriver.Database,campaign:string,kind:string,pack:string,version:string,id:string):string|null{const row=db.prepare(`SELECT visibility.public_definition_json value FROM campaign_catalog_current_pins pin JOIN rpg_catalog_definition_visibility visibility
  ON visibility.pack_id=pin.pack_id AND visibility.pack_version=pin.pack_version AND visibility.kind=? AND visibility.definition_id=? AND visibility.publicly_reachable=1
  WHERE pin.campaign_id=? AND pin.pack_id=? AND pin.pack_version=?`).get(kind,id,campaign,pack,version)as any;if(!row)return null;const value=JSON.parse(row.value);return typeof value.name==="string"?value.name:null;}
function visibleVendors(db:DatabaseDriver.Database,s:Scope):any[]{return db.prepare(`SELECT binding.npc_id,binding.shop_id,npc.public_name vendor_label,shop.name shop_label
  FROM campaign_npc_shop_bindings_v57 binding JOIN campaign_npcs_v28 npc ON npc.campaign_id=binding.campaign_id AND npc.npc_id=binding.npc_id
  JOIN rpg_shop_definitions_v25 shop ON shop.campaign_id=binding.campaign_id AND shop.shop_id=binding.shop_id
  JOIN campaign_npc_presence_v43 presence ON presence.campaign_id=binding.campaign_id AND presence.npc_id=binding.npc_id AND presence.session_id=? AND presence.state='present'
  JOIN campaign_actor_locations_v28 actor_location ON actor_location.campaign_id=binding.campaign_id AND actor_location.actor_id=? AND actor_location.session_id=? AND actor_location.location_id=presence.location_id
  JOIN campaign_locations_v28 location ON location.campaign_id=binding.campaign_id AND location.location_id=presence.location_id
  WHERE binding.campaign_id=? AND (location.visibility='public' OR EXISTS(SELECT 1 FROM campaign_location_discoveries_v28 discovery WHERE discovery.campaign_id=binding.campaign_id AND discovery.actor_id=? AND discovery.location_id=presence.location_id))
  ORDER BY npc.public_name,shop.name,binding.npc_id`).all(s.sessionId,s.actorId,s.sessionId,s.campaignId,s.actorId)as any[];}
function specs(db:DatabaseDriver.Database,s:Scope,issuedAt:string):Array<{public:Public;plan:Plan}>{const output:Array<{public:Public;plan:Plan}>=[],expiresAt=new Date(new Date(issuedAt).getTime()+300000).toISOString();
  const balance=(code:string)=>(db.prepare("SELECT balance_minor value FROM rpg_wallets_v25 WHERE campaign_id=? AND actor_id=? AND currency_code=?").get(s.campaignId,s.actorId,code)as any)?.value;
  for(const vendor of visibleVendors(db,s)){const stocks=db.prepare(`SELECT stock.*,policy.payout_unit_minor FROM rpg_shop_stock_v25 stock LEFT JOIN rpg_shop_buy_policies_v57 policy
      ON policy.campaign_id=stock.campaign_id AND policy.shop_id=stock.shop_id AND policy.stock_id=stock.stock_id WHERE stock.campaign_id=? AND stock.shop_id=? ORDER BY stock.stock_id`).all(s.campaignId,vendor.shop_id)as any[];
    for(const stock of stocks){const itemLabel=definitionLabel(db,s.campaignId,"item",stock.item_pack_id,stock.item_pack_version,stock.item_definition_id),currency=db.prepare("SELECT pack_id,pack_version,definition_id FROM rpg_currency_references_v25 WHERE campaign_id=? AND currency_code=?").get(s.campaignId,stock.currency_code)as any;
      if(!itemLabel||!currency)continue;const currencyLabel=definitionLabel(db,s.campaignId,"currency",currency.pack_id,currency.pack_version,currency.definition_id);if(!currencyLabel)continue;
      const wallet=balance(stock.currency_code);if(wallet===undefined)continue;
      const reference={kind:"item",packId:stock.item_pack_id,packVersion:stock.item_pack_version,definitionId:stock.item_definition_id};
      const existing=db.prepare("SELECT 1 FROM rpg_inventory_entries_v25 WHERE campaign_id=? AND actor_id=? AND entry_mode='stackable' AND item_pack_id=? AND item_pack_version=? AND item_definition_id=?").get(s.campaignId,s.actorId,stock.item_pack_id,stock.item_pack_version,stock.item_definition_id);
      const used=(db.prepare("SELECT count(*) value FROM rpg_inventory_entries_v25 WHERE campaign_id=? AND actor_id=?").get(s.campaignId,s.actorId)as any).value,capacity=(db.prepare("SELECT max value FROM rpg_actor_resources WHERE campaign_id=? AND actor_id=? AND name='inventory-capacity'").get(s.campaignId,s.actorId)as any)?.value??1000;
      if(stock.available_quantity>0&&stock.unit_price_minor>0&&wallet>=stock.unit_price_minor&&(existing||used<capacity)){const quoteId=`vendor-buy-quote:${sha(`${s.turnId}\0${stock.stock_id}`).slice(0,48)}`;
        db.prepare("INSERT OR IGNORE INTO rpg_shop_quotes_v25 VALUES(?,?,?,?,?,?,?,?,?,?)").run(quoteId,s.campaignId,stock.stock_id,vendor.shop_id,s.actorId,1,stock.unit_price_minor,stock.currency_code,issuedAt,expiresAt);
        output.push({public:{action:"buy",vendorLabel:vendor.vendor_label,shopLabel:vendor.shop_label,itemLabel,quantity:1,currencyLabel,priceMinorUnits:stock.unit_price_minor,consequence:`Pay ${stock.unit_price_minor} ${currencyLabel} and add 1 ${itemLabel} to inventory.`,confirmationRequired:true},plan:{quoteId,shopId:vendor.shop_id,stockId:stock.stock_id,entryId:null,currencyCode:stock.currency_code,priceMinorUnits:stock.unit_price_minor,sourceRevision:s.revision,expiresAt}});}
      const entries=db.prepare(`SELECT entry_id,quantity FROM rpg_inventory_entries_v25 WHERE campaign_id=? AND actor_id=? AND equipped=0 AND item_pack_id=? AND item_pack_version=? AND item_definition_id=? ORDER BY created_at,entry_id`).all(s.campaignId,s.actorId,stock.item_pack_id,stock.item_pack_version,stock.item_definition_id)as any[];
      for(const entry of entries){for(const action of (stock.payout_unit_minor?["sell","give"]:["give"]) as Array<"sell"|"give">){const price=action==="sell"?stock.payout_unit_minor:0;if(action==="sell"&&!price)continue;
          const quoteId=`vendor-${action}-quote:${sha(`${s.turnId}\0${stock.stock_id}\0${entry.entry_id}`).slice(0,48)}`;
          db.prepare("INSERT OR IGNORE INTO rpg_vendor_sale_quotes_v57 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(quoteId,s.campaignId,vendor.shop_id,stock.stock_id,s.actorId,entry.entry_id,1,action,price,stock.currency_code,s.revision,issuedAt,expiresAt);
          output.push({public:{action,vendorLabel:vendor.vendor_label,shopLabel:vendor.shop_label,itemLabel,quantity:1,currencyLabel,priceMinorUnits:price,consequence:action==="sell"?`Remove 1 ${itemLabel} and receive ${price} ${currencyLabel}.`:`Give 1 ${itemLabel} to ${vendor.vendor_label} without payment; it will not be dropped.`,confirmationRequired:true},plan:{quoteId,shopId:vendor.shop_id,stockId:stock.stock_id,entryId:entry.entry_id,currencyCode:stock.currency_code,priceMinorUnits:price,sourceRevision:s.revision,expiresAt}});}}
    }}return output;}
function frame(s:Scope,value:{public:Public;plan:Plan}){return{version:"v1",campaignId:s.campaignId,turnId:s.turnId,sessionId:s.sessionId,actorId:s.actorId,principalId:s.principalId,...value.public,privatePlan:value.plan};}

export function createAdventureCommerceRepository(db:DatabaseDriver.Database,deps:M15Dependencies,economy:EconomyRepository,guard:()=>void):AdventureCommerceRepository{
  const association=(principal:string,campaign:string,npc:string):VendorShopAssociation|null=>{resourceIdSchema.parse(principal);resourceIdSchema.parse(campaign);resourceIdSchema.parse(npc);if(!db.prepare("SELECT 1 FROM campaign_memberships WHERE campaign_id=? AND principal_id=?").get(campaign,principal))return null;const row=db.prepare(`SELECT binding.campaign_id campaignId,binding.npc_id npcId,npc.public_name vendorLabel,binding.shop_id shopId,shop.name shopLabel FROM campaign_npc_shop_bindings_v57 binding
    JOIN campaign_npcs_v28 npc ON npc.campaign_id=binding.campaign_id AND npc.npc_id=binding.npc_id JOIN rpg_shop_definitions_v25 shop ON shop.campaign_id=binding.campaign_id AND shop.shop_id=binding.shop_id WHERE binding.campaign_id=? AND binding.npc_id=?`).get(campaign,npc)as VendorShopAssociation|undefined;return row??null;};
  const verify=(row:any)=>{const receipt=adventureCommercePublicReceiptSchema.parse(JSON.parse(row.public_result_json));if(sha(canonicalAgentJson(receipt as never))!==row.result_digest)throw new Error("adventure commerce receipt is malformed");const source=db.prepare("SELECT result_digest,canonical_result_json FROM rpg_m15_receipts_v25 WHERE campaign_id=? AND actor_id=? AND command_id=? AND resulting_revision=?").get(row.campaign_id,row.actor_id,row.command_id,row.revision_after)as any;if(!source||source.result_digest!==row.source_result_digest||sha(source.canonical_result_json)!==source.result_digest)throw new Error("adventure commerce source receipt is malformed");return{commandId:row.command_id,receipt};};
  return{
    associateNpcShop(principal,campaign,npc,shop){guard();const role=(db.prepare("SELECT role FROM campaign_memberships WHERE campaign_id=? AND principal_id=?").get(campaign,principal)as any)?.role;if(role!=="owner"&&role!=="gm")throw new Error("vendor association requires owner or GM");const at=utcIsoTimestampSchema.parse(deps.clock.now().toISOString());return db.transaction(()=>{const valid=db.prepare(`SELECT 1 FROM campaign_npcs_v28 npc JOIN rpg_shop_definitions_v25 shop ON shop.campaign_id=npc.campaign_id WHERE npc.campaign_id=? AND npc.npc_id=? AND shop.shop_id=?`).get(campaign,npc,shop);if(!valid)throw new Error("NPC and shop must exist in the same campaign");const old=association(principal,campaign,npc);if(old){if(old.shopId!==shop)throw new Error("NPC already has a different shop");return old;}db.prepare("INSERT INTO campaign_npc_shop_bindings_v57 VALUES(?,?,?,?,?)").run(campaign,npc,shop,at,principal);return association(principal,campaign,npc)!;}).immediate();},
    setShopBuyPolicy(principal,campaign,shop,stock,payout){guard();const role=(db.prepare("SELECT role FROM campaign_memberships WHERE campaign_id=? AND principal_id=?").get(campaign,principal)as any)?.role;if(role!=="owner"&&role!=="gm")throw new Error("shop policy requires owner or GM");if(!Number.isSafeInteger(payout)||payout<0)throw new Error("payout must be non-negative");const row=db.prepare("SELECT currency_code FROM rpg_shop_stock_v25 WHERE campaign_id=? AND shop_id=? AND stock_id=?").get(campaign,shop,stock)as any;if(!row)throw new Error("shop stock is unavailable");db.prepare("INSERT INTO rpg_shop_buy_policies_v57 VALUES(?,?,?,?,?,?,?) ON CONFLICT(campaign_id,shop_id,stock_id) DO UPDATE SET payout_unit_minor=excluded.payout_unit_minor,currency_code=excluded.currency_code,accepted_at=excluded.accepted_at,accepted_by_principal_id=excluded.accepted_by_principal_id").run(campaign,shop,stock,payout,row.currency_code,deps.clock.now().toISOString(),principal);},
    getNpcShop:association,
    requestVendorSaleQuote(principal, campaign, actor, input){guard();
      const campaignId=resourceIdSchema.parse(campaign),actorId=resourceIdSchema.parse(actor);resourceIdSchema.parse(input.entryId);
      if(!Number.isSafeInteger(input.quantity)||input.quantity<1||input.quantity>1_000_000)return null;
      const role=(db.prepare("SELECT role FROM campaign_memberships WHERE campaign_id=? AND principal_id=?").get(campaignId,principal)as any)?.role;
      if(!role||role==="observer"||!m15Authorized(db,principal,campaignId,actorId))return null;
      const sessions=db.prepare(`SELECT attached.session_id FROM campaign_sessions attached JOIN sessions session
        ON session.id=attached.session_id AND session.state='active' AND session.stopped_at IS NULL WHERE attached.campaign_id=?`).all(campaignId)as Array<{session_id:string}>;
      if(sessions.length!==1)return null;
      const sessionId=sessions[0]!.session_id;
      const entry=db.prepare(`SELECT item_pack_id,item_pack_version,item_definition_id,quantity,equipped FROM rpg_inventory_entries_v25
        WHERE entry_id=? AND campaign_id=? AND actor_id=?`).get(input.entryId,campaignId,actorId)as any;
      if(!entry||entry.equipped||input.quantity>entry.quantity)return null;
      const revision=getM15ActorRevision(db,campaignId,actorId),at=utcIsoTimestampSchema.parse(deps.clock.now().toISOString()),expiresAt=new Date(new Date(at).getTime()+300000).toISOString();
      const scope:Scope={campaignId,turnId:"",sessionId,actorId,principalId:principal,revision};
      for(const vendor of visibleVendors(db,scope)){
        const stock=db.prepare(`SELECT stock.*,policy.payout_unit_minor FROM rpg_shop_stock_v25 stock
          JOIN rpg_shop_buy_policies_v57 policy ON policy.campaign_id=stock.campaign_id AND policy.shop_id=stock.shop_id AND policy.stock_id=stock.stock_id
          WHERE stock.campaign_id=? AND stock.shop_id=? AND stock.item_pack_id=? AND stock.item_pack_version=? AND stock.item_definition_id=? AND policy.payout_unit_minor>0
          ORDER BY stock.stock_id`).get(campaignId,vendor.shop_id,entry.item_pack_id,entry.item_pack_version,entry.item_definition_id)as any;
        if(!stock)continue;
        if(stock.payout_unit_minor>Math.floor(Number.MAX_SAFE_INTEGER/input.quantity))return null;
        const currency=db.prepare("SELECT pack_id,pack_version,definition_id FROM rpg_currency_references_v25 WHERE campaign_id=? AND currency_code=?").get(campaignId,stock.currency_code)as any;
        if(!currency)continue;
        const quoteId=`vendor-sale-quote:${sha(`${campaignId}\0${actorId}\0${input.entryId}\0${sessionId}\0${stock.stock_id}\0${input.quantity}`).slice(0,48)}`;
        db.prepare("INSERT OR REPLACE INTO rpg_vendor_sale_quotes_v57 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(quoteId,campaignId,vendor.shop_id,stock.stock_id,actorId,input.entryId,input.quantity,"sell",stock.payout_unit_minor,stock.currency_code,revision,at,expiresAt);
        return {quoteId,shopId:vendor.shop_id,entryId:input.entryId,quantity:input.quantity,
          payout:{currency:{kind:"currency",packId:currency.pack_id,packVersion:currency.pack_version,definitionId:currency.definition_id},minorUnits:stock.payout_unit_minor*input.quantity},
          expiresAt,expectedRevision:revision};
      }
      return null;},
    generateAdventureCommerceCandidates(principal,turnId){guard();return db.transaction(()=>{const old=db.prepare("SELECT * FROM adventure_commerce_batches_v57 WHERE turn_id=?").get(turnId)as any;if(old){const rows=db.prepare("SELECT public_json FROM adventure_commerce_candidates_v57 WHERE batch_id=? ORDER BY candidate_id").all(old.batch_id)as any[];const candidates=rows.map(row=>adventureCommerceCandidateSchema.parse(JSON.parse(row.public_json))),projection=canonicalAgentJson({version:"v1",candidates}as never);if(projection!==old.projection_json||sha(projection)!==old.projection_digest)throw new Error("commerce candidate projection is malformed");return candidates;}const s=scope(db,principal,turnId);if(!s)return[];const at=utcIsoTimestampSchema.parse(deps.clock.now().toISOString()),values=specs(db,s,at).map(value=>{const digest=sha(canonicalAgentJson(frame(s,value)as never));return{...value,candidateId:`commerce-candidate:${digest.slice(0,48)}`,digest};});if(values.length>512)throw new Error("too many commerce candidates");const candidates=values.map(value=>adventureCommerceCandidateSchema.parse({candidateId:value.candidateId,digest:value.digest,...value.public})).sort((a,b)=>a.candidateId.localeCompare(b.candidateId)),projection=canonicalAgentJson({version:"v1",candidates}as never),batchId=`commerce-batch:${sha(turnId).slice(0,48)}`;db.prepare("INSERT INTO adventure_commerce_batches_v57 VALUES(?,?,?,?,?,?,?)").run(batchId,s.campaignId,turnId,projection,sha(projection),candidates.length,at);const insert=db.prepare("INSERT INTO adventure_commerce_candidates_v57 VALUES(?,?,?,?,?,?,?,?,?,?,?,?)");for(const value of values){const candidate=candidates.find(item=>item.candidateId===value.candidateId)!;insert.run(value.candidateId,value.digest,batchId,s.campaignId,turnId,s.sessionId,s.actorId,s.principalId,value.public.action,canonicalAgentJson(candidate as never),canonicalAgentJson(value.plan as never),at);}return candidates;}).immediate();},
    executeAdventureCommerceProposal(principal,turnId,proposalId){guard();return db.transaction(()=>{const prior=db.prepare("SELECT * FROM adventure_commerce_executions_v57 WHERE turn_id=?").get(turnId)as any;if(prior){if(prior.proposal_id!==proposalId)throw new Error("commerce replay changed");return verify(prior);}const bound=db.prepare(`SELECT binding.*,candidate.public_json,candidate.private_json,candidate.candidate_digest,proposal.arguments_json,proposal.requires_confirmation,decision.decision FROM adventure_commerce_bindings_v57 binding JOIN adventure_commerce_candidates_v57 candidate ON candidate.candidate_id=binding.candidate_id JOIN tool_proposals proposal ON proposal.proposal_id=binding.proposal_id LEFT JOIN confirmation_decisions decision ON decision.proposal_id=proposal.proposal_id WHERE binding.turn_id=? AND binding.proposal_id=?`).get(turnId,proposalId)as any,s=scope(db,principal,turnId);if(!bound||!s||!bound.requires_confirmation||bound.decision!=="approved")throw new Error("commerce proposal is not executable");const args=JSON.parse(bound.arguments_json),selection=adventureCommerceSelectionSchema.parse({candidateId:args.candidateId,digest:args.digest});if(selection.candidateId!==bound.candidate_id||selection.digest!==bound.candidate_digest)throw new Error("commerce selection changed");const publicValue=adventureCommerceCandidateSchema.parse(JSON.parse(bound.public_json)),plan=JSON.parse(bound.private_json)as Plan;if(s.revision!==plan.sourceRevision||plan.expiresAt<=deps.clock.now().toISOString())throw new Error("commerce quote is stale");
      if(!visibleVendors(db,s).some(value=>value.shop_id===plan.shopId))throw new Error("vendor is no longer visible");const before=(db.prepare("SELECT balance_minor value FROM rpg_wallets_v25 WHERE campaign_id=? AND actor_id=? AND currency_code=?").get(s.campaignId,s.actorId,plan.currencyCode)as any)?.value;if(before===undefined)throw new Error("wallet is unavailable");const result=economy.mutateEconomyForActor(principal,s.campaignId,s.actorId,{kind:publicValue.action==="buy"?"purchase_from_shop":"sell_to_shop",quoteId:plan.quoteId,expectedRevision:s.revision,idempotencyKey:bound.execution_idempotency_key});const after=(db.prepare("SELECT balance_minor value FROM rpg_wallets_v25 WHERE campaign_id=? AND actor_id=? AND currency_code=?").get(s.campaignId,s.actorId,plan.currencyCode)as any).value,receipt=adventureCommercePublicReceiptSchema.parse({action:publicValue.action,vendorLabel:publicValue.vendorLabel,shopLabel:publicValue.shopLabel,itemLabel:publicValue.itemLabel,quantity:publicValue.quantity,currencyLabel:publicValue.currencyLabel,priceMinorUnits:publicValue.priceMinorUnits,debitMinorUnits:publicValue.action==="buy"?publicValue.priceMinorUnits:0,creditMinorUnits:publicValue.action==="buy"?0:publicValue.priceMinorUnits,balanceBefore:before,balanceAfter:after,revisionBefore:result.receipt.revisionBefore,revisionAfter:result.receipt.revisionAfter,occurredAt:result.receipt.occurredAt}),source=db.prepare("SELECT result_digest FROM rpg_m15_receipts_v25 WHERE campaign_id=? AND actor_id=? AND command_id=?").get(s.campaignId,s.actorId,result.receipt.commandId)as any,json=canonicalAgentJson(receipt as never);db.prepare("INSERT INTO adventure_commerce_executions_v57 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(`commerce-execution:${sha(`${turnId}\0${proposalId}`).slice(0,48)}`,bound.candidate_id,s.campaignId,turnId,proposalId,bound.provider_call_id,bound.provider_tool_call_id,result.receipt.commandId,s.actorId,result.receipt.revisionBefore,result.receipt.revisionAfter,source.result_digest,json,sha(json),result.receipt.occurredAt);return{commandId:result.receipt.commandId,receipt};}).immediate();},
    getAdventureCommercePublicReceipt(principal,campaign,command){const row=db.prepare(`SELECT execution.* FROM adventure_commerce_executions_v57 execution JOIN campaign_memberships member ON member.campaign_id=execution.campaign_id AND member.principal_id=? WHERE execution.campaign_id=? AND execution.command_id=?`).get(principal,campaign,command)as any;return row?verify(row).receipt:null;},
    getAdventureCommerceNarrationReceipt(principal,turnId,command){const row=db.prepare(`SELECT execution.* FROM adventure_commerce_executions_v57 execution JOIN adventure_turns turn ON turn.id=? AND turn.campaign_id=execution.campaign_id JOIN campaign_memberships member ON member.campaign_id=turn.campaign_id AND member.principal_id=? LEFT JOIN campaign_actor_private_state control ON control.campaign_id=turn.campaign_id AND control.actor_id=turn.actor_id WHERE execution.turn_id=? AND execution.command_id=? AND (member.role IN('owner','gm') OR control.controller_principal_id=?)`).get(turnId,principal,turnId,command,principal)as any;return row?verify(row).receipt:null;},
  };}
