import { createHash } from "node:crypto";
import type DatabaseDriver from "better-sqlite3";
import { adventureCombatConsumableCandidateSchema,adventureCombatConsumablePublicReceiptSchema,adventureCombatPowerCandidateSchema,adventureCombatPowerPublicReceiptSchema,
  adventurePowerCandidateSchema,adventurePowerPublicReceiptSchema,adventurePowerRestSelectionSchema,
  adventureRestCandidateSchema,adventureRestPublicReceiptSchema,canonicalAgentJson,resourceIdSchema,utcIsoTimestampSchema,
  type AdventureCombatConsumableCandidate,type AdventureCombatConsumablePublicReceipt,type AdventurePowerCandidate,
  type AdventurePowerPublicReceipt,type AdventureRestCandidate,type AdventureRestPublicReceipt,type UseConsumableCommandResult,type AdventureCombatPowerCandidate,type AdventureCombatPowerPublicReceipt } from "@velvet/contracts";
import type { M16Dependencies } from "./effectRepo.js";
import type { PowerRepository } from "./powerRepo.js";
import type { RestRepository } from "./restRepo.js";
import { actorHasActiveEncounter } from "./encounter/activeEncounterPolicy.js";
import type { EncounterRepository } from "./encounterRepo.js";
import { buildCombatPowerLegalActions } from "./encounter/combatPowerRuntime.js";
import { exactPairParameters, stripCandidateLabels } from "../agent/providerCandidateProjection.js";

const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
const label=(value:string)=>value.split(/[-_:]+/u).filter(Boolean).map(part=>part[0]!.toUpperCase()+part.slice(1)).join(" ").slice(0,200);
type Scope={campaignId:string;turnId:string;sessionId:string;actorId:string;principalId:string;timelineId:string};
type ActionKind="power"|"rest"|"combat-consumable"|"combat-power";
type Spec={kind:ActionKind;publicValue:any;privateValue:any;frame:any};

export interface AdventurePowerRestRepository {
  generateAdventurePowerCandidates(principalId:string,turnId:string):AdventurePowerCandidate[];
  generateAdventureRestCandidates(principalId:string,turnId:string):AdventureRestCandidate[];
  generateAdventureCombatConsumableCandidates(principalId:string,turnId:string):AdventureCombatConsumableCandidate[];
  generateAdventureCombatPowerCandidates(principalId:string,turnId:string):AdventureCombatPowerCandidate[];
  executeAdventurePowerRestProposal(principalId:string,turnId:string,proposalId:string):{commandId:string;receipt:AdventurePowerPublicReceipt|AdventureRestPublicReceipt|AdventureCombatConsumablePublicReceipt|AdventureCombatPowerPublicReceipt};
  getAdventurePowerPublicReceipt(principalId:string,campaignId:string,commandId:string):AdventurePowerPublicReceipt|null;
  getAdventureRestPublicReceipt(principalId:string,campaignId:string,commandId:string):AdventureRestPublicReceipt|null;
  getAdventureCombatConsumablePublicReceipt(principalId:string,campaignId:string,commandId:string):AdventureCombatConsumablePublicReceipt|null;
  getAdventureCombatPowerPublicReceipt(principalId:string,campaignId:string,commandId:string):AdventureCombatPowerPublicReceipt|null;
  getAdventurePowerRestNarrationReceipt(principalId:string,turnId:string,commandId:string):({kind:"power"}&AdventurePowerPublicReceipt)|({kind:"rest"}&AdventureRestPublicReceipt)|({kind:"combat-consumable"}&AdventureCombatConsumablePublicReceipt)|({kind:"combat-power"}&AdventureCombatPowerPublicReceipt)|null;
}

function baseScope(db:DatabaseDriver.Database,principalId:string,turnId:string):Scope|null {const row=db.prepare(`SELECT turn.campaign_id campaignId,turn.id turnId,turn.session_id sessionId,turn.actor_id actorId,
    turn.principal_id principalId,turn.timeline_id timelineId FROM adventure_turns turn JOIN campaigns campaign ON campaign.id=turn.campaign_id AND campaign.active_timeline_id=turn.timeline_id
    JOIN campaign_sessions attached ON attached.campaign_id=turn.campaign_id AND attached.session_id=turn.session_id JOIN sessions session ON session.id=attached.session_id AND session.state='active' AND session.stopped_at IS NULL
    JOIN campaign_memberships member ON member.campaign_id=turn.campaign_id AND member.principal_id=? LEFT JOIN campaign_actor_private_state control ON control.campaign_id=turn.campaign_id AND control.actor_id=turn.actor_id
    WHERE turn.id=? AND turn.principal_id=? AND turn.mode='original' AND member.role<>'observer' AND (member.role IN('owner','gm') OR control.controller_principal_id=?)`)
    .get(principalId,turnId,principalId,principalId) as Scope|undefined;
  return row??null;}
function scope(db:DatabaseDriver.Database,principalId:string,turnId:string):Scope|null {const row=baseScope(db,principalId,turnId);
  return row&&!actorHasActiveEncounter(db,row.campaignId,row.actorId)?row:null;}
function actorLabels(db:DatabaseDriver.Database,campaignId:string){return new Map((db.prepare(`SELECT actor.id,COALESCE(persona.name,'Campaign actor') name FROM campaign_actors actor
  LEFT JOIN campaign_characters character ON character.campaign_id=actor.campaign_id AND character.id=actor.campaign_character_id LEFT JOIN characters persona ON persona.id=character.character_id WHERE actor.campaign_id=?`).all(campaignId)as any[]).map(row=>[row.id,String(row.name).slice(0,200)]));}
function participantIds(db:DatabaseDriver.Database,value:Scope){return new Set((db.prepare(`SELECT actor.id FROM campaign_actors actor JOIN campaign_characters character ON character.campaign_id=actor.campaign_id AND character.id=actor.campaign_character_id
  JOIN session_characters participant ON participant.character_id=character.character_id AND participant.session_id=? WHERE actor.campaign_id=? AND actor.kind='player-character'`).all(value.sessionId,value.campaignId)as any[]).map(row=>row.id));}
function powerName(db:DatabaseDriver.Database,campaignId:string,ref:any):string|null{const row=db.prepare(`SELECT visibility.public_definition_json FROM campaign_catalog_current_pins pin JOIN rpg_catalog_definition_visibility visibility
  ON visibility.pack_id=pin.pack_id AND visibility.pack_version=pin.pack_version AND visibility.kind=? AND visibility.definition_id=? AND visibility.publicly_reachable=1
  WHERE pin.campaign_id=? AND pin.pack_id=? AND pin.pack_version=?`).get(ref.kind,ref.definitionId,campaignId,ref.packId,ref.packVersion)as any;
  if(!row)return null;const name=JSON.parse(row.public_definition_json).name;return typeof name==="string"&&name.trim()?name.trim().slice(0,200):null;}
function revision(db:DatabaseDriver.Database,campaignId:string,actorId:string,family:"m15"|"m16"){return(db.prepare(`SELECT revision FROM rpg_${family}_mutation_revisions_v${family==="m15"?"25":"26"} WHERE campaign_id=? AND actor_id=?`).get(campaignId,actorId)as any)?.revision??0;}

function powerSpecs(db:DatabaseDriver.Database,powers:PowerRepository,value:Scope):Spec[]{const snapshot=powers.getActorPowerSnapshot(value.principalId,value.actorId);if(!snapshot)return[];
  const labels=actorLabels(db,value.campaignId),participants=participantIds(db,value),uses=new Map(snapshot.uses.map(item=>[canonicalAgentJson(item.powerRef as never),item]));
  const slots=new Map(snapshot.slots.map(item=>[item.slotId,item]));const output:Spec[]=[];
  for(const command of snapshot.legalCommands){const name=powerName(db,value.campaignId,command.powerRef);if(!name)continue;
    const targets=command.targeting==="self"?[value.actorId]:command.validTargets.map(item=>item.actorId).filter(id=>participants.has(id)&&!actorHasActiveEncounter(db,value.campaignId,id));
    const targetSets=command.targeting==="self"?[[value.actorId]]:command.targeting==="single"?targets.map(id=>[id]):targets.length?[targets.slice(0,command.maxTargets)]:[];
    for(const selected of targetSets){const targetNames=selected.map(id=>labels.get(id)).filter((item):item is string=>Boolean(item));if(targetNames.length!==selected.length)continue;
      const costs=command.costs.map(cost=>cost.kind==="slot"?`1 level ${cost.slotId.slice(5)} spell slot`:`1 use of ${name}`);
      const costDeltas=command.costs.map(cost=>{const state=cost.kind==="slot"?slots.get(cost.slotId):uses.get(canonicalAgentJson(command.powerRef as never));return{label:cost.kind==="slot"?`Level ${cost.slotId.slice(5)} spell slot`:`${name} uses`,before:state!.current,after:state!.current-1};});
      const privateValue={powerRef:command.powerRef,targetIds:command.targeting==="self"?[]:selected,choices:[],sourceRevision:snapshot.revision,
        targetRevisions:selected.filter(id=>id!==value.actorId).map(actorId=>({actorId,revision:revision(db,value.campaignId,actorId,"m16")})),costDeltas};
      const publicValue={powerName:name,targets:targetNames,costs,concentration:command.concentration,effects:command.effectKinds,confirmationRequired:true as const};
      output.push({kind:"power",publicValue,privateValue,frame:{version:"v1",...value,kind:"power",...publicValue,...privateValue}});
    }}return output;}
function restSpecs(rest:RestRepository,value:Scope):Spec[]{return rest.previewRests(value.principalId,value.campaignId,value.actorId).map(option=>{const publicValue={restKind:option.kind,restName:option.kind==="short"?"Short rest":"Long rest",recovery:option.recovery.resources.map(delta=>({label:label(delta.resourceId),before:delta.before,after:delta.after})),confirmationRequired:true as const};
  const privateValue={restKind:option.kind,sourceRevision:option.revision,recovery:option.recovery,...(option.hitDiceToSpend===undefined?{}:{hitDiceToSpend:option.hitDiceToSpend})};return{kind:"rest",publicValue,privateValue,frame:{version:"v1",...value,kind:"rest",...publicValue,...privateValue}};});}

function combatantLabel(db:DatabaseDriver.Database,combatantId:string):string|null {const row=db.prepare(`SELECT combatant.combatant_kind,combatant.enemy_definition_id,persona.name,
    definition.public_definition_json FROM combatant LEFT JOIN campaign_actors actor ON actor.id=combatant.actor_id AND actor.campaign_id=combatant.campaign_id
    LEFT JOIN campaign_characters character ON character.id=actor.campaign_character_id AND character.campaign_id=actor.campaign_id
    LEFT JOIN characters persona ON persona.id=character.character_id
    LEFT JOIN rpg_catalog_definitions definition ON definition.pack_id=combatant.enemy_pack_id
      AND definition.pack_version=combatant.enemy_pack_version AND definition.kind IN('enemy','enemy-template')
      AND definition.definition_id=combatant.enemy_definition_id
    WHERE combatant.combatant_id=?`).get(combatantId)as any;
  if(!row)return null;if(typeof row.name==="string"&&row.name.trim())return row.name.trim().slice(0,200);
  try{const name=JSON.parse(row.public_definition_json).name;return typeof name==="string"&&name.trim()?name.trim().slice(0,200):null;}catch{const provenance=db.prepare(`SELECT definition.definition_json FROM encounter_enemy_provenance_v31 provenance JOIN rpg_catalog_definitions definition ON definition.pack_id=provenance.pack_id AND definition.pack_version=provenance.pack_version AND definition.kind=provenance.kind AND definition.definition_id=provenance.definition_id WHERE provenance.combatant_id=?`).get(combatantId)as any;try{const name=JSON.parse(provenance?.definition_json).name;return typeof name==="string"&&name.trim()?name.trim().slice(0,200):null;}catch{return typeof row.enemy_definition_id==="string"?label(row.enemy_definition_id.split(":").at(-1)!):null;}}}
function itemName(db:DatabaseDriver.Database,campaignId:string,ref:any):string|null {const row=db.prepare(`SELECT visibility.public_definition_json FROM campaign_catalog_current_pins pin
    JOIN rpg_catalog_definition_visibility visibility ON visibility.pack_id=pin.pack_id AND visibility.pack_version=pin.pack_version
      AND visibility.kind='item' AND visibility.definition_id=? AND visibility.publicly_reachable=1
    WHERE pin.campaign_id=? AND pin.pack_id=? AND pin.pack_version=?`).get(ref.definitionId,campaignId,ref.packId,ref.packVersion)as any;
  const fallback=db.prepare(`SELECT public_definition_json FROM rpg_catalog_definitions WHERE pack_id=? AND pack_version=? AND kind='item' AND definition_id=?
    AND EXISTS(SELECT 1 FROM campaign_catalog_current_pins WHERE campaign_id=? AND pack_id=? AND pack_version=?)`).get(ref.packId,ref.packVersion,ref.definitionId,campaignId,ref.packId,ref.packVersion)as any;
  try{const name=JSON.parse(row?.public_definition_json??fallback?.public_definition_json).name;return typeof name==="string"&&name.trim()?name.trim().slice(0,200):null;}catch{return null;}}
function combatSpecs(db:DatabaseDriver.Database,encounters:EncounterRepository,value:Scope):Spec[]{const combat=db.prepare(`SELECT encounter.encounter_id encounterId,encounter.round_number roundNumber,root.revision combatRevision,current.combatant_id actingCombatantId
    FROM encounter JOIN combat_mutation_revisions_v27 root ON root.encounter_id=encounter.encounter_id
    JOIN combatant current ON current.encounter_id=encounter.encounter_id AND current.combatant_id=encounter.current_turn_combatant_id
    WHERE encounter.campaign_id=? AND encounter.session_id=? AND encounter.status='active' AND current.actor_id=?`)
    .get(value.campaignId,value.sessionId,value.actorId)as any;if(!combat)return[];
  const combatState=encounters.getCombatState(value.principalId,combat.encounterId);
  const actingRevision=revision(db,value.campaignId,value.actorId,"m15");const output:Spec[]=[];
  for(const action of encounters.getUseConsumableLegalActions(value.principalId,combat.encounterId)){if(action.actingCombatantId!==combat.actingCombatantId)continue;
    const targetState=combatState?.combatants.find(item=>item.combatantId===action.target.combatantId),name=itemName(db,value.campaignId,action.item),
      target=combatantLabel(db,action.target.combatantId)??(targetState?.kind==="enemy"&&targetState.template?label(targetState.template.definitionId.split(":").at(-1)!):null);if(!name||!target)continue;
    const targetActor=(db.prepare("SELECT actor_id FROM combatant WHERE encounter_id=? AND combatant_id=?").get(combat.encounterId,action.target.combatantId)as any)?.actor_id??null;
    const targetRevision=targetActor===null?null:targetActor===value.actorId?actingRevision:revision(db,value.campaignId,targetActor,"m15");
    const consequences=action.effectPlan.effects.map(({effect})=>effect.kind==="damage"?{kind:"damage"as const,label:`${effect.dice.count}d${effect.dice.sides}${effect.dice.modifier?effect.dice.modifier>0?`+${effect.dice.modifier}`:effect.dice.modifier:""} ${label(effect.damageType)} damage`}
      :effect.kind==="healing"?{kind:"healing"as const,label:`${effect.dice.count}d${effect.dice.sides}${effect.dice.modifier?effect.dice.modifier>0?`+${effect.dice.modifier}`:effect.dice.modifier:""} healing`}
      :{kind:"resource"as const,label:`${effect.amount>=0?"Gain":"Spend"} ${Math.abs(effect.amount)} ${label(effect.resource)}`});
    const publicValue={itemName:name,target,quantity:1 as const,actionCost:"action"as const,consequences,confirmationRequired:true as const};
    const privateValue={encounterId:combat.encounterId,roundBefore:combat.roundNumber,legalActionId:action.legalActionId,
      inventoryEntryId:action.inventoryEntryId,item:action.item,targetCombatantId:action.target.combatantId,targetActorBacked:action.target.actorBacked,
      expectedCombatRevision:combat.combatRevision,expectedActingM15Revision:actingRevision,expectedTargetM15Revision:targetRevision};
    output.push({kind:"combat-consumable",publicValue,privateValue,frame:{version:"v1",...value,kind:"combat-consumable",...publicValue,...privateValue}});
  }return output;}

function combatPowerSpecs(db:DatabaseDriver.Database,value:Scope):Spec[]{const combat=db.prepare(`SELECT encounter.encounter_id encounterId,encounter.round_number roundNumber,root.revision combatRevision
    FROM encounter JOIN combat_mutation_revisions_v27 root USING(encounter_id) JOIN combatant current ON current.encounter_id=encounter.encounter_id AND current.combatant_id=encounter.current_turn_combatant_id
    WHERE encounter.campaign_id=? AND encounter.session_id=? AND encounter.status='active' AND current.actor_id=?`).get(value.campaignId,value.sessionId,value.actorId)as any;if(!combat)return[];
  return buildCombatPowerLegalActions(db,value.principalId,combat.encounterId).flatMap(action=>{const target=combatantLabel(db,action.targetCombatantId);if(!target)return[];const effects=action.definition.mechanics.effects as any[];
    const consequences=effects.map(effect=>effect.type==="damage"?{kind:"damage"as const,label:`${effect.dice.count}d${effect.dice.sides}${effect.dice.modifier?effect.dice.modifier>0?`+${effect.dice.modifier}`:effect.dice.modifier:""} ${label(effect.damageType)} damage (automatic effect)`}:effect.type==="healing"?{kind:"healing"as const,label:`${effect.dice.count}d${effect.dice.sides}${effect.dice.modifier?`+${effect.dice.modifier}`:""} healing`}:{kind:"effect"as const,label:effect.type==="condition"?`${label(effect.condition)} for ${effect.durationRounds} rounds`:`${effect.amount>=0?"+":""}${effect.amount} ${label(effect.statistic)} (${effect.duration})`});
    const costs=action.cost?[action.cost.kind==="slot"?`1 level ${action.cost.id.slice(5)} spell slot`:`1 use of ${action.definition.name}`]:[],concentration=action.definition.reference.kind==="spell"&&(action.definition as any).mechanics.concentration;
     const publicValue={powerName:action.definition.name,target,actionCost:action.definition.mechanics.actionCost,costs,consequences,concentration,confirmationRequired:true as const};
    const privateValue={encounterId:action.encounterId,roundBefore:combat.roundNumber,legalActionId:action.legalActionId,powerRef:action.powerRef,targetCombatantId:action.targetCombatantId,sourceM15Revision:revision(db,value.campaignId,action.sourceActorId,"m15"),sourceM16Revision:revision(db,value.campaignId,action.sourceActorId,"m16"),targetM15Revision:action.targetActorId?revision(db,value.campaignId,action.targetActorId,"m15"):null,targetM16Revision:action.targetActorId?revision(db,value.campaignId,action.targetActorId,"m16"):null,expectedCombatRevision:combat.combatRevision};
    return[{kind:"combat-power"as const,publicValue,privateValue,frame:{version:"v1",...value,kind:"combat-power",...publicValue,...privateValue}}];});}

export function createAdventurePowerRestRepository(db:DatabaseDriver.Database,deps:M16Dependencies,powers:PowerRepository,rest:RestRepository,encounters:EncounterRepository,guard:()=>void):AdventurePowerRestRepository{
  const specs=(kind:ActionKind,value:Scope)=>kind==="power"?powerSpecs(db,powers,value):kind==="rest"?restSpecs(rest,value):kind==="combat-consumable"?combatSpecs(db,encounters,value):combatPowerSpecs(db,value);
  const generate=(kind:ActionKind,principalInput:string,turnInput:string)=>{guard();const principal=resourceIdSchema.parse(principalInput),turnId=resourceIdSchema.parse(turnInput);return db.transaction(()=>{const current=kind==="combat-consumable"||kind==="combat-power"?baseScope(db,principal,turnId):scope(db,principal,turnId);if(!current)return[];
    const old=db.prepare("SELECT * FROM adventure_exact_action_batches_v56 WHERE turn_id=? AND action_kind=?").get(turnId,kind)as any;if(old){const rows=db.prepare("SELECT public_json FROM adventure_exact_action_candidates_v56 WHERE batch_id=? ORDER BY candidate_id").all(old.batch_id)as any[];
      const candidates=rows.map(row=>JSON.parse(row.public_json)),projection=canonicalAgentJson({version:"v1",candidates}as never);if(projection!==old.projection_json||sha(projection)!==old.projection_digest)throw new Error("adventure action projection is malformed");return candidates;}
    const at=utcIsoTimestampSchema.parse(deps.clock.now().toISOString()),values=specs(kind,current).map(item=>{const digest=sha(canonicalAgentJson(item.frame as never));return{...item,candidateId:`${kind}-candidate:${digest.slice(0,48)}`,digest};});
    if(values.length>512)throw new Error("too many adventure action candidates");const candidates=values.map(item=>kind==="power"?adventurePowerCandidateSchema.parse({candidateId:item.candidateId,digest:item.digest,...item.publicValue}):kind==="rest"?adventureRestCandidateSchema.parse({candidateId:item.candidateId,digest:item.digest,...item.publicValue}):kind==="combat-consumable"?adventureCombatConsumableCandidateSchema.parse({candidateId:item.candidateId,digest:item.digest,...item.publicValue}):adventureCombatPowerCandidateSchema.parse({candidateId:item.candidateId,digest:item.digest,...item.publicValue})).sort((a,b)=>a.candidateId.localeCompare(b.candidateId));
    const projection=canonicalAgentJson({version:"v1",candidates}as never),batchId=`${kind}-batch:${sha(`${turnId}\0${kind}`).slice(0,48)}`;db.prepare("INSERT INTO adventure_exact_action_batches_v56 VALUES(?,?,?,?,?,?,?,?)").run(batchId,current.campaignId,turnId,kind,projection,sha(projection),candidates.length,at);
    const insert=db.prepare("INSERT INTO adventure_exact_action_candidates_v56 VALUES(?,?,?,?,?,?,?,?,?,?,?,?)");for(const item of values){const candidate=candidates.find(value=>value.candidateId===item.candidateId)!;insert.run(item.candidateId,item.digest,batchId,current.campaignId,turnId,current.sessionId,current.actorId,current.principalId,kind,canonicalAgentJson(candidate as never),canonicalAgentJson(item.privateValue as never),at);}return candidates;}).immediate();};
  const verify=(row:any)=>{const receipt=row.action_kind==="power"?adventurePowerPublicReceiptSchema.parse(JSON.parse(row.public_result_json)):row.action_kind==="rest"?adventureRestPublicReceiptSchema.parse(JSON.parse(row.public_result_json)):row.action_kind==="combat-consumable"?adventureCombatConsumablePublicReceiptSchema.parse(JSON.parse(row.public_result_json)):adventureCombatPowerPublicReceiptSchema.parse(JSON.parse(row.public_result_json));if(sha(row.public_result_json)!==row.result_digest)throw new Error("adventure action receipt is malformed");
    const source=row.action_kind==="combat-consumable"||row.action_kind==="combat-power"?db.prepare(`SELECT receipt.canonical_result_json,receipt.result_digest FROM combat_receipts_v27 receipt JOIN encounter ON encounter.encounter_id=receipt.encounter_id WHERE encounter.campaign_id=? AND receipt.command_id=? AND receipt.resulting_revision=?`).get(row.campaign_id,row.command_id,row.revision_after)as any
      :db.prepare(`SELECT canonical_result_json,result_digest FROM ${row.action_kind==="power"?"rpg_m16_receipts_v26":"rpg_m15_receipts_v25"} WHERE campaign_id=? AND actor_id=? AND command_id=? AND resulting_revision=?`).get(row.campaign_id,row.actor_id,row.command_id,row.revision_after)as any;
    if(!source||source.result_digest!==row.source_result_digest||sha(source.canonical_result_json)!==source.result_digest)throw new Error("adventure action source receipt is malformed");return{commandId:row.command_id,receipt};};
  return{generateAdventurePowerCandidates:(principal,turnId)=>generate("power",principal,turnId)as AdventurePowerCandidate[],generateAdventureRestCandidates:(principal,turnId)=>generate("rest",principal,turnId)as AdventureRestCandidate[],
    generateAdventureCombatConsumableCandidates:(principal,turnId)=>generate("combat-consumable",principal,turnId)as AdventureCombatConsumableCandidate[],
    generateAdventureCombatPowerCandidates:(principal,turnId)=>generate("combat-power",principal,turnId)as AdventureCombatPowerCandidate[],
    executeAdventurePowerRestProposal(principalInput,turnInput,proposalInput){guard();const principal=resourceIdSchema.parse(principalInput),turnId=resourceIdSchema.parse(turnInput),proposalId=resourceIdSchema.parse(proposalInput);return db.transaction(()=>{const old=db.prepare("SELECT * FROM adventure_exact_action_executions_v56 WHERE turn_id=?").get(turnId)as any;if(old){if(old.proposal_id!==proposalId)throw new Error("adventure action replay changed");return verify(old);}
      const bound=db.prepare(`SELECT binding.*,candidate.public_json,candidate.private_json,candidate.candidate_digest,candidate.action_kind,proposal.arguments_json,proposal.requires_confirmation,decision.decision
        FROM adventure_exact_action_proposal_bindings_v56 binding JOIN adventure_exact_action_candidates_v56 candidate ON candidate.candidate_id=binding.candidate_id
        JOIN tool_proposals proposal ON proposal.proposal_id=binding.proposal_id LEFT JOIN confirmation_decisions decision ON decision.proposal_id=proposal.proposal_id WHERE binding.turn_id=? AND binding.proposal_id=?`).get(turnId,proposalId)as any;
       const current=bound?.action_kind==="combat-consumable"||bound?.action_kind==="combat-power"?baseScope(db,principal,turnId):scope(db,principal,turnId);if(!bound||!current||!bound.requires_confirmation||bound.decision!=="approved")throw new Error("adventure action proposal is not executable");const storedArguments=JSON.parse(bound.arguments_json);const selection=adventurePowerRestSelectionSchema.parse({candidateId:storedArguments.candidateId,digest:storedArguments.digest});
      if(selection.candidateId!==bound.candidate_id||selection.digest!==bound.candidate_digest)throw new Error("adventure action selection changed");const response=db.prepare(`SELECT response.response_json,response.response_digest,context.request_json,context.request_digest FROM agent_provider_responses_v39 response JOIN agent_provider_contexts_v39 context ON context.context_id=response.context_id WHERE response.turn_id=? AND response.provider_call_id=? AND response.status='succeeded'`).get(turnId,bound.provider_call_id)as any;
       const settled=response&&JSON.parse(response.response_json),call=settled?.calls?.find((item:any)=>item.providerToolCallId===bound.provider_tool_call_id),toolName=bound.action_kind==="power"?"exact_power_use.select":bound.action_kind==="rest"?"exact_rest.select":bound.action_kind==="combat-consumable"?"exact_combat_consumable.select":"exact_combat_power.select",request=response&&JSON.parse(response.request_json);
      const batch=db.prepare("SELECT projection_json,projection_digest FROM adventure_exact_action_batches_v56 WHERE batch_id=(SELECT batch_id FROM adventure_exact_action_candidates_v56 WHERE candidate_id=?)").get(bound.candidate_id)as any;
      const projection=batch&&JSON.parse(batch.projection_json),tool=request?.advertisedToolSchemas?.find((item:any)=>item.name===toolName);
       const requestProjection=bound.action_kind==="power"?request?.powerCandidateProjection:bound.action_kind==="rest"?request?.restCandidateProjection:bound.action_kind==="combat-consumable"?request?.combatConsumableCandidateProjection:request?.combatPowerCandidateProjection,expectedParameters=exactPairParameters(requestProjection?.candidates??[]);
      if(!response||!batch||sha(response.response_json)!==response.response_digest||sha(response.request_json)!==response.request_digest||sha(batch.projection_json)!==batch.projection_digest
        ||canonicalAgentJson(stripCandidateLabels(requestProjection) as never)!==batch.projection_json||!request?.advertisedTools?.includes(toolName)
        ||canonicalAgentJson(tool?.parameters as never)!==canonicalAgentJson(expectedParameters as never)||call?.toolName!==toolName
        ||canonicalAgentJson(call.arguments as never)!==canonicalAgentJson(selection as never))throw new Error("adventure action provider evidence is invalid");
      const matching=specs(bound.action_kind,current).find(item=>sha(canonicalAgentJson(item.frame as never))===bound.candidate_digest);if(!matching)throw new Error("adventure action candidate is stale or tampered");const privateValue=JSON.parse(bound.private_json),publicValue=JSON.parse(bound.public_json),executionKey=bound.execution_idempotency_key;
      let commandId:string,revisionBefore:number,revisionAfter:number,occurredAt:string,sourceResultDigest:string,receipt:any;
      if(bound.action_kind==="power"){const result=powers.useActorPower(principal,current.actorId,{powerRef:privateValue.powerRef,targetIds:privateValue.targetIds,choices:[],expectedRevision:privateValue.sourceRevision,idempotencyKey:executionKey});commandId=result.receipt.commandId;revisionBefore=result.receipt.revisionBefore;revisionAfter=result.receipt.revisionAfter;occurredAt=result.receipt.occurredAt;
        const names=actorLabels(db,current.campaignId),costs=privateValue.costDeltas,stateDeltas=result.resolution.stateDeltas.map((delta:any)=>({actor:names.get(delta.actorId)??"Campaign actor",change:delta.kind==="resource"?label(delta.resourceId):delta.kind==="effect-applied"?"Effect applied":"Concentration effect replaced",before:delta.kind==="resource"?delta.before:null,after:delta.kind==="resource"?delta.after:null}));
        receipt=adventurePowerPublicReceiptSchema.parse({powerName:publicValue.powerName,targets:publicValue.targets,costs,stateDeltas,concentration:publicValue.concentration,revisionBefore,revisionAfter,occurredAt});}
       else if(bound.action_kind==="rest"){const restCommand=privateValue.restKind==="short"?{type:"take_short_rest" as const,campaignId:current.campaignId,actorId:current.actorId,expectedRevision:privateValue.sourceRevision,idempotencyKey:executionKey,...(privateValue.hitDiceToSpend===undefined?{}:{hitDiceToSpend:privateValue.hitDiceToSpend})}:{type:"take_long_rest" as const,campaignId:current.campaignId,actorId:current.actorId,expectedRevision:privateValue.sourceRevision,idempotencyKey:executionKey};const result=rest.takeRest(principal,restCommand);commandId=result.receipt.commandId;revisionBefore=result.receipt.revisionBefore;revisionAfter=result.receipt.revisionAfter;occurredAt=result.receipt.occurredAt;receipt=adventureRestPublicReceiptSchema.parse({restKind:publicValue.restKind,restName:publicValue.restName,recovery:result.rest.recovery.resources.map(delta=>({label:label(delta.resourceId),before:delta.before,after:delta.after})),revisionBefore,revisionAfter,occurredAt});}
       else if(bound.action_kind==="combat-consumable"){const resourceBefore=new Map<string,number>();const targetActor=(db.prepare("SELECT actor_id FROM combatant WHERE encounter_id=? AND combatant_id=?").get(privateValue.encounterId,privateValue.targetCombatantId)as any)?.actor_id;
         if(targetActor)for(const row of db.prepare("SELECT name,current FROM rpg_actor_resources WHERE campaign_id=? AND actor_id=? AND name IN('guard','focus')").all(current.campaignId,targetActor)as any[])resourceBefore.set(row.name,row.current);
         const result=encounters.useConsumable(principal,{legalActionId:privateValue.legalActionId,inventoryEntryId:privateValue.inventoryEntryId,item:privateValue.item,quantity:1,targetCombatantId:privateValue.targetCombatantId,targetActorBacked:privateValue.targetActorBacked,expectedCombatRevision:privateValue.expectedCombatRevision,expectedActingM15Revision:privateValue.expectedActingM15Revision,expectedTargetM15Revision:privateValue.expectedTargetM15Revision,idempotencyKey:executionKey})as UseConsumableCommandResult;
         commandId=(db.prepare("SELECT command_id FROM combat_commands_v27 WHERE encounter_id=? AND idempotency_key=?").get(privateValue.encounterId,executionKey)as any).command_id;revisionBefore=result.receipt.revisionBefore;revisionAfter=result.receipt.revisionAfter;occurredAt=result.receipt.occurredAt;
         const working=new Map(resourceBefore);const outcomes=result.resolution.outcome.settlements.map((settlement:any)=>{if(settlement.kind==="combat-hp-damage")return{kind:"damage",damageType:settlement.damageType,roll:settlement.roll,requested:settlement.requested,adjustment:settlement.adjustment,applied:settlement.applied,before:settlement.before,after:settlement.after};if(settlement.kind==="combat-hp-healing")return{kind:"healing",roll:settlement.roll,requested:settlement.requested,applied:settlement.applied,before:settlement.before,after:settlement.after};if(settlement.kind==="combat-hp-resource")return{kind:"resource",resource:"Health",requested:settlement.requested,applied:settlement.applied,before:settlement.before,after:settlement.after};const before=working.get(settlement.resource)??null,after=before===null?null:before+settlement.applied;if(after!==null)working.set(settlement.resource,after);return{kind:"resource",resource:label(settlement.resource),requested:settlement.requested,applied:settlement.applied,before,after};});
          const roundAfter=(db.prepare("SELECT round_number FROM encounter WHERE encounter_id=?").get(privateValue.encounterId)as any).round_number;receipt=adventureCombatConsumablePublicReceiptSchema.parse({itemName:publicValue.itemName,target:publicValue.target,quantity:1,actionCost:"action",outcomes,roundBefore:privateValue.roundBefore,roundAfter,revisionBefore,revisionAfter,occurredAt});}
         else{const result=encounters.useCombatPower(principal,{legalActionId:privateValue.legalActionId,powerRef:privateValue.powerRef,targetCombatantId:privateValue.targetCombatantId,expectedCombatRevision:privateValue.expectedCombatRevision,expectedSourceM15Revision:privateValue.sourceM15Revision,expectedSourceM16Revision:privateValue.sourceM16Revision,expectedTargetM15Revision:privateValue.targetM15Revision,expectedTargetM16Revision:privateValue.targetM16Revision,idempotencyKey:executionKey});commandId=result.commandId;revisionBefore=result.revisionBefore;revisionAfter=result.revisionAfter;occurredAt=result.occurredAt;const outcomes=result.outcomes.map((outcome:any)=>outcome.kind==="damage"?{kind:outcome.kind,damageType:outcome.damageType,roll:outcome.roll,requested:outcome.requested,adjustment:outcome.adjustment,applied:outcome.applied,before:outcome.before,after:outcome.after}:outcome);receipt=adventureCombatPowerPublicReceiptSchema.parse({powerName:publicValue.powerName,target:publicValue.target,actionCost:publicValue.actionCost,costs:result.cost?[result.cost]:[],outcomes,concentration:result.concentration,roundBefore:result.roundBefore,roundAfter:result.roundAfter,revisionBefore,revisionAfter,occurredAt});}
       const source=bound.action_kind==="combat-consumable"||bound.action_kind==="combat-power"?db.prepare("SELECT receipt.result_digest FROM combat_receipts_v27 receipt JOIN encounter ON encounter.encounter_id=receipt.encounter_id WHERE encounter.campaign_id=? AND receipt.command_id=?").get(current.campaignId,commandId)as any:db.prepare(`SELECT result_digest FROM ${bound.action_kind==="power"?"rpg_m16_receipts_v26":"rpg_m15_receipts_v25"} WHERE campaign_id=? AND actor_id=? AND command_id=?`).get(current.campaignId,current.actorId,commandId)as any;sourceResultDigest=source.result_digest;const resultJson=canonicalAgentJson(receipt as never);
      db.prepare("INSERT INTO adventure_exact_action_executions_v56 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(`action-execution:${sha(`${turnId}\0${proposalId}`).slice(0,48)}`,bound.candidate_id,current.campaignId,turnId,proposalId,bound.action_kind,bound.provider_call_id,bound.provider_tool_call_id,commandId,current.actorId,revisionBefore,revisionAfter,sourceResultDigest,resultJson,sha(resultJson),occurredAt,utcIsoTimestampSchema.parse(deps.clock.now().toISOString()));return{commandId,receipt};}).immediate();},
    getAdventurePowerPublicReceipt(principal,campaignId,commandId){resourceIdSchema.parse(principal);const row=db.prepare(`SELECT execution.* FROM adventure_exact_action_executions_v56 execution JOIN campaign_memberships member ON member.campaign_id=execution.campaign_id AND member.principal_id=? WHERE execution.campaign_id=? AND execution.command_id=? AND execution.action_kind='power'`).get(principal,campaignId,commandId)as any;return row?verify(row).receipt as AdventurePowerPublicReceipt:null;},
    getAdventureRestPublicReceipt(principal,campaignId,commandId){resourceIdSchema.parse(principal);const row=db.prepare(`SELECT execution.* FROM adventure_exact_action_executions_v56 execution JOIN campaign_memberships member ON member.campaign_id=execution.campaign_id AND member.principal_id=? WHERE execution.campaign_id=? AND execution.command_id=? AND execution.action_kind='rest'`).get(principal,campaignId,commandId)as any;return row?verify(row).receipt as AdventureRestPublicReceipt:null;},
    getAdventureCombatConsumablePublicReceipt(principal,campaignId,commandId){resourceIdSchema.parse(principal);const row=db.prepare(`SELECT execution.* FROM adventure_exact_action_executions_v56 execution JOIN campaign_memberships member ON member.campaign_id=execution.campaign_id AND member.principal_id=? WHERE execution.campaign_id=? AND execution.command_id=? AND execution.action_kind='combat-consumable'`).get(principal,campaignId,commandId)as any;return row?verify(row).receipt as AdventureCombatConsumablePublicReceipt:null;},
    getAdventureCombatPowerPublicReceipt(principal,campaignId,commandId){resourceIdSchema.parse(principal);const row=db.prepare(`SELECT execution.* FROM adventure_exact_action_executions_v56 execution JOIN campaign_memberships member ON member.campaign_id=execution.campaign_id AND member.principal_id=? WHERE execution.campaign_id=? AND execution.command_id=? AND execution.action_kind='combat-power'`).get(principal,campaignId,commandId)as any;return row?verify(row).receipt as AdventureCombatPowerPublicReceipt:null;},
    getAdventurePowerRestNarrationReceipt(principal,requestedTurn,commandId){const row=db.prepare(`WITH RECURSIVE ancestry(id,prior_turn_id) AS (SELECT id,prior_turn_id FROM adventure_turns WHERE id=? UNION ALL SELECT turn.id,turn.prior_turn_id FROM adventure_turns turn JOIN ancestry ON ancestry.prior_turn_id=turn.id)
      SELECT execution.* FROM ancestry JOIN adventure_exact_action_executions_v56 execution ON execution.turn_id=ancestry.id JOIN adventure_turns requested ON requested.id=? JOIN campaign_memberships member ON member.campaign_id=requested.campaign_id AND member.principal_id=? LEFT JOIN campaign_actor_private_state control ON control.campaign_id=requested.campaign_id AND control.actor_id=requested.actor_id WHERE execution.command_id=? AND (member.role IN('owner','gm') OR control.controller_principal_id=?)`).get(requestedTurn,requestedTurn,principal,commandId,principal)as any;if(!row)return null;const value=verify(row).receipt;return{kind:row.action_kind,...value}as any;},
  };}
