import { createHash } from "node:crypto";
import type DatabaseDriver from "better-sqlite3";
import {
  adventureProgressionCandidateSchema, adventureProgressionPublicReceiptSchema, adventureProgressionReadSchema,
  adventureQuestLifecycleCandidateSchema, adventureQuestLifecyclePublicReceiptSchema, canonicalAgentJson,
  resourceIdSchema, utcIsoTimestampSchema,
  type AdventureProgressionCandidate, type AdventureProgressionPublicReceipt, type AdventureProgressionRead,
  type AdventureQuestLifecycleCandidate, type AdventureQuestLifecyclePublicReceipt, type ProgressionPreview,
} from "@velvet/contracts";
import type { CharacterProgressionRepository } from "./characterProgressionRepo.js";
import type { QuestRepository } from "./questRepo.js";
import { actorHasActiveEncounter } from "./encounter/activeEncounterPolicy.js";

const sha=(value:string)=>createHash("sha256").update(value).digest("hex");
const semantic=(value:string)=>value.split(/[-_:]+/u).filter(Boolean).map(part=>part[0]!.toUpperCase()+part.slice(1)).join(" ").slice(0,200);
type Scope={campaignId:string;turnId:string;sessionId:string;actorId:string;principalId:string;timelineId:string;campaignCharacterId:string};
type Kind="quest-accept"|"quest-abandon"|"quest-reward"|"progression";
type Spec={kind:Kind;publicValue:Record<string,unknown>;privateValue:Record<string,unknown>;frame:Record<string,unknown>};

export interface AdventureQuestProgressionRepository {
  generateAdventureQuestLifecycleCandidates(principalId:string,turnId:string):AdventureQuestLifecycleCandidate[];
  getAdventureProgressionRead(principalId:string,turnId:string):AdventureProgressionRead;
  generateAdventureProgressionCandidates(principalId:string,turnId:string):AdventureProgressionCandidate[];
  executeAdventureQuestProgressionProposal(principalId:string,turnId:string,proposalId:string):{commandId:string;receipt:AdventureQuestLifecyclePublicReceipt|AdventureProgressionPublicReceipt};
  getAdventureQuestLifecyclePublicReceipt(principalId:string,campaignId:string,commandId:string):AdventureQuestLifecyclePublicReceipt|null;
  getAdventureProgressionPublicReceipt(principalId:string,campaignId:string,commandId:string):AdventureProgressionPublicReceipt|null;
  getAdventureQuestProgressionNarrationReceipt(principalId:string,turnId:string,commandId:string):({kind:"quest-lifecycle"}&AdventureQuestLifecyclePublicReceipt)|({kind:"progression"}&AdventureProgressionPublicReceipt)|null;
}

function scope(db:DatabaseDriver.Database,principalId:string,turnId:string):Scope|null {const row=db.prepare(`SELECT turn.campaign_id campaignId,turn.id turnId,turn.session_id sessionId,turn.actor_id actorId,turn.principal_id principalId,
    turn.timeline_id timelineId,actor.campaign_character_id campaignCharacterId FROM adventure_turns turn
    JOIN campaigns campaign ON campaign.id=turn.campaign_id AND campaign.active_timeline_id=turn.timeline_id AND campaign.administration_revision=turn.campaign_revision
    JOIN campaign_sessions attached ON attached.campaign_id=turn.campaign_id AND attached.session_id=turn.session_id
    JOIN sessions session ON session.id=attached.session_id AND session.state='active' AND session.stopped_at IS NULL
    JOIN campaign_actors actor ON actor.campaign_id=turn.campaign_id AND actor.id=turn.actor_id
    JOIN campaign_memberships member ON member.campaign_id=turn.campaign_id AND member.principal_id=?
    LEFT JOIN campaign_actor_private_state control ON control.campaign_id=turn.campaign_id AND control.actor_id=turn.actor_id
    WHERE turn.id=? AND turn.principal_id=? AND turn.mode='original' AND member.role<>'observer'
      AND (member.role IN('owner','gm') OR control.controller_principal_id=?)`).get(principalId,turnId,principalId,principalId)as Scope|undefined;
  return row&&!actorHasActiveEncounter(db,row.campaignId,row.actorId)?row:null;}
function actorName(db:DatabaseDriver.Database,value:Scope):string {const row=db.prepare(`SELECT persona.name FROM campaign_characters character JOIN characters persona ON persona.id=character.character_id
    WHERE character.campaign_id=? AND character.id=?`).get(value.campaignId,value.campaignCharacterId)as {name:string}|undefined;return row?.name?.trim().slice(0,200)||"Campaign actor";}
function definitionName(db:DatabaseDriver.Database,campaignId:string,ref:{kind:string;packId:string;packVersion:string;definitionId:string}):string|null {const row=db.prepare(`SELECT visibility.public_definition_json FROM campaign_catalog_current_pins pin JOIN rpg_catalog_definition_visibility visibility
    ON visibility.pack_id=pin.pack_id AND visibility.pack_version=pin.pack_version AND visibility.kind=? AND visibility.definition_id=? AND visibility.publicly_reachable=1
    WHERE pin.campaign_id=? AND pin.pack_id=? AND pin.pack_version=?`).get(ref.kind,ref.definitionId,campaignId,ref.packId,ref.packVersion)as {public_definition_json:string}|undefined;
  try{const name=JSON.parse(row?.public_definition_json??"").name;return typeof name==="string"&&name.trim()?name.trim().slice(0,200):null;}catch{return null;}}
function progressionProjection(db:DatabaseDriver.Database,progression:CharacterProgressionRepository,value:Scope):{read:AdventureProgressionRead;preview:ProgressionPreview|null;className:string|null}{const state=progression.getCharacterProgression(value.principalId,value.campaignCharacterId);if(!state)return{read:adventureProgressionReadSchema.parse({available:false,className:null,currentLevel:null,eligibleLevel:null,mode:null,totalXp:null,milestoneCount:null,pendingChoices:[]}),preview:null,className:null};
  const preview=progression.previewCharacterProgression(value.principalId,value.campaignCharacterId),className=definitionName(db,value.campaignId,state.classRef)??"Adventurer";
  if(!preview)return{read:adventureProgressionReadSchema.parse({available:false,className:null,currentLevel:null,eligibleLevel:null,mode:null,totalXp:null,milestoneCount:null,pendingChoices:[]}),preview:null,className:null};
  const pendingChoices=preview.pendingChoices.map(choice=>({level:choice.level,label:`Level ${choice.level} ability choice`,options:choice.options.map(option=>definitionName(db,value.campaignId,option)).filter((name):name is string=>Boolean(name))})).filter(choice=>choice.options.length>=2);
  return{read:adventureProgressionReadSchema.parse({available:true,className,currentLevel:preview.currentLevel,eligibleLevel:preview.eligibleLevel,mode:preview.mode,totalXp:preview.totalXp,milestoneCount:preview.milestoneCount,pendingChoices}),preview,className};}
function questSpecs(db:DatabaseDriver.Database,value:Scope):Spec[]{const revision=(db.prepare("SELECT revision FROM quest_domain_revisions_v33 WHERE campaign_id=?").get(value.campaignId)as {revision:number}|undefined)?.revision??0,recipient=actorName(db,value);
  const rows=db.prepare(`SELECT quest.id quest_id,quest.title,quest.status,reward.id reward_id,reward.kind reward_kind,reward.amount reward_amount,reward.label reward_label
    FROM quests quest JOIN quest_definitions_v33 definition ON definition.campaign_id=quest.campaign_id AND definition.quest_id=quest.id AND definition.visibility='public'
    LEFT JOIN quest_rewards reward ON reward.campaign_id=quest.campaign_id AND reward.quest_id=quest.id
    LEFT JOIN quest_reward_definitions_v33 reward_definition ON reward_definition.campaign_id=reward.campaign_id AND reward_definition.quest_id=reward.quest_id AND reward_definition.reward_id=reward.id AND reward_definition.visibility='public'
    LEFT JOIN quest_reward_claims_v33 claim ON claim.campaign_id=reward.campaign_id AND claim.quest_id=reward.quest_id AND claim.reward_id=reward.id
    WHERE quest.campaign_id=? AND (quest.status<>'completed' OR reward.id IS NULL OR reward_definition.reward_id IS NOT NULL) AND claim.reward_id IS NULL
    ORDER BY quest.sort_order,quest.id,reward.created_at,reward.id`).all(value.campaignId)as any[];const out:Spec[]=[];
  for(const row of rows){const common={questId:row.quest_id,questRevision:revision,questTitle:row.title,status:row.status};
    if(row.status==="open"&&!out.some(item=>item.kind==="quest-accept"&&(item.privateValue as any).questId===row.quest_id)){const publicValue={action:"accept",questTitle:row.title,reward:null,confirmationRequired:true};out.push({kind:"quest-accept",publicValue,privateValue:{...common,action:"accept"},frame:{version:"v1",...value,...common,...publicValue}});}
    if((row.status==="open"||row.status==="active")&&!out.some(item=>item.kind==="quest-abandon"&&(item.privateValue as any).questId===row.quest_id)){const publicValue={action:"abandon",questTitle:row.title,reward:null,confirmationRequired:true};out.push({kind:"quest-abandon",publicValue,privateValue:{...common,action:"abandon"},frame:{version:"v1",...value,...common,...publicValue}});}
    if(row.status==="completed"&&row.reward_id){const reward={label:row.reward_label,kind:semantic(row.reward_kind),amount:row.reward_amount,recipient},publicValue={action:"claim-reward",questTitle:row.title,reward,confirmationRequired:true};out.push({kind:"quest-reward",publicValue,privateValue:{...common,action:"claim-reward",rewardId:row.reward_id,actorId:value.actorId},frame:{version:"v1",...value,...common,rewardId:row.reward_id,actorId:value.actorId,...publicValue}});}
  }return out;}
function progressionSpecs(db:DatabaseDriver.Database,progression:CharacterProgressionRepository,value:Scope):Spec[]{const {preview,className}=progressionProjection(db,progression,value);if(!preview||!className||preview.levels.length===0||preview.pendingChoices.length>0)return[];
  const features=[...new Set(preview.levels.flatMap(level=>[...level.fixedAbilities,...level.selectedAbilities,...level.spells]).map(ref=>definitionName(db,value.campaignId,ref)).filter((name):name is string=>Boolean(name)))];
  const resources=[...new Map(preview.levels.flatMap(level=>level.resources).map(change=>[change.resourceId,change])).entries()].map(([id,last])=>{const first=preview.levels.flatMap(level=>level.resources).find(change=>change.resourceId===id)!;return{label:semantic(id),before:first.maxBefore,after:last.maxAfter};});
  const publicValue={className,levelBefore:preview.currentLevel,levelAfter:preview.eligibleLevel,features,resources,confirmationRequired:true};
  return[{kind:"progression",publicValue,privateValue:{campaignCharacterId:value.campaignCharacterId,previewRevision:preview.revision,previewToken:preview.token,selections:[]},frame:{version:"v1",...value,...publicValue,previewRevision:preview.revision,previewToken:preview.token,selections:[]}}];}

export function createAdventureQuestProgressionRepository(db:DatabaseDriver.Database,deps:{clock:{now():Date}},quests:QuestRepository,progression:CharacterProgressionRepository,guard:()=>void):AdventureQuestProgressionRepository {
  const specs=(kind:Kind,value:Scope)=>kind==="progression"?progressionSpecs(db,progression,value):questSpecs(db,value).filter(item=>item.kind===kind);
  const generate=(kind:Kind,principalInput:string,turnInput:string)=>{guard();const principal=resourceIdSchema.parse(principalInput),turnId=resourceIdSchema.parse(turnInput);return db.transaction(()=>{const current=scope(db,principal,turnId);if(!current)return[];const old=db.prepare("SELECT * FROM adventure_exact_action_batches_v56 WHERE turn_id=? AND action_kind=?").get(turnId,kind)as any;if(old){const rows=db.prepare("SELECT public_json FROM adventure_exact_action_candidates_v56 WHERE batch_id=? ORDER BY candidate_id").all(old.batch_id)as any[],candidates=rows.map(row=>JSON.parse(row.public_json)),projection=canonicalAgentJson({version:"v1",candidates}as never);if(projection!==old.projection_json||sha(projection)!==old.projection_digest)throw new Error("adventure candidate projection is malformed");return candidates;}
    const at=utcIsoTimestampSchema.parse(deps.clock.now().toISOString()),values=specs(kind,current).map(item=>{const digest=sha(canonicalAgentJson(item.frame as never));return{...item,candidateId:`${kind}-candidate:${digest.slice(0,48)}`,digest};}),candidates=values.map(item=>kind==="progression"?adventureProgressionCandidateSchema.parse({candidateId:item.candidateId,digest:item.digest,...item.publicValue}):adventureQuestLifecycleCandidateSchema.parse({candidateId:item.candidateId,digest:item.digest,...item.publicValue})).sort((a,b)=>a.candidateId.localeCompare(b.candidateId));
    const projection=canonicalAgentJson({version:"v1",candidates}as never),batchId=`${kind}-batch:${sha(`${turnId}\0${kind}`).slice(0,48)}`;db.prepare("INSERT INTO adventure_exact_action_batches_v56 VALUES(?,?,?,?,?,?,?,?)").run(batchId,current.campaignId,turnId,kind,projection,sha(projection),candidates.length,at);const insert=db.prepare("INSERT INTO adventure_exact_action_candidates_v56 VALUES(?,?,?,?,?,?,?,?,?,?,?,?)");for(const item of values){const candidate=candidates.find(value=>value.candidateId===item.candidateId)!;insert.run(item.candidateId,item.digest,batchId,current.campaignId,turnId,current.sessionId,current.actorId,current.principalId,kind,canonicalAgentJson(candidate as never),canonicalAgentJson(item.privateValue as never),at);}return candidates;}).immediate();};
  const verify=(row:any)=>{const receipt=row.action_kind==="progression"?adventureProgressionPublicReceiptSchema.parse(JSON.parse(row.public_result_json)):adventureQuestLifecyclePublicReceiptSchema.parse(JSON.parse(row.public_result_json));if(sha(row.public_result_json)!==row.result_digest)throw new Error("adventure receipt is malformed");const source=row.action_kind==="progression"?db.prepare(`SELECT receipt.result_json FROM character_progression_receipts_v23 receipt JOIN character_progression_v23 root ON root.campaign_character_id=receipt.campaign_character_id WHERE root.campaign_id=? AND root.actor_id=? AND receipt.command_id=? AND receipt.revision_after=?`).get(row.campaign_id,row.actor_id,row.command_id,row.revision_after)as {result_json:string}|undefined:db.prepare("SELECT canonical_result_json result_json FROM quest_domain_receipts_v33 WHERE campaign_id=? AND command_id=? AND resulting_revision=?").get(row.campaign_id,row.command_id,row.revision_after)as {result_json:string}|undefined;if(!source||sha(canonicalAgentJson(JSON.parse(source.result_json)as never))!==row.source_result_digest)throw new Error("adventure source receipt is malformed");return{commandId:row.command_id,receipt};};
  return{generateAdventureQuestLifecycleCandidates(principal,turnId){const candidates=([...generate("quest-accept",principal,turnId),...generate("quest-abandon",principal,turnId),...generate("quest-reward",principal,turnId)]as AdventureQuestLifecycleCandidate[]).sort((a,b)=>a.candidateId.localeCompare(b.candidateId));if(candidates.length>32)throw new Error("too many adventure quest lifecycle candidates");return candidates;},
    getAdventureProgressionRead(principalInput,turnInput){guard();const principal=resourceIdSchema.parse(principalInput),turnId=resourceIdSchema.parse(turnInput),current=scope(db,principal,turnId);return current?progressionProjection(db,progression,current).read:adventureProgressionReadSchema.parse({available:false,className:null,currentLevel:null,eligibleLevel:null,mode:null,totalXp:null,milestoneCount:null,pendingChoices:[]});},
    generateAdventureProgressionCandidates:(principal,turnId)=>generate("progression",principal,turnId)as AdventureProgressionCandidate[],
    executeAdventureQuestProgressionProposal(principalInput,turnInput,proposalInput){guard();const principal=resourceIdSchema.parse(principalInput),turnId=resourceIdSchema.parse(turnInput),proposalId=resourceIdSchema.parse(proposalInput);return db.transaction(()=>{const old=db.prepare("SELECT * FROM adventure_exact_action_executions_v56 WHERE turn_id=?").get(turnId)as any;if(old){if(old.proposal_id!==proposalId)throw new Error("adventure action replay changed");return verify(old);}const bound=db.prepare(`SELECT binding.*,candidate.public_json,candidate.private_json,candidate.candidate_digest,candidate.action_kind,proposal.arguments_json,proposal.requires_confirmation,decision.decision
      FROM adventure_exact_action_proposal_bindings_v56 binding JOIN adventure_exact_action_candidates_v56 candidate ON candidate.candidate_id=binding.candidate_id
      JOIN tool_proposals proposal ON proposal.proposal_id=binding.proposal_id LEFT JOIN confirmation_decisions decision ON decision.proposal_id=proposal.proposal_id WHERE binding.turn_id=? AND binding.proposal_id=?`).get(turnId,proposalId)as any,current=scope(db,principal,turnId);if(!bound||!current||!bound.requires_confirmation||bound.decision!=="approved")throw new Error("adventure proposal is not executable");const selection=JSON.parse(bound.arguments_json),response=db.prepare(`SELECT response.response_json,response.response_digest,context.request_json,context.request_digest FROM agent_provider_responses_v39 response JOIN agent_provider_contexts_v39 context ON context.context_id=response.context_id WHERE response.turn_id=? AND response.provider_call_id=? AND response.status='succeeded'`).get(turnId,bound.provider_call_id)as any,settled=response&&JSON.parse(response.response_json),call=settled?.calls?.find((item:any)=>item.providerToolCallId===bound.provider_tool_call_id),request=response&&JSON.parse(response.request_json),toolName=bound.action_kind==="progression"?"exact_progression_apply.select":"exact_quest_lifecycle.select",projection=bound.action_kind==="progression"?request?.progressionCandidateProjection:request?.questLifecycleCandidateProjection;
      if(!response||sha(response.response_json)!==response.response_digest||sha(response.request_json)!==response.request_digest||!request?.advertisedTools?.includes(toolName)||call?.toolName!==toolName||call?.arguments?.candidateId!==bound.candidate_id||call?.arguments?.digest!==bound.candidate_digest||!projection?.candidates?.some((item:any)=>item.candidateId===bound.candidate_id&&item.digest===bound.candidate_digest))throw new Error("adventure provider evidence is invalid");const matching=specs(bound.action_kind,current).find(item=>sha(canonicalAgentJson(item.frame as never))===bound.candidate_digest);if(!matching)throw new Error("adventure candidate is stale or tampered");const privateValue=JSON.parse(bound.private_json),publicValue=JSON.parse(bound.public_json),executionKey=bound.execution_idempotency_key;let commandId:string,revisionBefore:number,revisionAfter:number,occurredAt:string,receipt:any,sourceJson:string;
      if(bound.action_kind==="progression"){const result=progression.applyCharacterProgression(principal,privateValue.campaignCharacterId,{previewRevision:privateValue.previewRevision,previewToken:privateValue.previewToken,selections:[],idempotencyKey:executionKey});commandId=result.receipt.commandId;revisionBefore=result.receipt.revisionBefore;revisionAfter=result.receipt.revisionAfter;occurredAt=result.receipt.occurredAt;sourceJson=canonicalAgentJson(result as never);receipt=adventureProgressionPublicReceiptSchema.parse({className:publicValue.className,levelBefore:publicValue.levelBefore,levelAfter:result.progression.level,features:publicValue.features,resources:publicValue.resources,revisionBefore,revisionAfter,occurredAt});}
      else{const statusBefore=privateValue.status==="open"?"offered":privateValue.status==="failed"?"abandoned":privateValue.status,result=quests.executeQuestCommand(principal,privateValue.questId,privateValue.action==="claim-reward"?{kind:"claim-reward",actorId:privateValue.actorId,rewardId:privateValue.rewardId,expectedRevision:privateValue.questRevision,idempotencyKey:executionKey}:{kind:privateValue.action,expectedRevision:privateValue.questRevision,idempotencyKey:executionKey});commandId=result.receipt.commandId;revisionBefore=result.receipt.revisionBefore;revisionAfter=result.receipt.revisionAfter;occurredAt=result.receipt.occurredAt;sourceJson=canonicalAgentJson(result as never);receipt=adventureQuestLifecyclePublicReceiptSchema.parse({action:publicValue.action,questTitle:publicValue.questTitle,statusBefore,statusAfter:result.quest.status,reward:publicValue.reward,revisionBefore,revisionAfter,occurredAt});}
      const resultJson=canonicalAgentJson(receipt as never);db.prepare("INSERT INTO adventure_exact_action_executions_v56 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(`action-execution:${sha(`${turnId}\0${proposalId}`).slice(0,48)}`,bound.candidate_id,current.campaignId,turnId,proposalId,bound.action_kind,'provider',bound.provider_call_id,bound.provider_tool_call_id,null,commandId,current.actorId,revisionBefore,revisionAfter,sha(sourceJson),resultJson,sha(resultJson),occurredAt,utcIsoTimestampSchema.parse(deps.clock.now().toISOString()));return{commandId,receipt};}).immediate();},
    getAdventureQuestLifecyclePublicReceipt(principal,campaignId,commandId){const row=db.prepare(`SELECT execution.* FROM adventure_exact_action_executions_v56 execution JOIN campaign_memberships member ON member.campaign_id=execution.campaign_id AND member.principal_id=? WHERE execution.campaign_id=? AND execution.command_id=? AND execution.action_kind LIKE 'quest-%'`).get(principal,campaignId,commandId)as any;return row?verify(row).receipt as AdventureQuestLifecyclePublicReceipt:null;},
    getAdventureProgressionPublicReceipt(principal,campaignId,commandId){const row=db.prepare(`SELECT execution.* FROM adventure_exact_action_executions_v56 execution JOIN campaign_memberships member ON member.campaign_id=execution.campaign_id AND member.principal_id=? WHERE execution.campaign_id=? AND execution.command_id=? AND execution.action_kind='progression'`).get(principal,campaignId,commandId)as any;return row?verify(row).receipt as AdventureProgressionPublicReceipt:null;},
    getAdventureQuestProgressionNarrationReceipt(principal,requestedTurn,commandId){const row=db.prepare(`WITH RECURSIVE ancestry(id,prior_turn_id) AS (SELECT id,prior_turn_id FROM adventure_turns WHERE id=? UNION ALL SELECT turn.id,turn.prior_turn_id FROM adventure_turns turn JOIN ancestry ON ancestry.prior_turn_id=turn.id) SELECT execution.* FROM ancestry JOIN adventure_exact_action_executions_v56 execution ON execution.turn_id=ancestry.id JOIN adventure_turns requested ON requested.id=? JOIN campaign_memberships member ON member.campaign_id=requested.campaign_id AND member.principal_id=? LEFT JOIN campaign_actor_private_state control ON control.campaign_id=requested.campaign_id AND control.actor_id=requested.actor_id WHERE execution.command_id=? AND execution.action_kind IN('quest-accept','quest-abandon','quest-reward','progression') AND (member.role IN('owner','gm') OR control.controller_principal_id=?)`).get(requestedTurn,requestedTurn,principal,commandId,principal)as any;if(!row)return null;return{kind:row.action_kind==="progression"?"progression":"quest-lifecycle",...verify(row).receipt}as any;},
  };}
