import { createHash } from "node:crypto";
import type DatabaseDriver from "better-sqlite3";
import {
  campaignGeneratedFoundationSchema, campaignGeneratedPlanningSchema, campaignPublishedMaterialsSchema,
  generatedCampaignContentProviderSchema, resourceIdSchema,
  stagedCampaignContentGenerationSchema, type DraftMutationInput, type GeneratedCampaignContentProvider,
  type PrivateGenerationDraft,
} from "@velvet/contracts";
import type { RepositoryDependencies } from "./campaign/campaignTypes.js";
import { AdventureTurnConflictError, AdventureTurnStaleError, AdventureTurnUnavailableError } from "./adventureTurn/errors.js";

type Drafts = {
  getGenerationDraft(principal: string, id: string): unknown;
  reviewGenerationDraft(principal: string, input: unknown): PrivateGenerationDraft;
  applyGenerationDraft(principal: string, input: unknown): PrivateGenerationDraft;
};
type CallState = { state: "running" | "succeeded" | "failed"; draftId: string | null; acquired: boolean; attempt: number; jobId: string };
type StartMetadata = { provider:string; model:string; operation:string; stage:string; promptVersion:string; schemaVersion:string; jobId:string };
type FinishMetadata = { responseModel:string|null; promptTokens:number|null; completionTokens:number|null; totalTokens:number|null; latencyMs:number; estimatedCostUsd:number|null };
type ContextArtifact = { key:string; kind:string; visibility:"public"|"gm"; canonical:Record<string,unknown>; digest:string; sourceDraftId:string; serverResourceId:string|null };

export interface CampaignGenerationRepository {
  beginCampaignGenerationCall(campaignId:string,idempotencyKey:string,requestDigest:string,metadata:StartMetadata,retryFailedAttempt:number|null): CallState;
  getCampaignGenerationCall(campaignId:string,idempotencyKey:string,requestDigest:string): CallState | null;
  finishCampaignGenerationCall(campaignId:string,idempotencyKey:string,attempt:number,draftId:string|null,outcomeCode:string,metadata?:FinishMetadata): void;
  getCampaignGenerationContext(principalId:string,campaignId:string,keys:string[]): { revision:number; artifacts:ContextArtifact[] } | null;
  recordCampaignGenerationCandidate(draftId:string,content:GeneratedCampaignContentProvider,dependencies:ContextArtifact[]): void;
  getCampaignGeneratedFoundation(principalId:string,campaignId:string): ReturnType<typeof campaignGeneratedFoundationSchema.parse> | null;
  getCampaignGeneratedPlanning(principalId:string,campaignId:string): ReturnType<typeof campaignGeneratedPlanningSchema.parse> | null;
  getCampaignPublishedMaterials(principalId:string,campaignId:string): ReturnType<typeof campaignPublishedMaterialsSchema.parse> | null;
  publishCampaignMaterial(principalId:string,campaignId:string,input:{artifactKey:string;expectedRevision:number;idempotencyKey:string}): {material:unknown;receipt:{idempotencyKey:string;revisionBefore:number;revisionAfter:number;occurredAt:string}};
  applyCampaignContentGenerationDraftAtomically(principalId:string,input:DraftMutationInput & {selectedArtifactKeys:string[]}): PrivateGenerationDraft;
  reconcileGeneratedNpcPlacements(campaignId:string): number;
}

const hash = (value:string) => createHash("sha256").update(value).digest("hex");
const stableId = (campaignId:string,draftId:string,kind:string,key:string) => resourceIdSchema.parse(`gen-${kind}-${hash(`${campaignId}:${draftId}:${key}`).slice(0,40)}`);
const canonical = (value:unknown) => JSON.stringify(value);

const collections = [
  ["outline","outlines"], ["arc","arcs"], ["location","locations"], ["connection","connections"],
  ["faction","factions"], ["npc","npcs"], ["quest","quests"], ["encounter","encounters"],
  ["clue","clues"], ["story-node","storyNodes"], ["story-relationship","storyRelationships"],
  ["handout","handouts"], ["scene-prompt","scenePrompts"],
] as const;
function artifactList(content:GeneratedCampaignContentProvider) {
  return collections.flatMap(([kind,field]) => content[field].map((value) => ({kind,key:value.key,visibility:value.visibility,value})));
}

/** Reconcile only when exactly one running session is attached to the same campaign. */
export function reconcileGeneratedNpcPlacementsV52(db:DatabaseDriver.Database,campaignId:string,at:string):number {
  const sessions=db.prepare(`SELECT attached.session_id FROM campaign_sessions attached JOIN sessions session ON session.id=attached.session_id
    WHERE attached.campaign_id=? AND session.state='active' AND session.stopped_at IS NULL ORDER BY attached.session_id`).all(campaignId) as Array<{session_id:string}>;
  if(sessions.length!==1)return 0;
  const sessionId=sessions[0]!.session_id;
  const intents=db.prepare(`SELECT npc_id,location_id,source_draft_id FROM generated_npc_placement_intents_v52
    WHERE campaign_id=? AND state='pending' ORDER BY npc_id`).all(campaignId) as Array<{npc_id:string;location_id:string;source_draft_id:string}>;
  if(intents.length===0)return 0;
  const rootRow=db.prepare("SELECT revision FROM npc_presence_session_revisions_v43 WHERE campaign_id=? AND session_id=?").get(campaignId,sessionId) as {revision:number}|undefined;
  let root:number=rootRow?.revision??0;
  if(!rootRow)db.prepare("INSERT INTO npc_presence_session_revisions_v43 VALUES(?,?,0,?)").run(campaignId,sessionId,at);
  for(const intent of intents){
    if(db.prepare("SELECT 1 FROM campaign_npc_presence_v43 WHERE campaign_id=? AND session_id=? AND npc_id=? AND state='present'").get(campaignId,sessionId,intent.npc_id))continue;
    const next:number=root+1,seed=`${intent.source_draft_id}:${intent.npc_id}`,commandId=stableId(campaignId,intent.source_draft_id,"placement-command",intent.npc_id),eventId=stableId(campaignId,intent.source_draft_id,"placement-event",intent.npc_id);
    db.prepare("INSERT INTO npc_presence_commands_v43 VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(campaignId,sessionId,commandId,`generated-${hash(seed).slice(0,40)}`,"local-owner",intent.npc_id,"present",intent.location_id,root,next,at);
    db.prepare("UPDATE npc_presence_session_revisions_v43 SET revision=?,updated_at=? WHERE campaign_id=? AND session_id=?").run(next,at,campaignId,sessionId);
    db.prepare("INSERT INTO npc_presence_events_v43 VALUES(?,?,?,?,?,?,?,?,?)").run(eventId,campaignId,sessionId,commandId,next,intent.npc_id,"present",intent.location_id,at);
    db.prepare("INSERT INTO npc_presence_receipts_v43 VALUES(?,?,?,?,?,?,?,?,?)").run(campaignId,sessionId,commandId,next,eventId,intent.npc_id,"present",intent.location_id,at);
    db.prepare("INSERT INTO campaign_npc_presence_v43 VALUES(?,?,?,?,?,?,?,?,?)").run(campaignId,sessionId,intent.npc_id,"present",intent.location_id,next,at,at,commandId);
    db.prepare("UPDATE generated_npc_placement_intents_v52 SET state='placed',session_id=?,reconciled_at=? WHERE campaign_id=? AND npc_id=? AND state='pending'").run(sessionId,at,campaignId,intent.npc_id);
    root=next;
  }
  return intents.length;
}

export function createCampaignGenerationRepository(db:DatabaseDriver.Database,dependencies:RepositoryDependencies,drafts:Drafts,guard:()=>void):CampaignGenerationRepository {
  const member=(principal:string,campaign:string)=>db.prepare("SELECT role FROM campaign_memberships WHERE campaign_id=? AND principal_id=?").get(campaign,principal) as {role:string}|undefined;
  const call=(campaignId:string,idempotencyKey:string):any=>db.prepare("SELECT * FROM campaign_generation_jobs_v52 WHERE campaign_id=? AND idempotency_key=?").get(campaignId,idempotencyKey);
  const accepted=(campaignId:string):ContextArtifact[]=>{
    const modern=db.prepare("SELECT * FROM campaign_generation_accepted_artifacts_v52 WHERE campaign_id=?").all(campaignId) as any[];
    const result=modern.map((row)=>({key:row.artifact_key,kind:row.artifact_kind,visibility:row.visibility,canonical:JSON.parse(row.canonical_json),digest:row.canonical_digest,sourceDraftId:row.source_draft_id,serverResourceId:row.server_resource_id}));
    const legacy=db.prepare(`SELECT * FROM campaign_generation_artifacts_v50 WHERE campaign_id=? AND artifact_key NOT IN
      (SELECT artifact_key FROM campaign_generation_accepted_artifacts_v52 WHERE campaign_id=?)`).all(campaignId,campaignId) as any[];
    for(const row of legacy){const value=JSON.parse(row.canonical_json);result.push({key:row.artifact_key,kind:row.artifact_kind,visibility:row.visibility,canonical:value,digest:hash(row.canonical_json),sourceDraftId:row.source_draft_id,serverResourceId:["location","faction","npc","quest"].includes(row.artifact_kind)?stableId(campaignId,row.source_draft_id,row.artifact_kind,row.artifact_key):null});}
    return result;
  };
  return {
    beginCampaignGenerationCall(campaignId,idempotencyKey,requestDigest,metadata,retryFailedAttempt){guard();return db.transaction(()=>{
      const row=call(campaignId,idempotencyKey);
      if(row){
        if(row.request_digest!==requestDigest)throw new AdventureTurnConflictError("idempotency key was reused");
        if(row.state!=="failed"||retryFailedAttempt===null)return {state:row.state,draftId:row.draft_id,acquired:false,attempt:row.attempt_count,jobId:row.job_id};
        if(retryFailedAttempt!==row.attempt_count)throw new AdventureTurnConflictError("failed attempt acknowledgement is stale");
        const attempt=row.attempt_count+1,at=dependencies.clock.now().toISOString();
        db.prepare("UPDATE campaign_generation_jobs_v52 SET state='running',attempt_count=?,last_outcome_code=NULL,updated_at=? WHERE job_id=? AND state='failed'").run(attempt,at,row.job_id);
        db.prepare(`INSERT INTO campaign_generation_attempts_v52(job_id,attempt,retry_count,provider,requested_model,operation,stage,prompt_version,schema_version,started_at)
          VALUES(?,?,?,?,?,?,?,?,?,?)`).run(row.job_id,attempt,attempt-1,metadata.provider,metadata.model,metadata.operation,metadata.stage,metadata.promptVersion,metadata.schemaVersion,at);
        return {state:"running" as const,draftId:null,acquired:true,attempt,jobId:row.job_id};
      }
      const at=dependencies.clock.now().toISOString();
      db.prepare("INSERT INTO campaign_generation_jobs_v52 VALUES(?,?,?,?,'running',1,NULL,NULL,?,?)").run(metadata.jobId,campaignId,idempotencyKey,requestDigest,at,at);
      db.prepare(`INSERT INTO campaign_generation_attempts_v52(job_id,attempt,retry_count,provider,requested_model,operation,stage,prompt_version,schema_version,started_at)
        VALUES(?,1,0,?,?,?,?,?,?,?)`).run(metadata.jobId,metadata.provider,metadata.model,metadata.operation,metadata.stage,metadata.promptVersion,metadata.schemaVersion,at);
      return {state:"running" as const,draftId:null,acquired:true,attempt:1,jobId:metadata.jobId};
    }).immediate();},
    getCampaignGenerationCall(campaignId,idempotencyKey,requestDigest){guard();const row=call(campaignId,idempotencyKey);if(!row)return null;if(row.request_digest!==requestDigest)throw new AdventureTurnConflictError("idempotency key was reused");return {state:row.state,draftId:row.draft_id,acquired:false,attempt:row.attempt_count,jobId:row.job_id};},
    finishCampaignGenerationCall(campaignId,idempotencyKey,attempt,draftId,outcomeCode,metadata){guard();db.transaction(()=>{
      const row=call(campaignId,idempotencyKey);if(!row||row.state!=="running"||row.attempt_count!==attempt)return;
      const at=dependencies.clock.now().toISOString();
      const changed=db.prepare(`UPDATE campaign_generation_attempts_v52 SET response_model=?,prompt_tokens=?,completion_tokens=?,total_tokens=?,latency_ms=?,estimated_cost_usd=?,terminal_at=?,outcome_code=?
        WHERE job_id=? AND attempt=? AND terminal_at IS NULL`).run(metadata?.responseModel??null,metadata?.promptTokens??null,metadata?.completionTokens??null,metadata?.totalTokens??null,metadata?.latencyMs??0,metadata?.estimatedCostUsd??null,at,draftId?"ok":outcomeCode,row.job_id,attempt);
      if(changed.changes!==1)return;
      db.prepare("UPDATE campaign_generation_jobs_v52 SET state=?,draft_id=?,last_outcome_code=?,updated_at=? WHERE job_id=? AND state='running'").run(draftId?"succeeded":"failed",draftId,draftId?"ok":outcomeCode,at,row.job_id);
    }).immediate();},
    getCampaignGenerationContext(principalId,campaignId,keys){guard();if(!member(principalId,campaignId))return null;const all=accepted(campaignId),byKey=new Map(all.map((item)=>[item.key,item]));const artifacts=keys.map((key)=>byKey.get(key)).filter((item):item is ContextArtifact=>Boolean(item));if(artifacts.length!==keys.length)throw new AdventureTurnConflictError("an expansion key is unavailable");const revision=(db.prepare("SELECT count(*) count FROM campaign_content_commands_v42 WHERE campaign_id=?").get(campaignId) as {count:number}).count;return {revision,artifacts};},
    recordCampaignGenerationCandidate(draftId,content,dependenciesInput){guard();db.transaction(()=>{
      const insert=db.prepare("INSERT INTO campaign_generation_candidate_artifacts_v52 VALUES(?,?,?,?,?)");for(const item of artifactList(content))insert.run(draftId,item.key,item.kind,item.visibility,canonical(item.value));
      const dependency=db.prepare("INSERT INTO campaign_generation_dependencies_v52 VALUES(?,?,?,?,?)");for(const item of dependenciesInput)dependency.run(draftId,item.key,item.digest,item.sourceDraftId,item.serverResourceId);
    }).immediate();},
    getCampaignGeneratedFoundation(principalId,campaignId){guard();if(!member(principalId,campaignId))return null;const row=db.prepare(`SELECT canonical_json,source_draft_id FROM campaign_generation_accepted_artifacts_v52 WHERE campaign_id=? AND artifact_kind='outline' AND visibility='public' ORDER BY accepted_at DESC LIMIT 1`).get(campaignId) as any
      ??db.prepare(`SELECT canonical_json,source_draft_id FROM campaign_generation_artifacts_v50 WHERE campaign_id=? AND artifact_kind='opening' AND visibility='public' ORDER BY created_at DESC LIMIT 1`).get(campaignId) as any;
      const revision=(db.prepare("SELECT count(*) count FROM campaign_content_commands_v42 WHERE campaign_id=?").get(campaignId) as {count:number}).count;if(!row)return campaignGeneratedFoundationSchema.parse({campaignId,revision,opening:null});const value=JSON.parse(row.canonical_json);return campaignGeneratedFoundationSchema.parse({campaignId,revision,opening:{opening:value.opening,premise:value.premise,...(value.startLocationKey?{startLocationKey:value.startLocationKey}:{}),sourceDraftId:row.source_draft_id}});},
    getCampaignGeneratedPlanning(principalId,campaignId){guard();const membership=member(principalId,campaignId);if(!membership||!['owner','gm'].includes(membership.role))return null;
      const rows=db.prepare(`SELECT artifact.*,delivery.published_at FROM campaign_generation_accepted_artifacts_v52 artifact
        LEFT JOIN campaign_material_deliveries_v53 delivery USING(campaign_id,artifact_key)
        WHERE artifact.campaign_id=? AND artifact.artifact_kind IN ('encounter','handout','scene-prompt') ORDER BY artifact.accepted_at,artifact.artifact_key`).all(campaignId) as any[];
      const resourceIds=new Map(accepted(campaignId).map((artifact)=>[artifact.key,artifact.serverResourceId]));const idFor=(key:string|null|undefined)=>key?resourceIds.get(key)??null:null;
      const encounters=[],deliverables=[];for(const row of rows){const value=JSON.parse(row.canonical_json),base={artifactKey:row.artifact_key,resourceId:row.server_resource_id,title:value.title,visibility:row.visibility,sourceDraftId:row.source_draft_id};if(row.artifact_kind==='encounter')encounters.push({...base,description:value.description,locationId:idFor(value.locationKey),participantNpcIds:value.participantNpcKeys.map((key:string)=>idFor(key)).filter(Boolean)});else deliverables.push({...base,kind:row.artifact_kind,content:row.artifact_kind==='handout'?value.content:value.prompt,locationId:idFor(value.locationKey),npcIds:(value.npcKeys??[]).map((key:string)=>idFor(key)).filter(Boolean),publishedAt:row.published_at??null});}
      const deliveryRevision=(db.prepare("SELECT revision FROM campaign_material_delivery_revisions_v53 WHERE campaign_id=?").get(campaignId) as {revision:number}|undefined)?.revision??0;return campaignGeneratedPlanningSchema.parse({campaignId,deliveryRevision,encounters,deliverables});},
    getCampaignPublishedMaterials(principalId,campaignId){guard();if(!member(principalId,campaignId))return null;const revision=(db.prepare("SELECT revision FROM campaign_material_delivery_revisions_v53 WHERE campaign_id=?").get(campaignId) as {revision:number}|undefined)?.revision??0;const rows=db.prepare(`SELECT artifact.artifact_key,artifact.artifact_kind,artifact.canonical_json,artifact.server_resource_id,delivery.published_at
        FROM campaign_material_deliveries_v53 delivery JOIN campaign_generation_accepted_artifacts_v52 artifact USING(campaign_id,artifact_key)
        WHERE delivery.campaign_id=? AND artifact.visibility='public' AND artifact.artifact_kind IN ('handout','scene-prompt') ORDER BY delivery.published_at,artifact.artifact_key`).all(campaignId) as any[];
      return campaignPublishedMaterialsSchema.parse({campaignId,revision,materials:rows.map((row)=>{const value=JSON.parse(row.canonical_json);return {artifactKey:row.artifact_key,resourceId:row.server_resource_id,kind:row.artifact_kind,title:value.title,content:row.artifact_kind==='handout'?value.content:value.prompt,publishedAt:row.published_at};})});},
    publishCampaignMaterial(principalId,campaignId,input){guard();return db.transaction(()=>{const membership=member(principalId,campaignId);if(!membership||!['owner','gm'].includes(membership.role))throw new AdventureTurnUnavailableError();const old=db.prepare(`SELECT receipt.canonical_result_json FROM campaign_material_delivery_commands_v53 command JOIN campaign_material_delivery_receipts_v53 receipt USING(campaign_id,command_id) WHERE command.campaign_id=? AND command.idempotency_key=?`).get(campaignId,input.idempotencyKey) as {canonical_result_json:string}|undefined;if(old){const result=JSON.parse(old.canonical_result_json);if(result.material.artifactKey!==input.artifactKey||result.receipt.revisionBefore!==input.expectedRevision)throw new AdventureTurnConflictError('idempotency key was reused');return result;}
      const artifact=db.prepare("SELECT * FROM campaign_generation_accepted_artifacts_v52 WHERE campaign_id=? AND artifact_key=? AND artifact_kind IN ('handout','scene-prompt') AND visibility='public'").get(campaignId,input.artifactKey) as any;if(!artifact||!artifact.server_resource_id)throw new AdventureTurnUnavailableError();const root=db.prepare("SELECT revision FROM campaign_material_delivery_revisions_v53 WHERE campaign_id=?").get(campaignId) as {revision:number}|undefined,before=root?.revision??0;if(before!==input.expectedRevision)throw new AdventureTurnStaleError();const at=dependencies.clock.now().toISOString(),after=before+1,commandId=stableId(campaignId,artifact.source_draft_id,'delivery-command',input.artifactKey);if(!root)db.prepare("INSERT INTO campaign_material_delivery_revisions_v53 VALUES(?,0,?)").run(campaignId,at);db.prepare("INSERT INTO campaign_material_delivery_commands_v53 VALUES(?,?,?,?,?,?,?,?)").run(campaignId,commandId,principalId,input.artifactKey,input.idempotencyKey,before,after,at);db.prepare("INSERT INTO campaign_material_deliveries_v53 VALUES(?,?,?,?,?)").run(campaignId,input.artifactKey,artifact.server_resource_id,commandId,at);const value=JSON.parse(artifact.canonical_json),material={artifactKey:input.artifactKey,resourceId:artifact.server_resource_id,kind:artifact.artifact_kind,title:value.title,content:artifact.artifact_kind==='handout'?value.content:value.prompt,publishedAt:at},result={material,receipt:{idempotencyKey:input.idempotencyKey,revisionBefore:before,revisionAfter:after,occurredAt:at}};db.prepare("INSERT INTO campaign_material_delivery_receipts_v53 VALUES(?,?,?,?,?)").run(campaignId,commandId,after,canonical(result),at);db.prepare("UPDATE campaign_material_delivery_revisions_v53 SET revision=?,updated_at=? WHERE campaign_id=?").run(after,at,campaignId);return result;}).immediate();},
    applyCampaignContentGenerationDraftAtomically(principalId,input){guard();return db.transaction(()=>{
      const before=drafts.getGenerationDraft(principalId,input.draftId) as PrivateGenerationDraft|null;if(!before||!("stagedContent" in before))throw new AdventureTurnUnavailableError();
      const applyKey=`content-apply:${hash(input.idempotencyKey).slice(0,48)}`;
      if(before.state==="applied"){const prior=db.prepare("SELECT idempotency_key,result_json FROM campaign_content_commands_v42 command JOIN campaign_content_receipts_v42 receipt ON receipt.command_id=command.command_id WHERE command.draft_id=?").get(before.draftId) as any;if(prior?.idempotency_key!==applyKey||JSON.parse(prior.result_json).selectedArtifactKeys?.join("\0")!==input.selectedArtifactKeys.join("\0"))throw new AdventureTurnConflictError("idempotency key or selection was reused");return before;}
      const staged=stagedCampaignContentGenerationSchema.parse(before.stagedContent),current=(db.prepare("SELECT count(*) count FROM campaign_content_commands_v42 WHERE campaign_id=?").get(before.campaignId) as {count:number}).count;if(current!==staged.baseContentRevision)throw new AdventureTurnStaleError("campaign content changed after generation");
      const existing=accepted(before.campaignId),acceptedByKey=new Map(existing.map((item)=>[item.key,item]));for(const [key,digest] of Object.entries(staged.dependencyDigests)){if(acceptedByKey.get(key)?.digest!==digest)throw new AdventureTurnStaleError("generation dependency changed");}
      const candidateRows=db.prepare("SELECT * FROM campaign_generation_candidate_artifacts_v52 WHERE draft_id=?").all(before.draftId) as any[],candidateByKey=new Map(candidateRows.map((row)=>[row.artifact_key,row]));if(new Set(input.selectedArtifactKeys).size!==input.selectedArtifactKeys.length||input.selectedArtifactKeys.some((key)=>!candidateByKey.has(key)||acceptedByKey.has(key)))throw new AdventureTurnConflictError("artifact selection is unavailable");
      const selected=new Set(input.selectedArtifactKeys),resolve=(key:string)=>selected.has(key)||acceptedByKey.has(key),referenceKeys=(kind:string,value:any):string[]=>kind==="outline"?(value.startLocationKey?[value.startLocationKey]:[]):kind==="location"?value.factionKeys:kind==="connection"?[value.fromLocationKey,value.toLocationKey]:kind==="npc"?[...(value.locationKey?[value.locationKey]:[]),...value.factionKeys]:kind==="quest"?[...(value.arcKey?[value.arcKey]:[]),...value.locationKeys]:kind==="encounter"?[...(value.locationKey?[value.locationKey]:[]),...value.participantNpcKeys]:kind==="clue"?[...(value.locationKey?[value.locationKey]:[]),...(value.revealsStoryNodeKey?[value.revealsStoryNodeKey]:[])]:kind==="story-relationship"?[value.fromStoryNodeKey,value.toStoryNodeKey]:kind==="scene-prompt"?[...(value.locationKey?[value.locationKey]:[]),...value.npcKeys]:[];
      for(const key of selected){const row=candidateByKey.get(key)!,value=JSON.parse(row.canonical_json);if(referenceKeys(row.artifact_kind,value).some((ref)=>!resolve(ref)))throw new AdventureTurnConflictError("selected artifacts have an unresolved dependency");}
      const reviewed=drafts.reviewGenerationDraft(principalId,{draftId:before.draftId,decision:"approved",expectedDraftRevision:input.expectedDraftRevision,expectedCampaignRevision:before.campaignRevision,idempotencyKey:`content-review:${hash(input.idempotencyKey).slice(0,48)}`});
      const at=dependencies.clock.now().toISOString(),commandId=stableId(before.campaignId,before.draftId,"command","apply");db.prepare("INSERT INTO campaign_content_commands_v42 VALUES(?,?,?,?,?,?,?)").run(commandId,before.campaignId,before.draftId,hash(principalId),applyKey,before.campaignRevision,at);
      const ids=new Map(existing.filter((item)=>item.serverResourceId).map((item)=>[item.key,item.serverResourceId!]));const priority=["arc","location","faction","npc","connection","quest","story-node","story-relationship","clue","encounter","handout","scene-prompt","outline"],selectedRows=[...selected].map((key)=>candidateByKey.get(key)!).sort((a,b)=>priority.indexOf(a.artifact_kind)-priority.indexOf(b.artifact_kind));
       for(const row of selectedRows)if(["arc","location","faction","npc","connection","quest","story-node","story-relationship","clue","encounter","handout","scene-prompt"].includes(row.artifact_kind))ids.set(row.artifact_key,stableId(before.campaignId,before.draftId,row.artifact_kind,row.artifact_key));
      let worldRevision=(db.prepare("SELECT revision FROM world_narrative_revisions_v32 WHERE campaign_id=?").get(before.campaignId) as {revision:number}|undefined)?.revision??0;db.prepare("INSERT INTO world_narrative_revisions_v32 VALUES(?,0,?) ON CONFLICT DO NOTHING").run(before.campaignId,at);
      const recordWorld=(kind:"npc"|"faction",resourceId:string,key:string,publicState:unknown,privateState:unknown)=>{const next=worldRevision+1,worldCommand=stableId(before.campaignId,before.draftId,`${kind}-command`,key),request=canonical({kind:`generated-${kind}`,sourceDraftId:before.draftId,artifactKey:key,publicState,privateState}),result=canonical({resourceId,sourceDraftId:before.draftId,artifactKey:key});db.prepare("INSERT INTO world_narrative_commands_v32 VALUES(?,?,?,?,?,?,?,?,?,?)").run(before.campaignId,worldCommand,resourceId,kind==="npc"?"create_npc":"create_faction",`generated-${hash(`${before.draftId}:${kind}:${key}`).slice(0,40)}`,request,hash(request),worldRevision,next,at);db.prepare("INSERT INTO world_narrative_receipts_v32 VALUES(?,?,?,?,?,?)").run(before.campaignId,worldCommand,next,result,hash(result),at);db.prepare("INSERT INTO world_narrative_events_v32 VALUES(?,?,?,?,?,?,?)").run(stableId(before.campaignId,before.draftId,`${kind}-event`,key),before.campaignId,worldCommand,next,kind==="npc"?"npc_created":"faction_created",canonical({resourceId,sourceDraftId:before.draftId}),at);db.prepare("UPDATE world_narrative_revisions_v32 SET revision=?,updated_at=? WHERE campaign_id=?").run(next,at,before.campaignId);worldRevision=next;return worldCommand;};
      const storyRoot=db.prepare("SELECT revision FROM story_campaign_revisions_v34 WHERE campaign_id=?").get(before.campaignId) as {revision:number}|undefined;let storyRevision=storyRoot?.revision??0;if(!storyRoot)db.prepare("INSERT INTO story_campaign_revisions_v34 VALUES(?,0,?)").run(before.campaignId,at);
       const graphRows=selectedRows.filter((row)=>["story-node","story-relationship","clue"].includes(row.artifact_kind));
       const graphArcKey=(selectedRows.find((row)=>row.artifact_kind==="arc")?JSON.parse(selectedRows.find((row)=>row.artifact_kind==="arc")!.canonical_json).key:null) as string|null;
       const graphNodeKeys=new Set(graphRows.filter((row)=>row.artifact_kind==="story-node").map((row)=>JSON.parse(row.canonical_json).key as string));
       for(const row of graphRows){const value=JSON.parse(row.canonical_json);if(row.artifact_kind==="story-relationship"&&(!graphNodeKeys.has(value.fromStoryNodeKey)||!graphNodeKeys.has(value.toStoryNodeKey)))throw new AdventureTurnConflictError("story relationships require selected nodes in the same graph");if(row.artifact_kind==="clue"&&value.revealsStoryNodeKey&&!graphNodeKeys.has(value.revealsStoryNodeKey))throw new AdventureTurnConflictError("clue story sources must be selected in the same graph");}
       const createStoryline=(storylineId:string,key:string,title:string,summary:string,withGraph=false)=>{const storyCommand=stableId(before.campaignId,before.draftId,"story-command",key),idempotencyKey=`generated-${hash(`${before.draftId}:${key}`).slice(0,40)}`,next=storyRevision+1;
         const nodeRows=withGraph?graphRows.filter((row)=>row.artifact_kind==="story-node"):[],edgeRows=withGraph?graphRows.filter((row)=>row.artifact_kind==="story-relationship"):[],clueRows=withGraph?graphRows.filter((row)=>row.artifact_kind==="clue"):[];
         const nodes=nodeRows.map((row)=>{const value=JSON.parse(row.canonical_json);return {nodeId:ids.get(value.key)!,title:value.title,description:value.description,gmNotes:value.visibility==="gm"?value.description:null,revealThreshold:0};});
         for(const row of clueRows){const value=JSON.parse(row.canonical_json);if(!value.revealsStoryNodeKey)nodes.push({nodeId:stableId(before.campaignId,before.draftId,"clue-anchor",value.key),title:`Source: ${value.title}`,description:value.description,gmNotes:value.visibility==="gm"?value.description:null,revealThreshold:0});}
         const edges=edgeRows.map((row)=>{const value=JSON.parse(row.canonical_json);return {edgeId:ids.get(value.key)!,kind:"sequence" as const,fromNodeId:ids.get(value.fromStoryNodeKey)!,toNodeId:ids.get(value.toStoryNodeKey)!};});
         const clues=clueRows.map((row)=>{const value=JSON.parse(row.canonical_json);return {clueId:ids.get(value.key)!,title:value.title,content:value.description,truth:value.description,gmNotes:value.visibility==="gm"?value.description:null,revealThreshold:1,sources:[{sourceId:stableId(before.campaignId,before.draftId,"clue-source",value.key),kind:"node" as const,targetId:value.revealsStoryNodeKey?ids.get(value.revealsStoryNodeKey)!:stableId(before.campaignId,before.draftId,"clue-anchor",value.key)}]};});
         const storyline={storylineId,title,summary,nodes,edges,plotPoints:[],clues},request=canonical({campaignId:before.campaignId,expectedRevision:storyRevision,idempotencyKey,storyline});db.prepare("INSERT INTO story_commands_v34 VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(before.campaignId,storyCommand,storylineId,principalId,"create-storyline",idempotencyKey,request,hash(request),storyRevision,next,at);db.prepare("INSERT INTO quest_storylines(id,campaign_id,title,description,status,created_at) VALUES(?,?,?,?,'active',?)").run(storylineId,before.campaignId,title,summary,at);db.prepare("INSERT INTO story_metadata_v34 VALUES(?,?,?,?,?,?)").run(before.campaignId,storylineId,summary,"active",storyCommand,at);
         nodes.forEach((node,index)=>{db.prepare("INSERT INTO story_nodes_v34 VALUES(?,?,?,?,?,?,?,?,?)").run(before.campaignId,storylineId,node.nodeId,node.title,node.description,node.gmNotes,node.revealThreshold,index,storyCommand);db.prepare("INSERT INTO story_node_state_v34 VALUES(?,?,?,?,?,?)").run(before.campaignId,storylineId,node.nodeId,"hidden",storyCommand,at);});for(const edge of edges)db.prepare("INSERT INTO story_edges_v34 VALUES(?,?,?,?,?,?,?)").run(before.campaignId,storylineId,edge.edgeId,edge.kind,edge.fromNodeId,edge.toNodeId,storyCommand);for(const clue of clues){db.prepare("INSERT INTO story_clues_v34 VALUES(?,?,?,?,?,?,?,?,?)").run(before.campaignId,storylineId,clue.clueId,clue.title,clue.content,clue.truth,clue.gmNotes,clue.revealThreshold,storyCommand);for(const source of clue.sources)db.prepare("INSERT INTO story_clue_sources_v34 VALUES(?,?,?,?,?,?)").run(before.campaignId,storylineId,clue.clueId,source.sourceId,source.kind,source.targetId);}
         const story={storylines:[{storylineId,campaignId:before.campaignId,title,summary,status:"active",createdAt:at,updatedAt:at}],nodes:nodes.map((node)=>({...node,storylineId,status:"hidden",createdAt:at,updatedAt:at})),edges:edges.map((edge)=>({...edge,storylineId})),plotPoints:[],clues:clues.map((clue)=>({...clue,storylineId,revealed:false,revealedAt:null}))};const result=canonical({campaignId:before.campaignId,storyline:{storylineId,campaignId:before.campaignId,title,summary,status:"active",createdAt:at,updatedAt:at},story,receipt:{commandId:storyCommand,idempotencyKey,revisionBefore:storyRevision,revisionAfter:next,occurredAt:at}});db.prepare("INSERT INTO story_receipts_v34 VALUES(?,?,?,?,?,?)").run(before.campaignId,storyCommand,next,result,hash(result),at);db.prepare("INSERT INTO story_events_v34 VALUES(?,?,?,?,?,?,?)").run(stableId(before.campaignId,before.draftId,"story-event",key),before.campaignId,storyCommand,next,"storyline-created",canonical({storylineId}),at);db.prepare("UPDATE story_campaign_revisions_v34 SET revision=?,updated_at=? WHERE campaign_id=?").run(next,at,before.campaignId);storyRevision=next;};
      const questRoot=db.prepare("SELECT revision FROM quest_domain_revisions_v33 WHERE campaign_id=?").get(before.campaignId) as {revision:number}|undefined;let fallbackStoryline:string|null=null,questRevision=questRoot?.revision??0;if(!questRoot)db.prepare("INSERT INTO quest_domain_revisions_v33 VALUES(?,0,?)").run(before.campaignId,at);
       if(graphRows.length&&!graphArcKey){const graphId=stableId(before.campaignId,before.draftId,"arc","generated-story");createStoryline(graphId,"generated-story","Generated story",`Story material from ${before.draftId}`,true);}
       for(const row of selectedRows){const value=JSON.parse(row.canonical_json),kind=row.artifact_kind;let serverId:string|null=null;
         if(kind==="arc"){serverId=ids.get(value.key)!;createStoryline(serverId,value.key,value.title,value.summary,value.key===graphArcKey);}
        if(kind==="location"){serverId=ids.get(value.key)!;db.prepare("INSERT INTO campaign_locations_v28(location_id,campaign_id,parent_location_id,public_name,public_description,visibility,created_at) VALUES(?,?,?,?,?,?,?)").run(serverId,before.campaignId,null,value.name,value.description,value.visibility,at);db.prepare("INSERT INTO campaign_location_private_state_v28 VALUES(?,?,?)").run(before.campaignId,serverId,"");}
        if(kind==="faction"){serverId=ids.get(value.key)!;db.prepare("INSERT INTO campaign_factions_v28 VALUES(?,?,?,?,?)").run(serverId,before.campaignId,value.name,value.visibility,at);db.prepare("INSERT INTO campaign_faction_private_state_v28 VALUES(?,?,?)").run(before.campaignId,serverId,value.gmNotes??"");const created=recordWorld("faction",serverId,value.key,{description:value.description},{gmNotes:value.gmNotes??"",visibility:value.visibility});db.prepare("INSERT INTO campaign_faction_metadata_v32 VALUES(?,?,?,?,?,?)").run(serverId,before.campaignId,canonical({description:value.description}),canonical({gmNotes:value.gmNotes??"",visibility:value.visibility}),created,at);}
        if(kind==="npc"){serverId=ids.get(value.key)!;const persona=stableId(before.campaignId,before.draftId,"persona",value.key);db.prepare("INSERT INTO characters(id,name,age,archetype,boundaries,fictional_confirmed,is_real_person,created_at) VALUES(?,?,18,?,'Generated fictional NPC',1,0,?)").run(persona,value.name,value.archetype,at);db.prepare("INSERT INTO campaign_npcs_v28 VALUES(?,?,?,'manual',?,?)").run(serverId,before.campaignId,persona,value.name,at);db.prepare("INSERT INTO campaign_npc_private_state_v28 VALUES(?,?,?,?,NULL)").run(before.campaignId,serverId,value.privateGoals??"","");const created=recordWorld("npc",serverId,value.key,{name:value.name,description:value.description},{goals:value.privateGoals??"",gmNotes:"",merchantState:null});db.prepare("INSERT INTO campaign_npc_metadata_v32 VALUES(?,?,?,?,?,?)").run(serverId,before.campaignId,canonical({name:value.name,description:value.description}),canonical({goals:value.privateGoals??"",gmNotes:"",merchantState:null}),created,at);db.prepare("INSERT INTO campaign_npc_baseline_stats_v41 VALUES(?,?,10,10,10,'generated-deterministic-baseline')").run(before.campaignId,serverId);}
        if(kind==="connection"){serverId=ids.get(value.key)!;db.prepare("INSERT INTO campaign_location_connections_v28 VALUES(?,?,?,?,?,'open','none',NULL,NULL,?)").run(serverId,before.campaignId,ids.get(value.fromLocationKey),ids.get(value.toLocationKey),value.visibility,at);}
         if(kind==="quest"){serverId=ids.get(value.key)!;let storyline=value.arcKey?ids.get(value.arcKey):null;if(!storyline){if(!fallbackStoryline){fallbackStoryline=stableId(before.campaignId,before.draftId,"arc","standalone-quests");createStoryline(fallbackStoryline,"standalone-quests","Generated quests",`Additive quests from ${before.draftId}`);}storyline=fallbackStoryline;}const qcommand=stableId(before.campaignId,before.draftId,"quest-command",value.key),next=questRevision+1,request=canonical({kind:"generated",sourceDraftId:before.draftId,questKey:value.key});db.prepare("INSERT INTO quest_domain_commands_v33 VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(before.campaignId,qcommand,serverId,principalId,"create",`generated-${hash(`${before.draftId}:${value.key}`).slice(0,40)}`,request,hash(request),questRevision,next,at);db.prepare("INSERT INTO quests VALUES(?,?,?,?,?,?,?,?,?)").run(serverId,storyline,before.campaignId,value.title,value.description,"open",0,at,at);db.prepare("INSERT INTO quest_definitions_v33 VALUES(?,?,?,?)").run(before.campaignId,serverId,value.visibility,qcommand);const result=canonical({campaignId:before.campaignId,questId:serverId,sourceDraftId:before.draftId});db.prepare("INSERT INTO quest_domain_receipts_v33 VALUES(?,?,?,?,?,?)").run(before.campaignId,qcommand,next,result,hash(result),at);db.prepare("INSERT INTO quest_domain_events_v33 VALUES(?,?,?,?,?,?,?)").run(stableId(before.campaignId,before.draftId,"quest-event",value.key),before.campaignId,qcommand,next,"quest-created",canonical({questId:serverId,kind:"generated"}),at);db.prepare("UPDATE quest_domain_revisions_v33 SET revision=?,updated_at=? WHERE campaign_id=?").run(next,at,before.campaignId);questRevision=next;}
         if(["story-node","story-relationship","clue","encounter","handout","scene-prompt"].includes(kind))serverId=ids.get(value.key)!;
        const json=row.canonical_json;db.prepare("INSERT INTO campaign_generation_accepted_artifacts_v52 VALUES(?,?,?,?,?,?,?,?,?)").run(before.campaignId,value.key,kind,value.visibility,json,hash(json),before.draftId,serverId,at);
      }
      for(const row of selectedRows){if(row.artifact_kind!=="npc")continue;const value=JSON.parse(row.canonical_json);if(!value.locationKey)continue;const npcId=ids.get(value.key),locationId=ids.get(value.locationKey);if(!npcId||!locationId)throw new AdventureTurnConflictError("NPC placement reference is unavailable");db.prepare("INSERT INTO generated_npc_placement_intents_v52 VALUES(?,?,?,?,'pending',NULL,?,NULL)").run(before.campaignId,npcId,locationId,before.draftId,at);}
      const outline=selectedRows.find((row)=>row.artifact_kind==="outline");if(outline){const value=JSON.parse(outline.canonical_json);if(value.startLocationKey){const start=ids.get(value.startLocationKey);if(!start)throw new AdventureTurnConflictError("starting location is unavailable");db.prepare("INSERT INTO campaign_starting_locations_v51(campaign_id,location_id,designated_at) VALUES(?,?,?) ON CONFLICT(campaign_id) DO NOTHING").run(before.campaignId,start,at);}}
      reconcileGeneratedNpcPlacementsV52(db,before.campaignId,at);
      const result={scope:"campaign-content",selectedArtifactKeys:input.selectedArtifactKeys},applied=drafts.applyGenerationDraft(principalId,{draftId:before.draftId,expectedDraftRevision:reviewed.revision,expectedCampaignRevision:reviewed.campaignRevision,idempotencyKey:applyKey,result});db.prepare("INSERT INTO campaign_content_receipts_v42 VALUES(?,?,?,?,?,?)").run(stableId(before.campaignId,before.draftId,"receipt","apply"),commandId,before.campaignId,before.draftId,at,canonical(result));return applied;
    }).immediate();},
    reconcileGeneratedNpcPlacements(campaignId){guard();return db.transaction(()=>reconcileGeneratedNpcPlacementsV52(db,campaignId,dependencies.clock.now().toISOString())).immediate();},
  };
}
