import type DatabaseDriver from "better-sqlite3";
import { checkCommandSchema, checkResolutionSchema, resourceIdSchema, type CheckCommand, type CheckResolution } from "@velvet/contracts";
import { evaluateDiceExpression } from "../dice.js";
import { m15Authorized } from "./actorResourceRepo.js";
import { M16ConflictError, runM16Mutation, type M16Dependencies, type M16Result } from "./effectRepo.js";

export class CheckUnavailableError extends Error { readonly code="CHECK_UNAVAILABLE"; }
const keys=new Set(["might","agility","resolve","insight","presence","craft","melee","ranged","spell","defense"]);
export interface CheckRepository { resolveCheck(principal:string,command:CheckCommand):M16Result<{resolution:CheckResolution}>; }
export function createCheckRepository(db:DatabaseDriver.Database,deps:M16Dependencies,guard:()=>void):CheckRepository{return {resolveCheck(principal,input){
 const command=checkCommandSchema.parse(input);
 return runM16Mutation(db,deps,guard,{principal,campaignId:command.campaignId,actorId:command.actorId,family:'check',type:'resolve_check',expectedRevision:command.expectedRevision,idempotencyKey:command.idempotencyKey,request:command,eventType:'check_resolved',build:(after,now,id)=>{
 const key=command.kind==='ability'||command.kind==='save'?command.abilityId:command.kind==='skill'?command.skillId:command.kind==='attack'?command.attackId:'insight';if(!keys.has(key))throw new CheckUnavailableError("unsupported check key");
 const sheet=db.prepare("SELECT sheet_id FROM campaign_actors WHERE campaign_id=? AND id=?").get(command.campaignId,command.actorId)as any;if(!sheet)throw new CheckUnavailableError("actor unavailable");
 const attribute=db.prepare("SELECT value FROM rpg_character_attributes WHERE campaign_id=? AND sheet_id=? AND attribute_id=?").get(command.campaignId,sheet.sheet_id,key)as any;
 const profCategory=command.kind==='save'?'saving-throw':command.kind==='skill'?'skill':command.kind==='attack'?'weapon':'none';const prof=Boolean(db.prepare("SELECT 1 FROM rpg_character_proficiencies WHERE campaign_id=? AND sheet_id=? AND category=? AND proficiency_id=?").get(command.campaignId,sheet.sheet_id,profCategory,key));
 const effects=(db.prepare(`SELECT command.canonical_request_json FROM rpg_active_effects_v26 e JOIN rpg_m16_commands_v26 command ON command.campaign_id=e.campaign_id AND command.actor_id=e.actor_id AND command.command_id=e.command_id WHERE e.campaign_id=? AND e.actor_id=? AND e.status='active' AND (e.duration_kind<>'rounds' OR e.remaining_rounds>0) AND (e.duration_kind<>'until_timestamp' OR e.expires_at>?)`).all(command.campaignId,command.actorId,now)as any[]).flatMap(row=>JSON.parse(row.canonical_request_json).effect.modifiers).filter((modifier:any)=>modifier.appliesToId===key||modifier.appliesToId==='all').map((modifier:any)=>({modifier_kind:modifier.kind,amount:modifier.amount??modifier.bonus??0}));
 const advantage=effects.some(e=>e.modifier_kind==='advantage'),roll=evaluateDiceExpression(advantage?'1d20adv':'1d20',deps.rng);const flat=(attribute?.value??0)+effects.filter(e=>e.modifier_kind==='flat').reduce((n,e)=>n+e.amount,0);const proficiency=prof?2+effects.filter(e=>e.modifier_kind==='proficiency').reduce((n,e)=>n+e.amount,0):0;const terms:any[]=[{kind:'roll',roll},{kind:'flat',sourceId:null,value:flat}];if(proficiency)terms.push({kind:'proficiency',sourceId:key,value:proficiency});const total=terms.reduce((n,t)=>n+(t.kind==='roll'?t.roll.total:t.value),0),target=command.kind==='opposed'?{kind:'opposed_total' as const,actorId:command.opponentActorId,value:14}:{kind:'difficulty_class' as const,value:10},outcome=roll.terms.some(t=>t.kept&&t.value===20)?'critical_success':roll.terms.some(t=>t.kept&&t.value===1)?'critical_failure':total>=target.value?'success':'failure';const resolution=checkResolutionSchema.parse({terms,total,target,outcome});
 return {result:{resolution},persist:()=>db.prepare("INSERT INTO rpg_check_results_v26(check_id,campaign_id,actor_id,command_id,resulting_revision,check_kind,check_key,target_actor_id,difficulty,dice_json,result_json,total,resolved_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(resourceIdSchema.parse(deps.ids.nextId()),command.campaignId,command.actorId,id,after,command.kind,key,command.kind==='opposed'?command.opponentActorId:command.kind==='attack'?command.targetActorId:null,target.value,JSON.stringify([roll]),JSON.stringify(resolution),total,now)};
}});}};}
