import { createHash } from "node:crypto";
import type DatabaseDriver from "better-sqlite3";
import { changeReputationCommandSchema, discoverLocationCommandSchema, resourceIdSchema, setActorLocationCommandSchema, travelCommandSchema, utcIsoTimestampSchema, worldCommandSchema, worldProjectionSchema, type TravelCommand, type WorldProjection } from "@velvet/contracts";
import type { Clock, IdGenerator } from "../runtime.js";

export class WorldAuthorizationError extends Error { readonly code="WORLD_FORBIDDEN"; }
export class WorldStaleError extends Error { readonly code="WORLD_STALE"; }
export class WorldConflictError extends Error { readonly code="WORLD_CONFLICT"; }
export class WorldUnavailableError extends Error { readonly code="WORLD_UNAVAILABLE"; }
export type WorldDependencies={clock:Clock;ids:IdGenerator};
export type WorldReceipt={travelId:string;destinationLocationId:string;receipt:{commandId:string;idempotencyKey:string;revisionBefore:number;revisionAfter:number;occurredAt:string}};
type MutationReceipt={receipt:{commandId:string;idempotencyKey:string;revisionBefore:number;revisionAfter:number;occurredAt:string}};
const canonical=(v:unknown)=>JSON.stringify(v,(_k,x)=>x&&typeof x==="object"&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,x[k]])):x);
const digest=(v:unknown)=>createHash("sha256").update(canonical(v)).digest("hex");
const member=(db:DatabaseDriver.Database,p:string,c:string)=>Boolean(db.prepare("SELECT 1 FROM campaign_memberships WHERE campaign_id=? AND principal_id=?").get(c,p));
const gm=(db:DatabaseDriver.Database,p:string,c:string)=>Boolean(db.prepare("SELECT 1 FROM campaign_memberships WHERE campaign_id=? AND principal_id=? AND role IN ('owner','gm')").get(c,p));
const controls=(db:DatabaseDriver.Database,p:string,c:string,a:string)=>Boolean(db.prepare("SELECT 1 FROM campaign_actor_private_state WHERE campaign_id=? AND actor_id=? AND controller_principal_id=?").get(c,a,p));

export interface WorldRepository {
  executeWorldCommand(principalId:string,sessionId:string,command:unknown):WorldReceipt|MutationReceipt;
  travel(principalId:string,sessionId:string,command:TravelCommand):WorldReceipt;
  setActorLocation(principalId:string,sessionId:string,command:unknown):MutationReceipt;
  getWorldProjection(principalId:string,campaignId:string,sessionId:string):WorldProjection|null;
  createLocation(principalId:string,input:unknown):{locationId:string;campaignId:string};
  createLocationConnection(principalId:string,input:unknown):{locationConnectionId:string;campaignId:string};
  createNpc(principalId:string,input:unknown):{npcId:string;campaignId:string};
  changeReputation(principalId:string,sessionId:string,input:unknown):MutationReceipt;
}

export function createWorldRepository(db:DatabaseDriver.Database,deps:WorldDependencies,guard:()=>void):WorldRepository {
  const now=()=>utcIsoTimestampSchema.parse(deps.clock.now().toISOString()); const id=()=>resourceIdSchema.parse(deps.ids.nextId());
  const requireGm=(p:string,c:string)=>{if(!gm(db,p,c))throw new WorldAuthorizationError("GM authority is required");};
  const session=(c:string,s:string)=>{if(!db.prepare("SELECT 1 FROM campaign_sessions WHERE campaign_id=? AND session_id=?").get(c,s))throw new WorldUnavailableError("session does not belong to campaign");};
  function begin(p:string,s:string,raw:unknown, type:string, actor:string, authorize:()=>void): { command:any;at:string;commandId:string;before:number;after:number;replay:any } {
    const command=worldCommandSchema.parse(raw); if(command.type!==type) throw new WorldUnavailableError("wrong world command");
    if(!member(db,p,command.campaignId)) throw new WorldAuthorizationError("campaign membership is required"); session(command.campaignId,s); authorize();
    const request=canonical(command); const replay=db.prepare("SELECT c.canonical_request_json,r.canonical_result_json FROM world_commands_v28 c JOIN world_receipts_v28 r USING(campaign_id,session_id,command_id) WHERE c.campaign_id=? AND c.session_id=? AND c.idempotency_key=?").get(command.campaignId,s,command.idempotencyKey) as any;
    if(replay){if(replay.canonical_request_json!==request)throw new WorldConflictError("idempotency key was reused"); return {command,at:"",commandId:"",before:0,after:0,replay};}
    const root=db.prepare("SELECT revision FROM world_mutation_revisions_v28 WHERE campaign_id=? AND session_id=?").get(command.campaignId,s) as any; const before=root?.revision??0;
    if(before!==command.expectedRevision)throw new WorldStaleError("world revision is stale"); return {command,at:now(),commandId:id(),before,after:before+1,replay:null};
  }
  function record(c:any,s:string,type:string,actor:string,b:any,result:any,eventType:string,event:any){
    if(!db.prepare("SELECT 1 FROM world_mutation_revisions_v28 WHERE campaign_id=? AND session_id=?").get(c.campaignId,s))db.prepare("INSERT INTO world_mutation_revisions_v28 VALUES(?,?,?,?)").run(c.campaignId,s,0,b.at);
    db.prepare("INSERT INTO world_commands_v28 VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(c.campaignId,s,b.commandId,actor,type,c.idempotencyKey,canonical(c),digest(c),b.before,b.after,b.at);
    db.prepare("INSERT INTO world_receipts_v28 VALUES(?,?,?,?,?,?,?)").run(c.campaignId,s,b.commandId,b.after,canonical(result),digest(result),b.at);
    db.prepare("INSERT INTO world_events_v28 VALUES(?,?,?,?,?,?,?,?)").run(id(),c.campaignId,s,b.commandId,b.after,eventType,canonical(event),b.at);
    db.prepare("UPDATE world_mutation_revisions_v28 SET revision=?,updated_at=? WHERE campaign_id=? AND session_id=?").run(b.after,b.at,c.campaignId,s);
  }
  function receipt(b:any,key:string):MutationReceipt{return {receipt:{commandId:b.commandId,idempotencyKey:key,revisionBefore:b.before,revisionAfter:b.after,occurredAt:b.at}};}
  function setActorLocation(p:string,s:string,raw:unknown):MutationReceipt {guard(); return db.transaction(()=>{const b=begin(p,s,setActorLocationCommandSchema.parse(raw),"set_actor_location","",()=>requireGm(p,(raw as any).campaignId)); if(b.replay)return JSON.parse(b.replay.canonical_result_json); const c=b.command;
    if(!db.prepare("SELECT 1 FROM campaign_actors WHERE campaign_id=? AND id=?").get(c.campaignId,c.actorId)||!db.prepare("SELECT 1 FROM campaign_locations_v28 WHERE campaign_id=? AND location_id=?").get(c.campaignId,c.locationId))throw new WorldUnavailableError("actor or location is unavailable"); const result=receipt(b,c.idempotencyKey); record(c,s,"set_actor_location",c.actorId,b,result,"actor_location_set",{actorId:c.actorId,locationId:c.locationId});
    const existing=db.prepare("SELECT 1 FROM campaign_actor_locations_v28 WHERE campaign_id=? AND actor_id=? AND session_id=?").get(c.campaignId,c.actorId,s); if(existing)db.prepare("UPDATE campaign_actor_locations_v28 SET location_id=?,state_revision=state_revision+1,updated_at=? WHERE campaign_id=? AND actor_id=? AND session_id=?").run(c.locationId,b.at,c.campaignId,c.actorId,s); else db.prepare("INSERT INTO campaign_actor_locations_v28 VALUES(?,?,?,?,0,?)").run(c.campaignId,c.actorId,c.locationId,s,b.at); return result;
  }).immediate();}
  function discoverCommand(p:string,s:string,raw:unknown):MutationReceipt {guard();return db.transaction(()=>{const b=begin(p,s,discoverLocationCommandSchema.parse(raw),"discover_location","",()=>requireGm(p,(raw as any).campaignId));if(b.replay)return JSON.parse(b.replay.canonical_result_json);const c=b.command;if(!db.prepare("SELECT 1 FROM campaign_actors WHERE campaign_id=? AND id=?").get(c.campaignId,c.actorId)||!db.prepare("SELECT 1 FROM campaign_locations_v28 WHERE campaign_id=? AND location_id=?").get(c.campaignId,c.locationId))throw new WorldUnavailableError("actor or location is unavailable");const result=receipt(b,c.idempotencyKey);record(c,s,"discover_location",c.actorId,b,result,"location_discovered",{actorId:c.actorId,locationId:c.locationId});db.prepare("INSERT OR IGNORE INTO campaign_location_discoveries_v28 VALUES(?,?,?,?)").run(c.campaignId,c.actorId,c.locationId,b.at);return result;}).immediate();}
  function travel(p:string,s:string,raw:TravelCommand):WorldReceipt {guard();return db.transaction(()=>{const b=begin(p,s,travelCommandSchema.parse(raw),"travel","",()=>{const c=raw as any;if(!gm(db,p,c.campaignId)&&c.selectedPartyActorIds.some((a:string)=>!controls(db,p,c.campaignId,a)))throw new WorldAuthorizationError("party control is required");});if(b.replay)return JSON.parse(b.replay.canonical_result_json);const c=b.command;const route=db.prepare("SELECT * FROM campaign_location_connections_v28 WHERE campaign_id=? AND connection_id=?").get(c.campaignId,c.locationConnectionId) as any;if(!route||route.route_state!=="open"||route.visibility==="gm")throw new WorldUnavailableError("route is unavailable");
    for(const actorId of c.selectedPartyActorIds){const pos=db.prepare("SELECT location_id FROM campaign_actor_locations_v28 WHERE campaign_id=? AND actor_id=? AND session_id=?").get(c.campaignId,actorId,s) as any;if(!pos||pos.location_id!==route.from_location_id)throw new WorldUnavailableError("party is not adjacent to route");if((route.visibility==="discovered"||route.requirement_kind==="discovery")&&!db.prepare("SELECT 1 FROM campaign_location_discoveries_v28 WHERE campaign_id=? AND actor_id=? AND location_id=?").get(c.campaignId,actorId,route.to_location_id))throw new WorldUnavailableError("route destination is undiscovered");}
    const result:WorldReceipt={travelId:c.travelId,destinationLocationId:route.to_location_id,receipt:{commandId:b.commandId,idempotencyKey:c.idempotencyKey,revisionBefore:b.before,revisionAfter:b.after,occurredAt:b.at}};record(c,s,"travel",c.selectedPartyActorIds[0],b,result,"travelled",{travelId:c.travelId,destinationLocationId:route.to_location_id});for(const actorId of c.selectedPartyActorIds){db.prepare("INSERT INTO world_travel_party_members_v28 VALUES(?,?,?,?)").run(c.campaignId,s,b.commandId,actorId);db.prepare("UPDATE campaign_actor_locations_v28 SET location_id=?,state_revision=state_revision+1,updated_at=? WHERE campaign_id=? AND actor_id=? AND session_id=?").run(route.to_location_id,b.at,c.campaignId,actorId,s);}db.prepare("INSERT INTO world_travel_destinations_v28 VALUES(?,?,?,?,?)").run(c.campaignId,s,b.commandId,route.connection_id,route.to_location_id);return result;}).immediate();}
  function reputation(p:string,s:string,raw:unknown):MutationReceipt {guard();return db.transaction(()=>{const b=begin(p,s,changeReputationCommandSchema.parse(raw),"change_reputation","",()=>requireGm(p,(raw as any).campaignId));if(b.replay)return JSON.parse(b.replay.canonical_result_json);const c=b.command;if(!db.prepare("SELECT 1 FROM campaign_actors WHERE campaign_id=? AND id=?").get(c.campaignId,c.actorId)||!db.prepare("SELECT 1 FROM campaign_factions_v28 WHERE campaign_id=? AND faction_id=?").get(c.campaignId,c.factionId))throw new WorldUnavailableError("reputation subject is unavailable");const entry=c.reputationLedgerEntryId??id(),result={reputationLedgerEntryId:entry,...receipt(b,c.idempotencyKey)};record(c,s,"change_reputation",c.actorId,b,result,"reputation_changed",{actorId:c.actorId,factionId:c.factionId,delta:c.delta});db.prepare("INSERT INTO campaign_reputation_ledger_v28 VALUES(?,?,?,?,?,?,?,?,?)").run(entry,c.campaignId,s,c.actorId,c.factionId,c.delta,c.reason,b.commandId,b.at);return result;}).immediate();}
  function createLocation(p:string,input:any){guard();const c=String(input.campaignId);requireGm(p,c);const locationId=input.locationId??id();db.prepare("INSERT INTO campaign_locations_v28(location_id,campaign_id,parent_location_id,public_name,public_description,visibility,created_at) VALUES(?,?,?,?,?,?,?)").run(locationId,c,input.parentLocationId??null,String(input.name).trim(),String(input.description??""),input.visibility==="hidden"?"gm":"public",now());return {locationId,campaignId:c};}
  function createLocationConnection(p:string,input:any){guard();const c=String(input.campaignId);requireGm(p,c);const locationConnectionId=input.locationConnectionId??id();db.prepare("INSERT INTO campaign_location_connections_v28(connection_id,campaign_id,from_location_id,to_location_id,visibility,route_state,requirement_kind,required_faction_id,minimum_reputation,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(locationConnectionId,c,input.fromLocationId,input.toLocationId,input.visibility==="hidden"?"gm":"public",input.routeState??"open",input.requirementKind??"none",input.requiredFactionId??null,input.minimumReputation??null,now());return {locationConnectionId,campaignId:c};}
  function createNpc(p:string,input:any){guard();const c=String(input.campaignId);requireGm(p,c);if(input.speechControl!==undefined&&input.speechControl!=="manual")throw new WorldUnavailableError("NPC AI speech is unavailable");const persona=db.prepare("SELECT fictional_confirmed,is_real_person FROM characters WHERE id=?").get(input.personaId) as any;if(!persona||persona.fictional_confirmed!==1||persona.is_real_person!==0)throw new WorldUnavailableError("NPC persona must be fictional and confirmed");if(db.prepare("SELECT 1 FROM campaign_actors a JOIN campaign_characters cc ON cc.id=a.campaign_character_id AND cc.campaign_id=a.campaign_id WHERE a.campaign_id=? AND cc.character_id=?").get(c,input.personaId))throw new WorldConflictError("a campaign character cannot be NPC-controlled");const npcId=input.npcId??id();db.prepare("INSERT INTO campaign_npcs_v28 VALUES(?,?,?,?,?,?)").run(npcId,c,input.personaId,"manual",String(input.name).trim(),now());return {npcId,campaignId:c};}
  function projection(p:string,c:string,s:string):WorldProjection|null {guard();if(!member(db,p,c)||!db.prepare("SELECT 1 FROM campaign_sessions WHERE campaign_id=? AND session_id=?").get(c,s))return null;const isGm=gm(db,p,c),revision=(db.prepare("SELECT revision FROM world_mutation_revisions_v28 WHERE campaign_id=? AND session_id=?").get(c,s) as any)?.revision??0;const locations=db.prepare("SELECT * FROM campaign_locations_v28 WHERE campaign_id=?").all(c) as any[];const connections=db.prepare("SELECT * FROM campaign_location_connections_v28 WHERE campaign_id=?").all(c) as any[];const actors=db.prepare("SELECT * FROM campaign_actor_locations_v28 WHERE campaign_id=? AND session_id=?"+(isGm?"":" AND actor_id IN (SELECT actor_id FROM campaign_actor_private_state WHERE campaign_id=? AND controller_principal_id=?)")).all(...(isGm?[c,s]:[c,s,c,p])) as any[];const actorLocations=actors.map(x=>({campaignId:c,sessionId:s,actorId:x.actor_id,locationId:x.location_id,revision:x.state_revision,updatedAt:x.updated_at}));if(isGm)return worldProjectionSchema.parse({audience:"gm",campaignId:c,revision,locations:locations.map(x=>({campaignId:c,locationId:x.location_id,parentLocationId:x.parent_location_id,name:x.public_name,description:x.public_description,visibility:x.visibility==="public"?"visible":"hidden",createdAt:x.created_at,updatedAt:x.created_at})),connections:connections.map(x=>({campaignId:c,locationConnectionId:x.connection_id,fromLocationId:x.from_location_id,toLocationId:x.to_location_id,visibility:x.visibility==="public"?"visible":"hidden",createdAt:x.created_at})),discoveries:[],actorLocations,npcPersonaLinks:[],privateNpcStates:[],factions:[],memberships:[],factionRelations:[],relationships:[],reputationLedger:[]});const discoveries=db.prepare("SELECT d.* FROM campaign_location_discoveries_v28 d JOIN campaign_actor_private_state a ON a.campaign_id=d.campaign_id AND a.actor_id=d.actor_id WHERE d.campaign_id=? AND a.controller_principal_id=?").all(c,p) as any[];const known=new Set(discoveries.map(x=>x.location_id));return worldProjectionSchema.parse({audience:"player",campaignId:c,revision,discoveries:discoveries.map(x=>({locationDiscoveryId:`discovery:${x.actor_id}:${x.location_id}`,campaignId:c,principalId:p,locationId:x.location_id,discoveredAt:x.discovered_at})),locations:locations.filter(x=>x.visibility==="public"&&known.has(x.location_id)).map(x=>({locationId:x.location_id,parentLocationId:x.parent_location_id,name:x.public_name,description:x.public_description})),connections:connections.filter(x=>x.visibility==="public"&&known.has(x.from_location_id)&&known.has(x.to_location_id)).map(x=>({locationConnectionId:x.connection_id,fromLocationId:x.from_location_id,toLocationId:x.to_location_id})),npcs:[],actorLocations,factions:[],relationships:[]});}
  function execute(p:string,s:string,c:unknown){const parsed=worldCommandSchema.parse(c);switch(parsed.type){case "travel":return travel(p,s,parsed);case "set_actor_location":return setActorLocation(p,s,parsed);case "discover_location":return discoverCommand(p,s,parsed);case "change_reputation":return reputation(p,s,parsed);}}
  return {executeWorldCommand:execute,travel,setActorLocation,getWorldProjection:projection,createLocation,createLocationConnection,createNpc,changeReputation:reputation};
}
