export {
  apiProblemIssueSchema,
  apiProblemSchema,
  requestIdSchema,
} from "./api-problem.js";
export type { ApiProblem, ApiProblemIssue } from "./api-problem.js";

export {
  roleplayFeatureFlagsSchema,
  rpgFeatureFlagsSchema,
} from "./feature-flags.js";
export type { RoleplayFeatureFlags, RpgFeatureFlags } from "./feature-flags.js";

export {
  campaignMemberRoleSchema,
  campaignRoleSchema,
  resourceIdSchema,
  utcIsoTimestampSchema,
} from "./domain-primitives.js";
export type { CampaignMemberRole, CampaignRole, ResourceId, UtcIsoTimestamp } from "./domain-primitives.js";

export * from "./campaign-administration.js";
export * from "./character-builder.js";
export * from "./character-progression.js";
export * from "./mechanics-starter.js";
export * from "./character-builder-http.js";
export * from "./character-progression-http.js";
export * from "./character-sheet-http.js";
export * from "./campaign-administration-http.js";
export * from "./campaign-history-http.js";
export * from "./campaign-transfer-http.js";
export * from "./actor-resources.js";
export * from "./inventory.js";
export * from "./economy.js";
export * from "./rest.js";
export * from "./checks.js";
export * from "./powers.js";
export * from "./effects.js";
export * from "./encounters.js";
export * from "./world.js";
export * from "./quest.js";
export * from "./quest-http.js";

export {
  addCampaignMembershipInputSchema,
  attachCampaignSessionInputSchema,
  campaignAccessSchema,
  campaignCreateRequestSchema,
  campaignCreateResponseSchema,
  campaignDetailContentSchema,
  campaignDetailResponseSchema,
  campaignDetailSchema,
  campaignListResponseSchema,
  campaignMechanicsStarterSetupRequestSchema,
  campaignMechanicsStarterSetupResponseSchema,
  campaignNameSchema,
  campaignMembershipReadSchema,
  campaignMembershipSchema,
  campaignRenameRequestSchema,
  campaignRenameResponseSchema,
  campaignRenameResultSchema,
  campaignStarterSetupRequestSchema,
  campaignStarterSetupResponseSchema,
  campaignSchema,
  campaignSessionAttachmentSchema,
  campaignRoomSummarySchema,
  attachedCampaignRoomSummarySchema,
  campaignRoomLinkingResponseSchema,
  campaignRoomAttachRequestSchema,
  campaignRoomAttachResponseSchema,
  MAX_CAMPAIGN_ROOM_PARTICIPANTS,
  MAX_CAMPAIGN_ROOM_SUMMARIES,
  campaignTimelineSchema,
  createCampaignInputSchema,
  detachCampaignSessionInputSchema,
  renameCampaignInputSchema,
  ORIGINAL_STARTER_ID,
  ORIGINAL_STARTER_BACKGROUND,
  ORIGINAL_STARTER_CLASS,
  ORIGINAL_STARTER_PACK,
  ORIGINAL_STARTER_PACK_ID,
  ORIGINAL_STARTER_PACK_VERSION,
  ORIGINAL_STARTER_PRESENTATION,
  ORIGINAL_STARTER_RACE,
  ORIGINAL_STARTER_RULES_PROFILE,
  originalStarterPresentationSchema,
} from "./campaigns.js";
export type {
  AddCampaignMembershipInput,
  AttachCampaignSessionInput,
  Campaign,
  CampaignAccess,
  CampaignCreateRequest,
  CampaignCreateResponse,
  CampaignDetail,
  CampaignDetailContent,
  CampaignDetailResponse,
  CampaignListResponse,
  CampaignMechanicsStarterSetupRequest,
  CampaignMechanicsStarterSetupResponse,
  CampaignMembership,
  CampaignMembershipRead,
  CampaignRenameRequest,
  CampaignRenameResponse,
  CampaignRenameResult,
  CampaignStarterSetupRequest,
  CampaignStarterSetupResponse,
  CampaignSessionAttachment,
  CampaignRoomSummary,
  AttachedCampaignRoomSummary,
  CampaignRoomLinkingResponse,
  CampaignRoomAttachRequest,
  CampaignRoomAttachResponse,
  CampaignTimeline,
  CreateCampaignInput,
  DetachCampaignSessionInput,
  DeepReadonly,
  RenameCampaignInput,
  OriginalStarterPresentation,
} from "./campaigns.js";

export {
  abilityDefinitionReferenceSchema,
  abilityDefinitionSchema,
  backgroundDefinitionReferenceSchema,
  backgroundDefinitionSchema,
  classDefinitionReferenceSchema,
  classDefinitionSchema,
  campaignContentConfigurationSchema,
  campaignContentPackIdentifiersSchema,
  configureCampaignContentInputSchema,
  contentPackIdentifierSchema,
  contentPackIdSchema,
  contentPackSchema,
  contentPackVersionSchema,
  definitionKindSchema,
  definitionReferenceSchema,
  enemyDefinitionReferenceSchema,
  enemyDefinitionSchema,
  installContentPackInputSchema,
  MAX_CAMPAIGN_CONTENT_PACKS,
  MAX_DEFINITIONS_PER_KIND,
  MAX_DEFINITIONS_PER_PACK,
  itemDefinitionReferenceSchema,
  itemDefinitionSchema,
  raceDefinitionReferenceSchema,
  raceDefinitionSchema,
  rpgContentDescriptionSchema,
  rpgContentNameSchema,
  rpgContentTagSchema,
  rpgContentTagsSchema,
  rpgDefinitionSchema,
  rulesProfileIdentifierSchema,
  rulesProfileIdSchema,
  rulesProfileMetadataSchema,
  rulesProfileSchema,
  spellDefinitionReferenceSchema,
  spellDefinitionSchema,
} from "./rpg-content.js";

// M1.2 validated immutable catalog contracts. The legacy rpg-content exports
// above intentionally remain unchanged for existing APIs and stored v10 packs.
export * from "./content-catalog.js";
export * from "./content-catalog-http.js";
export type {
  AbilityDefinition,
  AbilityDefinitionReference,
  BackgroundDefinition,
  BackgroundDefinitionReference,
  ClassDefinition,
  ClassDefinitionReference,
  CampaignContentConfiguration,
  ConfigureCampaignContentInput,
  ContentPack,
  ContentPackId,
  ContentPackIdentifier,
  ContentPackVersion,
  DefinitionKind,
  DefinitionReference,
  EnemyDefinition,
  EnemyDefinitionReference,
  InstallContentPackInput,
  ItemDefinition,
  ItemDefinitionReference,
  RaceDefinition,
  RaceDefinitionReference,
  RpgContentDescription,
  RpgContentName,
  RpgContentTag,
  RpgDefinition,
  RulesProfile,
  RulesProfileId,
  RulesProfileIdentifier,
  RulesProfileMetadata,
  SpellDefinition,
  SpellDefinitionReference,
} from "./rpg-content.js";

export {
  actorControlSchema,
  actorIdSchema,
  actorKindSchema,
  campaignCharacterAttributeSchema,
  campaignCharacterBasicStarterMetadataSchema,
  campaignCharacterClassSchema,
  campaignCharacterCreateRequestSchema,
  campaignCharacterCreateResponseSchema,
  campaignCharacterCreationOptionsResponseSchema,
  campaignCharacterIdSchema,
  campaignCharacterListResponseSchema,
  campaignCharacterPersonaSummarySchema,
  campaignCharacterProficiencySchema,
  campaignCharacterReadSchema,
  campaignCharacterSchema,
  campaignCharacterSheetSchema,
  campaignCharacterWorkspaceAttributeSchema,
  campaignCharacterWorkspaceAttributeLabelSchema,
  campaignCharacterWorkspaceChoiceSchema,
  campaignCharacterWorkspaceChoiceLabelSchema,
  campaignCharacterWorkspaceClassSchema,
  campaignCharacterWorkspaceDescriptionSchema,
  campaignCharacterWorkspaceNameSchema,
  campaignCharacterWorkspaceNamedDescriptionSchema,
  campaignCharacterWorkspaceProficiencySchema,
  campaignCharacterWorkspaceProficiencyLabelSchema,
  campaignCharacterWorkspaceResourceSchema,
  campaignCharacterWorkspaceResourceLabelSchema,
  campaignCharacterWorkspaceResponseSchema,
  campaignCharacterWorkspaceSchema,
  campaignIdSchema,
  campaignSheetIdSchema,
  createCampaignCharacterInputSchema,
  legacyVelvetCharacterIdSchema,
  MAX_CAMPAIGN_CHARACTER_PERSONAS,
  MAX_CAMPAIGN_CHARACTER_ROSTER,
  MAX_CAMPAIGN_CHARACTER_WORKSPACE_RESOURCES,
  MAX_CHARACTER_ATTRIBUTES,
  MAX_CHARACTER_CHOICES,
  MAX_CHARACTER_CLASSES,
  MAX_CHARACTER_LEVEL,
  MAX_CHARACTER_PROFICIENCIES,
  MAX_CHARACTER_RESOURCES,
  MAX_PRIVATE_NOTES_LENGTH,
  principalIdSchema,
  privilegedCampaignActorSchema,
  privilegedCampaignCharacterProjectionSchema,
  proficiencyCategorySchema,
  publicCampaignActorSchema,
  publicCampaignCharacterProjectionSchema,
  publicCampaignCharacterSummarySchema,
  resolvedCharacterChoiceSchema,
} from "./rpg-characters.js";
export type {
  ActorControl,
  ActorId,
  ActorKind,
  CampaignId,
  CampaignCharacter,
  CampaignCharacterAttribute,
  CampaignCharacterBasicStarterMetadata,
  CampaignCharacterClass,
  CampaignCharacterCreateRequest,
  CampaignCharacterCreateResponse,
  CampaignCharacterCreationOptionsResponse,
  CampaignCharacterId,
  CampaignCharacterListResponse,
  CampaignCharacterPersonaSummary,
  CampaignCharacterProficiency,
  CampaignCharacterRead,
  CampaignCharacterSheet,
  CampaignCharacterWorkspace,
  CampaignCharacterWorkspaceAttribute,
  CampaignCharacterWorkspaceAttributeLabel,
  CampaignCharacterWorkspaceChoice,
  CampaignCharacterWorkspaceChoiceLabel,
  CampaignCharacterWorkspaceClass,
  CampaignCharacterWorkspaceDescription,
  CampaignCharacterWorkspaceName,
  CampaignCharacterWorkspaceNamedDescription,
  CampaignCharacterWorkspaceProficiency,
  CampaignCharacterWorkspaceProficiencyLabel,
  CampaignCharacterWorkspaceResource,
  CampaignCharacterWorkspaceResourceLabel,
  CampaignCharacterWorkspaceResponse,
  CampaignSheetId,
  CreateCampaignCharacterInput,
  LegacyVelvetCharacterId,
  PrivilegedCampaignActor,
  PrivilegedCampaignCharacterProjection,
  PrincipalId,
  ProficiencyCategory,
  PublicCampaignActor,
  PublicCampaignCharacterProjection,
  PublicCampaignCharacterSummary,
  ResolvedCharacterChoice,
} from "./rpg-characters.js";

export {
  actorResourceAmountSchema,
  actorResourceNameSchema,
  actorResourceSchema,
  actorResourceStateSchema,
} from "./rpg-resources.js";
export type {
  ActorResource,
  ActorResourceAmount,
  ActorResourceName,
  ActorResourceState,
} from "./rpg-resources.js";

export {
  diceExpressionSchema,
  diceResultTermSchema,
  diceRollResultSchema,
  diceSelectionSchema,
  MAX_DICE_COUNT,
  MAX_DICE_MODIFIER,
  MAX_DICE_SIDES,
  normalizedDiceExpressionSchema,
} from "./rpg-dice.js";

export {
  campaignDiceHistoryResponseSchema,
  campaignDiceHistoryRollSchema,
  campaignDiceRollRequestSchema,
  campaignDiceRollResponseSchema,
  campaignDiceVisibleCharacterSchema,
  MAX_CAMPAIGN_DICE_HISTORY,
} from "./rpg-dice-http.js";
export type {
  CampaignDiceHistoryResponse,
  CampaignDiceHistoryRoll,
  CampaignDiceRollRequest,
  CampaignDiceRollResponse,
  CampaignDiceVisibleCharacter,
} from "./rpg-dice-http.js";
export type {
  DiceExpression,
  DiceResultTerm,
  DiceRollResult,
  DiceSelection,
  NormalizedDiceExpression,
} from "./rpg-dice.js";

export {
  actorDiceRolledEventDataSchema,
  actorDiceRolledEventSchema,
  actorAttributeSetEventDataSchema,
  actorAttributeSetEventSchema,
  actorResourceInitializedEventDataSchema,
  actorResourceInitializedEventSchema,
  commandEnvelopeSchema,
  commandIdSchema,
  commandReceiptSchema,
  eventIdSchema,
  expectedRevisionSchema,
  idempotencyKeySchema,
  initializeActorResourceCommandSchema,
  initializeActorResourcePayloadSchema,
  revisionSchema,
  rollActorDiceCommandSchema,
  rollActorDicePayloadSchema,
  rpgCommandSchema,
  rpgEventSchema,
  setActorAttributeCommandSchema,
  setActorAttributePayloadSchema,
} from "./rpg-commands.js";
export type {
  ActorDiceRolledEvent,
  ActorDiceRolledEventData,
  ActorAttributeSetEvent,
  ActorAttributeSetEventData,
  ActorResourceInitializedEvent,
  ActorResourceInitializedEventData,
  CommandEnvelope,
  CommandId,
  CommandReceipt,
  EventId,
  ExpectedRevision,
  IdempotencyKey,
  InitializeActorResourceCommand,
  InitializeActorResourcePayload,
  Revision,
  RollActorDiceCommand,
  RollActorDicePayload,
  RpgCommand,
  RpgEvent,
  SetActorAttributeCommand,
  SetActorAttributePayload,
} from "./rpg-commands.js";
