import { useState } from "react";

const topics = [
  { title: "Start here: your next move", tags: "beginner first play story map journal table tools send action", text: "Read the latest scene in Story. Choose your character beside What do you do?, then describe what they try. Send action submits your words once. New to the scene? Look around, Introduce myself, and Find a lead give you editable ideas. Character opens your sheet, Journal keeps the current situation close, and Map shows routes and local positioning. Table tools holds the Director, travel, combat, settings, and campaign views. Your draft stays with you." },
  { title: "Human DM or no human DM", tags: "director ai delegation opening continue takeover approval scene evidence binding preparation narrator", text: "Director shows who runs the table. An owner or GM can review and confirm AI delegation, or Take over while a director run is pending. Changing mode never calls the provider and cannot undo committed mechanics. In human mode, the GM privately approves or rejects the exact proposal. In AI mode, the server executes supported actions under explicit GM delegation. Open scene and Continue scene each request one bounded beat, with at most two configured-provider calls: planning and narration. Continue is always explicit; there is no background provider loop. The public DM chronicle stays beside player declarations. Opening never fabricates a player declaration. For autonomous scene resolution, the GM can open Prepare scene resolution in Director, choose a named scene and quest objective or room encounter, reload fresh story revision for review, and confirm the evidence binding. Only qualifying committed evidence linked to that scene counts; unrelated successes do not. Binding does not itself finish quests, end combat, resolve scenes, or reveal secrets, and calls no provider. A scene also needs separately authored publishable public content, not exposure of private GM notes. Refresh, mounting, and polling are reads only. Unknown outcomes stay locked: retain and explicitly recover the identical request and key after reload, never create a replacement paid beat. Refresh does not confirm an ambiguous binding write or generate missing preparation." },
  { title: "Your first declaration", tags: "chat conversation narration story agent", text: "Choose your character and describe what you try in What do you do? Send action submits once (Declare action in legacy Atlas). Suggested choices and character references only prepare your draft. Existing writing is protected by Append suggestion, Replace declaration, or Cancel. Your draft clears when the durable turn starts, not when you first press the button. Public DM scene narration and your actions share the story. Map and the story stay mounted while you use tools." },
  { title: "Local movement: preview, then confirm", tags: "maps tokens path grid exploration distance", text: "Choose Exploration grid or Combat grid. Select your character in the composer. Inspect a token, or select a visible reachable empty cell to request a server path and cost. Confirm move sends one revision-bound command; Cancel preview sends none. Dragging pans the map, not the token. Another token is an inspection target, not a transfer of control. The server owns visibility, terrain, reachability, and movement budgets." },
  { title: "World travel is not a local move", tags: "routes destinations geography world", text: "World routes describe directed connections between known locations; they are not to scale. A route's Prefill travel button only prepares an in-fiction declaration. For direct party travel, open Travel or Open World, choose an acting character, party, and an outgoing route, then Review and Confirm travel. The server checks actor control, party eligibility, and world revision. Travel refreshes the room's map context; local grid movement is a separate operation. If world services are disabled, the drawer explains that no direct command can be issued." },
  { title: "Reading and navigating the map", tags: "keyboard accessibility zoom pan fog legend", text: "Use the map's labeled zoom and reset controls. Arrow keys move its cell cursor, Enter selects, and plus/minus zoom when the map controls have focus. Use Accessible cells and tokens for a text equivalent and selectable cells. Unknown and remembered terrain are not permission to move. Token labels and the inspection message identify occupants and control; do not rely only on color. Refresh reads state without repeating movement or generation." },
  { title: "Dice at the table", tags: "roll d20 expression advantage disadvantage history", text: "Open Dice, enter a supported dice expression, review the roll options, and press Roll dice. Results and history come from the server. Access is determined by campaign dice capability, not a client-side GM switch. A table roll is not an attack, spell, resource spend, or adventure declaration. Use Combat for a mechanical action; do not apply a free roll to game state yourself." },
  { title: "Character, inventory, and powers", tags: "sheet equipment item stats hp spells resources gift consume drop shop trade attachments context", text: "Open Character or Add from character sheet beside your draft. Search or jump to a section, then select any entry: identity, ancestry, background, class, attribute, statistic, progression, skill, save, feature, resource, item, spell, effect, or calculation. You can attach up to 16 references, including unavailable spells you want to ask about. Each selection shows its value and an Added state; select it again to remove it. Back to draft returns to your words, which stay unchanged. Remove individual references or Clear references beside the composer. Send action sends your words and exact selectors together; the server resolves current sheet facts for the DM and preserves them in the transcript. Drafts and references are saved separately for each character and room in this tab until the original turn is durably acknowledged. Refresh sheet updates values and removes entries no longer available. For actual equipment, wallet, shop, rest, and trade commands, choose Inventory & equipment and use its review controls. Combat powers and consumables remain in Combat & rewards. Selecting context never spends, casts, rolls, or changes the character." },
  { title: "Advancement without leaving the table", tags: "level up progression xp milestone character", text: "Open Character, then Advancement. Explicitly choose a campaign roster character: public responses do not expose its play-actor binding, so the UI does not match by name or assume IDs are interchangeable. Review server-calculated crossed levels, make required choices, calculate an exact preview, and Apply reviewed levels once. The server enforces control and eligibility. Applying or uncertain advancement locks other room commands. Authoritative progression and sheet refresh use the existing wizard recovery; changing drawers does not replay advancement." },
  { title: "NPCs, quests, and the field journal", tags: "cast objectives location party published lore", text: "Journal opens the Field journal with server-visible location, present cast, objectives, selected-character resources, encounters, and published material when available. Present cast means present in this session; NPCs are not necessarily at your character's location. GMs can place, move, or remove present NPCs using the contextual controls. Players cannot gain GM access by inspecting a token. Quest progress here is a projection, not an editable counter; quest authoring and reward editing are not embedded. A stopped room shows cast history rather than pretending it is still live." },
  { title: "Combat and legal actions", tags: "attack initiative end turn enemy consumables spells targets complete encounter", text: "While combat is active, the bar above the story shows the round and whose turn it is. End turn prepares a declaration; Open combat leads to Combat & rewards. Inspect an authorized encounter, choose a server-offered action and allowed target, review, then confirm. Players act only on their controlled character's turn. GMs can explicitly resolve the current enemy turn; the server selects its action and outcome. Combat never ends by itself when the last enemy falls: Review encounter completion opens the combat tool for the GM to confirm and settle rewards. Use Map then Combat grid for local movement. Changing or closing tools never ends a turn." },
  { title: "GM session operations and map preparation", tags: "start end encounter generation seed spawns", text: "GM tools can start an already prepared encounter, review its completion, and rest controlled characters. Each operation is reviewed against fresh state. Creating new encounter rosters is not embedded here. A missing map may expose GM generation controls: review exact seed, layout, and spawns before authorizing creation or replacement. Replacement is destructive to existing placements; a missing actor projection does not prove that no map exists." },
  { title: "Rest and recovery", tags: "camp short long heal health resources", text: "GMs can review short or long rest for controlled characters in GM tools. A controlled actor's Inventory & equipment panel also exposes Review rest when resource state is available. Confirm the exact rest intent; the server decides eligibility and what recovers, and can reject rest during combat. This does not automatically rest the entire party, advance time, create a camp, or generate narration. Describing a rest in prose is not evidence of committed recovery." },
  { title: "Rewards and receipts", tags: "loot claims wallet history completion", text: "Completing an encounter makes reward bundles available; it does not claim them. In Combat & rewards, load the completed encounter and explicitly claim an eligible bundle for the selected character. Claims and wallet updates require server confirmation. Turn receipts remain available below the conversation. Retry narration or Swipe narration requests another narration variant, not another execution of the original mechanics." },
  { title: "Permissions and unavailable controls", tags: "observer spectator player gm owner locked read only", text: "Your role and controlled actors come from the server. Observers can read authorized projections but cannot declare, move, or manage NPCs. A tactical viewpoint may be unavailable without an authorized actor. Inactive rooms, missing actor bindings, stale revisions, session reviews, and unresolved operations lock commands. Use the displayed reason and authoritative refresh; changing a drawer or actor must never bypass a lock." },
  { title: "Interrupted or uncertain operations", tags: "reconcile reload connection stream retry ambiguous idempotency", text: "If delivery stops, use Reconcile submitted declaration or Reconcile known turn. These read the exact durable identity rather than replaying your words. Stop receiving live updates stops delivery, not the server turn. Travel, character, and combat tools retain their command locks when you close a drawer. Character inventory commands with an uncertain outcome remain locked after generic reads; a confirmed receipt can be cleared after all lanes refresh. Travel and combat use their existing authoritative recovery controls. GM start/rest recovery may resend only the saved identical idempotent request. Never clear recovery storage to force a new attempt." },
  { title: "What the adventure agents can and cannot do", tags: "ai orchestration tools approvals automation limits dm", text: "Live status, tool proposals, approvals, narration, and receipts expose the adventure pipeline. Proposals are not committed mechanics. Approve only the listed proposals you intend; the server validates every command. Agents do not bypass role limits, invent legal targets, guarantee a rule outcome, or operate every drawer for you. Combat, table dice, map generation, rest, and reward claims have explicit controls. There is no client-side autonomous GM or hidden background orchestration switch." },
  { title: "Keyboard, drawers, and small screens", tags: "help shortcuts mobile accessibility focus", text: "Press ? outside text fields to open help. Use Left/Right, Home, or End on the Story/Map tabs. F6 cycles the visible story or map, action area, and desktop companion; Shift+F6 reverses. Modal drawers keep Tab and Shift+Tab inside the visible overlay. Escape or Close returns focus to the opening control; menu-launched tools return to Table tools. Back to draft returns to the composer. Sheet entries work with Enter or Space and announce their selected state and values. Search narrows all sections, and Jump to section focuses its heading. The legacy Atlas dock is non-modal. On phones, the composer follows a scrollable story in normal page flow so it can remain reachable with a small viewport or software keyboard. The sheet has its own scroll area with a persistent return control. Table tools → Display offers light, dark, and high-contrast themes. Reduced-motion and forced-color preferences are respected. Map, draft, and conversation remain mounted when switching tools." },
];

export function PlayHelp() {
  const [query, setQuery] = useState("");
  const words = query.toLocaleLowerCase().trim().split(/\s+/).filter(Boolean);
  const matches = topics.filter((topic) => words.every((word) => `${topic.title} ${topic.tags} ${topic.text}`.toLocaleLowerCase().includes(word)));
  return <section className="atlas-help" aria-label="Player's field guide">
    <p className="atlas-help-intro">A field guide for the moments between knowing where you are and deciding what comes next.</p>
    <label className="atlas-help-search">Search the field guide<input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try movement, rest, recovery..." /></label>
    <p role="status">{matches.length} {matches.length === 1 ? "topic" : "topics"}</p>
    {matches.length === 0 && <p>No matching topics. Try a shorter phrase or a gameplay term.</p>}
    {matches.map((topic) => <article key={topic.title}><h3>{topic.title}</h3><p>{topic.text}</p></article>)}
  </section>;
}
