import type { StarterReferences } from "../references.js";

type ActionCost = "action" | "bonus-action" | "reaction";

export function magicRodsStaffsWands(refs: StarterReferences): object[] {
  const { ref, currency } = refs;

  const attuned = { prerequisite: "short-rest" };
  const dawn = (maximum: number) => ({ maximum, recharge: { kind: "event", event: "dawn", amount: 1 } });
  const wandCharges = (maximum: number) => ({ maximum, recharge: { kind: "roll", dieSides: 20, minimum: 20, amount: maximum } });

  const granted = (key: string, slug: string, cost: number, actionCost: ActionCost = "action", requireAttunement = true) => ({
    key, power: ref("spell", `srd-5.1:spell:${slug}`), requireAttunement, actionCost, cost,
  });

  const focus = (id: string, name: string, description: string, kind: "rod" | "staff" | "wand", amount: number, magic: object) => ({
    reference: ref("item", `srd-5.1:item:${id}`), name, description, tags: ["srd-5.1", "magic-item", kind],
    mechanics: { category: "gear", stackable: false, slot: "focus", price: { currency, amount }, effects: [], magic },
  });

  return [
    focus("immovable-rod", "Immovable Rod", "An iron rod with a button that magically fixes it in place, holding up to 8,000 pounds of weight.", "rod", 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    focus("rod-of-absorption", "Rod of Absorption", "A rod that absorbs spells cast at its wielder, storing the energy until it is released.", "rod", 5000, { attunement: attuned, charges: { maximum: 50, recharge: { kind: "none" } }, passiveModifiers: [], grantedPowers: [] }),
    focus("rod-of-alertness", "Rod of Alertness", "A rod that sharpens the senses and can radiate a protective aura of watchfulness.", "rod", 5000, { attunement: attuned, charges: dawn(10), passiveModifiers: [{ modifier: { kind: "advantage", target: { kind: "saving-throw", ability: "wisdom" } }, requireAttunement: true }], grantedPowers: [granted("rod-alertness-detect-evil-and-good", "detect-evil-and-good", 1), granted("rod-alertness-detect-magic", "detect-magic", 1), granted("rod-alertness-detect-poison-and-disease", "detect-poison-and-disease", 1), granted("rod-alertness-see-invisibility", "see-invisibility", 1)] }),
    focus("rod-of-lordly-might", "Rod of Lordly Might", "A legendary rod that shifts between weapon forms and can paralyze, frighten, or drain the life from foes.", "rod", 50000, { attunement: attuned, charges: null, passiveModifiers: [{ modifier: { kind: "flat", amount: 3, target: { kind: "attack-roll" } }, requireAttunement: true }, { modifier: { kind: "flat", amount: 3, target: { kind: "damage-roll" } }, requireAttunement: true }], grantedPowers: [granted("rod-lordly-might-fear", "fear", 0)] }),
    focus("rod-of-rulership", "Rod of Rulership", "A rod that lets its bearer command the obedience of onlookers who fail to resist.", "rod", 5000, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    focus("rod-of-security", "Rod of Security", "A rod that opens a peaceful demiplane refuge for its bearer and companions.", "rod", 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    focus("staff-of-charming", "Staff of Charming", "A staff that charms, commands, and translates for its wielder, turning enchantments back on their caster.", "staff", 5000, { attunement: attuned, charges: dawn(10), passiveModifiers: [], grantedPowers: [granted("staff-charming-charm-person", "charm-person", 1), granted("staff-charming-command", "command", 1), granted("staff-charming-comprehend-languages", "comprehend-languages", 1)] }),
    focus("staff-of-fire", "Staff of Fire", "A staff wreathed in flame that grants resistance to fire and unleashes fiery evocations.", "staff", 50000, { attunement: attuned, charges: dawn(10), passiveModifiers: [{ modifier: { kind: "resistance", damageType: "fire" }, requireAttunement: true }], grantedPowers: [granted("staff-fire-burning-hands", "burning-hands", 1), granted("staff-fire-fireball", "fireball", 3), granted("staff-fire-wall-of-fire", "wall-of-fire", 4)] }),
    focus("staff-of-frost", "Staff of Frost", "A staff of clinging cold that grants resistance to cold and conjures freezing magic.", "staff", 50000, { attunement: attuned, charges: dawn(10), passiveModifiers: [{ modifier: { kind: "resistance", damageType: "cold" }, requireAttunement: true }], grantedPowers: [granted("staff-frost-fog-cloud", "fog-cloud", 1), granted("staff-frost-ice-storm", "ice-storm", 4), granted("staff-frost-wall-of-ice", "wall-of-ice", 4)] }),
    focus("staff-of-healing", "Staff of Healing", "A staff of restorative power that mends wounds and lifts afflictions from the wielder's allies.", "staff", 5000, { attunement: attuned, charges: dawn(10), passiveModifiers: [], grantedPowers: [granted("staff-healing-cure-wounds", "cure-wounds", 1), granted("staff-healing-lesser-restoration", "lesser-restoration", 2)] }),
    focus("staff-of-swarming-insects", "Staff of Swarming Insects", "A staff that summons biting swarms and transforms creatures into giant insects.", "staff", 5000, { attunement: attuned, charges: dawn(10), passiveModifiers: [], grantedPowers: [granted("staff-swarming-insects-giant-insect", "giant-insect", 4)] }),
    focus("staff-of-the-magi", "Staff of the Magi", "An immensely powerful staff that stores and unleashes a broad repertoire of arcane spells.", "staff", 50000, { attunement: attuned, charges: dawn(50), passiveModifiers: [], grantedPowers: [granted("staff-magi-arcane-lock", "arcane-lock", 2), granted("staff-magi-detect-magic", "detect-magic", 1), granted("staff-magi-enlarge-reduce", "enlarge-reduce", 2), granted("staff-magi-fireball", "fireball", 3), granted("staff-magi-ice-storm", "ice-storm", 4), granted("staff-magi-invisibility", "invisibility", 2), granted("staff-magi-lightning-bolt", "lightning-bolt", 3), granted("staff-magi-web", "web", 2)] }),
    focus("staff-of-the-python", "Staff of the Python", "A staff that can transform into a giant constrictor snake under its wielder's command.", "staff", 5000, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    focus("staff-of-the-woodlands", "Staff of the Woodlands", "A living staff of the druids that channels nature magic and can take root as a tree.", "staff", 50000, { attunement: attuned, charges: dawn(10), passiveModifiers: [], grantedPowers: [granted("staff-woodlands-animal-friendship", "animal-friendship", 1), granted("staff-woodlands-barkskin", "barkskin", 2), granted("staff-woodlands-locate-animals-or-plants", "locate-animals-or-plants", 2), granted("staff-woodlands-pass-without-trace", "pass-without-trace", 2), granted("staff-woodlands-speak-with-animals", "speak-with-animals", 1), granted("staff-woodlands-speak-with-plants", "speak-with-plants", 3)] }),
    focus("staff-of-thunder-and-lightning", "Staff of Thunder and Lightning", "A staff that crackles with thunder and lightning, striking foes with both when its power is evoked.", "staff", 50000, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    focus("staff-of-withering", "Staff of Withering", "A staff of necrotic power that withers the flesh of those it strikes.", "staff", 5000, { attunement: attuned, charges: dawn(3), passiveModifiers: [], grantedPowers: [] }),
    focus("wand-of-binding", "Wand of Binding", "A wand that pins foes in place and helps its wielder slip free of restraints.", "wand", 5000, { attunement: attuned, charges: wandCharges(7), passiveModifiers: [], grantedPowers: [granted("wand-binding-hold-person", "hold-person", 2)] }),
    focus("wand-of-enemy-detection", "Wand of Enemy Detection", "A wand that pulses to reveal hostile creatures lurking nearby.", "wand", 5000, { attunement: attuned, charges: wandCharges(7), passiveModifiers: [], grantedPowers: [] }),
    focus("wand-of-fear", "Wand of Fear", "A wand that commands or terrifies those who oppose its wielder.", "wand", 5000, { attunement: attuned, charges: wandCharges(7), passiveModifiers: [], grantedPowers: [granted("wand-fear-command", "command", 1), granted("wand-fear-fear", "fear", 3)] }),
    focus("wand-of-fireballs", "Wand of Fireballs", "A wand that hurls blasts of searing flame at the wielder's enemies.", "wand", 5000, { attunement: attuned, charges: wandCharges(7), passiveModifiers: [], grantedPowers: [granted("wand-fireballs-fireball", "fireball", 3)] }),
    focus("wand-of-lightning-bolts", "Wand of Lightning Bolts", "A wand that discharges crackling bolts of lightning.", "wand", 5000, { attunement: attuned, charges: wandCharges(7), passiveModifiers: [], grantedPowers: [granted("wand-lightning-bolts-lightning-bolt", "lightning-bolt", 3)] }),
    focus("wand-of-magic-detection", "Wand of Magic Detection", "A wand that reveals magical auras in the vicinity when its charge is spent.", "wand", 500, { attunement: null, charges: wandCharges(3), passiveModifiers: [], grantedPowers: [granted("wand-magic-detection-detect-magic", "detect-magic", 1, "action", false)] }),
    focus("wand-of-magic-missiles", "Wand of Magic Missiles", "A wand that fires unerring darts of force and can be recharged by a fortunate roll.", "wand", 500, { attunement: null, charges: wandCharges(7), passiveModifiers: [], grantedPowers: [granted("wand-magic-missile", "magic-missile", 1, "action", false)] }),
    focus("wand-of-paralysis", "Wand of Paralysis", "A wand that freezes a target in place with a crackling beam.", "wand", 5000, { attunement: attuned, charges: wandCharges(7), passiveModifiers: [], grantedPowers: [] }),
    focus("wand-of-secrets", "Wand of Secrets", "A wand that points the way to hidden doors and traps.", "wand", 500, { attunement: null, charges: wandCharges(3), passiveModifiers: [], grantedPowers: [] }),
    focus("wand-of-the-war-mage-1", "Wand of the War Mage, +1", "A spellcaster's wand that sharpens spell attacks and ignores partial cover.", "wand", 500, { attunement: attuned, charges: null, passiveModifiers: [{ modifier: { kind: "flat", amount: 1, target: { kind: "attack-roll" } }, requireAttunement: true }], grantedPowers: [] }),
    focus("wand-of-the-war-mage-2", "Wand of the War Mage, +2", "A spellcaster's wand that sharpens spell attacks and ignores partial cover.", "wand", 5000, { attunement: attuned, charges: null, passiveModifiers: [{ modifier: { kind: "flat", amount: 2, target: { kind: "attack-roll" } }, requireAttunement: true }], grantedPowers: [] }),
    focus("wand-of-the-war-mage-3", "Wand of the War Mage, +3", "A spellcaster's wand that sharpens spell attacks and ignores partial cover.", "wand", 50000, { attunement: attuned, charges: null, passiveModifiers: [{ modifier: { kind: "flat", amount: 3, target: { kind: "attack-roll" } }, requireAttunement: true }], grantedPowers: [] }),
    focus("wand-of-web", "Wand of Web", "A wand that fills an area with thick, sticky webbing.", "wand", 500, { attunement: attuned, charges: wandCharges(7), passiveModifiers: [], grantedPowers: [granted("wand-web-web", "web", 2)] }),
    focus("wand-of-wonder", "Wand of Wonder", "A chaotic wand whose effects are determined by a roll of the dice.", "wand", 5000, { attunement: attuned, charges: wandCharges(7), passiveModifiers: [], grantedPowers: [] }),
  ];
}
