import type { MagicItemProperties } from "@velvet/contracts";
import type { StarterReferences } from "../references.js";

type WondrousSlot = "hand" | "body" | "focus" | "accessory" | null;

export function magicWondrousNZ(refs: StarterReferences) {
  const { ref, currency } = refs;
  const spellRef = (slug: string) => ({ ...ref("spell", `srd-5.1:spell:${slug}`), kind: "spell" as const });
  const magic = (slug: string, name: string, description: string, slot: WondrousSlot, amount: number,
    attunement: MagicItemProperties["attunement"], charges: MagicItemProperties["charges"],
    passiveModifiers: MagicItemProperties["passiveModifiers"], grantedPowers: MagicItemProperties["grantedPowers"]) => ({
    reference: ref("item", `srd-5.1:item:${slug}`), name, description, tags: ["srd-5.1", "magic-item", "wondrous"],
    mechanics: { category: "gear", stackable: false, slot, price: { currency, amount }, effects: [],
      magic: { attunement, charges, passiveModifiers, grantedPowers } satisfies MagicItemProperties },
  });
  const attuned = { prerequisite: "short-rest" } as const;
  const dawn = (amount: number) => ({ kind: "event", event: "dawn", amount } as const);
  const noRecharge = { kind: "none" } as const;
  const power = (key: string, slug: string, requireAttunement: boolean, actionCost: "action" | "bonus-action" | "reaction", cost: number) =>
    ({ key, power: spellRef(slug), requireAttunement, actionCost, cost });
  return [
    magic("necklace-of-adaptation", "Necklace of Adaptation", "While worn, you can breathe normally in any environment and have advantage on saving throws against harmful gases and vapors.", "accessory", 500, attuned, null, [], []),
    magic("necklace-of-fireballs", "Necklace of Fireballs", "This necklace holds 1d6 + 3 beads. Detaching and throwing a bead up to 60 feet away makes it detonate as a 3rd-level fireball (save DC 15); additional beads raise the spell's level.", "accessory", 5000, null, null, [], [power("necklace-fireball", "fireball", false, "action", 0)]),
    magic("necklace-of-prayer-beads", "Necklace of Prayer Beads", "A rare necklace bearing 1d4 + 2 magic beads. Each bead lets you cast its spell as a bonus action; a spent magic bead recovers at the next dawn.", "accessory", 5000, attuned, null, [], [power("bead-bless", "bless", true, "bonus-action", 0), power("bead-cure-wounds", "cure-wounds", true, "bonus-action", 0), power("bead-branding-smite", "branding-smite", true, "bonus-action", 0), power("bead-planar-ally", "planar-ally", true, "bonus-action", 0), power("bead-wind-walk", "wind-walk", true, "bonus-action", 0)]),
    magic("orb-of-dragonkind", "Orb of Dragonkind", "An artifact orb controlled with a DC 15 Charisma check that calls evil dragons and casts cure wounds, daylight, death ward, and detect magic from its charges.", "hand", 0, attuned, { maximum: 7, recharge: dawn(4) }, [], [power("orb-cure-wounds", "cure-wounds", true, "action", 3), power("orb-daylight", "daylight", true, "action", 1), power("orb-death-ward", "death-ward", true, "action", 2), power("orb-detect-magic", "detect-magic", true, "action", 0)]),
    magic("pearl-of-power", "Pearl of Power", "While this pearl is on your person, you can speak its command word to regain one expended spell slot (a slot of 4th level or higher returns as 3rd level). Usable once per dawn.", "accessory", 500, attuned, { maximum: 1, recharge: dawn(1) }, [], []),
    magic("periapt-of-health", "Periapt of Health", "You are immune to contracting any disease while you wear this pendant, and any disease you already have is suppressed while you wear it.", "accessory", 500, null, null, [], []),
    magic("periapt-of-proof-against-poison", "Periapt of Proof against Poison", "While you wear this pendant, poisons have no effect on you; you are immune to the poisoned condition and to poison damage.", "accessory", 5000, null, null, [{ modifier: { kind: "immunity", damageType: "poison" }, requireAttunement: false }], []),
    magic("periapt-of-wound-closure", "Periapt of Wound Closure", "While you wear this pendant, you stabilize whenever you are dying at the start of your turn, and each Hit Die you roll to regain hit points restores double the amount.", "accessory", 500, attuned, null, [], []),
    magic("pipes-of-haunting", "Pipes of Haunting", "These pipes have 3 charges. Playing them expends a charge and forces creatures within 30 feet to make a DC 15 Wisdom save or be frightened for 1 minute. They regain 1d3 charges daily at dawn.", "hand", 500, null, { maximum: 3, recharge: dawn(3) }, [], []),
    magic("pipes-of-the-sewers", "Pipes of the Sewers", "These pipes have 3 charges. While attuned, ordinary and giant rats are indifferent to you, and you can summon one swarm of rats per expended charge. They regain 1d3 charges daily at dawn.", "hand", 500, attuned, { maximum: 3, recharge: dawn(3) }, [], []),
    magic("portable-hole", "Portable Hole", "This fine black cloth unfolds into a circular sheet 6 feet in diameter that creates a 10-foot-deep extradimensional hole in a solid surface.", null, 5000, null, null, [], []),
    magic("restorative-ointment", "Restorative Ointment", "This jar holds 1d4 + 1 doses. Applying or swallowing a dose restores 2d8 + 2 hit points and ends poison and disease.", null, 500, null, null, [], []),
    magic("robe-of-eyes", "Robe of Eyes", "This robe lets you see in all directions with advantage on sight-based Wisdom (Perception) checks, grants darkvision out to 120 feet, and lets you see invisible creatures and into the Ethereal Plane.", "body", 5000, attuned, null, [], []),
    magic("robe-of-scintillating-colors", "Robe of Scintillating Colors", "This robe has 3 charges. Expending a charge displays shifting colors that shed light, impose disadvantage on attacks against you, and can stun onlookers on a failed DC 15 Wisdom save. It regains 1d3 charges daily at dawn.", "body", 50000, attuned, { maximum: 3, recharge: dawn(3) }, [], []),
    magic("robe-of-stars", "Robe of Stars", "You gain a +1 bonus to saving throws. Six large stars let you cast magic missile as a 5th-level spell, and 1d6 removed stars reappear at dusk; you can also enter the Astral Plane.", "body", 50000, attuned, null, [], [power("robe-star-magic-missile", "magic-missile", true, "action", 0)]),
    magic("robe-of-useful-items", "Robe of Useful Items", "This robe is covered in patches that become useful objects when detached, including daggers, lanterns, rope, a 10-foot pole, a sack, and other GM-chosen items.", "body", 500, null, null, [], []),
    magic("robe-of-the-archmagi", "Robe of the Archmagi", "While you wear this robe, your base AC is 15 + your Dexterity modifier if you are not wearing armor, you have advantage on saving throws against spells, and your spell save DC and spell attack bonus increase by 2.", "body", 500000, attuned, null, [], []),
    magic("rope-of-climbing", "Rope of Climbing", "This 60-foot silk rope animates on command, moving its free end 10 feet per turn, and can knot, unknot, fasten, or unfasten itself.", "hand", 500, null, null, [], []),
    magic("rope-of-entanglement", "Rope of Entanglement", "This 30-foot rope darts forward on command to entangle a creature you can see within 20 feet, which must succeed on a DC 15 Dexterity save or be restrained.", "hand", 5000, null, null, [], []),
    magic("scarab-of-protection", "Scarab of Protection", "This beetle-shaped medallion grants advantage on saving throws against spells and has 12 charges that turn a failed save against a necromancy spell or an undead effect into a success.", "accessory", 500000, attuned, { maximum: 12, recharge: noRecharge }, [], []),
    magic("slippers-of-spider-climbing", "Slippers of Spider Climbing", "While you wear these light shoes, you can move up, down, and across vertical surfaces and along ceilings with your hands free, with a climbing speed equal to your walking speed.", "accessory", 500, attuned, null, [], []),
    magic("sovereign-glue", "Sovereign Glue", "This milky-white substance forms a permanent adhesive bond between any two objects. The bond can be broken only by universal solvent, oil of etherealness, or a wish spell.", null, 500000, null, null, [], []),
    magic("sphere-of-annihilation", "Sphere of Annihilation", "This 2-foot-diameter black sphere obliterates all matter it passes through. A creature within 60 feet can use an action to make a DC 25 Intelligence (Arcana) check to control it.", null, 500000, null, null, [], []),
    magic("stone-of-controlling-earth-elementals", "Stone of Controlling Earth Elementals", "If this stone touches the ground, you can use an action to summon an earth elemental, as if you had cast the conjure elemental spell. It can be used again after the next dawn.", null, 5000, null, null, [], []),
    magic("stone-of-good-luck", "Stone of Good Luck (Luckstone)", "While this polished agate is on your person, you gain a +1 bonus to ability checks and saving throws.", "accessory", 500, attuned, null, [], []),
    magic("talisman-of-pure-good", "Talisman of Pure Good", "This legendary talisman has 7 charges. A good cleric or paladin can use it as a holy symbol and gains a +2 bonus to spell attack rolls; expending a charge can destroy an evil creature.", "accessory", 500000, attuned, { maximum: 7, recharge: noRecharge }, [], []),
    magic("talisman-of-ultimate-evil", "Talisman of Ultimate Evil", "This legendary talisman has 6 charges. An evil cleric or paladin can use it as a holy symbol and gains a +2 bonus to spell attack rolls; expending a charge can destroy a good creature.", "accessory", 500000, attuned, { maximum: 6, recharge: noRecharge }, [], []),
    magic("talisman-of-the-sphere", "Talisman of the Sphere", "Holding this talisman doubles your proficiency bonus on Intelligence (Arcana) checks made to control a sphere of annihilation and improves your control over it.", "accessory", 500000, attuned, null, [], []),
    magic("tome-of-clear-thought", "Tome of Clear Thought", "Studying this book for 48 hours over a period of 6 days or fewer increases your Intelligence score and maximum by 2. It then loses its magic for a century.", null, 50000, null, null, [], []),
    magic("tome-of-leadership-and-influence", "Tome of Leadership and Influence", "Studying this book for 48 hours over a period of 6 days or fewer increases your Charisma score and maximum by 2. It then loses its magic for a century.", null, 50000, null, null, [], []),
    magic("tome-of-understanding", "Tome of Understanding", "Studying this book for 48 hours over a period of 6 days or fewer increases your Wisdom score and maximum by 2. It then loses its magic for a century.", null, 50000, null, null, [], []),
    magic("universal-solvent", "Universal Solvent", "This milky liquid with a strong alcohol smell dissolves up to 1 square foot of adhesive it touches, including sovereign glue.", null, 500000, null, null, [], []),
    magic("well-of-many-worlds", "Well of Many Worlds", "This fine black cloth unfolds into a circular sheet 6 feet in diameter that opens a two-way portal to another world or plane. It cannot open another portal for 1d8 hours.", null, 500000, null, null, [], []),
    magic("wind-fan", "Wind Fan", "While holding this fan, you can use an action to cast the gust of wind spell (save DC 13). Reusing it before the next dawn risks tearing it into useless tatters.", "hand", 500, null, { maximum: 1, recharge: dawn(1) }, [], [power("fan-gust-of-wind", "gust-of-wind", false, "action", 0)]),
    magic("winged-boots", "Winged Boots", "While you wear these boots, you have a flying speed equal to your walking speed for up to 4 hours, recovering 2 hours of flying for every 12 hours they are not in use.", "accessory", 500, attuned, null, [], []),
    magic("wings-of-flying", "Wings of Flying", "While wearing this cloak, you can speak its command word to turn it into a pair of wings for 1 hour, granting you a flying speed of 60 feet.", "body", 5000, attuned, null, [], []),
  ];
}
