import type { StarterReferences } from "../references.js";

type ActionCost = "action" | "bonus-action" | "reaction";
type WondrousSlot = "hand" | "body" | "focus" | "accessory" | null;

export function magicWondrousAM(refs: StarterReferences): object[] {
  const { ref, currency } = refs;

  const attuned = { prerequisite: "short-rest" };
  const dawnAll = (maximum: number) => ({ maximum, recharge: { kind: "event", event: "dawn", amount: maximum } });
  const dawnOne = (maximum: number) => ({ maximum, recharge: { kind: "event", event: "dawn", amount: 1 } });
  const spent = (maximum: number) => ({ maximum, recharge: { kind: "none" } });

  const spell = (key: string, slug: string, cost: number, actionCost: ActionCost = "action", requireAttunement = true) => ({
    key, power: ref("spell", `srd-5.1:spell:${slug}`), requireAttunement, actionCost, cost,
  });
  const flat = (amount: number, target: object, requireAttunement = true) => ({ modifier: { kind: "flat", amount, target }, requireAttunement });
  const resist = (damageType: string, requireAttunement = true) => ({ modifier: { kind: "resistance", damageType }, requireAttunement });

  const wondrous = (id: string, name: string, description: string, slot: WondrousSlot, amount: number, magic: object) => ({
    reference: ref("item", `srd-5.1:item:${id}`), name, description, tags: ["srd-5.1", "magic-item", "wondrous"],
    mechanics: { category: "gear", stackable: false, slot, price: { currency, amount }, effects: [], magic },
  });

  return [
    wondrous("amulet-of-health", "Amulet of Health", "Sets your Constitution score to 19 while you wear it.", "accessory", 5000, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("amulet-of-proof-against-detection-and-location", "Amulet of Proof against Detection and Location", "Hides you from divination magic and magical scrying sensors while worn.", "accessory", 500, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("amulet-of-the-planes", "Amulet of the Planes", "Names a familiar location on another plane and, on a successful DC 15 Intelligence check, casts plane shift.", "accessory", 50000, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [spell("amulet-planes-plane-shift", "plane-shift", 0)] }),
    wondrous("apparatus-of-the-crab", "Apparatus of the Crab", "A sealed iron barrel that unfolds into a giant lobster-like vehicle controlled by ten levers.", null, 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("bag-of-beans", "Bag of Beans", "Holds 3d4 dry beans that explode or grow into bizarre magical effects when planted and watered.", null, 5000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("bag-of-devouring", "Bag of Devouring", "An extradimensional feeding orifice disguised as a bag of holding that devours creatures and matter.", null, 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("bag-of-holding", "Bag of Holding", "Holds up to 500 pounds or 64 cubic feet in an extradimensional space while always weighing 15 pounds.", null, 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("bag-of-tricks", "Bag of Tricks", "Produces fuzzy objects that become friendly beasts when thrown; usable three times before the next dawn.", null, 500, { attunement: null, charges: dawnAll(3), passiveModifiers: [], grantedPowers: [] }),
    wondrous("bead-of-force", "Bead of Force", "A thrown bead explodes for force damage and traps failed savers inside a weightless sphere of force.", null, 5000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("belt-of-dwarvenkind", "Belt of Dwarvenkind", "Grants dwarven resilience, poison resistance, and darkvision, and may grow the wearer a beard.", "body", 5000, { attunement: attuned, charges: null, passiveModifiers: [resist("poison")], grantedPowers: [] }),
    wondrous("belt-of-giant-strength", "Belt of Giant Strength", "Sets your Strength score to the value granted by the belt's giant type.", "body", 5000, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("boots-of-elvenkind", "Boots of Elvenkind", "Your steps make no sound and you have advantage on Dexterity (Stealth) checks to move silently.", "accessory", 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("boots-of-levitation", "Boots of Levitation", "You can cast the levitate spell on yourself at will.", "accessory", 5000, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [spell("boots-levitation-levitate", "levitate", 0)] }),
    wondrous("boots-of-speed", "Boots of Speed", "Clicking the heels doubles walking speed and imposes disadvantage on opportunity attacks; 10 minutes per long rest.", "accessory", 5000, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("boots-of-striding-and-springing", "Boots of Striding and Springing", "Your walking speed becomes 30 feet, encumbrance never slows you, and you jump three times as far.", "accessory", 500, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("boots-of-the-winterlands", "Boots of the Winterlands", "Grant resistance to cold, immunity to ice and snow difficult terrain, and extreme cold tolerance.", "accessory", 500, { attunement: attuned, charges: null, passiveModifiers: [resist("cold")], grantedPowers: [] }),
    wondrous("bowl-of-commanding-water-elementals", "Bowl of Commanding Water Elementals", "A water-filled bowl summons a water elemental once per dawn as if by conjure elemental.", "focus", 5000, { attunement: null, charges: dawnOne(1), passiveModifiers: [], grantedPowers: [] }),
    wondrous("bracers-of-archery", "Bracers of Archery", "Grant proficiency with longbows and shortbows and a +2 bonus to ranged damage with such weapons.", "accessory", 500, { attunement: attuned, charges: null, passiveModifiers: [flat(2, { kind: "damage-roll" })], grantedPowers: [] }),
    wondrous("bracers-of-defense", "Bracers of Defense", "Grant a +2 bonus to AC while you wear no armor and use no shield.", "accessory", 5000, { attunement: attuned, charges: null, passiveModifiers: [flat(2, { kind: "armor-class" })], grantedPowers: [] }),
    wondrous("brazier-of-commanding-fire-elementals", "Brazier of Commanding Fire Elementals", "A burning brazier summons a fire elemental once per dawn as if by conjure elemental.", "focus", 5000, { attunement: null, charges: dawnOne(1), passiveModifiers: [], grantedPowers: [] }),
    wondrous("brooch-of-shielding", "Brooch of Shielding", "Grants resistance to force damage and immunity to damage from the magic missile spell.", "accessory", 500, { attunement: attuned, charges: null, passiveModifiers: [resist("force")], grantedPowers: [] }),
    wondrous("broom-of-flying", "Broom of Flying", "Flies at 50 feet when ridden, carries up to 400 pounds, and can travel to a named destination alone.", null, 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("candle-of-invocation", "Candle of Invocation", "A lit candle grants advantage to matching-alignment creatures and can be consumed to cast gate.", null, 50000, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [spell("candle-invocation-gate", "gate", 0)] }),
    wondrous("cape-of-the-mountebank", "Cape of the Mountebank", "Casts dimension door once per dawn, leaving clouds of smoke at departure and arrival.", "body", 5000, { attunement: null, charges: dawnOne(1), passiveModifiers: [], grantedPowers: [spell("cape-mountebank-dimension-door", "dimension-door", 1, "action", false)] }),
    wondrous("carpet-of-flying", "Carpet of Flying", "A command word makes the carpet hover and fly under your spoken direction within 30 feet.", null, 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("censer-of-controlling-air-elementals", "Censer of Controlling Air Elementals", "Burning incense and a command word summon an air elemental once per dawn as if by conjure elemental.", "focus", 5000, { attunement: null, charges: dawnOne(1), passiveModifiers: [], grantedPowers: [] }),
    wondrous("chime-of-opening", "Chime of Opening", "Struck as an action, opens one lock or latch within 120 feet; usable ten times before it cracks.", "focus", 5000, { attunement: null, charges: spent(10), passiveModifiers: [], grantedPowers: [] }),
    wondrous("circlet-of-blasting", "Circlet of Blasting", "Casts scorching ray once per dawn with a +5 attack bonus.", "accessory", 500, { attunement: null, charges: dawnOne(1), passiveModifiers: [], grantedPowers: [spell("circlet-blasting-scorching-ray", "scorching-ray", 1, "action", false)] }),
    wondrous("cloak-of-arachnida", "Cloak of Arachnida", "Grants poison resistance, spider climbing, web immunity, and a once-per-dawn web spell.", "body", 50000, { attunement: attuned, charges: dawnOne(1), passiveModifiers: [resist("poison")], grantedPowers: [spell("cloak-arachnida-web", "web", 1)] }),
    wondrous("cloak-of-displacement", "Cloak of Displacement", "Projects an illusion that imposes disadvantage on attack rolls against you until you take damage.", "body", 5000, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("cloak-of-elvenkind", "Cloak of Elvenkind", "With the hood up, Perception checks to see you have disadvantage and your Stealth checks have advantage.", "body", 500, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("cloak-of-protection", "Cloak of Protection", "Grants a +1 bonus to AC and saving throws while worn.", "body", 500, { attunement: attuned, charges: null, passiveModifiers: [flat(1, { kind: "armor-class" })], grantedPowers: [] }),
    wondrous("cloak-of-the-bat", "Cloak of the Bat", "Grants Stealth advantage and dark-flight, and can polymorph the wearer into a bat once per dawn.", "body", 5000, { attunement: attuned, charges: dawnOne(1), passiveModifiers: [], grantedPowers: [spell("cloak-bat-polymorph", "polymorph", 1)] }),
    wondrous("cloak-of-the-manta-ray", "Cloak of the Manta Ray", "With the hood up, lets you breathe underwater and grants a 60-foot swimming speed.", "body", 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("crystal-ball", "Crystal Ball", "A crystal sphere used to cast scrying, with legendary variants adding mind reading, telepathy, or true seeing.", "focus", 50000, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("cube-of-force", "Cube of Force", "Spends charges to raise a 15-foot barrier keyed to one of five face effects; regains charges at dawn.", "focus", 5000, { attunement: attuned, charges: dawnOne(36), passiveModifiers: [], grantedPowers: [] }),
    wondrous("cubic-gate", "Cubic Gate", "A six-sided cube that opens a portal to a keyed plane with gate or plane shift; has 3 charges.", "focus", 50000, { attunement: null, charges: dawnOne(3), passiveModifiers: [], grantedPowers: [spell("cubic-gate-gate", "gate", 1, "action", false), spell("cubic-gate-plane-shift", "plane-shift", 1, "action", false)] }),
    wondrous("decanter-of-endless-water", "Decanter of Endless Water", "Pours fresh or salt water on command as a stream, fountain, or 30-foot geyser.", "focus", 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("deck-of-illusions", "Deck of Illusions", "Thrown cards create silent, harmless illusions of creatures that last until moved or dispelled.", null, 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("deck-of-many-things", "Deck of Many Things", "Drawing from this deck of fate invokes powerful boons or disastrous curses.", null, 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("dimensional-shackles", "Dimensional Shackles", "Manacles that block extradimensional movement for the bound creature until it breaks free.", null, 5000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("dust-of-disappearance", "Dust of Disappearance", "One use turns you and nearby creatures and objects invisible for 2d4 minutes.", null, 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("dust-of-dryness", "Dust of Dryness", "Pinches of dust absorb a 15-foot cube of water into a pellet and harm water elementals.", null, 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("dust-of-sneezing-and-choking", "Dust of Sneezing and Choking", "One use incapacitates you and nearby breathing creatures with uncontrollable sneezing.", null, 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("efficient-quiver", "Efficient Quiver", "Three extradimensional compartments hold arrows, javelins, and long objects while weighing 2 pounds.", null, 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("efreeti-bottle", "Efreeti Bottle", "Releasing the stopper summons an efreeti whose behavior is determined when the bottle is first opened.", "focus", 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("elemental-gem", "Elemental Gem", "Breaking the gem summons an elemental as if by conjure elemental, then the gem is lost.", null, 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("eversmoking-bottle", "Eversmoking Bottle", "An open bottle pours a heavily obscuring smoke cloud that expands over time.", "focus", 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("eyes-of-charming", "Eyes of Charming", "Three charges cast charm person with save DC 13; all charges return at dawn.", "accessory", 500, { attunement: attuned, charges: dawnAll(3), passiveModifiers: [], grantedPowers: [spell("eyes-charming-charm-person", "charm-person", 1)] }),
    wondrous("eyes-of-minute-seeing", "Eyes of Minute Seeing", "Lets you see fine detail within 1 foot and grants advantage on Investigation checks relying on sight.", "accessory", 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("eyes-of-the-eagle", "Eyes of the Eagle", "Grants advantage on Wisdom (Perception) checks relying on sight and magnifies distant detail.", "accessory", 500, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("feather-token", "Feather Token", "A single-use token whose kind determines a magical anchor, bird, fan, swan boat, tree, or whip effect.", null, 5000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("figurine-of-wondrous-power", "Figurine of Wondrous Power", "A pocket statuette that becomes a friendly living creature for a duration that varies by figurine.", null, 5000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("folding-boat", "Folding Boat", "Unfolds from a wooden box into a boat or ship and back again on command.", null, 5000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("gauntlets-of-ogre-power", "Gauntlets of Ogre Power", "Sets your Strength score to 19 while you wear them.", "accessory", 500, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("gem-of-brightness", "Gem of Brightness", "Fifty charges of light: sheds light freely or blinds one creature or a cone for five charges.", "focus", 500, { attunement: null, charges: spent(50), passiveModifiers: [], grantedPowers: [] }),
    wondrous("gem-of-seeing", "Gem of Seeing", "Three charges grant truesight out to 120 feet for 10 minutes; regains 1d3 charges at dawn.", "focus", 5000, { attunement: attuned, charges: dawnOne(3), passiveModifiers: [], grantedPowers: [] }),
    wondrous("gloves-of-missile-snaring", "Gloves of Missile Snaring", "Use your reaction to reduce ranged weapon damage by 1d10 + Dexterity and catch the missile.", "accessory", 500, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("gloves-of-swimming-and-climbing", "Gloves of Swimming and Climbing", "Climbing and swimming cost no extra movement and gain a +5 bonus to Athletics checks.", "accessory", 500, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("goggles-of-night", "Goggles of Night", "Grant darkvision out to 60 feet, or extend existing darkvision by 60 feet.", "accessory", 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("handy-haversack", "Handy Haversack", "A backpack whose extradimensional pouches always place the desired item on top.", null, 5000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("hat-of-disguise", "Hat of Disguise", "Casts disguise self at will, ending if the hat is removed.", "accessory", 500, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [spell("hat-disguise-disguise-self", "disguise-self", 0)] }),
    wondrous("headband-of-intellect", "Headband of Intellect", "Sets your Intelligence score to 19 while you wear it.", "accessory", 500, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("helm-of-brilliance", "Helm of Brilliance", "Gem-set helm that resists fire and casts daylight, fireball, prismatic spray, or wall of fire.", "accessory", 50000, { attunement: attuned, charges: null, passiveModifiers: [resist("fire")], grantedPowers: [spell("helm-brilliance-daylight", "daylight", 0), spell("helm-brilliance-fireball", "fireball", 0), spell("helm-brilliance-prismatic-spray", "prismatic-spray", 0), spell("helm-brilliance-wall-of-fire", "wall-of-fire", 0)] }),
    wondrous("helm-of-comprehending-languages", "Helm of Comprehending Languages", "Casts comprehend languages at will.", "accessory", 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [spell("helm-comprehending-languages-comprehend-languages", "comprehend-languages", 0, "action", false)] }),
    wondrous("helm-of-telepathy", "Helm of Telepathy", "Casts detect thoughts at will and can cast suggestion once per dawn on a focused creature.", "accessory", 500, { attunement: attuned, charges: dawnOne(1), passiveModifiers: [], grantedPowers: [spell("helm-telepathy-detect-thoughts", "detect-thoughts", 0), spell("helm-telepathy-suggestion", "suggestion", 1)] }),
    wondrous("helm-of-teleportation", "Helm of Teleportation", "Three charges cast the teleport spell; regains 1d3 charges at dawn.", "accessory", 5000, { attunement: attuned, charges: dawnOne(3), passiveModifiers: [], grantedPowers: [spell("helm-teleportation-teleport", "teleport", 1)] }),
    wondrous("horn-of-blasting", "Horn of Blasting", "A thunderous 30-foot cone deals 5d6 thunder damage and deafens; each use risks exploding.", "focus", 5000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("horn-of-valhalla", "Horn of Valhalla", "Summons warrior spirits that use berserker statistics for 1 hour; usable once every 7 days.", "focus", 5000, { attunement: null, charges: spent(1), passiveModifiers: [], grantedPowers: [] }),
    wondrous("horseshoes-of-speed", "Horseshoes of Speed", "A set of four shoes increases the wearer's walking speed by 30 feet.", null, 5000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("horseshoes-of-a-zephyr", "Horseshoes of a Zephyr", "A mounted creature floats 4 inches above the ground, ignoring terrain and leaving no tracks.", null, 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("instant-fortress", "Instant Fortress", "Grows from a metal cube into an adamantine tower and can be dismissed on command.", null, 5000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("ioun-stone", "Ioun Stone", "A stone that orbits your head and grants a benefit that varies by type.", "accessory", 50000, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("iron-bands-of-binding", "Iron Bands of Binding", "A thrown iron sphere opens into bands that restrain a Huge or smaller creature until the next dawn.", null, 5000, { attunement: null, charges: dawnOne(1), passiveModifiers: [], grantedPowers: [] }),
    wondrous("iron-flask", "Iron Flask", "Traps a creature from another plane and later releases it to serve you for 1 hour.", "focus", 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("lantern-of-revealing", "Lantern of Revealing", "A lit hooded lantern reveals invisible creatures and objects in its bright light.", "focus", 500, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("mantle-of-spell-resistance", "Mantle of Spell Resistance", "Grants advantage on saving throws against spells while worn.", "body", 5000, { attunement: attuned, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("manual-of-bodily-health", "Manual of Bodily Health", "Study for 48 hours over 6 days to increase your Constitution and its maximum by 2.", null, 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("manual-of-gainful-exercise", "Manual of Gainful Exercise", "Study for 48 hours over 6 days to increase your Strength and its maximum by 2.", null, 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("manual-of-golems", "Manual of Golems", "Contains the incantations needed to construct and animate a particular type of golem.", null, 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("manual-of-quickness-of-action", "Manual of Quickness of Action", "Study for 48 hours over 6 days to increase your Dexterity and its maximum by 2.", null, 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("marvelous-pigments", "Marvelous Pigments", "Paints two-dimensional images that become real nonmagical objects worth no more than 25 gp.", null, 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
    wondrous("medallion-of-thoughts", "Medallion of Thoughts", "Three charges cast detect thoughts with save DC 13; regains 1d3 charges at dawn.", "accessory", 500, { attunement: attuned, charges: dawnOne(3), passiveModifiers: [], grantedPowers: [spell("medallion-thoughts-detect-thoughts", "detect-thoughts", 1)] }),
    wondrous("mirror-of-life-trapping", "Mirror of Life Trapping", "Traps creatures that see their reflection in one of twelve extradimensional cells.", "focus", 50000, { attunement: null, charges: null, passiveModifiers: [], grantedPowers: [] }),
  ];
}
