import { createCampaignQuestHttpRequestSchema } from "@velvet/contracts";
import type { CampaignQuestsHttpResponse, CreateCampaignQuestHttpRequest, QuestCommandHttpRequest } from "@velvet/contracts";
import { useCallback, useEffect, useRef, useState } from "react";
import { isDefiniteNarrativeRejection, NarrativeMutationStatus, receiptFrom } from "../NarrativeMutationStatus";
import { beginNarrativeMutation, blocksNarrativeMutation, clearNarrativeMutation, consumeNarrativeConfirmed, markNarrativeAmbiguous, markNarrativeConfirmed, markNarrativePartial, useNarrativeMutation } from "../narrativeMutationRegistry";
import type { StudioAuthorization } from "../StudioAuthorization";

export interface QuestJournalApi { list:(id:string)=>Promise<{data:CampaignQuestsHttpResponse;revision:number}>;create:(id:string,input:CreateCampaignQuestHttpRequest)=>Promise<unknown>;command:(id:string,input:QuestCommandHttpRequest)=>Promise<unknown>;preview:(data:CampaignQuestsHttpResponse)=>CampaignQuestsHttpResponse }
type ObjectiveDraft={objectiveId:string;description:string;targetProgress:number;dependencyObjectiveIds:string[];visibility:"public"|"gm"};
type RewardDraft={rewardId:string;kind:"xp"|"currency"|"item"|"custom";amount:number|null;label:string;visibility:"public"|"gm"};
type QuestCommandBody=QuestCommandHttpRequest extends infer Command?Command extends unknown?Omit<Command,"expectedRevision"|"idempotencyKey">:never:never;
const uid=()=>`quest-ui-${crypto.randomUUID()}`;
export function QuestJournalPage({campaignId,authorization,api,onBack,focusHeadingRequest}:{campaignId:string;authorization:StudioAuthorization;api:QuestJournalApi;onBack:()=>void;focusHeadingRequest?:number}){
  const isGm=authorization.audience==="gm",mutation=useNarrativeMutation(campaignId,"quest"),observer=authorization.role==="observer";
  const [data,setData]=useState<CampaignQuestsHttpResponse|null>(null),[revision,setRevision]=useState(0),[phase,setPhase]=useState<"loading"|"ready"|"failed">("loading"),[status,setStatus]=useState(""),[preview,setPreview]=useState<CampaignQuestsHttpResponse|null>(null),[previewRequest,setPreviewRequest]=useState<CreateCampaignQuestHttpRequest|null>(null);
  const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[storylineId,setStorylineId]=useState(""),[visibility,setVisibility]=useState<"public"|"gm">("public"),[journalText,setJournalText]=useState(""),[objectives,setObjectives]=useState<ObjectiveDraft[]>([{objectiveId:uid(),description:"",targetProgress:1,dependencyObjectiveIds:[],visibility:"public"}]),[rewards,setRewards]=useState<RewardDraft[]>([]),[claimActors,setClaimActors]=useState<Record<string,string>>({});
  const mounted=useRef(true),generation=useRef(0),heading=useRef<HTMLHeadingElement>(null);
  const invalidate=()=>{setPreviewRequest(null);setPreview(null)};
  const load=useCallback(async(focus=false)=>{const token=++generation.current;setPhase("loading");try{const result=await api.list(campaignId);if(!mounted.current||token!==generation.current)return false;setData(result.data);setRevision(result.revision);setPhase("ready");if(focus)queueMicrotask(()=>heading.current?.focus());return result.revision}catch{if(mounted.current&&token===generation.current)setPhase("failed");return false}},[api,campaignId]);
  useEffect(()=>{mounted.current=true;void load().then((fresh)=>{if(fresh!==false&&mutation?.phase==="confirmed"){fresh===mutation.resultingRevision?consumeNarrativeConfirmed(mutation):markNarrativePartial(mutation)}});return()=>{mounted.current=false;generation.current+=1}},[load]);
  useEffect(()=>{if(focusHeadingRequest!==undefined&&phase!=="loading")heading.current?.focus()},[focusHeadingRequest,phase]);
  async function refreshAuthorized(){try{await authorization.reauthorize()}catch{/* gate renders the authorized fallback */}}
  async function mutate(operation:string,request:{idempotencyKey:string;expectedRevision:number},write:()=>Promise<unknown>,gmRequired=false){let auth;try{auth=await authorization.reauthorize()}catch{return}if(auth.role==="observer"||(gmRequired&&auth.audience!=="gm")){setStatus("Your current campaign role does not authorize this command.");return}const pending=beginNarrativeMutation(campaignId,"quest",operation,{idempotencyKey:request.idempotencyKey,expectedRevision:request.expectedRevision});if(!pending)return;try{const result=await write(),receipt=receiptFrom(result);markNarrativeConfirmed(pending,result,receipt);const fresh=await api.list(campaignId).catch(()=>null);const confirmed={...pending,phase:"confirmed" as const,memoryResult:result,receipt,resultingRevision:receipt?.revisionAfter,refresh:"required" as const};if(fresh&&receipt!==undefined&&fresh.revision===receipt.revisionAfter){if(mounted.current){setData(fresh.data);setRevision(fresh.revision);setPhase("ready");}consumeNarrativeConfirmed(confirmed)}else markNarrativePartial(confirmed)}catch(error){if(isDefiniteNarrativeRejection(error)){clearNarrativeMutation(campaignId,"quest");setStatus(`${operation} was definitely rejected as stale or conflicting. Latest journal must be refreshed.`)}else markNarrativeAmbiguous(pending)}}
  function buildRequest():CreateCampaignQuestHttpRequest|null{const parsed=createCampaignQuestHttpRequestSchema.safeParse({quest:{questId:previewRequest?.quest.questId??uid(),storylineId,title,description:description||null,visibility,objectives,rewards,journalText},expectedRevision:revision,idempotencyKey:previewRequest?.idempotencyKey??uid()});return parsed.success?parsed.data:null}
  function previewExact(){const request=buildRequest();if(!request)return;const now=new Date().toISOString(),visible=request.quest.visibility==="public";const candidate:CampaignQuestsHttpResponse={quests:visible?[{questId:request.quest.questId,campaignId,storylineId:request.quest.storylineId,title:request.quest.title,description:request.quest.description,status:"offered",rewards:request.quest.rewards.filter((item)=>item.visibility==="public").map(({visibility:_,...reward})=>({...reward,claimedByActorId:null,claimedAt:null})),createdAt:now,updatedAt:now}]:[],objectives:visible?request.quest.objectives.filter((item)=>item.visibility==="public").map(({visibility:_,...objective})=>({...objective,questId:request.quest.questId,progress:0,completedAt:null})):[],journal:visible?[{entryId:"preview-entry",questId:request.quest.questId,text:request.quest.journalText,occurredAt:now}]:[]};setPreview(api.preview(candidate));setPreviewRequest(request)}
  function issue(questId:string,body:QuestCommandBody){const request={...body,expectedRevision:revision,idempotencyKey:uid()} as QuestCommandHttpRequest;void mutate(`Quest ${request.kind}`,request,()=>api.command(questId,request))}
  const locked=blocksNarrativeMutation(mutation);
  return <main className="studio-page" aria-labelledby="journal-heading"><div className="studio-shell"><header className="studio-header"><div><button className="back-link" onClick={onBack}>← Campaign</button><p className="eyebrow">{isGm?"GM QUEST STUDIO":"ADVENTURE JOURNAL"}</p><h1 ref={heading} tabIndex={-1} id="journal-heading">Quest journal</h1></div><button className="ghost" onClick={()=>void refreshAuthorized()}>Reauthorize & refresh</button></header><NarrativeMutationStatus mutation={mutation} onRefresh={()=>void refreshAuthorized()}/>{status&&<p role="status">{status}</p>}{phase==="failed"&&<p role="alert">Quest journal could not be loaded.</p>}
    {data&&<div className="studio-grid"><section className="studio-panel"><h2>Quests</h2>{data.quests.length?<ul className="quest-list">{data.quests.map((quest)=><li key={quest.questId}><h3>{quest.title}</h3><p>{quest.status}{quest.description&&` · ${quest.description}`}</p><h4>Objectives</h4><ul>{data.objectives.filter((item)=>item.questId===quest.questId).map((item)=><li key={item.objectiveId}>{item.description} — {item.progress}/{item.targetProgress}<button className="text-button" disabled={locked||observer} onClick={()=>issue(quest.questId,{kind:"advance-objective",objectiveId:item.objectiveId})}>Advance this objective</button></li>)}</ul><h4>Journal</h4><ol>{data.journal.filter((item)=>item.questId===quest.questId).map((item)=><li key={item.entryId}>{item.text} <time>{item.occurredAt}</time></li>)}</ol><div className="button-row"><button disabled={locked||observer} onClick={()=>issue(quest.questId,{kind:"accept"})}>Accept</button><button disabled={locked||observer} onClick={()=>issue(quest.questId,{kind:"abandon"})}>Abandon</button></div>{quest.rewards.map((reward)=><div className="inline-command" key={reward.rewardId}><span>{reward.label}{reward.claimedAt?" — claimed":""}</span>{!reward.claimedAt&&<><label>Claiming actor ID<input value={claimActors[reward.rewardId]??""} onChange={(e)=>setClaimActors((current)=>({...current,[reward.rewardId]:e.target.value}))}/></label><button disabled={locked||observer||!claimActors[reward.rewardId]} onClick={()=>issue(quest.questId,{kind:"claim-reward",actorId:claimActors[reward.rewardId]!,rewardId:reward.rewardId})}>Claim this reward</button></>}</div>)}</li>)}</ul>:<p>No visible quests.</p>}</section>
      {isGm&&<section className="studio-panel"><form className="studio-form" onSubmit={(e)=>{e.preventDefault();if(previewRequest)void mutate("Quest creation",previewRequest,()=>api.create(campaignId,previewRequest),true)}}><h2>Create complete quest definition</h2><label>Storyline ID<input required value={storylineId} onChange={(e)=>{setStorylineId(e.target.value);invalidate()}}/></label><label>Title<input required value={title} onChange={(e)=>{setTitle(e.target.value);invalidate()}}/></label><label>Description<textarea value={description} onChange={(e)=>{setDescription(e.target.value);invalidate()}}/></label><label>Quest visibility<select value={visibility} onChange={(e)=>{setVisibility(e.target.value as "public"|"gm");invalidate()}}><option value="public">Public</option><option value="gm">GM only</option></select></label><label>Exact initial journal entry<textarea required value={journalText} onChange={(e)=>{setJournalText(e.target.value);invalidate()}}/></label>
        <fieldset><legend>Objectives and dependencies</legend>{objectives.map((objective,index)=><div className="draft-row" key={objective.objectiveId}><label>Description<input value={objective.description} onChange={(e)=>{setObjectives((all)=>all.map((item,i)=>i===index?{...item,description:e.target.value}:item));invalidate()}}/></label><label>Target<input type="number" min="1" value={objective.targetProgress} onChange={(e)=>{setObjectives((all)=>all.map((item,i)=>i===index?{...item,targetProgress:Number(e.target.value)}:item));invalidate()}}/></label><label>Visibility<select value={objective.visibility} onChange={(e)=>{setObjectives((all)=>all.map((item,i)=>i===index?{...item,visibility:e.target.value as "public"|"gm"}:item));invalidate()}}><option value="public">Public</option><option value="gm">GM</option></select></label><fieldset><legend>Dependencies</legend>{objectives.filter((item)=>item.objectiveId!==objective.objectiveId).map((dependency)=><label key={dependency.objectiveId}><input type="checkbox" checked={objective.dependencyObjectiveIds.includes(dependency.objectiveId)} onChange={(e)=>{setObjectives((all)=>all.map((item,i)=>i===index?{...item,dependencyObjectiveIds:e.target.checked?[...item.dependencyObjectiveIds,dependency.objectiveId]:item.dependencyObjectiveIds.filter((id)=>id!==dependency.objectiveId)}:item));invalidate()}}/>{dependency.description||"Untitled objective"}</label>)}</fieldset><button type="button" onClick={()=>{setObjectives((all)=>all.filter((_,i)=>i!==index));invalidate()}} disabled={objectives.length===1}>Remove objective</button></div>)}<button type="button" onClick={()=>{setObjectives((all)=>[...all,{objectiveId:uid(),description:"",targetProgress:1,dependencyObjectiveIds:[],visibility:"public"}]);invalidate()}}>Add objective</button></fieldset>
        <fieldset><legend>Rewards</legend>{rewards.map((reward,index)=><div className="draft-row" key={reward.rewardId}><label>Label<input value={reward.label} onChange={(e)=>{setRewards((all)=>all.map((item,i)=>i===index?{...item,label:e.target.value}:item));invalidate()}}/></label><label>Kind<select value={reward.kind} onChange={(e)=>{setRewards((all)=>all.map((item,i)=>i===index?{...item,kind:e.target.value as RewardDraft["kind"]}:item));invalidate()}}>{["xp","currency","item","custom"].map((kind)=><option key={kind}>{kind}</option>)}</select></label><label>Amount<input type="number" value={reward.amount??""} onChange={(e)=>{setRewards((all)=>all.map((item,i)=>i===index?{...item,amount:e.target.value===""?null:Number(e.target.value)}:item));invalidate()}}/></label><label>Visibility<select value={reward.visibility} onChange={(e)=>{setRewards((all)=>all.map((item,i)=>i===index?{...item,visibility:e.target.value as "public"|"gm"}:item));invalidate()}}><option value="public">Public</option><option value="gm">GM</option></select></label><button type="button" onClick={()=>{setRewards((all)=>all.filter((_,i)=>i!==index));invalidate()}}>Remove reward</button></div>)}<button type="button" onClick={()=>{setRewards((all)=>[...all,{rewardId:uid(),kind:"custom",amount:null,label:"",visibility:"public"}]);invalidate()}}>Add reward</button></fieldset>
        <div className="button-row"><button type="button" onClick={previewExact} disabled={locked||!buildRequest()}>Preview exact public projection</button><button className="primary" disabled={locked||!previewRequest}>Create exact previewed quest</button></div></form></section>}</div>}
    {isGm&&preview&&<section className="projection-preview"><h2>Exact player projection preview</h2><pre>{JSON.stringify(preview,null,2)}</pre></section>}</div></main>;
}
