import type { CampaignQuestsHttpResponse, CreateCampaignQuestHttpRequest, QuestCommandHttpRequest } from "@velvet/contracts";
import { useCallback, useEffect, useRef, useState } from "react";

export interface QuestJournalApi { list:(id:string)=>Promise<{data:CampaignQuestsHttpResponse;revision:number}>;create:(id:string,input:CreateCampaignQuestHttpRequest)=>Promise<unknown>;command:(id:string,input:QuestCommandHttpRequest)=>Promise<unknown>;preview:(data:CampaignQuestsHttpResponse)=>CampaignQuestsHttpResponse }
type QuestCommandBody = QuestCommandHttpRequest extends infer Command ? Command extends unknown ? Omit<Command,"expectedRevision"|"idempotencyKey"> : never : never;
type Lock={phase:"ambiguous"|"confirmed";kind:string;receipt?:unknown};const key=(id:string)=>`velvet.quest-command.v1:${id}`;const read=(id:string):Lock|null=>{try{return JSON.parse(localStorage.getItem(key(id))??"null")as Lock|null}catch{return null}};const store=(id:string,value:Lock|null)=>{try{value?localStorage.setItem(key(id),JSON.stringify(value)):localStorage.removeItem(key(id))}catch{/* persistent lock is best effort */}};const id=()=>`journal-${crypto.randomUUID()}`;
export function QuestJournalPage({campaignId,isGm,api,onBack,focusHeadingRequest}:{campaignId:string;isGm:boolean;api:QuestJournalApi;onBack:()=>void;focusHeadingRequest?:number}){
  const [data,setData]=useState<CampaignQuestsHttpResponse|null>(null),[revision,setRevision]=useState(0),[phase,setPhase]=useState<"loading"|"ready"|"failed">("loading"),[lock,setLock]=useState<Lock|null>(()=>read(campaignId)),[status,setStatus]=useState(""),[preview,setPreview]=useState<CampaignQuestsHttpResponse|null>(null);
  const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[storyline,setStoryline]=useState(""),[objective,setObjective]=useState(""),[journal,setJournal]=useState(""),[previewed,setPreviewed]=useState(false),[claimActor,setClaimActor]=useState("");
  const mounted=useRef(true),generation=useRef(0),heading=useRef<HTMLHeadingElement>(null);
  const load=useCallback(async(focus=false)=>{const token=++generation.current;setPhase("loading");try{const result=await api.list(campaignId);if(!mounted.current||token!==generation.current)return false;setData(isGm?result.data:api.preview(result.data));setRevision(result.revision);setPhase("ready");if(focus)queueMicrotask(()=>heading.current?.focus());return true}catch{if(mounted.current&&token===generation.current)setPhase("failed");return false}},[api,campaignId,isGm]);
  useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;generation.current+=1}},[load]);useEffect(()=>{if(focusHeadingRequest!==undefined&&phase!=="loading")heading.current?.focus()},[focusHeadingRequest,phase]);
  async function mutate(kind:string,write:()=>Promise<unknown>){if(lock)return;const pending:Lock={phase:"ambiguous",kind};store(campaignId,pending);setLock(pending);setStatus(`${kind} submitted once; automatic replay is disabled.`);try{const receipt=await write();const confirmed:Lock={phase:"confirmed",kind,receipt};store(campaignId,confirmed);if(!mounted.current)return;setLock(confirmed);const fresh=await load();if(fresh){store(campaignId,null);setLock(null);setStatus(`${kind} confirmed; authoritative journal refreshed.`)}else setStatus(`${kind} confirmed, but refresh failed. Receipt and lock are preserved.`)}catch{if(mounted.current)setStatus(`${kind} outcome is ambiguous or stale. It will not be replayed.`)}}
  function newQuest():CreateCampaignQuestHttpRequest{const objectiveId=id();return{quest:{questId:id(),storylineId:storyline,title,description:description||null,visibility:"public",objectives:[{objectiveId,description:objective,targetProgress:1,dependencyObjectiveIds:[],visibility:"public"}],rewards:[],journalText:journal},expectedRevision:revision,idempotencyKey:id()}}
  function issue(questId:string,command:QuestCommandBody){void mutate(`Quest ${command.kind}`,()=>api.command(questId,{...command,expectedRevision:revision,idempotencyKey:id()} as QuestCommandHttpRequest))}
  return <main className="studio-page" aria-labelledby="journal-heading"><div className="studio-shell"><header className="studio-header"><div><button className="back-link" onClick={onBack}>← Campaign</button><p className="eyebrow">{isGm?"GM QUEST STUDIO":"ADVENTURE JOURNAL"}</p><h1 ref={heading} tabIndex={-1} id="journal-heading">Quest journal</h1></div><button className="ghost" onClick={()=>void load(true)}>Refresh</button></header>{lock&&<section className="studio-lock" role="alert"><strong>{lock.phase==="confirmed"?"Confirmed command awaiting refresh":"Quest outcome unresolved"}</strong><p>No duplicate or automatic replay is allowed across reload.</p></section>}{status&&<p role="status">{status}</p>}{phase==="failed"&&<p role="alert">Quest journal could not be loaded.</p>}
    {data&&<div className="studio-grid"><section className="studio-panel"><h2>Quests</h2>{data.quests.length?<ul className="quest-list">{data.quests.map((quest)=><li key={quest.questId}><h3><bdi dir="auto">{quest.title}</bdi></h3><p>{quest.status}{quest.description&&<> · <bdi dir="auto">{quest.description}</bdi></>}</p><h4>Objectives</h4><ul>{data.objectives.filter((item)=>item.questId===quest.questId).map((item)=><li key={item.objectiveId}><bdi dir="auto">{item.description}</bdi> — {item.progress}/{item.targetProgress}{item.completedAt&&" complete"}<button className="text-button" disabled={Boolean(lock)} onClick={()=>issue(quest.questId,{kind:"advance-objective",objectiveId:item.objectiveId})}>Advance objective</button></li>)}</ul><h4>Journal</h4><ol>{data.journal.filter((item)=>item.questId===quest.questId).map((item)=><li key={item.entryId}><bdi dir="auto">{item.text}</bdi> <time>{item.occurredAt}</time></li>)}</ol><div className="button-row"><button className="ghost" disabled={Boolean(lock)} onClick={()=>issue(quest.questId,{kind:"accept"})}>Accept</button><button className="ghost" disabled={Boolean(lock)} onClick={()=>issue(quest.questId,{kind:"abandon"})}>Abandon</button></div>{quest.rewards.filter((item)=>item.claimedAt===null).map((reward)=><div className="inline-command" key={reward.rewardId}><span>{reward.label}</span><label>Claiming actor ID<input value={claimActor} onChange={(e)=>setClaimActor(e.target.value)} /></label><button disabled={Boolean(lock)||!claimActor} onClick={()=>issue(quest.questId,{kind:"claim-reward",actorId:claimActor,rewardId:reward.rewardId})}>Claim reward</button></div>)}</li>)}</ul>:<p>No visible quests.</p>}</section>
      {isGm&&<section className="studio-panel"><form className="studio-form" onSubmit={(e)=>{e.preventDefault();if(previewed)void mutate("Quest creation",()=>api.create(campaignId,newQuest()))}}><h2>Create quest</h2><label>Storyline ID<input required value={storyline} onChange={(e)=>{setStoryline(e.target.value);setPreviewed(false)}} /></label><label>Title<input required value={title} onChange={(e)=>{setTitle(e.target.value);setPreviewed(false)}} /></label><label>Player description<textarea value={description} onChange={(e)=>{setDescription(e.target.value);setPreviewed(false)}} /></label><label>First objective<textarea required value={objective} onChange={(e)=>{setObjective(e.target.value);setPreviewed(false)}} /></label><label>Initial journal entry<textarea required value={journal} onChange={(e)=>{setJournal(e.target.value);setPreviewed(false)}} /></label><div className="button-row"><button type="button" className="ghost" disabled={Boolean(lock)||!storyline||!title||!objective||!journal} onClick={()=>{const now=new Date().toISOString();const request=newQuest();const gm:CampaignQuestsHttpResponse={quests:[{questId:request.quest.questId,campaignId,storylineId:request.quest.storylineId,title:request.quest.title,description:request.quest.description,status:"offered",rewards:[],createdAt:now,updatedAt:now}],objectives:[],journal:[]};setPreview(api.preview(gm));setPreviewed(true)}}>Preview player projection</button><button className="primary" disabled={Boolean(lock)||!previewed}>Create after preview</button></div></form></section>}</div>}
    {isGm&&preview&&<section className="projection-preview"><h2>Player projection preview</h2><p>Storyline ancestry and non-player fields are structurally absent.</p><pre>{JSON.stringify(preview,null,2)}</pre></section>}</div></main>;
}
