import { createCampaignStorylineHttpRequestSchema } from "@velvet/contracts";
import type { CampaignStoryHttpResponse, CreateCampaignStorylineHttpRequest, StorylineCommandHttpRequest } from "@velvet/contracts";
import { useCallback, useEffect, useRef, useState } from "react";
import { isDefiniteNarrativeRejection, NarrativeMutationStatus, receiptFrom } from "../NarrativeMutationStatus";
import { beginNarrativeMutation, blocksNarrativeMutation, clearNarrativeMutation, consumeNarrativeConfirmed, markNarrativeAmbiguous, markNarrativeConfirmed, markNarrativePartial, useNarrativeMutation } from "../narrativeMutationRegistry";
import type { StudioAuthorization } from "../StudioAuthorization";

export interface StoryStudioApi { get:(id:string,audience:"gm"|"player")=>Promise<{data:CampaignStoryHttpResponse;revision:number}>;create:(id:string,input:CreateCampaignStorylineHttpRequest)=>Promise<unknown>;command:(id:string,input:StorylineCommandHttpRequest)=>Promise<unknown>;preview:(data:CampaignStoryHttpResponse)=>CampaignStoryHttpResponse }
type NodeDraft={nodeId:string;title:string;description:string|null;gmNotes:string|null;revealThreshold:number};
type EdgeDraft={edgeId:string;kind:"sequence"|"requires";fromNodeId:string;toNodeId:string};
type PointDraft={plotPointId:string;nodeId:string;question:string;answer:string;gmNotes:string|null};
type SourceDraft={sourceId:string;kind:"node"|"plot-point";targetId:string};
type ClueDraft={clueId:string;title:string;content:string;truth:string;gmNotes:string|null;revealThreshold:number;sources:SourceDraft[]};
const uid=()=>`story-ui-${crypto.randomUUID()}`;
export function StoryStudioPage({campaignId,authorization,api,onBack,focusHeadingRequest}:{campaignId:string;authorization:StudioAuthorization;api:StoryStudioApi;onBack:()=>void;focusHeadingRequest?:number}){
  const isGm=authorization.audience==="gm",mutation=useNarrativeMutation(campaignId,"story");
  const [story,setStory]=useState<CampaignStoryHttpResponse|null>(null),[revision,setRevision]=useState(0),[phase,setPhase]=useState<"loading"|"ready"|"failed">("loading"),[status,setStatus]=useState(""),[preview,setPreview]=useState<CampaignStoryHttpResponse|null>(null),[previewRequest,setPreviewRequest]=useState<CreateCampaignStorylineHttpRequest|null>(null);
  const [title,setTitle]=useState(""),[summary,setSummary]=useState(""),[nodes,setNodes]=useState<NodeDraft[]>([{nodeId:uid(),title:"",description:null,gmNotes:null,revealThreshold:0}]),[edges,setEdges]=useState<EdgeDraft[]>([]),[points,setPoints]=useState<PointDraft[]>([]),[clues,setClues]=useState<ClueDraft[]>([]),[answers,setAnswers]=useState<Record<string,string>>({});
  const mounted=useRef(true),generation=useRef(0),heading=useRef<HTMLHeadingElement>(null);
  const invalidate=()=>{setPreview(null);setPreviewRequest(null)};
  const load=useCallback(async(focus=false)=>{const token=++generation.current;setPhase("loading");try{const result=await api.get(campaignId,authorization.audience);if(!mounted.current||token!==generation.current)return false;setStory(result.data);setRevision(result.revision);setPhase("ready");if(focus)queueMicrotask(()=>heading.current?.focus());return result.revision}catch{if(mounted.current&&token===generation.current)setPhase("failed");return false}},[api,campaignId,authorization.audience]);
  useEffect(()=>{mounted.current=true;void load().then((fresh)=>{if(fresh!==false&&mutation?.phase==="confirmed"){fresh===mutation.resultingRevision?consumeNarrativeConfirmed(mutation):markNarrativePartial(mutation)}});return()=>{mounted.current=false;generation.current+=1}},[load]);useEffect(()=>{if(focusHeadingRequest!==undefined&&phase!=="loading")heading.current?.focus()},[focusHeadingRequest,phase]);
  async function refreshAuthorized(){try{await authorization.reauthorize()}catch{/* gate renders the authorized fallback */}}
  async function mutate(operation:string,request:{idempotencyKey:string;expectedRevision:number},write:()=>Promise<unknown>){let auth;try{auth=await authorization.reauthorize()}catch{return}if(auth.audience!=="gm"){setStatus("GM authority is required for story mutations.");return}const pending=beginNarrativeMutation(campaignId,"story",operation,{idempotencyKey:request.idempotencyKey,expectedRevision:request.expectedRevision});if(!pending)return;try{const result=await write(),receipt=receiptFrom(result);markNarrativeConfirmed(pending,result,receipt);const fresh=await api.get(campaignId,"gm").catch(()=>null);const confirmed={...pending,phase:"confirmed" as const,memoryResult:result,receipt,resultingRevision:receipt?.revisionAfter,refresh:"required" as const};if(fresh&&receipt!==undefined&&fresh.revision===receipt.revisionAfter){if(mounted.current){setStory(fresh.data);setRevision(fresh.revision);setPhase("ready");}consumeNarrativeConfirmed(confirmed)}else markNarrativePartial(confirmed)}catch(error){if(isDefiniteNarrativeRejection(error)){clearNarrativeMutation(campaignId,"story");setStatus(`${operation} was definitely rejected as stale or conflicting.`)}else markNarrativeAmbiguous(pending)}}
  function build():CreateCampaignStorylineHttpRequest|null{const parsed=createCampaignStorylineHttpRequestSchema.safeParse({storyline:{storylineId:previewRequest?.storyline.storylineId??uid(),title,summary:summary||null,nodes,edges,plotPoints:points,clues},expectedRevision:revision,idempotencyKey:previewRequest?.idempotencyKey??uid()});return parsed.success?parsed.data:null}
  function previewExact(){const request=build();if(!request)return;const now=new Date().toISOString(),line=request.storyline.storylineId;const candidate:CampaignStoryHttpResponse={storylines:[{storylineId:line,campaignId,title:request.storyline.title,summary:request.storyline.summary,status:"active",createdAt:now,updatedAt:now}],nodes:request.storyline.nodes.map((node)=>({...node,storylineId:line,status:"hidden" as const,createdAt:now,updatedAt:now})),edges:request.storyline.edges.map((edge)=>({...edge,storylineId:line})),plotPoints:request.storyline.plotPoints.map((point)=>({...point,storylineId:line,answered:false,playerAnswer:null,answeredAt:null})),clues:request.storyline.clues.map((clue)=>({...clue,storylineId:line,revealed:false,revealedAt:null}))};setPreview(api.preview(candidate));setPreviewRequest(request)}
  function command(storylineId:string,kind:StorylineCommandHttpRequest["kind"],targetId:string,data:Record<string,unknown>={}){const request={kind,targetId,data,expectedRevision:revision,idempotencyKey:uid()} as StorylineCommandHttpRequest;void mutate(`Story ${kind}`,request,()=>api.command(storylineId,request))}
  const gm=story&&"storylines"in story?story:null,player=story&&"visibleNodes"in story?story:null,locked=blocksNarrativeMutation(mutation);
  const nodeLabel=(id:string)=>nodes.find((node)=>node.nodeId===id)?.title||"Untitled node",pointLabel=(id:string)=>points.find((point)=>point.plotPointId===id)?.question||"Untitled plot point";
  return <main className="studio-page" aria-labelledby="story-heading"><div className="studio-shell"><header className="studio-header"><div><button className="back-link" onClick={onBack}>← Campaign</button><p className="eyebrow">{isGm?"PRIVATE STORY STUDIO":"DISCOVERED STORY"}</p><h1 ref={heading} tabIndex={-1} id="story-heading">Story studio</h1></div><button className="ghost" onClick={()=>void refreshAuthorized()}>Reauthorize & refresh</button></header><NarrativeMutationStatus mutation={mutation} onRefresh={()=>void refreshAuthorized()}/>{status&&<p role="status">{status}</p>}{phase==="failed"&&<p role="alert">Story could not be loaded.</p>}
    {player&&<div className="studio-grid"><section className="studio-panel"><h2>Revealed story nodes</h2><ul className="story-list" aria-label="Revealed story graph list">{player.visibleNodes.map((node)=><li key={node.nodeId}><strong>{node.title}</strong><span>{node.status}</span>{node.description&&<p>{node.description}</p>}</li>)}</ul></section><section className="studio-panel"><h2>Discovered clues</h2><ul>{player.discoveredClues.map((clue)=><li key={clue.clueId}><strong>{clue.title}</strong><p>{clue.content}</p></li>)}</ul></section></div>}
    {gm&&<div className="studio-grid"><section className="studio-panel"><h2>Story graph keyboard list</h2>{gm.storylines.map((line)=><section key={line.storylineId}><h3>{line.title}</h3><p>{line.status}{line.summary&&` · ${line.summary}`}</p><ul className="story-list" aria-label={`${line.title} graph nodes`}>{gm.nodes.filter((node)=>node.storylineId===line.storylineId).map((node)=><li key={node.nodeId}><strong>{node.title}</strong><span>{node.status}</span>{node.description&&<p>{node.description}</p>}{node.gmNotes&&<p className="private-record"><strong>GM notes:</strong> {node.gmNotes}</p>}<div className="button-row"><button disabled={locked} onClick={()=>command(line.storylineId,"reveal-node",node.nodeId)}>Reveal node</button><button disabled={locked} onClick={()=>command(line.storylineId,"resolve-node",node.nodeId)}>Resolve node</button></div></li>)}</ul><h4>Semantic edges (list alternative)</h4><ul>{gm.edges.filter((edge)=>edge.storylineId===line.storylineId).map((edge)=><li key={edge.edgeId}>{gm.nodes.find((node)=>node.nodeId===edge.fromNodeId)?.title||"Story node"} → {gm.nodes.find((node)=>node.nodeId===edge.toNodeId)?.title||"Story node"} ({edge.kind})</li>)}</ul><h4>Plot points</h4><ul>{gm.plotPoints.filter((point)=>point.storylineId===line.storylineId).map((point)=><li key={point.plotPointId}><strong>{point.question}</strong><p>Canonical answer: {point.answer}</p>{point.gmNotes&&<p className="private-record">GM notes: {point.gmNotes}</p>}<p>{point.answered?`Answered: ${point.playerAnswer}`:"Unanswered"}</p><label>Exact player answer<input value={answers[point.plotPointId]??""} onChange={(e)=>setAnswers((current)=>({...current,[point.plotPointId]:e.target.value}))}/></label><button disabled={locked||!answers[point.plotPointId]} onClick={()=>command(line.storylineId,"answer-plot-point",point.plotPointId,{answer:answers[point.plotPointId]})}>Answer plot point</button></li>)}</ul><h4>Clues</h4><ul>{gm.clues.filter((clue)=>clue.storylineId===line.storylineId).map((clue)=><li key={clue.clueId}><strong>{clue.title}</strong> — {clue.revealed?"revealed":"hidden"}<p>{clue.content}</p><p className="private-record">Truth: {clue.truth}{clue.gmNotes&&` · ${clue.gmNotes}`}</p><button disabled={locked} onClick={()=>command(line.storylineId,"reveal-clue",clue.clueId)}>Reveal clue</button></li>)}</ul></section>)}</section>
      <section className="studio-panel"><form className="studio-form" onSubmit={(e)=>{e.preventDefault();if(previewRequest)void mutate("Storyline creation",previewRequest,()=>api.create(campaignId,previewRequest))}}><h2>Author complete initial graph</h2><p className="field-help">Persisted graphs are read-only after creation; current commands change reveal, resolution, clue, and answer state.</p><label>Storyline title<input required value={title} onChange={(e)=>{setTitle(e.target.value);invalidate()}}/></label><label>Summary<textarea value={summary} onChange={(e)=>{setSummary(e.target.value);invalidate()}}/></label>
        <fieldset><legend>Nodes</legend>{nodes.map((node,index)=><div className="draft-row" key={node.nodeId}><label>Node title<input value={node.title} onChange={(e)=>{setNodes((all)=>all.map((item,i)=>i===index?{...item,title:e.target.value}:item));invalidate()}}/></label><label>Player description<textarea value={node.description??""} onChange={(e)=>{setNodes((all)=>all.map((item,i)=>i===index?{...item,description:e.target.value||null}:item));invalidate()}}/></label><label>GM notes<textarea value={node.gmNotes??""} onChange={(e)=>{setNodes((all)=>all.map((item,i)=>i===index?{...item,gmNotes:e.target.value||null}:item));invalidate()}}/></label><label>Reveal threshold<input type="number" min="0" value={node.revealThreshold} onChange={(e)=>{setNodes((all)=>all.map((item,i)=>i===index?{...item,revealThreshold:Number(e.target.value)}:item));invalidate()}}/></label><button type="button" disabled={nodes.length===1} onClick={()=>{setNodes((all)=>all.filter((_,i)=>i!==index));invalidate()}}>Remove node</button></div>)}<button type="button" onClick={()=>{setNodes((all)=>[...all,{nodeId:uid(),title:"",description:null,gmNotes:null,revealThreshold:0}]);invalidate()}}>Add node</button></fieldset>
        <fieldset><legend>Semantic edges</legend>{edges.map((edge,index)=><div className="draft-row" key={edge.edgeId}><label>From<select value={edge.fromNodeId} onChange={(e)=>{setEdges((all)=>all.map((item,i)=>i===index?{...item,fromNodeId:e.target.value}:item));invalidate()}}>{nodes.map((node)=><option key={node.nodeId} value={node.nodeId}>{node.title||"Untitled node"}</option>)}</select></label><label>Kind<select value={edge.kind} onChange={(e)=>{setEdges((all)=>all.map((item,i)=>i===index?{...item,kind:e.target.value as EdgeDraft["kind"]}:item));invalidate()}}><option value="sequence">Sequence</option><option value="requires">Requires</option></select></label><label>To<select value={edge.toNodeId} onChange={(e)=>{setEdges((all)=>all.map((item,i)=>i===index?{...item,toNodeId:e.target.value}:item));invalidate()}}>{nodes.map((node)=><option key={node.nodeId} value={node.nodeId}>{node.title||"Untitled node"}</option>)}</select></label><button type="button" onClick={()=>{setEdges((all)=>all.filter((_,i)=>i!==index));invalidate()}}>Remove edge</button></div>)}<button type="button" disabled={nodes.length<2} onClick={()=>{setEdges((all)=>[...all,{edgeId:uid(),kind:"sequence",fromNodeId:nodes[0]!.nodeId,toNodeId:nodes[1]!.nodeId}]);invalidate()}}>Add edge</button></fieldset>
        <fieldset><legend>Plot points</legend>{points.map((point,index)=><div className="draft-row" key={point.plotPointId}><label>Node<select value={point.nodeId} onChange={(e)=>{setPoints((all)=>all.map((item,i)=>i===index?{...item,nodeId:e.target.value}:item));invalidate()}}>{nodes.map((node)=><option key={node.nodeId} value={node.nodeId}>{node.title||"Untitled node"}</option>)}</select></label><label>Question<input value={point.question} onChange={(e)=>{setPoints((all)=>all.map((item,i)=>i===index?{...item,question:e.target.value}:item));invalidate()}}/></label><label>Canonical answer<textarea value={point.answer} onChange={(e)=>{setPoints((all)=>all.map((item,i)=>i===index?{...item,answer:e.target.value}:item));invalidate()}}/></label><label>GM notes<textarea value={point.gmNotes??""} onChange={(e)=>{setPoints((all)=>all.map((item,i)=>i===index?{...item,gmNotes:e.target.value||null}:item));invalidate()}}/></label><button type="button" onClick={()=>{setPoints((all)=>all.filter((_,i)=>i!==index));invalidate()}}>Remove plot point</button></div>)}<button type="button" onClick={()=>{setPoints((all)=>[...all,{plotPointId:uid(),nodeId:nodes[0]!.nodeId,question:"",answer:"",gmNotes:null}]);invalidate()}}>Add plot point</button></fieldset>
        <fieldset><legend>Clues and source links</legend>{clues.map((clue,index)=><div className="draft-row" key={clue.clueId}><label>Title<input value={clue.title} onChange={(e)=>{setClues((all)=>all.map((item,i)=>i===index?{...item,title:e.target.value}:item));invalidate()}}/></label><label>Player content<textarea value={clue.content} onChange={(e)=>{setClues((all)=>all.map((item,i)=>i===index?{...item,content:e.target.value}:item));invalidate()}}/></label><label>Private truth<textarea value={clue.truth} onChange={(e)=>{setClues((all)=>all.map((item,i)=>i===index?{...item,truth:e.target.value}:item));invalidate()}}/></label><label>GM notes<textarea value={clue.gmNotes??""} onChange={(e)=>{setClues((all)=>all.map((item,i)=>i===index?{...item,gmNotes:e.target.value||null}:item));invalidate()}}/></label><label>Reveal threshold<input type="number" min="1" value={clue.revealThreshold} onChange={(e)=>{setClues((all)=>all.map((item,i)=>i===index?{...item,revealThreshold:Number(e.target.value)}:item));invalidate()}}/></label><fieldset><legend>Source links</legend>{clue.sources.map((source,sourceIndex)=><div key={source.sourceId}><label>Source kind<select value={source.kind} onChange={(e)=>{const kind=e.target.value as SourceDraft["kind"],targetId=kind==="node"?nodes[0]?.nodeId??"":points[0]?.plotPointId??"";setClues((all)=>all.map((item,i)=>i===index?{...item,sources:item.sources.map((entry,j)=>j===sourceIndex?{...entry,kind,targetId}:entry)}:item));invalidate()}}><option value="node">Node</option><option value="plot-point">Plot point</option></select></label><label>Target<select value={source.targetId} onChange={(e)=>{setClues((all)=>all.map((item,i)=>i===index?{...item,sources:item.sources.map((entry,j)=>j===sourceIndex?{...entry,targetId:e.target.value}:entry)}:item));invalidate()}}>{source.kind==="node"?nodes.map((node)=><option key={node.nodeId} value={node.nodeId}>{nodeLabel(node.nodeId)}</option>):points.map((point)=><option key={point.plotPointId} value={point.plotPointId}>{pointLabel(point.plotPointId)}</option>)}</select></label><button type="button" disabled={clue.sources.length===1} onClick={()=>{setClues((all)=>all.map((item,i)=>i===index?{...item,sources:item.sources.filter((_,j)=>j!==sourceIndex)}:item));invalidate()}}>Remove source</button></div>)}<button type="button" onClick={()=>{setClues((all)=>all.map((item,i)=>i===index?{...item,sources:[...item.sources,{sourceId:uid(),kind:"node",targetId:nodes[0]!.nodeId}]}:item));invalidate()}}>Add source</button></fieldset><button type="button" onClick={()=>{setClues((all)=>all.filter((_,i)=>i!==index));invalidate()}}>Remove clue</button></div>)}<button type="button" onClick={()=>{setClues((all)=>[...all,{clueId:uid(),title:"",content:"",truth:"",gmNotes:null,revealThreshold:1,sources:[{sourceId:uid(),kind:"node",targetId:nodes[0]!.nodeId}]}]);invalidate()}}>Add clue</button></fieldset>
        <div className="button-row"><button type="button" disabled={locked||!build()} onClick={previewExact}>Preview exact public graph</button><button className="primary" disabled={locked||!previewRequest}>Create exact previewed graph</button></div></form></section></div>}
    {isGm&&preview&&<section className="projection-preview"><h2>Exact player projection preview</h2><p>Initial nodes and clues remain hidden until current story commands reveal them; all private graph fields are absent.</p><pre>{JSON.stringify(preview,null,2)}</pre></section>}</div></main>;
}
