import { actorTravelCommandRequestSchema } from "@velvet/contracts";
import type { ActorTravelCommandRequest, CampaignWorldHttpResponse } from "@velvet/contracts";
import { FormEvent, useMemo, useRef, useState } from "react";

export function TravelDialog({ world, revision, disabled, onTravel }: { world: CampaignWorldHttpResponse; revision: number; disabled?: boolean; onTravel: (actorId: string, command: ActorTravelCommandRequest) => Promise<void> }) {
  const dialog = useRef<HTMLDialogElement>(null), [actorId,setActorId]=useState(""), [party,setParty]=useState(""), [connectionId,setConnectionId]=useState(""), [review,setReview]=useState(false), [busy,setBusy]=useState(false);
  const names=useMemo(()=>new Map(world.visibleLocations.map((item)=>[item.locationId,item.name])),[world]);
  const eligible=world.visibleConnections.filter((connection)=>world.currentLocations.some((current)=>current.locationId===connection.fromLocationId));
  const actors=party.split(/[\s,]+/).filter(Boolean); const exactParty=actors.length?actors:actorId?[actorId]:[];
  const command=actorTravelCommandRequestSchema.safeParse({connectionId,partyActorIds:exactParty,expectedRevision:revision,idempotencyKey:`travel-ui-${typeof crypto!=="undefined"&&"randomUUID"in crypto?crypto.randomUUID():Date.now()}`});
  const route=eligible.find((item)=>item.connectionId===connectionId);
  function begin(event:FormEvent){event.preventDefault();if(!command.success||!exactParty.includes(actorId))return;setReview(true);}
  async function confirm(){if(!command.success||busy)return;setBusy(true);try{await onTravel(actorId,command.data);dialog.current?.close();setReview(false);}finally{setBusy(false);}}
  return <><button type="button" className="primary" disabled={disabled||eligible.length===0} onClick={()=>dialog.current?.showModal()}>Plan travel</button><dialog ref={dialog} className="rpg-dialog" onClose={()=>setReview(false)} aria-labelledby="travel-heading"><form onSubmit={begin}><h2 id="travel-heading">{review?"Confirm travel":"Plan travel"}</h2>{review&&route?<div className="review-card"><p><strong>Route:</strong> {names.get(route.fromLocationId)??"Known location"} → {names.get(route.toLocationId)??"Known destination"}</p><p><strong>Exact party:</strong> {exactParty.join(", ")}</p><p>Expected world revision {revision}. This command is sent once.</p></div>:<><label>Acting actor ID<input required value={actorId} onChange={(event)=>setActorId(event.target.value)} autoComplete="off" /></label><label>Exact party actor IDs <span className="field-help">comma or space separated</span><input value={party} onChange={(event)=>setParty(event.target.value)} placeholder="Defaults to acting actor" autoComplete="off" /></label><label>Eligible route<select required value={connectionId} onChange={(event)=>setConnectionId(event.target.value)}><option value="">Choose a visible connection</option>{eligible.map((item)=><option key={item.connectionId} value={item.connectionId}>{names.get(item.fromLocationId)??"Known location"} → {names.get(item.toLocationId)??"Known destination"}</option>)}</select></label></>}
        <div className="button-row"><button type="button" className="ghost" disabled={busy} onClick={()=>review?setReview(false):dialog.current?.close()}>{review?"Back":"Cancel"}</button><button type={review?"button":"submit"} className="primary" disabled={busy||!command.success||!exactParty.includes(actorId)} onClick={review?()=>void confirm():undefined}>{busy?"Submitting once…":review?"Confirm travel":"Review"}</button></div></form></dialog></>;
}
