import type { ActorTravelCommandRequest, ActorTravelCommandResponse, CampaignWorldHttpResponse } from "@velvet/contracts";
import { useCallback, useEffect, useRef, useState } from "react";
import { LocationTree } from "./LocationTree";
import { TravelDialog } from "./TravelDialog";

export interface WorldExplorerApi { getWorld:(campaignId:string)=>Promise<{data:CampaignWorldHttpResponse;revision:number}>; travel:(actorId:string,input:ActorTravelCommandRequest)=>Promise<ActorTravelCommandResponse> }
type Marker={campaignId:string;phase:"ambiguous"|"confirmed";actorId:string;command:ActorTravelCommandRequest;receipt?:ActorTravelCommandResponse};
const key=(id:string)=>`velvet.world-travel.v1:${id}`;
const readMarker=(id:string):Marker|null=>{try{const value=JSON.parse(localStorage.getItem(key(id))??"null") as Marker|null;return value?.campaignId===id?value:null;}catch{return null;}};
const writeMarker=(id:string,value:Marker|null)=>{try{value?localStorage.setItem(key(id),JSON.stringify(value)):localStorage.removeItem(key(id));}catch{/* best-effort durable ambiguity lock */}};
export function WorldExplorerPage({campaignId,api,onBack,focusHeadingRequest}:{campaignId:string;api:WorldExplorerApi;onBack:()=>void;focusHeadingRequest?:number}){
  const [world,setWorld]=useState<CampaignWorldHttpResponse|null>(null),[revision,setRevision]=useState(0),[phase,setPhase]=useState<"loading"|"ready"|"failed">("loading"),[status,setStatus]=useState(""),[marker,setMarker]=useState<Marker|null>(()=>readMarker(campaignId));
  const generation=useRef(0),mounted=useRef(true),heading=useRef<HTMLHeadingElement>(null);
  const load=useCallback(async(focus=false)=>{const token=++generation.current;setPhase("loading");try{const next=await api.getWorld(campaignId);if(!mounted.current||token!==generation.current)return false;setWorld(next.data);setRevision(next.revision);setPhase("ready");if(focus)queueMicrotask(()=>heading.current?.focus());return true;}catch{if(mounted.current&&token===generation.current)setPhase("failed");return false;}},[api,campaignId]);
  useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;generation.current+=1;};},[load]);useEffect(()=>{if(focusHeadingRequest!==undefined&&phase!=="loading")queueMicrotask(()=>heading.current?.focus());},[focusHeadingRequest,phase]);
  async function travel(actorId:string,command:ActorTravelCommandRequest){if(marker)return;const pending:Marker={campaignId,phase:"ambiguous",actorId,command};writeMarker(campaignId,pending);setMarker(pending);setStatus("Travel submitted once. Automatic replay is disabled.");try{const receipt=await api.travel(actorId,command);const confirmed:Marker={...pending,phase:"confirmed",receipt};writeMarker(campaignId,confirmed);if(!mounted.current)return;setMarker(confirmed);const refreshed=await load();if(!mounted.current)return;if(refreshed){writeMarker(campaignId,null);setMarker(null);setStatus("Travel confirmed; authoritative world refreshed.");}else setStatus("Travel confirmed, but refresh failed. The receipt and lock are preserved.");}catch{if(mounted.current)setStatus("Travel outcome is ambiguous or stale. It will not be replayed; authoritative world may be refreshed.");}}
  const currentIds=world?.currentLocations.map((item)=>item.locationId)??[];const names=new Map(world?.visibleLocations.map((item)=>[item.locationId,item.name])??[]);
  return <main className="studio-page" aria-labelledby="world-heading"><div className="studio-shell"><header className="studio-header"><div><button className="back-link" onClick={onBack}>← Campaign</button><p className="eyebrow">KNOWN WORLD</p><h1 ref={heading} tabIndex={-1} id="world-heading">World explorer</h1></div>{world&&<TravelDialog world={world} revision={revision} disabled={Boolean(marker)} onTravel={travel}/>}</header>
    {marker&&<section className="studio-lock" role="alert"><strong>{marker.phase==="confirmed"?"Confirmed travel awaiting refresh":"Travel outcome unresolved"}</strong><p>No duplicate or automatic replay is permitted.</p><button className="ghost" onClick={()=>void load(true)}>Refresh authoritative world</button></section>}{status&&<p role="status">{status}</p>}
    {phase==="loading"&&!world&&<p role="status">Loading known world…</p>}{phase==="failed"&&!world&&<section role="alert"><p>Known world could not be loaded.</p><button className="ghost" onClick={()=>void load(true)}>Retry</button></section>}{world&&<div className="studio-grid"><section className="studio-panel"><h2>Known locations</h2><LocationTree locations={world.visibleLocations} currentLocationIds={currentIds}/></section><section className="studio-panel"><h2>Visible exits</h2>{world.visibleConnections.length?<ul className="plain-list">{world.visibleConnections.map((item)=><li key={item.connectionId}><strong>{names.get(item.fromLocationId)??"Known location"}</strong> → {names.get(item.toLocationId)??"Known destination"}</li>)}</ul>:<p>No visible exits.</p>}<h2>Current locations</h2><ul>{world.currentLocations.map((item)=><li key={item.actorId}>{names.get(item.locationId)??"Known location"}</li>)}</ul></section></div>}
    {marker?.receipt&&<section className="studio-receipt"><h2>Travel receipt</h2><p>Revision {marker.receipt.receipt.revisionBefore} → {marker.receipt.receipt.revisionAfter}</p><p>Occurred {marker.receipt.receipt.occurredAt}</p></section>}</div></main>;
}
