import { ChangeEvent, useRef, useState } from "react";
import type { Character, ProviderSettings, Session } from "../api";

export interface CharacterLibraryPageProps {
  characters: Character[]; sessions: Session[]; selectedIds: string[]; primaryId: string; busy: boolean; error: string | null; provider: ProviderSettings | null;
  campaignLibraryAvailable: boolean; onCampaigns: () => void;
  onSelected: (ids: string[]) => void; onPrimary: (id: string) => void; onCreate: () => void; onEdit: (id: string) => void; onMemory: (id: string) => void; onLore: () => void; onStart: (title: string) => void; onResume: (id: string) => void; onDeleteSession: (session: Session) => void; onDelete: (character: Character) => void; onExport: (character: Character) => void; onImport: (file: File) => void;
}

export function CharacterLibraryPage(props: CharacterLibraryPageProps) {
  const [title, setTitle] = useState(""); const inputRef = useRef<HTMLInputElement>(null);
  const participantNames = (session: Session) => session.participants?.map((participant) => participant.name).join(", ") || props.characters.find((item) => item.id === session.characterId)?.name || "Missing character";
  function importFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) props.onImport(file); event.target.value = ""; }
  return <main className="page library-page"><section className="library-shell">
    <header className="library-header"><div><p className="eyebrow">LOCAL CHARACTER STUDIO</p><h1 className="title">Velvet</h1><p className="subtitle">Your characters, shared worlds, and ongoing scenes.</p></div><div className="button-row"><input ref={inputRef} className="sr-only" type="file" accept="application/json,.json" onChange={importFile} /><button className="ghost" onClick={() => inputRef.current?.click()}>Import</button><button className="ghost" onClick={props.onLore}>World lore</button>{props.campaignLibraryAvailable && <button className="ghost" onClick={props.onCampaigns}>Campaigns</button>}<button className="primary" onClick={props.onCreate}>New character</button></div></header>
    {props.error && <p className="error notice-error" role="alert">{props.error}</p>}
    <div className="library-grid"><section className="library-panel"><div className="section-heading-row"><div><h2>Characters</h2><p className="meta-text">Select one or more for a new scene.</p></div><span className="count-badge">{props.characters.length}</span></div>
      {props.characters.length === 0 ? <div className="empty-state large"><p>No characters yet.</p><button className="primary" onClick={props.onCreate}>Create your first character</button></div> : <div className="character-grid">{props.characters.map((character) => { const selected = props.selectedIds.includes(character.id); return <article className={`character-card ${selected ? "selected" : ""}`} key={character.id}><div className="character-select"><label className="checkbox"><input type="checkbox" checked={selected} onChange={(e) => props.onSelected(e.target.checked ? [...props.selectedIds, character.id] : props.selectedIds.filter((id) => id !== character.id))} /><span className="avatar">{character.name.slice(0, 1).toUpperCase()}</span><span><strong>{character.name}</strong><small>{character.age} · {character.archetype}</small></span></label>{selected && <label className="primary-radio" title="Primary speaker"><input type="radio" name="primary" checked={props.primaryId === character.id} onChange={() => props.onPrimary(character.id)} /> Primary</label>}</div><p className="boundary-preview">{character.boundaries}</p><div className="item-actions"><button className="ghost small" onClick={() => props.onEdit(character.id)}>Edit</button><button className="ghost small" onClick={() => props.onMemory(character.id)}>Memory</button><button className="ghost small" onClick={() => props.onExport(character)}>Export</button><button className="danger subtle small" onClick={() => props.onDelete(character)}>Delete</button></div></article>; })}</div>}
      {props.selectedIds.length > 0 && <div className="session-builder"><div><strong>{props.selectedIds.length === 1 ? "Solo scene" : `Group scene · ${props.selectedIds.length} characters`}</strong><p className="meta-text">Primary: {props.characters.find((item) => item.id === props.primaryId)?.name}</p></div><input aria-label="Session title" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Optional scene title" maxLength={120} /><button className="primary" disabled={props.busy || !props.primaryId} onClick={() => props.onStart(title)}>{props.busy ? "Opening…" : "Start new session"}</button></div>}
    </section>
    <aside className="library-panel sessions-panel"><div className="section-heading-row"><div><h2>Sessions</h2><p className="meta-text">Resume or remove a saved scene.</p></div><span className="count-badge">{props.sessions.length}</span></div>{props.sessions.length === 0 ? <p className="empty-state">No sessions yet.</p> : <div className="session-list">{props.sessions.map((item) => <article className="session-row" key={item.id}><button className="session-open" onClick={() => props.onResume(item.id)} disabled={props.busy}><span><strong>{item.title || participantNames(item)}</strong><small>{participantNames(item)}</small></span><span><span className={`status-pill ${item.state === "closed" ? "forgotten" : "active"}`}>{item.state}</span><small>{new Date(item.createdAt).toLocaleDateString()}</small></span></button><button className="danger subtle small session-delete" onClick={() => props.onDeleteSession(item)} disabled={props.busy} aria-label={`Delete session: ${item.title || participantNames(item)}`}>Delete</button></article>)}</div>}<div className="provider-card"><span className="provider-dot" /><div><strong>{props.provider?.model || "Local story engine"}</strong><small>{props.provider ? `${props.provider.providerType} · ${props.provider.streaming ? "streaming" : "buffered"}` : "Provider unavailable"}</small></div></div></aside>
    </div>
  </section></main>;
}
