import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import type { CampaignQuestsHttpResponse, CampaignStoryHttpResponse, CampaignWorldHttpResponse } from "@velvet/contracts";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { projectFactionsForPlayers, projectNpcsForPlayers, projectQuestsForPlayers, projectStoryForPlayers, type CampaignFactionsHttpResponse, type CampaignNpcsHttpResponse } from "../../api";
import { NpcRosterPage, type CastStudioApi } from "./cast/NpcRosterPage";
import { QuestJournalPage, type QuestJournalApi } from "./journal/QuestJournalPage";
import { StoryStudioPage, type StoryStudioApi } from "./journal/StoryStudioPage";
import { LocationTree } from "./world/LocationTree";
import { WorldExplorerPage, type WorldExplorerApi } from "./world/WorldExplorerPage";

const at="2030-01-01T00:00:00.000Z";
const world:CampaignWorldHttpResponse={currentLocations:[{actorId:"actor",locationId:"town",revision:2,updatedAt:at}],visibleLocations:[{locationId:"town",parentLocationId:null,name:"Moon Town",description:"Known"},{locationId:"wood",parentLocationId:"town",name:"Whisper Wood",description:"Road"}],visibleConnections:[{connectionId:"road",fromLocationId:"town",toLocationId:"wood"}]};
const npcs:CampaignNpcsHttpResponse={npcs:[{npcId:"npc",personaId:"persona",publicState:{name:"Mira"},privateState:{goals:"SECRET GOAL",gmNotes:"SECRET NOTE",merchantState:null},createdAt:at}],relationships:[]};
const factions:CampaignFactionsHttpResponse={factions:[{factionId:"hidden-faction",name:"Hidden Hand",publicState:{description:"SECRET DESCRIPTION"},privateState:{gmNotes:"SECRET FACTION",visibility:"gm"},createdAt:at}],standings:[]};
const quests:CampaignQuestsHttpResponse={quests:[{questId:"quest",campaignId:"campaign",storylineId:"secret-lineage",title:"Find dawn",description:"Visible",status:"active",rewards:[],createdAt:at,updatedAt:at}],objectives:[{objectiveId:"objective",questId:"quest",description:"Reach the hill",targetProgress:2,progress:1,dependencyObjectiveIds:[],completedAt:null}],journal:[{entryId:"entry",questId:"quest",text:"A road opened.",occurredAt:at}]};
const story:CampaignStoryHttpResponse={storylines:[{storylineId:"line",campaignId:"campaign",title:"Secret arc",summary:null,status:"active",createdAt:at,updatedAt:at}],nodes:[{nodeId:"hidden",storylineId:"line",title:"HIDDEN NODE",description:null,gmNotes:"SECRET STORY NOTE",status:"hidden",revealThreshold:1,createdAt:at,updatedAt:at},{nodeId:"seen",storylineId:"line",title:"Revealed Gate",description:"Visible",gmNotes:null,status:"revealed",revealThreshold:0,createdAt:at,updatedAt:at}],edges:[{edgeId:"edge",storylineId:"line",kind:"sequence",fromNodeId:"hidden",toNodeId:"seen"}],plotPoints:[],clues:[]};

describe("M3.6 role-filtered studios",()=>{
  beforeEach(()=>localStorage.clear());afterEach(()=>{cleanup();vi.restoreAllMocks()});
  it("uses a keyboard-operable named location tree without IDs as labels",()=>{render(<LocationTree locations={world.visibleLocations}/>);const tree=screen.getByRole("tree",{name:"Known location hierarchy"}),items=within(tree).getAllByRole("treeitem");expect(tree.tagName).toBe("UL");items[0]!.focus();fireEvent.keyDown(items[0]!,{key:"ArrowDown"});expect(document.activeElement).toBe(items[1]);expect(tree.textContent).not.toContain("town");});
  it("never renders NPC, faction, quest ancestry, or hidden story secrets for players",async()=>{
    const castApi={listNpcs:vi.fn().mockResolvedValue({data:npcs,revision:2}),listFactions:vi.fn().mockResolvedValue({data:factions,revision:2}),previewNpcs:projectNpcsForPlayers,previewFactions:projectFactionsForPlayers} as unknown as CastStudioApi;
    render(<NpcRosterPage campaignId="campaign" isGm={false} api={castApi} onBack={()=>undefined}/>);await screen.findByText("Mira");expect(document.body.textContent).not.toMatch(/SECRET|Hidden Hand/);cleanup();
    const questApi={list:vi.fn().mockResolvedValue({data:quests,revision:1}),preview:projectQuestsForPlayers} as unknown as QuestJournalApi;render(<QuestJournalPage campaignId="campaign" isGm={false} api={questApi} onBack={()=>undefined}/>);await screen.findByText("Find dawn");expect(document.body.textContent).not.toContain("secret-lineage");cleanup();
    const storyApi={get:vi.fn().mockResolvedValue({data:story,revision:1}),preview:projectStoryForPlayers} as unknown as StoryStudioApi;render(<StoryStudioPage campaignId="campaign" isGm={false} api={storyApi} onBack={()=>undefined}/>);await screen.findByText("Revealed Gate");expect(document.body.textContent).not.toMatch(/HIDDEN NODE|SECRET STORY NOTE|Secret arc/);
  });
  it("constructs a schema-stripped GM player preview before NPC creation",async()=>{const api={listNpcs:vi.fn().mockResolvedValue({data:npcs,revision:2}),listFactions:vi.fn().mockResolvedValue({data:{factions:[],standings:[]},revision:2}),previewNpcs:projectNpcsForPlayers,previewFactions:projectFactionsForPlayers,createNpc:vi.fn()} as unknown as CastStudioApi;render(<NpcRosterPage campaignId="campaign" isGm api={api} onBack={()=>undefined}/>);await screen.findAllByText("Mira");fireEvent.change(screen.getByLabelText("Persona ID"),{target:{value:"persona-two"}});fireEvent.change(screen.getByLabelText("Public name"),{target:{value:"Tala"}});fireEvent.change(screen.getByLabelText("Private goals"),{target:{value:"DO NOT LEAK"}});fireEvent.click(screen.getAllByRole("button",{name:"Preview player projection"})[0]!);const preview=screen.getByRole("heading",{name:"Player projection preview"}).parentElement!;expect(preview.textContent).toContain("Tala");expect(preview.textContent).not.toContain("DO NOT LEAK");expect((screen.getAllByRole("button",{name:"Create after preview"})[0] as HTMLButtonElement).disabled).toBe(false);});
  it("persists an ambiguous travel lock across unmount and blocks duplicate travel",async()=>{let reject!:()=>void;const pending=new Promise<never>((_,next)=>{reject=()=>next(new Error("unknown"))});const api={getWorld:vi.fn().mockResolvedValue({data:world,revision:2}),travel:vi.fn().mockReturnValue(pending)} satisfies WorldExplorerApi;const first=render(<WorldExplorerPage campaignId="campaign" api={api} onBack={()=>undefined}/>);await screen.findAllByText("Moon Town");fireEvent.click(screen.getByRole("button",{name:"Plan travel"}));fireEvent.change(screen.getByLabelText("Acting actor ID"),{target:{value:"actor"}});fireEvent.change(screen.getByLabelText("Eligible route"),{target:{value:"road"}});fireEvent.click(screen.getByRole("button",{name:"Review"}));fireEvent.click(screen.getByRole("button",{name:"Confirm travel"}));expect(api.travel).toHaveBeenCalledTimes(1);first.unmount();reject();render(<WorldExplorerPage campaignId="campaign" api={api} onBack={()=>undefined}/>);await screen.findByText("Travel outcome unresolved");expect((screen.getByRole("button",{name:"Plan travel"}) as HTMLButtonElement).disabled).toBe(true);expect(api.travel).toHaveBeenCalledTimes(1);});
  it("ignores an out-of-order world read after unmount",async()=>{let resolve!: (value:{data:CampaignWorldHttpResponse;revision:number})=>void;const api={getWorld:vi.fn().mockReturnValue(new Promise((done)=>{resolve=done})),travel:vi.fn()} as WorldExplorerApi;const consoleError=vi.spyOn(console,"error").mockImplementation(()=>undefined);const view=render(<WorldExplorerPage campaignId="campaign" api={api} onBack={()=>undefined}/>);view.unmount();resolve({data:world,revision:9});await waitFor(()=>expect(consoleError).not.toHaveBeenCalled());});
});
