import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import type { CampaignQuestsHttpResponse, CampaignStoryHttpResponse, CampaignWorldHttpResponse, GmCampaignFactionsHttpResponse, GmCampaignNpcsHttpResponse } from "@velvet/contracts";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { ApiError, projectFactionsForPlayers, projectNpcsForPlayers, projectQuestsForPlayers, projectStoryForPlayers } from "../../api";
import { NpcRosterPage, type CastStudioApi } from "./cast/NpcRosterPage";
import { StoryStudioPage, type StoryStudioApi } from "./journal/StoryStudioPage";
import { QuestJournalPage, type QuestJournalApi } from "./journal/QuestJournalPage";
import { resetNarrativeMutationRegistryForTests } from "./narrativeMutationRegistry";
import type { StudioAuthorization } from "./StudioAuthorization";
import { LocationTree } from "./world/LocationTree";
import { WorldExplorerPage, type WorldExplorerApi } from "./world/WorldExplorerPage";

const at="2030-01-01T00:00:00.000Z";
const authorization=(audience:"gm"|"player"="gm",role:StudioAuthorization["role"]=audience==="gm"?"gm":"player"):StudioAuthorization=>({audience,role,generation:1,reauthorize:vi.fn().mockResolvedValue({audience,role,generation:2,reauthorize:vi.fn()})});
const world:CampaignWorldHttpResponse={currentLocations:[{actorId:"actor-one",locationId:"town",revision:2,updatedAt:at},{actorId:"actor-two",locationId:"wood",revision:1,updatedAt:at}],visibleLocations:[{locationId:"town",parentLocationId:null,name:"Moon Town",description:"Known"},{locationId:"wood",parentLocationId:"town",name:"Whisper Wood",description:"Road"}],visibleConnections:[{connectionId:"road",fromLocationId:"town",toLocationId:"wood"}]};
const npcs:GmCampaignNpcsHttpResponse={npcs:[{npcId:"npc",personaId:"persona",publicState:{name:"Mira"},privateState:{goals:"SECRET GOAL",gmNotes:"SECRET NOTE",merchantState:null},createdAt:at}],relationships:[]};
const factions:GmCampaignFactionsHttpResponse={factions:[{factionId:"hidden-faction",name:"Hidden Hand",publicState:{description:"SECRET DESCRIPTION"},privateState:{gmNotes:"SECRET FACTION",visibility:"gm"},createdAt:at}],standings:[]};
const quests:CampaignQuestsHttpResponse={quests:[{questId:"quest",campaignId:"campaign",storylineId:"secret-lineage",title:"Find dawn",description:"Visible",status:"active",rewards:[],createdAt:at,updatedAt:at}],objectives:[],journal:[]};
const story:CampaignStoryHttpResponse={storylines:[{storylineId:"line",campaignId:"campaign",title:"Secret arc",summary:null,status:"active",createdAt:at,updatedAt:at}],nodes:[{nodeId:"seen",storylineId:"line",title:"Revealed Gate",description:"Visible",gmNotes:"SECRET STORY",status:"revealed",revealThreshold:0,createdAt:at,updatedAt:at}],edges:[],plotPoints:[{plotPointId:"point",storylineId:"line",nodeId:"seen",question:"Who opens it?",answer:"Mira",gmNotes:"SECRET ANSWER",answered:false,playerAnswer:null,answeredAt:null}],clues:[]};

describe("M3.6 hardened narrative studios",()=>{
  beforeEach(()=>{localStorage.clear();resetNarrativeMutationRegistryForTests()});afterEach(()=>{cleanup();vi.restoreAllMocks()});
  it("provides a native keyboard tree without technical IDs as labels",()=>{render(<LocationTree locations={world.visibleLocations}/>);const tree=screen.getByRole("tree",{name:"Known location hierarchy"}),items=within(tree).getAllByRole("treeitem");items[0]!.focus();fireEvent.keyDown(items[0]!,{key:"ArrowDown"});expect(document.activeElement).toBe(items[1]);expect(tree.textContent).not.toContain("town")});
  it("renders structurally strict player cast projections with no private fields",async()=>{const api={listNpcs:vi.fn().mockResolvedValue({data:projectNpcsForPlayers(npcs),revision:4}),listFactions:vi.fn().mockResolvedValue({data:projectFactionsForPlayers(factions),revision:4})} as unknown as CastStudioApi;render(<NpcRosterPage campaignId="campaign" authorization={authorization("player")} api={api} onBack={()=>undefined}/>);await screen.findByText("Mira");expect(document.body.textContent).not.toMatch(/SECRET|Hidden Hand/);expect(api.listNpcs).toHaveBeenCalledWith("campaign","player")});
  it("blocks cast writes when NPC and faction revisions disagree",async()=>{const api={listNpcs:vi.fn().mockResolvedValue({data:npcs,revision:4}),listFactions:vi.fn().mockResolvedValue({data:factions,revision:5}),previewNpcs:projectNpcsForPlayers,previewFactions:projectFactionsForPlayers} as unknown as CastStudioApi;render(<NpcRosterPage campaignId="campaign" authorization={authorization()} api={api} onBack={()=>undefined}/>);await screen.findByText(/revisions disagree/);expect(screen.queryByText("Mira")).toBeNull()});
  it("publishes a reconciled cast projection before consuming its receipt",async()=>{const freshNpcs={...npcs,npcs:[{...npcs.npcs[0]!,publicState:{name:"Authoritative Mira"}}],relationships:[{npcId:"npc",subjectActorId:"actor",affinity:1,trust:0,fear:0,updatedAt:at}]};const receipt={idempotencyKey:"relationship",revisionBefore:2,revisionAfter:3,occurredAt:at};const api={listNpcs:vi.fn().mockResolvedValueOnce({data:npcs,revision:2}).mockResolvedValueOnce({data:freshNpcs,revision:3}),listFactions:vi.fn().mockResolvedValueOnce({data:factions,revision:2}).mockResolvedValueOnce({data:factions,revision:3}),relationship:vi.fn().mockResolvedValue({receipt}),previewNpcs:projectNpcsForPlayers,previewFactions:projectFactionsForPlayers} as unknown as CastStudioApi;render(<NpcRosterPage campaignId="campaign" authorization={authorization()} api={api} onBack={()=>undefined}/>);await screen.findAllByText("Mira");fireEvent.change(screen.getByLabelText("NPC"),{target:{value:"npc"}});fireEvent.change(screen.getAllByLabelText("Subject actor ID")[0]!,{target:{value:"actor"}});fireEvent.change(screen.getByLabelText("Affinity delta"),{target:{value:"1"}});fireEvent.change(screen.getByLabelText("Exact reason"),{target:{value:"Trust earned"}});fireEvent.click(screen.getByRole("button",{name:"Apply exact relationship command"}));await screen.findAllByText("Authoritative Mira");expect(screen.getByText("Confirmed command receipt")).toBeTruthy();expect(screen.queryByText(/refresh partial/)).toBeNull()});
  it("binds travel routes to the acting location and preserves unknown locks across reload",async()=>{const travel=vi.fn().mockRejectedValue(new Error("unknown")),api={getWorld:vi.fn().mockResolvedValue({data:world,revision:2}),travel} satisfies WorldExplorerApi;const first=render(<WorldExplorerPage campaignId="campaign" authorization={authorization("player")} api={api} onBack={()=>undefined}/>);await screen.findAllByText("Moon Town");fireEvent.click(screen.getByRole("button",{name:"Plan travel"}));fireEvent.change(screen.getByLabelText("Acting actor"),{target:{value:"actor-two"}});expect((screen.getByLabelText("Eligible route") as HTMLSelectElement).options).toHaveLength(1);fireEvent.change(screen.getByLabelText("Acting actor"),{target:{value:"actor-one"}});fireEvent.change(screen.getByLabelText("Eligible route"),{target:{value:"road"}});fireEvent.click(screen.getByRole("button",{name:"Review"}));expect(screen.getByText(/actor-one/)).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:"Confirm travel"}));await screen.findByText("Command outcome unresolved");first.unmount();resetNarrativeMutationRegistryForTests();render(<WorldExplorerPage campaignId="campaign" authorization={authorization("player")} api={api} onBack={()=>undefined}/>);await screen.findByText("Command outcome unresolved");expect((screen.getByRole("button",{name:"Plan travel"}) as HTMLButtonElement).disabled).toBe(true);expect(travel).toHaveBeenCalledTimes(1)});
  it("persists only receipt-safe mutation metadata across reload",async()=>{const response={locations:[{actorId:"actor-one",locationId:"wood",revision:3,updatedAt:at}],discoveries:[{actorId:"actor-one",locationId:"wood",discoveredAt:at}],privateGmNote:"NEVER STORE",receipt:{idempotencyKey:"travel-receipt",revisionBefore:2,revisionAfter:3,occurredAt:at}};const getWorld=vi.fn().mockResolvedValueOnce({data:world,revision:2}).mockRejectedValueOnce(new Error("partial")).mockResolvedValue({data:world,revision:3}),api={getWorld,travel:vi.fn().mockResolvedValue(response)} satisfies WorldExplorerApi;const first=render(<WorldExplorerPage campaignId="campaign" authorization={authorization("player")} api={api} onBack={()=>undefined}/>);await screen.findAllByText("Moon Town");fireEvent.click(screen.getByRole("button",{name:"Plan travel"}));fireEvent.change(screen.getByLabelText("Acting actor"),{target:{value:"actor-one"}});fireEvent.change(screen.getByLabelText("Eligible route"),{target:{value:"road"}});fireEvent.click(screen.getByRole("button",{name:"Review"}));fireEvent.click(screen.getByRole("button",{name:"Confirm travel"}));await screen.findByText("Confirmed command; refresh partial");const stored=localStorage.getItem("velvet.narrative-mutation.v3:campaign:travel")??"";expect(stored).toContain("travel-receipt");expect(stored).not.toMatch(/locations|discoveries|NEVER STORE|memoryResult|request/);first.unmount();resetNarrativeMutationRegistryForTests();render(<WorldExplorerPage campaignId="campaign" authorization={authorization("player")} api={api} onBack={()=>undefined}/>);await screen.findByText("travel-receipt");expect(screen.queryByText("Exact confirmed server response")).toBeNull();expect(document.body.textContent).not.toContain("NEVER STORE")});
  it("does not retain a typed stale precommit response as ambiguous",async()=>{const problem={type:"https://velvet.local/problems/stale",title:"Stale",status:409,detail:"stale",code:"RPG_WORLD_STALE",requestId:"r",error:"stale"};const api={getWorld:vi.fn().mockResolvedValue({data:world,revision:2}),travel:vi.fn().mockRejectedValue(new ApiError(409,"stale",[],false,problem))} satisfies WorldExplorerApi;render(<WorldExplorerPage campaignId="campaign" authorization={authorization("player")} api={api} onBack={()=>undefined}/>);await screen.findAllByText("Moon Town");fireEvent.click(screen.getByRole("button",{name:"Plan travel"}));fireEvent.change(screen.getByLabelText("Acting actor"),{target:{value:"actor-one"}});fireEvent.change(screen.getByLabelText("Eligible route"),{target:{value:"road"}});fireEvent.click(screen.getByRole("button",{name:"Review"}));fireEvent.click(screen.getByRole("button",{name:"Confirm travel"}));await screen.findByText(/definitely rejected/);expect(screen.queryByText("Command outcome unresolved")).toBeNull()});
  it("renders plot points and exact answer controls in the keyboard graph list",async()=>{const api={get:vi.fn().mockResolvedValue({data:story,revision:2}),preview:projectStoryForPlayers,command:vi.fn()} as unknown as StoryStudioApi;render(<StoryStudioPage campaignId="campaign" authorization={authorization()} api={api} onBack={()=>undefined}/>);await screen.findByText("Who opens it?");expect(screen.getByRole("list",{name:"Secret arc graph nodes"})).toBeTruthy();fireEvent.change(screen.getByLabelText("Exact player answer"),{target:{value:"Tala"}});fireEvent.click(screen.getByRole("button",{name:"Answer plot point"}));await waitFor(()=>expect(api.command).toHaveBeenCalledWith("line",expect.objectContaining({kind:"answer-plot-point",targetId:"point",data:{answer:"Tala"}})))});
  it("publishes reconciled quest and story projections before consuming",async()=>{const receipt={idempotencyKey:"command",revisionBefore:2,revisionAfter:3,occurredAt:at},freshQuests={...quests,quests:[{...quests.quests[0]!,title:"Authoritative quest",status:"abandoned" as const}]};const questApi={list:vi.fn().mockResolvedValueOnce({data:quests,revision:2}).mockResolvedValueOnce({data:freshQuests,revision:3}),preview:projectQuestsForPlayers,command:vi.fn().mockResolvedValue({quest:freshQuests.quests[0],receipt})} as unknown as QuestJournalApi;const questRender=render(<QuestJournalPage campaignId="campaign" authorization={authorization()} api={questApi} onBack={()=>undefined}/>);await screen.findByText("Find dawn");fireEvent.click(screen.getByRole("button",{name:"Abandon"}));await screen.findByText("Authoritative quest");expect(screen.getByText("Confirmed command receipt")).toBeTruthy();questRender.unmount();resetNarrativeMutationRegistryForTests();const freshStory={...story,nodes:[{...story.nodes[0]!,title:"Authoritative Gate",status:"revealed" as const}]},storyApi={get:vi.fn().mockResolvedValueOnce({data:story,revision:2}).mockResolvedValueOnce({data:freshStory,revision:3}),preview:projectStoryForPlayers,command:vi.fn().mockResolvedValue({story:freshStory,receipt})} as unknown as StoryStudioApi;render(<StoryStudioPage campaignId="campaign" authorization={authorization()} api={storyApi} onBack={()=>undefined}/>);await screen.findByText("Revealed Gate");fireEvent.click(screen.getByRole("button",{name:"Reveal node"}));await screen.findByText("Authoritative Gate");expect(screen.getByText("Confirmed command receipt")).toBeTruthy()});
  it("previews the exact rich quest candidate with multiple objectives and rewards",async()=>{const api={list:vi.fn().mockResolvedValue({data:{quests:[],objectives:[],journal:[]},revision:0}),preview:projectQuestsForPlayers,create:vi.fn(),command:vi.fn()} as QuestJournalApi;render(<QuestJournalPage campaignId="campaign" authorization={authorization()} api={api} onBack={()=>undefined}/>);await screen.findByRole("heading",{name:"Create complete quest definition"});fireEvent.change(screen.getByLabelText("Storyline ID"),{target:{value:"line"}});fireEvent.change(screen.getByLabelText("Title"),{target:{value:"Dawn road"}});fireEvent.change(screen.getByLabelText("Exact initial journal entry"),{target:{value:"The road begins."}});fireEvent.change(screen.getAllByLabelText("Description")[1]!,{target:{value:"First objective"}});fireEvent.click(screen.getByRole("button",{name:"Add objective"}));const descriptions=screen.getAllByLabelText("Description");fireEvent.change(descriptions[2]!,{target:{value:"Second objective"}});fireEvent.click(screen.getByRole("button",{name:"Add reward"}));fireEvent.change(screen.getByLabelText("Label"),{target:{value:"Moon coin"}});fireEvent.click(screen.getByRole("button",{name:"Preview exact public projection"}));const preview=screen.getByRole("heading",{name:"Exact player projection preview"}).parentElement!;expect(preview.textContent).toMatch(/First objective|Second objective/);expect(preview.textContent).toContain("Moon coin");expect((screen.getByRole("button",{name:"Create exact previewed quest"}) as HTMLButtonElement).disabled).toBe(false)});
  it("player projection helpers strip quest ancestry and story private structures",()=>{expect(projectQuestsForPlayers(quests).quests[0]).not.toHaveProperty("storylineId");expect(projectStoryForPlayers(story)).toEqual(expect.objectContaining({visibleNodes:[expect.objectContaining({title:"Revealed Gate"})]}));expect(JSON.stringify(projectStoryForPlayers(story))).not.toMatch(/SECRET|plotPoint|edge/)});
});
