import DatabaseDriver from "better-sqlite3";
import path from "node:path";
import { describe,expect,it } from "vitest";
import { CHARACTER_BUILDER_STANDARD_ARRAY,type CharacterBuilderAttributeScores,type PublishContentCatalogInput } from "@velvet/contracts";
import { defaultHarnessSettings,defaultProviderSettings } from "../src/defaults.js";
import { orchestrateAdventureTurn,type AdventureAgentDependencies } from "../src/agent/adventureOrchestrator.js";
import { calculateCatalogDigest,createRepository,MECHANICS_STARTER_CATALOG } from "../src/repo/index.js";
import type { ProviderCompletionResult } from "../src/provider/index.js";
import { narrationFallback } from "../src/routes/rpg/v1/adventureTurns.js";
import { useTmpDataDir } from "./helpers.js";

useTmpDataDir();
const at="2035-01-01T00:00:00.000Z",scores=Object.fromEntries(["might","agility","resolve","insight","presence","craft"].map((name,index)=>[name,CHARACTER_BUILDER_STANDARD_ARRAY[index]]))as CharacterBuilderAttributeScores;
let sequence=0;
function replaceIdentity(value:unknown,packId:string,packVersion:string):void{if(Array.isArray(value)){value.forEach(child=>replaceIdentity(child,packId,packVersion));return;}if(!value||typeof value!=="object")return;const record=value as Record<string,unknown>;if("packId" in record)record.packId=packId;if("packVersion" in record)record.packVersion=packVersion;Object.values(record).forEach(child=>replaceIdentity(child,packId,packVersion));}
function noChoiceCatalog():PublishContentCatalogInput{const catalog=structuredClone(MECHANICS_STARTER_CATALOG)as PublishContentCatalogInput,packId="velvet:no-choice";catalog.idempotencyKey="no-choice-publish";replaceIdentity(catalog,packId,"1.2.0+000000000000");const level=catalog.definitions.find(value=>value.reference.kind==="class-level"&&(value.mechanics as any).level===2)as any;delete level.mechanics.progressionChoices;catalog.manifest.digest="0".repeat(64);const digest=calculateCatalogDigest(catalog);replaceIdentity(catalog,packId,`1.2.0+${digest.slice(0,12)}`);catalog.manifest.digest=digest;return catalog;}
function fixture(catalog:PublishContentCatalogInput=MECHANICS_STARTER_CATALOG as PublishContentCatalogInput){const suffix=++sequence,storyId=`story-${suffix}`,sessionId=`session-${suffix}`,repo=createRepository({clock:{now:()=>new Date(at)}}),campaign=repo.createCampaign("local-owner",{name:"Quest progression"});repo.publishContentCatalog("local-owner",catalog);repo.configureCampaignCatalog("local-owner",campaign.id,{rulesProfileId:catalog.manifest.compatibility.rulesProfileId,contentPacks:[{packId:catalog.manifest.packId,packVersion:catalog.manifest.packVersion}],expectedRevision:0,idempotencyKey:`pins-${++sequence}`});const persona=repo.createCharacter({name:"Aster",age:30,archetype:"Warden",boundaries:"",fictionalConfirmed:true}),draft=repo.createCharacterDraft("local-owner",campaign.id,{personaId:persona.id,controllerPrincipalId:"local-owner",durability:"durable",allocation:{method:"standard-array",scores},idempotencyKey:`draft-${++sequence}`}),definitions=catalog.definitions,selected=repo.updateCharacterDraft("local-owner",draft.draft.id,{expectedRevision:0,idempotencyKey:`select-${++sequence}`,selections:{race:definitions.find(x=>x.reference.kind==="race")!.reference as any,background:definitions.find(x=>x.reference.kind==="background")!.reference as any,class:definitions.find(x=>x.reference.kind==="class")!.reference as any,starterGrant:"kit"}}as any),done=repo.finalizeCharacterDraft("local-owner",draft.draft.id,{expectedRevision:selected.draft.revision,idempotencyKey:`final-${++sequence}`});
  repo.createCampaignStorylineGraph("local-owner",campaign.id,{storyline:{storylineId:storyId,title:"Story",summary:null,nodes:[],edges:[],plotPoints:[],clues:[]},expectedRevision:0,idempotencyKey:`story-${++sequence}`});
  const db=new DatabaseDriver(path.join(process.env.VELVET_DATA_DIR!,"velvet.sqlite"));db.prepare("INSERT INTO sessions(id,character_id,title,state,preset_id,created_at) VALUES(?,?,'Room','active','default',?)").run(sessionId,persona.id,at);db.prepare("INSERT INTO session_characters VALUES(?,?,0)").run(sessionId,persona.id);db.prepare("INSERT INTO campaign_sessions VALUES(?,?,?)").run(sessionId,campaign.id,at);db.close();return{repo,campaign,actorId:done.receipt.actorId,characterId:done.receipt.campaignCharacterId,storyId,sessionId};}
function quest(f:ReturnType<typeof fixture>,id:string,reward=true){const revision=f.repo.listCampaignQuests("local-owner",f.campaign.id)!.revision;f.repo.createCampaignQuest("local-owner",f.campaign.id,{quest:{questId:id,storylineId:f.storyId,title:`Quest ${id}`,description:null,visibility:"public",journalText:"Offered",objectives:[{objectiveId:`${id}-objective`,description:"Finish it",targetProgress:1,dependencyObjectiveIds:[],visibility:"public"}],rewards:reward?[{rewardId:`${id}-reward`,kind:"currency",amount:12,label:"Twelve coins",visibility:"public"}]:[]},expectedRevision:revision,idempotencyKey:`create-${id}`});}
function turn(f:ReturnType<typeof fixture>,declaration:string){return f.repo.createAdventureTurn("local-owner",{campaignId:f.campaign.id,timelineId:f.campaign.activeTimelineId,sessionId:f.sessionId,actorId:f.actorId,declaration,expectedCampaignRevision:1,idempotencyKey:`turn-${++sequence}`});}
const deps=(candidate:{candidateId:string;digest:string},tool:string,extra:Record<string,unknown>={}):AdventureAgentDependencies=>({getProvider:async()=>({...defaultProviderSettings(),model:"fake"}),getHarness:async()=>defaultHarnessSettings(),now:()=>new Date(at),complete:async input=>{expect((input.tools?.find(value=>value.name===tool)?.parameters.oneOf as any[])[0].required).toEqual(["candidateId","digest"]);return{message:{role:"assistant",content:null,toolCalls:[{id:`call-${++sequence}`,name:tool,arguments:JSON.stringify({candidateId:candidate.candidateId,digest:candidate.digest,...extra})}]},usage:null,model:{requestedModel:"fake",responseModel:"fake"}}satisfies ProviderCompletionResult;}});
async function approve(f:ReturnType<typeof fixture>,created:ReturnType<typeof turn>,candidate:{candidateId:string;digest:string},tool:string){const pending=await orchestrateAdventureTurn(f.repo,created.turnId,deps(candidate,tool));expect(pending.outcome,JSON.stringify(pending.turn)).toBe("awaiting-confirmation");const proposal=pending.turn.toolCalls[0]!.proposal;f.repo.decideToolProposals("local-owner",{turnId:created.turnId,proposalIds:[proposal.proposalId],decision:"approved",expectedTurnRevision:pending.turn.revision,expectedCampaignRevision:1,idempotencyKey:`approve-${++sequence}`});return orchestrateAdventureTurn(f.repo,created.turnId,{...deps(candidate,tool),complete:async()=>{throw new Error("must not redispatch");}});}

describe("exact quest lifecycle and progression adventure candidates",()=>{
  it("accepts, abandons, claims the exact actor reward, redacts receipts, narrates facts, and replays after restart",async()=>{const f=fixture();quest(f,"main");quest(f,"spare",false);const acceptTurn=turn(f,"accept main"),accept=f.repo.generateAdventureQuestLifecycleCandidates("local-owner",acceptTurn.turnId).find(value=>value.action==="accept"&&value.questTitle==="Quest main")!;expect(JSON.stringify(accept)).not.toMatch(/questId|rewardId|actorId|revision/);const accepted=await approve(f,acceptTurn,accept,"exact_quest_lifecycle.select"),acceptCommand=accepted.turn.receiptLinks[0]!.commandId,acceptReceipt=f.repo.getAdventureQuestLifecyclePublicReceipt("local-owner",f.campaign.id,acceptCommand)!;expect(acceptReceipt).toMatchObject({action:"accept",questTitle:"Quest main",statusBefore:"offered",statusAfter:"active",reward:null});expect(narrationFallback("invent",[{kind:"quest-lifecycle",...acceptReceipt}])).toContain("Quest accepted: Quest main");
    const revision=f.repo.listCampaignQuests("local-owner",f.campaign.id)!.revision;f.repo.executeQuestCommand("local-owner","main",{kind:"advance-objective",objectiveId:"main-objective",expectedRevision:revision,idempotencyKey:"complete-main"});const rewardTurn=turn(f,"claim reward"),reward=f.repo.generateAdventureQuestLifecycleCandidates("local-owner",rewardTurn.turnId).find(value=>value.action==="claim-reward")!;expect(reward.reward).toEqual({label:"Twelve coins",kind:"Currency",amount:12,recipient:"Aster"});const claimed=await approve(f,rewardTurn,reward,"exact_quest_lifecycle.select"),rewardReceipt=f.repo.getAdventureQuestLifecyclePublicReceipt("local-owner",f.campaign.id,claimed.turn.receiptLinks[0]!.commandId)!;expect(rewardReceipt.reward).toEqual(reward.reward);expect(JSON.stringify(rewardReceipt)).not.toMatch(/questId|rewardId|actorId|candidateId|digest|commandId/);
    const abandonTurn=turn(f,"abandon spare"),abandon=f.repo.generateAdventureQuestLifecycleCandidates("local-owner",abandonTurn.turnId).find(value=>value.action==="abandon"&&value.questTitle==="Quest spare")!,waiting=await orchestrateAdventureTurn(f.repo,abandonTurn.turnId,deps(abandon,"exact_quest_lifecycle.select")),proposal=waiting.turn.toolCalls[0]!.proposal;f.repo.decideToolProposals("local-owner",{turnId:abandonTurn.turnId,proposalIds:[proposal.proposalId],decision:"rejected",expectedTurnRevision:waiting.turn.revision,expectedCampaignRevision:1,idempotencyKey:"reject-abandon"});expect((await orchestrateAdventureTurn(f.repo,abandonTurn.turnId,{...deps(abandon,"exact_quest_lifecycle.select"),complete:async()=>{throw new Error("must not redispatch");}})).turn.receiptLinks).toEqual([]);f.repo.close();const reopened=createRepository({clock:{now:()=>new Date(at)}}),replayed=await orchestrateAdventureTurn(reopened,rewardTurn.turnId,{...deps(reward,"exact_quest_lifecycle.select"),complete:async()=>{throw new Error("must not redispatch");}});expect(replayed.turn.receiptLinks[0]!.commandId).toBe(claimed.turn.receiptLinks[0]!.commandId);reopened.close();});
  it("applies only a complete authoritative preview and abstains when player choices remain",async()=>{const f=fixture(noChoiceCatalog());f.repo.grantCharacterXp("local-owner",f.characterId,{amount:300,reason:"Journey",expectedRevision:0,idempotencyKey:"xp-300"});const created=turn(f,"level up"),read=f.repo.getAdventureProgressionRead("local-owner",created.turnId),candidate=f.repo.generateAdventureProgressionCandidates("local-owner",created.turnId)[0]!;expect(read).toMatchObject({available:true,currentLevel:1,eligibleLevel:2,pendingChoices:[]});expect(JSON.stringify({read,candidate})).not.toMatch(/campaignCharacterId|actorId|classRef|packId|definitionId|previewToken|revision/);const tampered=await orchestrateAdventureTurn(f.repo,created.turnId,deps(candidate,"exact_progression_apply.select",{levelAfter:20}));expect(tampered.turn.receiptLinks).toEqual([]);
    const staleTurn=turn(f,"stale level"),staleCandidate=f.repo.generateAdventureProgressionCandidates("local-owner",staleTurn.turnId)[0]!,waiting=await orchestrateAdventureTurn(f.repo,staleTurn.turnId,deps(staleCandidate,"exact_progression_apply.select")),proposal=waiting.turn.toolCalls[0]!.proposal;f.repo.grantCharacterXp("local-owner",f.characterId,{amount:1,reason:"Late award",expectedRevision:1,idempotencyKey:"late-xp"});f.repo.decideToolProposals("local-owner",{turnId:staleTurn.turnId,proposalIds:[proposal.proposalId],decision:"approved",expectedTurnRevision:waiting.turn.revision,expectedCampaignRevision:1,idempotencyKey:"approve-stale"});const stale=await orchestrateAdventureTurn(f.repo,staleTurn.turnId,{...deps(staleCandidate,"exact_progression_apply.select"),complete:async()=>{throw new Error("must not redispatch");}});expect(stale.turn.receiptLinks).toEqual([]);expect(stale.turn.toolCalls[0]!.status).toBe("cancelled");
    const exactTurn=turn(f,"apply exact level"),exact=f.repo.generateAdventureProgressionCandidates("local-owner",exactTurn.turnId)[0]!,completed=await approve(f,exactTurn,exact,"exact_progression_apply.select"),receipt=f.repo.getAdventureProgressionPublicReceipt("local-owner",f.campaign.id,completed.turn.receiptLinks[0]!.commandId)!;expect(receipt).toMatchObject({levelBefore:1,levelAfter:2});expect(JSON.stringify(receipt)).not.toMatch(/campaignCharacterId|actorId|previewToken|candidate|digest|commandId/);expect(narrationFallback("invent",[{kind:"progression",...receipt}])).toContain("advances from level 1 to level 2");f.repo.close();const choice=fixture();choice.repo.grantCharacterXp("local-owner",choice.characterId,{amount:300,reason:"Journey",expectedRevision:0,idempotencyKey:"choice-xp"});const choiceTurn=turn(choice,"pick for me"),choiceRead=choice.repo.getAdventureProgressionRead("local-owner",choiceTurn.turnId);expect(choiceRead.pendingChoices[0]!.options.length).toBeGreaterThan(1);expect(choice.repo.generateAdventureProgressionCandidates("local-owner",choiceTurn.turnId)).toEqual([]);choice.repo.close();});
});
