import DatabaseDriver from "better-sqlite3";
import path from "node:path";
import {describe,expect,it} from "vitest";
import {createRepository} from "../src/repo/index.js";
import {EXACT_CANDIDATE_EXECUTION_V47_LAYOUT_DIGEST,EXACT_CANDIDATE_EXECUTION_V47_MANAGED_OBJECTS,assertExactCandidateExecutionsLayoutV47} from "../src/repo/db/migrations/v47_exact_candidate_executions.js";
import {buildCanonicalPopulatedV45CompanionFixture} from "./fixtures/migrations/support-window.js";
import {migrate45to46} from "../src/repo/db/migrations/v46_exact_candidates.js";
import {migrate46to47} from "../src/repo/db/migrations/v47_exact_candidate_executions.js";
import {migrate47to48} from "../src/repo/db/migrations/v48_exact_candidate_provider_bridge.js";
import {EXACT_CANDIDATE_PROVIDER_V48_MANAGED_OBJECTS} from "../src/repo/db/migrations/v48_exact_candidate_provider_bridge.js";
import {useTmpDataDir} from "./helpers.js";

useTmpDataDir();
const file=()=>path.join(process.env.VELVET_DATA_DIR!,"velvet.sqlite");
const marker=()=>{const db=new DatabaseDriver(file(),{readonly:true});const row=db.prepare("SELECT value FROM meta WHERE key='schemaVersion'").get() as {value:string};db.close();return row.value;};
function rewindToV46(){createRepository().close();const db=new DatabaseDriver(file());db.pragma("foreign_keys=OFF");
  for(const managed of [EXACT_CANDIDATE_PROVIDER_V48_MANAGED_OBJECTS,EXACT_CANDIDATE_EXECUTION_V47_MANAGED_OBJECTS]){
    for(const [type,name] of [...managed].reverse()){if(type==="trigger")db.exec(`DROP TRIGGER "${name}"`);if(type==="index")db.exec(`DROP INDEX "${name}"`);}
    for(const [,name] of [...managed].filter(([type])=>type==="table").reverse())db.exec(`DROP TABLE "${name}"`);
  }
  db.prepare("UPDATE meta SET value='46' WHERE key='schemaVersion'").run();db.close();}
const snapshotV46=(db:DatabaseDriver.Database)=>Object.fromEntries((db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name GLOB '*v46*' ORDER BY name").all() as Array<{name:string}>).map(({name})=>[name,db.prepare(`SELECT * FROM ${name} ORDER BY rowid`).all()]));
function populateCandidate(execute=false){const fixture=buildCanonicalPopulatedV45CompanionFixture();const promote=new DatabaseDriver(file());migrate45to46(promote);migrate46to47(promote);migrate47to48(promote);promote.close();let n=0;const repository=createRepository({clock:{now:()=>new Date("2035-01-01T00:00:00.000Z")},ids:{nextId:()=>`migration-v47-${++n}`}});const db=new DatabaseDriver(file());const campaign=db.prepare("SELECT active_timeline_id id,administration_revision revision FROM campaigns WHERE id=?").get(fixture.campaignId) as {id:string;revision:number};const persona=(db.prepare("SELECT character.character_id FROM campaign_actors actor JOIN campaign_characters character ON character.campaign_id=actor.campaign_id AND character.id=actor.campaign_character_id WHERE actor.campaign_id=? AND actor.id=?").get(fixture.campaignId,fixture.actorId) as {character_id:string}).character_id;
  db.prepare("INSERT OR IGNORE INTO session_characters VALUES(?,?,0)").run(fixture.sessionId,persona);db.prepare("INSERT INTO campaign_locations_v28 VALUES('migration-origin',?,NULL,'Origin','','public',?)").run(fixture.campaignId,"2035-01-01T00:00:00.000Z");db.prepare("INSERT INTO campaign_locations_v28 VALUES('migration-destination',?,NULL,'Destination','','public',?)").run(fixture.campaignId,"2035-01-01T00:00:00.000Z");db.prepare("INSERT INTO campaign_location_connections_v28 VALUES('migration-road',?,'migration-origin','migration-destination','public','open','none',NULL,NULL,?)").run(fixture.campaignId,"2035-01-01T00:00:00.000Z");db.prepare("INSERT INTO campaign_actor_locations_v28 VALUES(?,?, 'migration-origin',?,0,?)").run(fixture.campaignId,fixture.actorId,fixture.sessionId,"2035-01-01T00:00:00.000Z");db.close();const turn=repository.createAdventureTurn("local-owner",{campaignId:fixture.campaignId,timelineId:campaign.id,sessionId:fixture.sessionId,actorId:fixture.actorId,declaration:"travel",expectedCampaignRevision:campaign.revision,idempotencyKey:"migration-turn"});const batch=repository.generateActorTravelCandidates("local-owner",{turnId:turn.turnId,idempotencyKey:"migration-candidates"});expect(batch.candidates).toHaveLength(1);const selection={candidateId:batch.candidates[0]!.candidateId,kind:"actor.travel" as const,version:"v1" as const,choices:[] as []};if(execute)repository.executeExactActorTravelCandidate("local-owner",{turnId:turn.turnId,selection});repository.close();return{batch,selection};}

describe("historical schema v47 exact candidate execution migration",()=>{
  it("migrates v46 with empty backfill, static attestation, and global foreign keys",()=>{rewindToV46();createRepository().close();const db=new DatabaseDriver(file());assertExactCandidateExecutionsLayoutV47(db);expect(marker()).toBe("48");expect(db.prepare("SELECT count(*) count FROM exact_candidate_executions_v47").get()).toEqual({count:0});expect(db.prepare("SELECT layout_digest FROM exact_candidate_execution_layout_attestation_v47").get()).toEqual({layout_digest:EXACT_CANDIDATE_EXECUTION_V47_LAYOUT_DIGEST});expect(db.pragma("foreign_key_check")).toEqual([]);db.close();});
  it("preserves every populated v46 table byte-for-byte with empty execution backfill",()=>{populateCandidate();rewindToV46();let db=new DatabaseDriver(file());const before=snapshotV46(db);expect((before.exact_candidate_batches_v46 as unknown[]).length).toBeGreaterThan(0);expect((before.exact_candidates_v46 as unknown[]).length).toBeGreaterThan(0);db.close();createRepository().close();db=new DatabaseDriver(file());expect(snapshotV46(db)).toEqual(before);expect(db.prepare("SELECT count(*) count FROM exact_candidate_executions_v47").get()).toEqual({count:0});expect(db.pragma("foreign_key_check")).toEqual([]);db.close();});
  it("rolls marker failure back completely and retries",()=>{rewindToV46();let db=new DatabaseDriver(file());db.exec("CREATE TRIGGER reject_schema_marker BEFORE UPDATE OF value ON meta WHEN NEW.value='47' BEGIN SELECT RAISE(ABORT,'reject v47 marker');END");db.close();expect(()=>createRepository()).toThrow("reject v47 marker");db=new DatabaseDriver(file());expect(marker()).toBe("46");expect(db.prepare("SELECT name FROM sqlite_master WHERE name GLOB '*v47*'").all()).toEqual([]);db.exec("DROP TRIGGER reject_schema_marker");db.close();createRepository().close();expect(marker()).toBe("48");});
  it("cleans only an exact empty future shell and rejects malformed shell",()=>{rewindToV46();createRepository().close();let db=new DatabaseDriver(file());db.prepare("UPDATE meta SET value='46' WHERE key='schemaVersion'").run();db.close();createRepository().close();expect(marker()).toBe("48");db=new DatabaseDriver(file());db.exec("DROP TRIGGER exact_candidate_executions_v47_immutable_delete_v47");db.prepare("UPDATE meta SET value='46' WHERE key='schemaVersion'").run();db.close();expect(()=>createRepository()).toThrow("malformed future v47 artifacts");});
  it("rejects and preserves a populated canonical future v47 shell",()=>{populateCandidate(true);let db=new DatabaseDriver(file());const beforeRows=db.prepare("SELECT * FROM exact_candidate_executions_v47 ORDER BY execution_id").all();const beforeSchema=db.prepare("SELECT type,name,tbl_name,sql FROM sqlite_master WHERE name GLOB '*v47*' OR tbl_name='exact_candidate_executions_v47' ORDER BY type,name").all();expect(beforeRows).toHaveLength(1);db.prepare("UPDATE meta SET value='46' WHERE key='schemaVersion'").run();db.close();expect(()=>createRepository()).toThrow("populated future v47 artifact exact_candidate_executions_v47");db=new DatabaseDriver(file(),{readonly:true});expect(db.prepare("SELECT value FROM meta WHERE key='schemaVersion'").get()).toEqual({value:"46"});expect(db.prepare("SELECT * FROM exact_candidate_executions_v47 ORDER BY execution_id").all()).toEqual(beforeRows);expect(db.prepare("SELECT type,name,tbl_name,sql FROM sqlite_master WHERE name GLOB '*v47*' OR tbl_name='exact_candidate_executions_v47' ORDER BY type,name").all()).toEqual(beforeSchema);db.close();});
});
