import DatabaseDriver from "better-sqlite3";
import Fastify from "fastify";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { buildApp } from "../src/app.js";
import { campaignContentGenerationHttpRoutes } from "../src/routes/rpg/v1/campaignContentGeneration.js";
import { createRepository, updateProviderSettings } from "../src/repo/index.js";
import { createSession, transitionSession } from "../src/repo/sessionRepo.js";
import { useTmpDataDir } from "./helpers.js";

useTmpDataDir();
afterEach(()=>{delete process.env.FEATURE_RPG_CAMPAIGN;delete process.env.FEATURE_RPG_MECHANICS;delete process.env.FEATURE_RPG_COMBAT;});
const enable=()=>{process.env.FEATURE_RPG_CAMPAIGN="true";process.env.FEATURE_RPG_MECHANICS="true";process.env.FEATURE_RPG_COMBAT="true";};
const content={
  outlines:[{key:"rainy-opening",opening:"Rain falls on the old road.",premise:"A courier is missing.",startLocationKey:"old-road",visibility:"public" as const}],
  locations:[{key:"old-road",name:"Old Road",description:"A wet road.",visibility:"public" as const,discoveries:["Tracks"],hazards:[],hooks:[],factionKeys:[]}],
  npcs:[{key:"mara",name:"Mara",archetype:"Guide",description:"A wary guide.",visibility:"public" as const,locationKey:"old-road",factionKeys:[]}],
};
const request=(campaignId:string,idempotencyKey="content-draft")=>({campaignId,brief:"A rainy opening",tone:"Mysterious",exclusions:[],sections:["outline","locations","npcs"],expandArtifactKeys:[],revisionFeedback:null,idempotencyKey});
const db=()=>new DatabaseDriver(path.join(process.env.VELVET_DATA_DIR!,"velvet.sqlite"));

describe("campaign-content section generation",()=>{
  it("stages a public-safe sparse preview, applies only selected artifacts, and reads immediately",async()=>{
    enable();const repo=createRepository(),campaign=repo.createCampaign("local-owner",{name:"Content"}),generate=vi.fn().mockResolvedValue(content),app=buildApp({campaignRepositoryFactory:()=>repo,campaignContentGeneration:generate});
    const created=await app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:request(campaign.id)});expect(created.statusCode,created.body).toBe(201);expect(created.body).not.toMatch(/privateGoals|gmNotes|local-owner/);
    const id=created.json().draft.draftId,selected=["rainy-opening","old-road","mara"],payload={expectedRevision:0,idempotencyKey:"content-apply",selectedArtifactKeys:selected};
    const applied=await app.inject({method:"POST",url:`/api/rpg/v1/campaign-content-drafts/${id}/apply`,headers:{"content-type":"application/json"},payload});expect(applied.statusCode,applied.body).toBe(200);
    const replay=await app.inject({method:"POST",url:`/api/rpg/v1/campaign-content-drafts/${id}/apply`,headers:{"content-type":"application/json"},payload});expect(replay.json()).toEqual(applied.json());expect(generate).toHaveBeenCalledTimes(1);
    const foundation=await app.inject({method:"GET",url:`/api/rpg/v1/campaigns/${campaign.id}/generated-foundation`});expect(foundation.json().opening).toMatchObject({premise:"A courier is missing.",startLocationKey:"old-road",sourceDraftId:id});
    const database=db();expect(database.prepare("SELECT state FROM generated_npc_placement_intents_v52 WHERE campaign_id=?").get(campaign.id)).toEqual({state:"pending"});expect((database.prepare("SELECT count(*) count FROM campaign_generation_accepted_artifacts_v52 WHERE campaign_id=?").get(campaign.id) as any).count).toBe(3);database.close();await app.close();
  });

  it("coalesces concurrent exact requests without a duplicate provider call",async()=>{
    enable();const repo=createRepository(),campaign=repo.createCampaign("local-owner",{name:"Concurrent"});let release!:(value:unknown)=>void;const generate=vi.fn(()=>new Promise((resolve)=>{release=resolve;}));const app=buildApp({campaignRepositoryFactory:()=>repo,campaignContentGeneration:generate});
    const first=app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:request(campaign.id,"same-key")});while(generate.mock.calls.length===0)await new Promise((resolve)=>setTimeout(resolve,5));
    const second=app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:request(campaign.id,"same-key")});release(content);const [a,b]=await Promise.all([first,second]);expect(a.statusCode).toBe(201);expect(b.statusCode).toBe(201);expect(b.json().draft.draftId).toBe(a.json().draft.draftId);expect(generate).toHaveBeenCalledTimes(1);await app.close();
  });

  it("materializes arcs and quests through standard reads and rejects stale expansion dependencies",async()=>{
    enable();const repo=createRepository(),campaign=repo.createCampaign("local-owner",{name:"Expansion"});const arcQuest={arcs:[{key:"courier-arc",title:"The Lost Courier",summary:"Find the courier.",visibility:"public" as const}],quests:[{key:"follow-tracks",title:"Follow the tracks",description:"Search the flooded road.",visibility:"public" as const,arcKey:"courier-arc",locationKeys:[]}]},faction={factions:[{key:"road-wardens",name:"Road Wardens",description:"They patrol the road.",visibility:"public" as const}]};const generate=vi.fn().mockResolvedValueOnce(content).mockResolvedValueOnce(faction).mockResolvedValueOnce(arcQuest);const app=buildApp({campaignRepositoryFactory:()=>repo,campaignContentGeneration:generate});
    const foundation=await app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:request(campaign.id,"base")}),foundationId=foundation.json().draft.draftId;await app.inject({method:"POST",url:`/api/rpg/v1/campaign-content-drafts/${foundationId}/apply`,headers:{"content-type":"application/json"},payload:{expectedRevision:0,idempotencyKey:"base-apply",selectedArtifactKeys:["rainy-opening","old-road","mara"]}});
    const expansion=await app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:{...request(campaign.id,"dependency"),sections:["factions"],expandArtifactKeys:["old-road"]}});expect(expansion.statusCode,expansion.body).toBe(201);
    const quests=await app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:{...request(campaign.id,"quests"),sections:["arcs","quests"]}}),questId=quests.json().draft.draftId;const questApply=await app.inject({method:"POST",url:`/api/rpg/v1/campaign-content-drafts/${questId}/apply`,headers:{"content-type":"application/json"},payload:{expectedRevision:0,idempotencyKey:"quest-apply",selectedArtifactKeys:["courier-arc","follow-tracks"]}});expect(questApply.statusCode,questApply.body).toBe(200);expect(repo.listCampaignQuests("local-owner",campaign.id)?.quests.map((quest)=>quest.title)).toContain("Follow the tracks");
    const stale=await app.inject({method:"POST",url:`/api/rpg/v1/campaign-content-drafts/${expansion.json().draft.draftId}/apply`,headers:{"content-type":"application/json"},payload:{expectedRevision:0,idempotencyKey:"stale-apply",selectedArtifactKeys:["road-wardens"]}});expect(stale.statusCode).toBe(409);await app.close();
  });

  it("requires explicit acknowledgement to retry a failed provider attempt and records exact attempts",async()=>{
    enable();const repo=createRepository(),campaign=repo.createCampaign("local-owner",{name:"Retry"}),generate=vi.fn().mockRejectedValueOnce(new Error("provider down")).mockResolvedValueOnce(content),app=buildApp({campaignRepositoryFactory:()=>repo,campaignContentGeneration:generate});
    const first=await app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:request(campaign.id,"retry-key")});expect(first.statusCode).toBe(503);
    const silent=await app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:request(campaign.id,"retry-key")});expect(silent.statusCode).toBe(409);expect(generate).toHaveBeenCalledTimes(1);
    const retry=await app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:{...request(campaign.id,"retry-key"),retryFailedAttempt:{failedAttempt:1}}});expect(retry.statusCode,retry.body).toBe(201);expect(generate).toHaveBeenCalledTimes(2);
    const database=db(),attempts=database.prepare("SELECT attempt,retry_count,outcome_code,terminal_at FROM campaign_generation_attempts_v52 ORDER BY attempt").all() as any[];expect(attempts.map(({attempt,retry_count,outcome_code})=>({attempt,retry_count,outcome_code}))).toEqual([{attempt:1,retry_count:0,outcome_code:"generation-failed"},{attempt:2,retry_count:1,outcome_code:"ok"}]);expect(attempts.every((row)=>row.terminal_at)).toBe(true);database.close();await app.close();
  });

  it("records requested and response models, usage, latency, IDs, retries, and configured estimated cost",async()=>{
    enable();const repo=createRepository(),campaign=repo.createCampaign("local-owner",{name:"Metrics"});await updateProviderSettings({model:"requested-model",pricing:{promptPerMillion:2,completionPerMillion:4}});const app=buildApp({campaignRepositoryFactory:()=>repo,campaignContentGeneration:async()=>({content,responseModel:"provider-model",usage:{promptTokens:100,completionTokens:50,totalTokens:150}})});const response=await app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:request(campaign.id,"metrics")});expect(response.statusCode,response.body).toBe(201);
    const database=db(),row=database.prepare(`SELECT job.job_id,job.attempt_count,attempt.provider,attempt.requested_model,attempt.response_model,
      attempt.prompt_tokens,attempt.completion_tokens,attempt.total_tokens,attempt.latency_ms,attempt.estimated_cost_usd,
      attempt.prompt_version,attempt.schema_version,attempt.terminal_at FROM campaign_generation_jobs_v52 job JOIN campaign_generation_attempts_v52 attempt ON attempt.job_id=job.job_id`).get() as any;expect(row).toMatchObject({attempt_count:1,requested_model:"requested-model",response_model:"provider-model",prompt_tokens:100,completion_tokens:50,total_tokens:150,prompt_version:"campaign-content-v3",schema_version:"campaign-content-v3"});expect(row.job_id).toMatch(/^campaign-generation-/);expect(row.latency_ms).toBeGreaterThanOrEqual(0);expect(row.estimated_cost_usd).toBeCloseTo(0.0004);expect(row.terminal_at).toBeTruthy();database.close();await app.close();
  });

  it("reconciles a pending NPC placement when one running attached session becomes available",async()=>{
    enable();const repo=createRepository(),campaign=repo.createCampaign("local-owner",{name:"Placement"}),app=buildApp({campaignRepositoryFactory:()=>repo,campaignContentGeneration:async()=>content});const created=await app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:request(campaign.id,"placement")});const id=created.json().draft.draftId;
    await app.inject({method:"POST",url:`/api/rpg/v1/campaign-content-drafts/${id}/apply`,headers:{"content-type":"application/json"},payload:{expectedRevision:0,idempotencyKey:"place-apply",selectedArtifactKeys:["rainy-opening","old-road","mara"]}});
    const persona=repo.createCharacter({name:"Player",age:30,archetype:"Warden",boundaries:"",fictionalConfirmed:true}),session=await createSession({characterId:persona.id,title:"Live"});await transitionSession(session.id,"active","test");repo.attachCampaignSession("local-owner",{campaignId:campaign.id,sessionId:session.id} as any);
    const database=db(),placement=database.prepare("SELECT state,session_id FROM generated_npc_placement_intents_v52 WHERE campaign_id=?").get(campaign.id);expect(placement).toEqual({state:"placed",session_id:session.id});expect(database.prepare("SELECT location_id FROM campaign_npc_presence_v43 WHERE campaign_id=? AND session_id=? AND state='present'").get(campaign.id,session.id)).toBeTruthy();database.close();await app.close();
  });

  it("materializes story graphs, keeps encounter concepts inert, and explicitly publishes only public materials",async()=>{
    enable();const repo=createRepository(),campaign=repo.createCampaign("local-owner",{name:"Materialized"}),principalDb=db();principalDb.prepare("INSERT INTO principals(id,display_name,is_local) VALUES('reader','Reader',0)").run();principalDb.close();repo.addCampaignMembership("local-owner",campaign.id,{principalId:"reader",role:"player"});
    const expanded={arcs:[{key:"mystery-arc",title:"Bell Mystery",summary:"Trace the silent bell.",visibility:"public" as const}],storyNodes:[{key:"bell-found",title:"The Bell",description:"A cracked bell is found.",visibility:"public" as const},{key:"tower-open",title:"The Tower",description:"The tower opens.",visibility:"gm" as const}],storyRelationships:[{key:"bell-before-tower",fromStoryNodeKey:"bell-found",toStoryNodeKey:"tower-open",description:"The bell points to the tower.",visibility:"gm" as const}],clues:[{key:"bell-mark",title:"Maker's mark",description:"A silver maker's mark.",visibility:"public" as const,revealsStoryNodeKey:"bell-found"}],encounters:[{key:"tower-watch",title:"Tower Watch",description:"Guards watch the sealed door.",visibility:"gm" as const,participantNpcKeys:[]}],handouts:[{key:"bell-rubbing",title:"Bell rubbing",content:"Three moons around a tower.",visibility:"public" as const},{key:"gm-cipher",title:"Cipher key",content:"SECRET KEY",visibility:"gm" as const}],scenePrompts:[{key:"tower-wind",title:"Tower wind",prompt:"Cold wind moves through the stones.",visibility:"public" as const,npcKeys:[]}]};
    const app=buildApp({campaignRepositoryFactory:()=>repo,campaignContentGeneration:async()=>expanded});const created=await app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:{...request(campaign.id,"expanded"),sections:["arcs","story","clues","encounters","handouts","scene-prompts"]}});expect(created.statusCode,created.body).toBe(201);const draftId=created.json().draft.draftId,keys=["mystery-arc","bell-found","tower-open","bell-before-tower","bell-mark","tower-watch","bell-rubbing","gm-cipher","tower-wind"];
    const applied=await app.inject({method:"POST",url:`/api/rpg/v1/campaign-content-drafts/${draftId}/apply`,headers:{"content-type":"application/json"},payload:{expectedRevision:0,idempotencyKey:"expanded-apply",selectedArtifactKeys:keys}});expect(applied.statusCode,applied.body).toBe(200);
    const storyRead=await app.inject({method:"GET",url:`/api/rpg/v1/campaigns/${campaign.id}/story`}),story=storyRead.json();expect(storyRead.statusCode,storyRead.body).toBe(200);expect(story.nodes.map((node:any)=>node.title)).toEqual(expect.arrayContaining(["The Bell","The Tower"]));expect(story.edges).toHaveLength(1);expect(story.clues).toHaveLength(1);
    const planning=await app.inject({method:"GET",url:`/api/rpg/v1/campaigns/${campaign.id}/generated-planning`});expect(planning.statusCode,planning.body).toBe(200);expect(planning.json().encounters).toEqual([expect.objectContaining({title:"Tower Watch"})]);expect(planning.json().deliverables.every((item:any)=>item.publishedAt===null)).toBe(true);
    const database=db();expect((database.prepare("SELECT count(*) count FROM encounter_lifecycle_v31 WHERE campaign_id=?").get(campaign.id) as any).count).toBe(0);const accepted=database.prepare("SELECT artifact_kind,server_resource_id FROM campaign_generation_accepted_artifacts_v52 WHERE campaign_id=? AND artifact_kind IN ('story-node','story-relationship','clue','encounter','handout','scene-prompt')").all(campaign.id) as any[];expect(accepted.every((row)=>row.server_resource_id)).toBe(true);database.close();
    expect(repo.getCampaignPublishedMaterials("reader",campaign.id)?.materials).toEqual([]);const publish={artifactKey:"bell-rubbing",expectedRevision:0,idempotencyKey:"publish-bell"},first=await app.inject({method:"POST",url:`/api/rpg/v1/campaigns/${campaign.id}/material-publications`,headers:{"content-type":"application/json"},payload:publish}),replay=await app.inject({method:"POST",url:`/api/rpg/v1/campaigns/${campaign.id}/material-publications`,headers:{"content-type":"application/json"},payload:publish});expect(first.statusCode,first.body).toBe(200);expect(replay.json()).toEqual(first.json());const player=repo.getCampaignPublishedMaterials("reader",campaign.id)!;expect(player.materials.map((item)=>item.title)).toEqual(["Bell rubbing"]);expect(JSON.stringify(player)).not.toMatch(/SECRET KEY|Cipher key/);
    const privatePublish=await app.inject({method:"POST",url:`/api/rpg/v1/campaigns/${campaign.id}/material-publications`,headers:{"content-type":"application/json"},payload:{artifactKey:"gm-cipher",expectedRevision:1,idempotencyKey:"publish-secret"}});expect(privatePublish.statusCode).toBe(404);await app.close();
  });

  it("treats a mismatched post-publication projection as commit-ambiguous",async()=>{
    enable();let committed=false;const app=Fastify({logger:false});await app.register(campaignContentGenerationHttpRoutes,{prefix:"/api/rpg/v1",generationDraftRepositoryAccessor:()=>({publishCampaignMaterial:()=>{committed=true;return {material:{artifactKey:"other-handout",resourceId:"material",kind:"handout",title:"Other",content:"Other content",publishedAt:"2035-01-01T00:00:00.000Z"},receipt:{idempotencyKey:"publish",revisionBefore:0,revisionAfter:1,occurredAt:"2035-01-01T00:00:00.000Z"}};}} as any)});
    const response=await app.inject({method:"POST",url:"/api/rpg/v1/campaigns/campaign/material-publications",headers:{"content-type":"application/json"},payload:{artifactKey:"public-handout",expectedRevision:0,idempotencyKey:"publish"}});
    expect(committed).toBe(true);expect(response.statusCode).toBe(503);expect(response.json()).toMatchObject({code:"RPG_GENERATION_UNAVAILABLE",detail:expect.stringContaining("could not be confirmed")});expect(response.body).toContain("do not automatically retry");await app.close();
  });

  it("treats a malformed post-apply projection as commit-ambiguous",async()=>{
    enable();const repo=createRepository(),campaign=repo.createCampaign("local-owner",{name:"Apply ambiguity"});let malform=false;const proxy=new Proxy(repo as any,{get(target,key){const value=target[key];if(key==="applyCampaignContentGenerationDraftAtomically")return (...args:any[])=>{const result=value.apply(target,args);return malform?{...result,draftId:"other-draft",applyReceipt:{...result.applyReceipt,draftId:"other-draft"}}:result;};return typeof value==="function"?value.bind(target):value;}});const app=buildApp({campaignRepositoryFactory:()=>proxy,campaignContentGeneration:async()=>content});
    const created=await app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:request(campaign.id,"apply-ambiguous")});malform=true;const response=await app.inject({method:"POST",url:`/api/rpg/v1/campaign-content-drafts/${created.json().draft.draftId}/apply`,headers:{"content-type":"application/json"},payload:{expectedRevision:0,idempotencyKey:"apply-ambiguous-write",selectedArtifactKeys:["rainy-opening","old-road","mara"]}});
    expect(response.statusCode).toBe(503);expect(response.json()).toMatchObject({code:"RPG_GENERATION_UNAVAILABLE",detail:expect.stringContaining("could not be confirmed")});expect(repo.getCampaignGeneratedFoundation("local-owner",campaign.id)?.opening).not.toBeNull();expect(response.body).toContain("do not automatically retry");await app.close();
  });

  it("rejects a generated read bound to another campaign",async()=>{
    enable();const app=Fastify({logger:false});await app.register(campaignContentGenerationHttpRoutes,{prefix:"/api/rpg/v1",generationDraftRepositoryAccessor:()=>({getCampaignGeneratedFoundation:()=>({campaignId:"other-campaign",revision:0,opening:null})} as any)});
    const response=await app.inject({method:"GET",url:"/api/rpg/v1/campaigns/campaign/generated-foundation"});expect(response.statusCode).toBe(500);expect(response.body).not.toContain("other-campaign");await app.close();
  });

  it("does not log provider-controlled generation error text",async()=>{
    enable();const messages:string[]=[];const stream={write:(message:string)=>{messages.push(message);}};const repo=createRepository(),campaign=repo.createCampaign("local-owner",{name:"Log redaction"});const app=Fastify({logger:{level:"error",stream} as any});await app.register(campaignContentGenerationHttpRoutes,{prefix:"/api/rpg/v1",generationDraftRepositoryAccessor:()=>repo,generateCampaignContent:async()=>{throw new Error("PRIVATE_PROVIDER_ECHO");}});
    const response=await app.inject({method:"POST",url:"/api/rpg/v1/campaign-content-drafts",headers:{"content-type":"application/json"},payload:request(campaign.id,"log-redaction")});expect(response.statusCode).toBe(503);expect(messages.join("\n")).not.toContain("PRIVATE_PROVIDER_ECHO");expect(response.body).not.toContain("PRIVATE_PROVIDER_ECHO");await app.close();
  });
});
