import { createHash } from "node:crypto";
import type { DiceRollResult } from "@velvet/contracts";
import { describe, expect, it } from "vitest";
import {
  CLIENT_ENTROPY_BYTES,
  CLIENT_NONCE_BYTES,
  DIGEST_BYTES,
  SERVER_SECRET_BYTES,
  VERIFIABLE_DICE_MAGIC,
  VERIFIABLE_DICE_VERSION,
  canonicalDiceResult,
  diceProtocolDomains,
  frameDiceProtocol,
  type VerifiableRollBinding,
} from "../src/verifiableDiceContract.js";
import {
  abandonVerifiableRoll,
  beginVerifiableRoll,
  commitmentFrame,
  computeCommitment,
  computeProofMac,
  computeRandomBlock,
  computeTranscriptDigest,
  contributeToObservedVerifiableDiceCommitment,
  createClientEntropy,
  deriveRollKey,
  evaluateVerifiableDice,
  hkdfInfoFrame,
  hkdfSaltFrame,
  InMemoryProtocolTransitionRegistry,
  markLegacyRoll,
  observeVerifiableDiceCommitment,
  proofFromSettled,
  proofHandleFromContributedVerifiableRoll,
  proofFrame,
  projectPendingVerifiableRoll,
  randomBlockFrame,
  sampleUnbiasedBounded,
  settleVerifiableRoll,
  submitClientEntropy,
  transcriptFrame,
  verifyVerifiableDiceProof,
  type SecureByteSource,
} from "../src/verifiableDiceProtocol.js";

const hex = (value: Uint8Array): string => Buffer.from(value).toString("hex");
const sequence = (start: number, length: number): Uint8Array =>
  Uint8Array.from({ length }, (_, index) => start + index);

const binding: VerifiableRollBinding = {
  rollId: "roll-vector-001",
  commandId: "command-abc",
  candidateId: "candidate-7",
  expression: "4d6kh3+2",
};
const serverSecret = sequence(0x00, SERVER_SECRET_BYTES);
const clientEntropy = sequence(0xa0, CLIENT_ENTROPY_BYTES);
const clientNonce = sequence(0xf0, CLIENT_NONCE_BYTES);

// Generated independently from the prose framing table with OpenSSL 3 SHA-256,
// HMAC-SHA256, and HKDF, then frozen here rather than generated by test helpers.
const VECTOR = {
  commitmentFrame: "564c5654444943450001001676656c7665742e646963652f636f6d6d69746d656e74000501020000000f726f6c6c2d766563746f722d30303102020000000b636f6d6d616e642d61626303050000000c0163616e6469646174652d370402000000083464366b68332b32050100000020000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
  commitment: "03bff812ab5185444fadc72f640493ed55fdd325fac0dac40b0607467db41c91",
  saltFrame: "564c5654444943450001001576656c7665742e646963652f686b64662d73616c74000301010000002003bff812ab5185444fadc72f640493ed55fdd325fac0dac40b0607467db41c91020100000020a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf030100000010f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff",
  saltDigest: "db8b295715c5897145f5898c798601da1773a4636decf7414ea99d09bd16af67",
  infoFrame: "564c5654444943450001001576656c7665742e646963652f686b64662d696e666f000701020000000f726f6c6c2d766563746f722d30303102020000000b636f6d6d616e642d61626303050000000c0163616e6469646174652d370402000000083464366b68332b3205010000002003bff812ab5185444fadc72f640493ed55fdd325fac0dac40b0607467db41c91060100000020a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf070100000010f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff",
  rollKey: "4c4d01e974a7c75980825b92f3f5fe6969bd04d00958fb789fb7514d99fe0caf",
  randomBlock0: "92c3e645f031cbc44033f7026eb8fef55803bae143bb697c7a597592c66de337",
  resultFrame: "564c5654444943450001001c76656c7665742e646963652f63616e6f6e6963616c2d726573756c7400040102000000083464366b68332b3202010000000e0004000201000501000501000200030400000004000000020404000000040000000e",
  transcriptFrame: "564c5654444943450001001676656c7665742e646963652f7472616e736372697074000901020000000f726f6c6c2d766563746f722d30303102020000000b636f6d6d616e642d61626303050000000c0163616e6469646174652d370402000000083464366b68332b3205010000002003bff812ab5185444fadc72f640493ed55fdd325fac0dac40b0607467db41c91060100000020a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf070100000010f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff080100000020000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f090100000060564c5654444943450001001c76656c7665742e646963652f63616e6f6e6963616c2d726573756c7400040102000000083464366b68332b3202010000000e0004000201000501000501000200030400000004000000020404000000040000000e",
  transcriptDigest: "cb44f58914ca5cf39caccf84692abfdf6b341fd9c6182791e3c0852111a2d42a",
  proofMac: "c857ae2db88107611d748dc0d6b7118efcf39362e0add08c43f6f2913d3f5830",
  randomBlockFrame0: "564c5654444943450001001876656c7665742e646963652f72616e646f6d2d626c6f636b000501020000000f726f6c6c2d766563746f722d30303102020000000b636f6d6d616e642d61626303050000000c0163616e6469646174652d370402000000083464366b68332b3205030000000400000000",
  proofFrame: "564c5654444943450001001176656c7665742e646963652f70726f6f66000501020000000f726f6c6c2d766563746f722d30303102020000000b636f6d6d616e642d61626303050000000c0163616e6469646174652d370402000000083464366b68332b32050100000020cb44f58914ca5cf39caccf84692abfdf6b341fd9c6182791e3c0852111a2d42a",
} as const;

const expectedResult: DiceRollResult = {
  expression: "4d6kh3+2",
  normalized: { count: 4, sides: 6, selection: { type: "keep_highest", count: 3 }, modifier: 2 },
  terms: [
    { value: 2, kept: true },
    { value: 5, kept: true },
    { value: 5, kept: true },
    { value: 2, kept: false },
  ],
  modifier: 2,
  total: 14,
};

describe("M5.5 exact binary protocol vectors", () => {
  it("freezes magic, version, commitment, and every HKDF input", () => {
    expect(new TextDecoder().decode(VERIFIABLE_DICE_MAGIC)).toBe("VLVTDICE");
    expect(VERIFIABLE_DICE_VERSION).toBe(1);
    const commitment = computeCommitment(binding, serverSecret);
    const saltFrame = hkdfSaltFrame(commitment, clientEntropy, clientNonce);
    expect(hex(commitmentFrame(binding, serverSecret))).toBe(VECTOR.commitmentFrame);
    expect(hex(commitment)).toBe(VECTOR.commitment);
    expect(hex(saltFrame)).toBe(VECTOR.saltFrame);
    expect(createHash("sha256").update(saltFrame).digest("hex")).toBe(VECTOR.saltDigest);
    expect(hex(hkdfInfoFrame(binding, commitment, clientEntropy, clientNonce))).toBe(VECTOR.infoFrame);
    expect(hex(deriveRollKey(binding, commitment, serverSecret, clientEntropy, clientNonce))).toBe(VECTOR.rollKey);
  });

  it("reproduces the HMAC stream, unbiased result, canonical result, transcript, and proof", () => {
    const commitment = computeCommitment(binding, serverSecret);
    const key = deriveRollKey(binding, commitment, serverSecret, clientEntropy, clientNonce);
    const result = evaluateVerifiableDice(binding, key);
    const transcript = transcriptFrame(binding, commitment, clientEntropy, clientNonce, serverSecret, result);
    const digest = computeTranscriptDigest(binding, commitment, clientEntropy, clientNonce, serverSecret, result);
    expect(hex(randomBlockFrame(binding, 0))).toBe(VECTOR.randomBlockFrame0);
    expect(hex(computeRandomBlock(key, binding, 0))).toBe(VECTOR.randomBlock0);
    expect(result).toEqual(expectedResult);
    expect(hex(canonicalDiceResult(result))).toBe(VECTOR.resultFrame);
    expect(hex(transcript)).toBe(VECTOR.transcriptFrame);
    expect(hex(digest)).toBe(VECTOR.transcriptDigest);
    expect(hex(proofFrame(binding, digest))).toBe(VECTOR.proofFrame);
    expect(hex(computeProofMac(key, binding, digest))).toBe(VECTOR.proofMac);
  });

  it("separates domains, versions, commands, candidates, rolls, and optional presence", () => {
    const field = [{ tag: 1, type: "bytes", value: Uint8Array.of(1, 2, 3) }] as const;
    expect(hex(frameDiceProtocol(diceProtocolDomains.commitment, field)))
      .not.toBe(hex(frameDiceProtocol(diceProtocolDomains.proof, field)));
    expect(hex(computeCommitment({ ...binding, commandId: "command-other" }, serverSecret))).not.toBe(VECTOR.commitment);
    expect(hex(frameDiceProtocol(diceProtocolDomains.commitment, [
      { tag: 1, type: "optionalUtf8", value: null },
    ]))).not.toBe(hex(frameDiceProtocol(diceProtocolDomains.commitment, [
      { tag: 1, type: "optionalUtf8", value: "" },
    ])));
    expect(hex(computeCommitment({ ...binding, rollId: "roll-vector-002" }, serverSecret))).not.toBe(VECTOR.commitment);
    expect(() => frameDiceProtocol(diceProtocolDomains.commitment, [
      { tag: 2, type: "u32", value: 1 }, { tag: 1, type: "u32", value: 2 },
    ])).toThrow("strictly increasing");
  });

  it("rejects lone surrogates before TextEncoder can collide them with U+FFFD", () => {
    const replacement = frameDiceProtocol(diceProtocolDomains.commitment, [
      { tag: 1, type: "utf8", value: "\ufffd" },
    ]);
    for (const [malformed, replacementText] of [
      ["\ud800", "\ufffd"],
      ["\udfff", "\ufffd"],
      ["x\ud800y", "x\ufffdy"],
      ["\ud800\ud800", "\ufffd\ufffd"],
    ] as const) {
      expect(() => frameDiceProtocol(diceProtocolDomains.commitment, [
        { tag: 1, type: "utf8", value: malformed },
      ])).toThrow("unpaired UTF-16 surrogate");
      expect(new TextEncoder().encode(malformed)).toEqual(new TextEncoder().encode(replacementText));
    }
    expect(replacement).toBeInstanceOf(Uint8Array);
    expect(() => computeCommitment({ ...binding, rollId: "bad\ud800" }, serverSecret))
      .toThrow("unpaired UTF-16 surrogate");
  });

  it("traverses a rejected HMAC word through commit, settle, proof, and verification", () => {
    const rejectionBinding: VerifiableRollBinding = {
      rollId: "rejection-e2e",
      commandId: "rejection-fixture",
      candidateId: null,
      expression: "100d997kh1",
    };
    const secret = Buffer.from("000000000000000000000000000000000000000000000000000000000000191a", "hex");
    const entropy = sequence(0x40, CLIENT_ENTROPY_BYTES);
    const nonce = sequence(0x80, CLIENT_NONCE_BYTES);
    const registry = new InMemoryProtocolTransitionRegistry();
    const pending = beginVerifiableRoll(rejectionBinding, 30_000, 5_000, registry, fixedSource(secret));
    const verifier = new InMemoryProtocolTransitionRegistry();
    const observed = observeVerifiableDiceCommitment(
      rejectionBinding, projectPendingVerifiableRoll(pending).commitment, verifier,
    );
    const proofHandle = contributeToObservedVerifiableDiceCommitment(observed, entropy, nonce, verifier);
    const settled = settleVerifiableRoll(
      submitClientEntropy(pending, entropy, nonce, 30_100, registry),
      30_200,
      registry,
    );
    const key = deriveRollKey(rejectionBinding, settled.commitment, secret, entropy, nonce);
    const block = computeRandomBlock(key, rejectionBinding, 8);
    expect(hex(settled.commitment)).toBe("ff904b7fb070ab60494575eff4c696ef6c0e6f6c507f6d8e91e0d012ad919397");
    expect(hex(key)).toBe("3babc5e3568df1940beba638391efaf6141752521e11d062a01994d13b273efc");
    expect(hex(block)).toBe("b8ea553e7d2936d87e787f6e0c8aac2dffffffab644373dc18a1dd86daf3d962");
    const view = new DataView(block.buffer, block.byteOffset, block.byteLength);
    expect(view.getUint32(16, false)).toBeGreaterThanOrEqual(Math.floor(0x1_0000_0000 / 997) * 997);
    expect(settled.result.terms).toHaveLength(100);
    expect(settled.result.terms[68]).toEqual({ value: 782, kept: false });
    expect(settled.result.total).toBe(976);
    expect(createHash("sha256").update(canonicalDiceResult(settled.result)).digest("hex"))
      .toBe("d1dd6b2891d6d222c2fc2e17cfed03e1dec05611677309ee5b7a461b17bccd88");
    expect(hex(settled.transcriptDigest)).toBe("ed1a130798d1480eaa1cc4fb366fc067e64ce6c1935e03099254597e7b54c2a8");
    expect(hex(settled.proofMac)).toBe("0f95efcaa9512b7e42e4a23fb136a7bebef339bc531230514966ecf57003e3c7");
    expect(verifyVerifiableDiceProof(
      proofFromSettled(settled),
      proofHandle,
      verifier,
    ).total).toBe(976);
  });
});

const fixedSource = (...values: readonly Uint8Array[]): SecureByteSource => {
  let index = 0;
  return {
    bytes(length) {
      const value = values[index++];
      if (value === undefined) throw new Error("unexpected secure byte request");
      void length;
      return value;
    },
  };
};

const settledVector = () => {
  const registry = new InMemoryProtocolTransitionRegistry();
  const pending = beginVerifiableRoll(binding, 10_000, 5_000, registry, fixedSource(serverSecret));
  const contributed = submitClientEntropy(pending, clientEntropy, clientNonce, 10_100, registry);
  return settleVerifiableRoll(contributed, 10_200, registry);
};

describe("M5.5 proof validation", () => {
  it("verifies the vector only after explicit observed then contributed transitions", () => {
    const proof = proofFromSettled(settledVector());
    const verifier = new InMemoryProtocolTransitionRegistry();
    const observed = observeVerifiableDiceCommitment(binding, proof.commitment, verifier);
    const contributed = contributeToObservedVerifiableDiceCommitment(
      observed, clientEntropy, clientNonce, verifier,
    );

    expect(() => contributeToObservedVerifiableDiceCommitment(
      observed, sequence(0x20, 32), sequence(0x30, 16), verifier,
    )).toThrow("stale_capability");
    expect(verifyVerifiableDiceProof(proof, contributed, verifier)).toEqual(expectedResult);
    expect(() => verifyVerifiableDiceProof(proof, contributed, verifier)).toThrow("roll_terminal");
  });

  it("cannot register an unobserved or replacement commitment at verification", () => {
    const proof = proofFromSettled(settledVector());
    const verifier = new InMemoryProtocolTransitionRegistry();
    const forgedHandle = { kind: "verifiable-dice-contributed-proof-handle" } as const;
    expect(() => verifyVerifiableDiceProof(proof, forgedHandle, verifier))
      .toThrow("invalid contributed proof handle");

    const observed = observeVerifiableDiceCommitment(binding, proof.commitment, verifier);
    const contributed = contributeToObservedVerifiableDiceCommitment(
      observed, clientEntropy, clientNonce, verifier,
    );
    const replacementLifecycle = new InMemoryProtocolTransitionRegistry();
    const replacement = settleVerifiableRoll(
      submitClientEntropy(
        beginVerifiableRoll(
          binding, 60_000, 5_000, replacementLifecycle, fixedSource(sequence(0x40, 32)),
        ),
        clientEntropy,
        clientNonce,
        60_100,
        replacementLifecycle,
      ),
      60_200,
      replacementLifecycle,
    );
    expect(hex(replacement.commitment)).not.toBe(hex(proof.commitment));
    expect(() => verifyVerifiableDiceProof(proofFromSettled(replacement), contributed, verifier))
      .toThrow("observed precommitment");
    expect(() => observeVerifiableDiceCommitment(binding, replacement.commitment, verifier))
      .toThrow("roll_reused");
  });

  it("requires exact contributed values and rejects malformed proofs", () => {
    const proof = proofFromSettled(settledVector());
    const verifier = new InMemoryProtocolTransitionRegistry();
    const contributed = contributeToObservedVerifiableDiceCommitment(
      observeVerifiableDiceCommitment(binding, proof.commitment, verifier),
      clientEntropy,
      clientNonce,
      verifier,
    );
    const changedMac = proof.proofMac.slice();
    changedMac[0] = changedMac[0]! ^ 1;
    expect(() => verifyVerifiableDiceProof({ ...proof, proofMac: changedMac }, contributed, verifier))
      .toThrow("proof MAC mismatch");

    const mismatchRegistry = new InMemoryProtocolTransitionRegistry();
    const mismatched = contributeToObservedVerifiableDiceCommitment(
      observeVerifiableDiceCommitment(binding, proof.commitment, mismatchRegistry),
      sequence(0x20, CLIENT_ENTROPY_BYTES),
      sequence(0x30, CLIENT_NONCE_BYTES),
      mismatchRegistry,
    );
    expect(() => verifyVerifiableDiceProof(proof, mismatched, mismatchRegistry))
      .toThrow("proof contribution mismatch");
  });

  it("uses the registered lifecycle contribution capability and consumes it", () => {
    const proof = proofFromSettled(settledVector());
    const registry = new InMemoryProtocolTransitionRegistry();
    const contributedRoll = submitClientEntropy(
      beginVerifiableRoll(binding, 40_000, 5_000, registry, fixedSource(serverSecret)),
      clientEntropy,
      clientNonce,
      40_100,
      registry,
    );
    const proofHandle = proofHandleFromContributedVerifiableRoll(contributedRoll);
    const competingHandle = proofHandleFromContributedVerifiableRoll(contributedRoll);
    expect(verifyVerifiableDiceProof(proof, proofHandle, registry)).toEqual(expectedResult);
    expect(() => verifyVerifiableDiceProof(proof, competingHandle, registry)).toThrow("roll_terminal");
    expect(() => settleVerifiableRoll(contributedRoll, 40_200, registry)).toThrow("roll_terminal");
  });

  it("atomically rejects cross-roll commitment reuse and requires pending registration", () => {
    const registry = new InMemoryProtocolTransitionRegistry();
    const commitment = Uint8Array.from(serverSecret);
    expect(registry.transition({
      kind: "create", rollId: "roll-a", commitment, source: "lifecycle",
    }).accepted).toBe(true);
    expect(registry.transition({
      kind: "create", rollId: "roll-b", commitment, source: "lifecycle",
    })).toEqual({
      accepted: false,
      conflict: "commitment_reused",
    });
    expect(registry.transition({
      kind: "contribute",
      rollId: "unknown-roll",
      commitment: sequence(0x40, DIGEST_BYTES),
      nonce: clientNonce,
      contributionDigest: sequence(0x60, DIGEST_BYTES),
      expectedCapability: "missing",
    })).toEqual({ accepted: false, conflict: "invalid_transition" });

    const creationRegistry = new InMemoryProtocolTransitionRegistry();
    beginVerifiableRoll(binding, 1_000, 1_000, creationRegistry, fixedSource(serverSecret));
    expect(() => beginVerifiableRoll(
      binding, 1_000, 1_000, creationRegistry, fixedSource(serverSecret),
    )).toThrow("roll_reused");
  });
});

describe("M5.5 entropy, rejection, and lifecycle rules", () => {
  it("uses exact injectable secure-byte requests and rejects invalid source output", () => {
    const requests: number[] = [];
    const source: SecureByteSource = {
      bytes(length) {
        requests.push(length);
        return requests.length === 1 ? clientEntropy : clientNonce;
      },
    };
    const generated = createClientEntropy(source);
    expect(generated).toEqual({ entropy: clientEntropy, nonce: clientNonce });
    expect(requests).toEqual([CLIENT_ENTROPY_BYTES, CLIENT_NONCE_BYTES]);
    expect(() => createClientEntropy(fixedSource(new Uint8Array(31), clientNonce))).toThrow("exactly 32 bytes");
    expect(() => beginVerifiableRoll(
      binding, 0, 1_000, new InMemoryProtocolTransitionRegistry(), fixedSource(new Uint8Array(31)),
    ))
      .toThrow("exactly 32 bytes");
  });

  it("rejects the biased u32 tail and fails closed on invalid or exhausted words", () => {
    expect(sampleUnbiasedBounded([0xffff_ffff, 5][Symbol.iterator](), 1_000)).toBe(6);
    expect(() => sampleUnbiasedBounded([0xffff_ffff][Symbol.iterator](), 1_000)).toThrow("exhausted");
    expect(() => sampleUnbiasedBounded([-1][Symbol.iterator](), 6)).toThrow("invalid random word");
    expect(() => sampleUnbiasedBounded([0][Symbol.iterator](), 1)).toThrow("invalid die upper bound");
  });

  it("forbids entropy replacement and enforces the half-open pending window", () => {
    const registry = new InMemoryProtocolTransitionRegistry();
    const pending = beginVerifiableRoll(binding, 1_000, 1_000, registry, fixedSource(serverSecret));
    const contributed = submitClientEntropy(pending, clientEntropy, clientNonce, 1_999, registry);
    expect(() => submitClientEntropy(contributed, clientEntropy, clientNonce, 1_999, registry)).toThrow("reuse");
    expect(() => submitClientEntropy(pending, sequence(0x20, 32), sequence(0x10, 16), 1_999, registry))
      .toThrow("stale_capability");
    expect(() => submitClientEntropy(pending, clientEntropy, sequence(0x10, 16), 2_000, registry))
      .toThrow("outside pending window");
    expect(() => settleVerifiableRoll(contributed, 2_000, registry)).toThrow("at or after expiry");
  });

  it("makes cancellation and timeout terminal against every stale handle", () => {
    const cancelledRegistry = new InMemoryProtocolTransitionRegistry();
    const cancelledPending = beginVerifiableRoll(
      binding, 1_000, 1_000, cancelledRegistry, fixedSource(serverSecret),
    );
    expect(abandonVerifiableRoll(cancelledPending, 1_500, cancelledRegistry, true).reason).toBe("cancelled");
    expect(() => submitClientEntropy(
      cancelledPending, clientEntropy, clientNonce, 1_600, cancelledRegistry,
    )).toThrow("roll_terminal");
    expect(() => abandonVerifiableRoll(cancelledPending, 1_700, cancelledRegistry, true)).toThrow("roll_terminal");

    const timeoutBinding = { ...binding, rollId: "timeout-roll" };
    const timeoutRegistry = new InMemoryProtocolTransitionRegistry();
    const timeoutPending = beginVerifiableRoll(
      timeoutBinding, 1_000, 1_000, timeoutRegistry, fixedSource(serverSecret),
    );
    expect(abandonVerifiableRoll(timeoutPending, 2_000, timeoutRegistry).reason).toBe("timeout");
    expect(() => submitClientEntropy(
      timeoutPending, clientEntropy, sequence(0x10, 16), 1_900, timeoutRegistry,
    )).toThrow("roll_terminal");
    expect(() => abandonVerifiableRoll(timeoutPending, 2_001, timeoutRegistry)).toThrow("roll_terminal");
  });

  it("allows only contributed-to-withheld and binds its evidence", () => {
    const registry = new InMemoryProtocolTransitionRegistry();
    const pending = beginVerifiableRoll(binding, 1_000, 1_000, registry, fixedSource(serverSecret));
    const contributed = submitClientEntropy(pending, clientEntropy, clientNonce, 1_500, registry);
    expect(() => abandonVerifiableRoll(contributed, 1_501, registry, true)).toThrow("cannot be cancelled");
    expect(() => abandonVerifiableRoll(pending, 2_000, registry)).toThrow("stale_capability");
    const withheld = abandonVerifiableRoll(contributed, 2_000, registry);
    expect(withheld.reason).toBe("withheld");
    expect(withheld.clientContributionEvidenceDigest).toHaveLength(DIGEST_BYTES);
    const otherBinding = { ...binding, commandId: "different-command" };
    const otherRegistry = new InMemoryProtocolTransitionRegistry();
    const other = submitClientEntropy(
      beginVerifiableRoll(otherBinding, 1_000, 1_000, otherRegistry, fixedSource(serverSecret)),
      clientEntropy,
      clientNonce,
      1_500,
      otherRegistry,
    );
    expect(hex(abandonVerifiableRoll(other, 2_000, otherRegistry).clientContributionEvidenceDigest!))
      .not.toBe(hex(withheld.clientContributionEvidenceDigest!));
    expect(() => settleVerifiableRoll(contributed, 1_900, registry)).toThrow("roll_terminal");
    expect(() => abandonVerifiableRoll(contributed, 2_001, registry)).toThrow("roll_terminal");
  });

  it("makes settlement terminal and rejects duplicate or divergent outcomes", () => {
    const registry = new InMemoryProtocolTransitionRegistry();
    const pending = beginVerifiableRoll(binding, 1_000, 1_000, registry, fixedSource(serverSecret));
    const contributed = submitClientEntropy(pending, clientEntropy, clientNonce, 1_500, registry);
    expect(settleVerifiableRoll(contributed, 1_600, registry).state).toBe("settled");
    expect(() => settleVerifiableRoll(contributed, 1_700, registry)).toThrow("roll_terminal");
    expect(() => abandonVerifiableRoll(contributed, 2_000, registry)).toThrow("roll_terminal");
    expect(() => submitClientEntropy(
      pending, sequence(0x20, 32), sequence(0x10, 16), 1_700, registry,
    )).toThrow("roll_terminal");
  });

  it("keeps server secrets outside serializable pending state and defensive projections", () => {
    const pending = beginVerifiableRoll(
      binding, 1_000, 1_000, new InMemoryProtocolTransitionRegistry(), fixedSource(serverSecret),
    );
    const projection = projectPendingVerifiableRoll(pending);
    expect(projection).not.toHaveProperty("serverSecret");
    expect(JSON.stringify(projection)).not.toContain(hex(serverSecret));
    expect(JSON.stringify(pending)).toBe('{"kind":"verifiable-dice-pending-handle"}');
    projection.commitment[0] = projection.commitment[0]! ^ 1;
    expect(hex(projectPendingVerifiableRoll(pending).commitment)).toBe(VECTOR.commitment);
  });

  it("keeps historical results explicitly legacy without manufacturing a proof", () => {
    const legacy = markLegacyRoll(binding.rollId, expectedResult);
    expect(legacy).toEqual({ state: "legacy", rollId: binding.rollId, result: expectedResult });
    expect(legacy).not.toHaveProperty("commitment");
  });
});
