import { canonical, nextId, revision, sha } from "./util.js";
import type { EffectContext } from "./types.js";

export function applyEffectKind(ctx:EffectContext,powerUseId:string):void{
  const {db,deps,action,target,at,outcomes}=ctx;let replaced=false;
  const effect=(ctx.rage?ctx.effects[0]:action.definition.mechanics.effects[0])as any,targetActor=target.actor_id!,targetRevisionNow=revision(db,"m16",action.campaignId,targetActor),targetAfter=targetRevisionNow+1,effectCommandId=nextId(deps),effectId=nextId(deps),concentration=action.definition.reference.kind==="spell"&&(action.definition as any).mechanics.concentration;
  if(targetRevisionNow===0&&!db.prepare("SELECT 1 FROM rpg_m16_mutation_revisions_v26 WHERE campaign_id=? AND actor_id=?").get(action.campaignId,targetActor))db.prepare("INSERT INTO rpg_m16_mutation_revisions_v26 VALUES(?,?,0,?)").run(action.campaignId,targetActor,at);const linked=canonical({linkedPowerUseId:powerUseId});db.prepare("INSERT INTO rpg_m16_commands_v26 VALUES(?,?,?,'effect','apply_effect',?,?,?,?,?,?)").run(action.campaignId,targetActor,effectCommandId,effectCommandId,linked,sha(linked),targetRevisionNow,targetAfter,at);db.prepare("INSERT INTO rpg_m16_receipts_v26 VALUES(?,?,?,?,?,?,?)").run(action.campaignId,targetActor,effectCommandId,targetAfter,linked,sha(linked),at);
  const priorEffect=concentration?db.prepare("SELECT effect_id FROM rpg_active_effects_v26 WHERE campaign_id=? AND actor_id=? AND concentration_key='power-concentration' AND status='active'").get(action.campaignId,targetActor)as any:null;if(priorEffect){replaced=true;const life=nextId(deps);db.prepare("INSERT INTO rpg_effect_lifecycle_events_v26 VALUES(?,?,?,?,?,?,'concentration_replaced',NULL,?)").run(life,priorEffect.effect_id,action.campaignId,targetActor,effectCommandId,targetAfter,at);db.prepare("UPDATE rpg_active_effects_v26 SET status='removed',state_revision=state_revision+1,last_lifecycle_event_id=?,updated_at=?,ended_at=? WHERE effect_id=?").run(life,at,at,priorEffect.effect_id);}
  const condition=effect.type==="condition",duration=condition?{kind:"rounds",remaining:effect.durationRounds}:ctx.rage?{kind:"rounds",remaining:10}:effect.duration==="turn"||effect.duration==="round"?{kind:"rounds",remaining:1}:{kind:"until_removed"},modifier=ctx.rage?{kind:"resistance",appliesToId:"physical",amount:null}:{kind:"flat",appliesToId:condition?`condition:${effect.condition}`:effect.statistic,amount:condition?1:effect.amount};
  db.prepare("INSERT INTO rpg_m16_events_v26 VALUES(?,?,?,?,?,?,?,?)").run(nextId(deps),action.campaignId,targetActor,effectCommandId,targetAfter,"effect_applied",linked,at);db.prepare("UPDATE rpg_m16_mutation_revisions_v26 SET revision=?,updated_at=? WHERE campaign_id=? AND actor_id=? AND revision=?").run(targetAfter,at,action.campaignId,targetActor,targetRevisionNow);
  db.prepare(`INSERT INTO rpg_active_effects_v26(effect_id,campaign_id,actor_id,command_id,resulting_revision,source_pack_id,source_pack_version,source_kind,source_definition_id,status,concentration_key,duration_kind,remaining_rounds,expires_at,recovery_kind,applied_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'active',?,?,?,?,?,?,?)`).run(effectId,action.campaignId,targetActor,effectCommandId,targetAfter,action.powerRef.packId,action.powerRef.packVersion,action.powerRef.kind,action.powerRef.definitionId,concentration?"power-concentration":null,duration.kind,duration.kind==="rounds"?duration.remaining:null,null,"none",at,at);db.prepare("INSERT INTO rpg_effect_modifiers_v26 VALUES(?,?,?,?,?)").run(effectId,0,modifier.kind,modifier.appliesToId,modifier.amount);outcomes.push({kind:"effect",effect:ctx.rage?"physical resistance for 10 rounds":condition?`${effect.condition} for ${effect.durationRounds} rounds`:`${effect.amount>=0?"+":""}${effect.amount} ${effect.statistic} (${effect.duration})`,replacedConcentration:replaced});
}
