/**
 * Pure, deterministic mapping from one player declaration to the closest SRD 5.1 skill check.
 *
 * The adventure prompt advertises the full SRD ability/skill check family, so a declaration that
 * looks, searches, climbs, sneaks, lies, intimidates, or recalls lore has a universal resolution
 * even when no exact action candidate fits. This module only classifies intent. It never reads
 * authoritative state, never rolls, and never commits anything: callers decide how a `strong`
 * mapping becomes a check and treat `weak` as ranking evidence only.
 *
 * The `ability` and `skill` strings mirror the display labels built by `adventureCheckRepo.ts`
 * (`ABILITY_NAMES` and `SKILLS`), so a caller can locate the advertised candidate by label.
 *
 * Conservatism:
 * - Matching is whole-word or contiguous-phrase matching over lowercased tokens. Substrings never
 *   match ("hi" inside "history" is not a greeting, "aim" inside "claims" is not Intimidation).
 * - A lone strong trigger maps the declaration. Two unrelated skills with strong triggers are
 *   ambiguous and map to null; strong triggers outrank weak ones, and two unrelated weak skills
 *   are ambiguous too. Null is always preferred over a likely-wrong check.
 * - Questions, greetings, meta/table talk, and movement-only travel map to null, as does any
 *   declaration with no trigger at all.
 */

export interface DeclarationCheckMapping {
  /** Display ability label, matching `ABILITY_NAMES` in `adventureCheckRepo.ts`. */
  ability: string;
  /** Display skill label, matching `SKILLS` in `adventureCheckRepo.ts`. */
  skill: string;
  /** `strong` may be committed deterministically; `weak` only informs relevance ranking. */
  confidence: "strong" | "weak";
  rationale: string;
}

export interface DeclarationCheckVerbEntry {
  ability: string;
  skill: string;
  confidence: "strong" | "weak";
  /** Canonical trigger words or contiguous phrases; inflections are generated by the matcher. */
  triggers: readonly string[];
  /** When present, at least one of these context words must also appear for the entry to match. */
  contexts?: readonly string[];
}

/** The 18 SRD 5.1 skill labels with their abilities, exactly as `adventureCheckRepo.ts` renders them. */
export const DECLARATION_CHECK_SKILL_LABELS = Object.freeze([
  ["Strength", "Athletics"], ["Dexterity", "Acrobatics"], ["Dexterity", "Sleight of Hand"], ["Dexterity", "Stealth"],
  ["Intelligence", "Arcana"], ["Intelligence", "History"], ["Intelligence", "Investigation"], ["Intelligence", "Nature"],
  ["Intelligence", "Religion"], ["Wisdom", "Animal Handling"], ["Wisdom", "Insight"], ["Wisdom", "Medicine"],
  ["Wisdom", "Perception"], ["Wisdom", "Survival"], ["Charisma", "Deception"], ["Charisma", "Intimidation"],
  ["Charisma", "Performance"], ["Charisma", "Persuasion"],
] as const);

const MAGIC_CONTEXTS = Object.freeze(["magic", "magical", "arcane", "spell", "spells", "rune", "runes", "enchantment", "curse", "curses", "artifact", "artifacts"]);
const HISTORY_CONTEXTS = Object.freeze(["history", "histories", "historical", "legend", "legends", "lore"]);
const NATURE_CONTEXTS = Object.freeze(["nature", "natural", "plant", "plants", "animal", "animals", "beast", "beasts", "forest", "forests", "weather"]);
const RELIGION_CONTEXTS = Object.freeze(["god", "gods", "goddess", "goddesses", "temple", "temples", "divine", "religion", "religious", "holy", "shrine", "shrines", "rite", "rites", "ritual", "rituals"]);
const ANIMAL_CONTEXTS = Object.freeze(["animal", "animals", "beast", "beasts", "horse", "horses", "dog", "dogs", "wolf", "wolves", "creature", "creatures", "steed", "steeds"]);
const RECALL_TRIGGERS = Object.freeze(["recall", "remember"]);

const entry = (ability: string, skill: string, confidence: "strong" | "weak", triggers: readonly string[],
  contexts?: readonly string[]): DeclarationCheckVerbEntry => Object.freeze({ ability, skill, confidence, triggers: Object.freeze([...triggers]),
    ...(contexts ? { contexts } : {}) });

/**
 * The exported verb table: strong entries may resolve a held turn, weak entries never do. Each
 * skill in `DECLARATION_CHECK_SKILL_LABELS` has at least one strong entry.
 */
export const DECLARATION_CHECK_VERBS: readonly DeclarationCheckVerbEntry[] = Object.freeze([
  // Wisdom
  entry("Wisdom", "Perception", "strong", ["look", "spot", "observe", "watch", "listen", "hear"]),
  entry("Wisdom", "Perception", "weak", ["scan", "glance", "survey", "peer", "notice"]),
  entry("Wisdom", "Insight", "strong", ["sense motive", "read someone", "read somebody", "read him", "read her", "read them", "read the room", "insight"]),
  entry("Wisdom", "Insight", "weak", ["read"]),
  entry("Wisdom", "Survival", "strong", ["track", "forage", "navigate", "survive"]),
  entry("Wisdom", "Survival", "weak", ["hunt", "scout", "follow tracks"]),
  entry("Wisdom", "Medicine", "strong", ["heal", "treat", "bandage"]),
  entry("Wisdom", "Medicine", "weak", ["tend", "first aid", "patch up"]),
  entry("Wisdom", "Animal Handling", "strong", ["calm", "soothe", "handle", "approach"], ANIMAL_CONTEXTS),
  entry("Wisdom", "Animal Handling", "weak", ["animal handling"]),
  // Intelligence
  entry("Intelligence", "Investigation", "strong", ["search", "inspect", "examine", "investigate", "check for traps", "check for trap"]),
  entry("Intelligence", "Investigation", "weak", ["check", "study", "analyze", "scrutinize"]),
  entry("Intelligence", "Arcana", "strong", RECALL_TRIGGERS, MAGIC_CONTEXTS),
  entry("Intelligence", "Arcana", "weak", ["arcana"]),
  entry("Intelligence", "History", "strong", RECALL_TRIGGERS, HISTORY_CONTEXTS),
  entry("Intelligence", "History", "weak", ["history"]),
  entry("Intelligence", "Nature", "strong", RECALL_TRIGGERS, NATURE_CONTEXTS),
  entry("Intelligence", "Nature", "weak", ["nature"]),
  entry("Intelligence", "Religion", "strong", RECALL_TRIGGERS, RELIGION_CONTEXTS),
  entry("Intelligence", "Religion", "weak", ["religion"]),
  // Strength
  entry("Strength", "Athletics", "strong", ["climb", "swim", "lift", "push", "pull", "jump", "force", "force open"]),
  entry("Strength", "Athletics", "weak", ["haul", "heave", "drag", "sprint"]),
  // Dexterity
  entry("Dexterity", "Acrobatics", "strong", ["balance", "tumble", "somersault", "squeeze through"]),
  entry("Dexterity", "Acrobatics", "weak", ["vault", "flip"]),
  entry("Dexterity", "Stealth", "strong", ["sneak", "hide", "creep", "skulk"]),
  entry("Dexterity", "Stealth", "weak", ["tiptoe", "silently", "stealthily", "quietly"]),
  entry("Dexterity", "Sleight of Hand", "strong", ["pick a lock", "pick the lock", "pick lock", "pickpocket", "palm", "steal"]),
  entry("Dexterity", "Sleight of Hand", "weak", ["filch", "snatch", "swipe"]),
  // Charisma
  entry("Charisma", "Persuasion", "strong", ["persuade", "convince", "plead", "reason with"]),
  entry("Charisma", "Persuasion", "weak", ["bargain", "negotiate", "appeal", "reassure", "flatter"]),
  entry("Charisma", "Intimidation", "strong", ["intimidate", "threaten", "scare"]),
  entry("Charisma", "Intimidation", "weak", ["warn", "menace", "pressure", "loom"]),
  entry("Charisma", "Deception", "strong", ["lie", "deceive", "bluff", "disguise"]),
  entry("Charisma", "Deception", "weak", ["trick", "mislead", "pretend", "fake", "feign", "con"]),
  entry("Charisma", "Performance", "strong", ["perform", "sing", "dance"]),
  entry("Charisma", "Performance", "weak", ["play", "recite", "story"]),
]);

/** The Medium-difficulty, normal-mode candidate label for a mapping, as `adventureCheckRepo.ts` renders it. */
export function declarationCheckCandidateLabel(mapping: Pick<DeclarationCheckMapping, "ability" | "skill">): string {
  return `${mapping.skill} (${mapping.ability}), Medium difficulty, normal`;
}

/** Irregular forms the suffix generator cannot derive; everything else is built from the base word. */
const IRREGULAR_FORMS: Record<string, readonly string[]> = {
  lie: ["lie", "lies", "lied", "lying"],
  hide: ["hide", "hides", "hid", "hidden", "hiding"],
  hear: ["hear", "hears", "heard", "hearing"],
  steal: ["steal", "steals", "stole", "stolen", "stealing"],
  sing: ["sing", "sings", "sang", "sung", "singing"],
  swim: ["swim", "swims", "swam", "swum", "swimming"],
  creep: ["creep", "creeps", "crept", "creeping"],
};

const formsCache = new Map<string, ReadonlySet<string>>();

/** Whole-word token forms for one trigger word: base, plural, and ordinary verb inflections. */
function wordForms(word: string): ReadonlySet<string> {
  const cached = formsCache.get(word);
  if (cached) return cached;
  const irregular = IRREGULAR_FORMS[word];
  if (irregular) {
    const forms = new Set(irregular);
    formsCache.set(word, forms);
    return forms;
  }
  const forms = new Set<string>([word, `${word}s`, `${word}es`, `${word}ed`, `${word}d`, `${word}ing`]);
  if (word.endsWith("e")) {
    forms.delete(`${word}ed`);
    forms.delete(`${word}es`);
    forms.add(`${word.slice(0, -1)}ing`);
  }
  if (word.endsWith("y")) {
    forms.delete(`${word}s`); forms.delete(`${word}ed`); forms.delete(`${word}d`);
    forms.add(`${word.slice(0, -1)}ies`); forms.add(`${word.slice(0, -1)}ied`);
  }
  // A short consonant-vowel-consonant verb doubles its final consonant before -ing/-ed.
  if (word.length >= 3 && /[^aeiou]/u.test(word.at(-3)!) && /[aeiou]/u.test(word.at(-2)!) && /[^aeiouwxy]/u.test(word.at(-1)!)) {
    forms.add(`${word}${word.slice(-1)}ing`).add(`${word}${word.slice(-1)}ed`);
  }
  formsCache.set(word, forms);
  return forms;
}

interface CompiledTrigger { source: string; forms: readonly ReadonlySet<string>[]; }
interface CompiledEntry { ability: string; skill: string; confidence: "strong" | "weak"; triggers: readonly CompiledTrigger[]; contexts: ReadonlySet<string> | null; }

/** The first and last phrase tokens inflect; interior tokens (articles, prepositions) match literally. */
function compileTrigger(trigger: string): CompiledTrigger {
  const words = trigger.split(/\s+/u);
  return { source: trigger, forms: words.map((word, index) =>
    index === 0 || index === words.length - 1 ? wordForms(word) : new Set([word])) };
}

const COMPILED_ENTRIES: readonly CompiledEntry[] = DECLARATION_CHECK_VERBS.map((value) => ({
  ability: value.ability, skill: value.skill, confidence: value.confidence,
  triggers: value.triggers.map(compileTrigger),
  contexts: value.contexts ? new Set(value.contexts.flatMap((context) => [...wordForms(context)])) : null,
}));

/** A contiguous whole-word phrase match; nothing here matches a substring of a token. */
function matchesTrigger(tokens: readonly string[], trigger: CompiledTrigger): boolean {
  const length = trigger.forms.length;
  for (let start = 0; start + length <= tokens.length; start += 1) {
    let matched = true;
    for (let offset = 0; offset < length; offset += 1) {
      if (!trigger.forms[offset]!.has(tokens[start + offset]!)) { matched = false; break; }
    }
    if (matched) return true;
  }
  return false;
}

/** The first trigger whose phrase matches, or null. Contexts are an additional any-of requirement. */
function matchesEntry(tokens: readonly string[], value: CompiledEntry): string | null {
  const trigger = value.triggers.find((candidate) => matchesTrigger(tokens, candidate));
  if (!trigger) return null;
  if (value.contexts && !tokens.some((token) => value.contexts!.has(token))) return null;
  return trigger.source;
}

const QUESTION_START = /^(?:where|what|who|whom|whose|why|when|how|which|is|are|was|were|do|does|did|can|could|should|would|will|shall|have|has|had|am|may|might|must)\b/u;
const QUESTION_PHRASE = /^(?:please\s+)?(?:tell|explain|describe|clarify)\b/u;
const GREETING = /^(?:hi|hello|hey|howdy|yo|greetings|good\s+(?:morning|afternoon|evening)|farewell|goodbye|bye|thanks|thank\s+you|cheers|salutations)\b/u;
const META_TALK = /^(?:ooc\b|out\s+of\s+character\b|let'?s\s+(?:take\s+a\s+break|pause|stop|wrap\s+up|move\s+on)\b|let\s+us\s+(?:take\s+a\s+break|pause|stop|wrap\s+up|move\s+on)\b|(?:i\s+think\s+we\s+should|maybe\s+we\s+should|we\s+should|we\s+need\s+to)\b|(?:can|could|should)\s+we\s+(?:pause|stop|take\s+a\s+break)\b|what(?:'s|\s+is)\s+(?:the|my|our)\s+(?:plan|hp|health)\b|roll\s+initiative\b|let\s+me\s+think\b)/u;

function isQuestion(text: string): boolean { return text.endsWith("?") || QUESTION_START.test(text) || QUESTION_PHRASE.test(text); }
function isGreeting(text: string): boolean { return GREETING.test(text); }
function isMetaTalk(text: string): boolean { return META_TALK.test(text); }

/**
 * Maps a declaration to at most one SRD skill check, or null when no conservative whole-word
 * classification exists. `strong` means a single unmistakable attempt; `weak` means a leaning
 * that must never be committed on its own.
 */
export function mapDeclarationToCheck(declaration: string): DeclarationCheckMapping | null {
  const text = declaration.trim();
  if (!text) return null;
  const lowered = text.toLocaleLowerCase("en-US");
  if (isQuestion(lowered) || isGreeting(lowered) || isMetaTalk(lowered)) return null;
  const tokens = lowered.match(/[a-z0-9]+/gu) ?? [];
  if (tokens.length === 0) return null;
  const strongHits: Array<{ ability: string; skill: string; trigger: string }> = [];
  const weakHits: Array<{ ability: string; skill: string; trigger: string }> = [];
  for (const value of COMPILED_ENTRIES) {
    const trigger = matchesEntry(tokens, value);
    if (!trigger) continue;
    (value.confidence === "strong" ? strongHits : weakHits).push({ ability: value.ability, skill: value.skill, trigger });
  }
  const strongSkills = [...new Set(strongHits.map((hit) => hit.skill))];
  // A single strong attempt wins over weak leanings; two unrelated strong skills are ambiguous.
  if (strongSkills.length > 1) return null;
  if (strongSkills.length === 1) {
    const hit = strongHits.find((candidate) => candidate.skill === strongSkills[0]!)!;
    return { ability: hit.ability, skill: hit.skill, confidence: "strong",
      rationale: `Strong ${hit.skill} trigger "${hit.trigger}" for ${hit.ability}.` };
  }
  const weakSkills = [...new Set(weakHits.map((hit) => hit.skill))];
  if (weakSkills.length !== 1) return null;
  const hit = weakHits.find((candidate) => candidate.skill === weakSkills[0]!)!;
  return { ability: hit.ability, skill: hit.skill, confidence: "weak",
    rationale: `Weak ${hit.skill} trigger "${hit.trigger}" for ${hit.ability}.` };
}
