import type { StarterReferences } from "../references.js";

/** SRD 5.1 7th-level spells. Each file under `spells/` owns one level band. */
export function buildLevel7Spells(refs: StarterReferences) {
  const conjureCelestial = refs.ref("spell", "srd-5.1:spell:conjure-celestial");
  const delayedBlastFireball = refs.ref("spell", "srd-5.1:spell:delayed-blast-fireball");
  const divineWord = refs.ref("spell", "srd-5.1:spell:divine-word");
  const etherealness = refs.ref("spell", "srd-5.1:spell:etherealness");
  const fingerOfDeath = refs.ref("spell", "srd-5.1:spell:finger-of-death");
  const fireStorm = refs.ref("spell", "srd-5.1:spell:fire-storm");
  const forcecage = refs.ref("spell", "srd-5.1:spell:forcecage");
  const mirageArcane = refs.ref("spell", "srd-5.1:spell:mirage-arcane");
  const mordenkainensMagnificentMansion = refs.ref("spell", "srd-5.1:spell:mordenkainens-magnificent-mansion");
  const mordenkainensSword = refs.ref("spell", "srd-5.1:spell:mordenkainens-sword");
  const planeShift = refs.ref("spell", "srd-5.1:spell:plane-shift");
  const prismaticSpray = refs.ref("spell", "srd-5.1:spell:prismatic-spray");
  const projectImage = refs.ref("spell", "srd-5.1:spell:project-image");
  const regenerate = refs.ref("spell", "srd-5.1:spell:regenerate");
  const resurrection = refs.ref("spell", "srd-5.1:spell:resurrection");
  const reverseGravity = refs.ref("spell", "srd-5.1:spell:reverse-gravity");
  const sequester = refs.ref("spell", "srd-5.1:spell:sequester");
  const simulacrum = refs.ref("spell", "srd-5.1:spell:simulacrum");
  const symbol = refs.ref("spell", "srd-5.1:spell:symbol");
  const teleport = refs.ref("spell", "srd-5.1:spell:teleport");
  return [
    { reference: conjureCelestial, name: "Conjure Celestial", description: "Summons a celestial that obeys your commands and fights alongside you while you concentrate.", tags: ["srd-5.1", "level-7", "metadata-only", "cleric"], mechanics: { level: 7, school: "conjuration", castingTime: "1-minute", actionCost: "action", range: 90, target: "area", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: delayedBlastFireball, name: "Delayed Blast Fireball", description: "Creates a bead of fire that can be delayed and then explodes in a 20-foot radius, with damage increasing the longer it waits.", tags: ["srd-5.1", "level-7", "metadata-only", "sorcerer", "wizard"], mechanics: { level: 7, school: "evocation", castingTime: "action", actionCost: "action", range: 150, target: "area", duration: "concentration", attackType: "none", saveType: "dexterity", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a tiny ball of bat guano and sulfur" }, effects: [] } },
    { reference: divineWord, name: "Divine Word", description: "Uttering a divine word forces creatures in range to make a Charisma save or suffer effects based on their current hit points.", tags: ["srd-5.1", "level-7", "metadata-only", "cleric"], mechanics: { level: 7, school: "evocation", castingTime: "bonus-action", actionCost: "bonus-action", range: 30, target: "area", duration: "instantaneous", attackType: "none", saveType: "charisma", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: false }, effects: [] } },
    { reference: etherealness, name: "Etherealness", description: "Steps you onto the Ethereal Plane for the duration, allowing movement through the Border Ethereal.", tags: ["srd-5.1", "level-7", "metadata-only", "bard", "cleric", "sorcerer", "warlock", "wizard"], mechanics: { level: 7, school: "transmutation", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "8-hours", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: fingerOfDeath, name: "Finger of Death", description: "Hurls negative energy at a creature, dealing 7d8+30 necrotic damage and killing it on a failed Constitution save.", tags: ["srd-5.1", "level-7", "metadata-only", "sorcerer", "warlock", "wizard"], mechanics: { level: 7, school: "necromancy", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "instantaneous", attackType: "none", saveType: "constitution", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: fireStorm, name: "Fire Storm", description: "Fills up to ten 10-foot cubes with roaring flame that deals fire damage to creatures in the area.", tags: ["srd-5.1", "level-7", "metadata-only", "cleric", "druid", "sorcerer"], mechanics: { level: 7, school: "evocation", castingTime: "action", actionCost: "action", range: 150, target: "area", duration: "instantaneous", attackType: "none", saveType: "dexterity", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: forcecage, name: "Forcecage", description: "Creates an immobile, invisible cage or box of force that traps creatures, who must make a Charisma save to escape by teleportation.", tags: ["srd-5.1", "level-7", "metadata-only", "bard", "warlock", "wizard"], mechanics: { level: 7, school: "evocation", castingTime: "action", actionCost: "action", range: 100, target: "area", duration: "1-hour", attackType: "none", saveType: "charisma", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "ruby dust worth 1,500 gp" }, effects: [] } },
    { reference: mirageArcane, name: "Mirage Arcane", description: "Makes terrain in a 1-mile area look, sound, smell, and even feel like another sort of terrain.", tags: ["srd-5.1", "level-7", "metadata-only", "bard", "druid", "wizard"], mechanics: { level: 7, school: "illusion", castingTime: "10-minutes", actionCost: "action", range: 0, target: "area", duration: "8-hours", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: mordenkainensMagnificentMansion, name: "Mordenkainen's Magnificent Mansion", description: "Creates an extradimensional dwelling with a portal entrance that lasts for the duration.", tags: ["srd-5.1", "level-7", "metadata-only", "bard", "wizard"], mechanics: { level: 7, school: "conjuration", castingTime: "1-minute", actionCost: "action", range: 300, target: "area", duration: "8-hours", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a miniature portal carved from ivory, a small piece of polished marble, and a tiny silver spoon" }, effects: [] } },
    { reference: mordenkainensSword, name: "Mordenkainen's Sword", description: "Creates a spectral sword that attacks a creature of your choice while you concentrate.", tags: ["srd-5.1", "level-7", "metadata-only", "bard", "wizard"], mechanics: { level: 7, school: "evocation", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "concentration", attackType: "melee", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a miniature platinum sword with a grip and pommel of copper and zinc worth 250 gp" }, effects: [] } },
    { reference: planeShift, name: "Plane Shift", description: "Transports you and willing creatures to another plane, or banishes an unwilling creature with a melee spell attack and Charisma save.", tags: ["srd-5.1", "level-7", "metadata-only", "cleric", "druid", "sorcerer", "warlock", "wizard"], mechanics: { level: 7, school: "conjuration", castingTime: "action", actionCost: "action", range: 5, target: "single", duration: "instantaneous", attackType: "melee", saveType: "charisma", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a forked, metal rod worth at least 250 gp, attuned to a particular plane of existence" }, effects: [] } },
    { reference: prismaticSpray, name: "Prismatic Spray", description: "Fires eight multicolored rays in a 60-foot cone, each imposing a different magical effect on creatures in the area.", tags: ["srd-5.1", "level-7", "metadata-only", "sorcerer", "wizard"], mechanics: { level: 7, school: "evocation", castingTime: "action", actionCost: "action", range: 0, target: "area", duration: "instantaneous", attackType: "none", saveType: "dexterity", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: projectImage, name: "Project Image", description: "Creates an illusory duplicate of yourself that you can move and speak through while you concentrate.", tags: ["srd-5.1", "level-7", "metadata-only", "bard", "wizard"], mechanics: { level: 7, school: "illusion", castingTime: "action", actionCost: "action", range: 10000, target: "self", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a small replica of you made from materials worth 5 gp" }, effects: [] } },
    { reference: regenerate, name: "Regenerate", description: "A touched creature regains 4d8+15 hit points and regrows severed body parts over the duration.", tags: ["srd-5.1", "level-7", "metadata-only", "bard", "cleric", "druid"], mechanics: { level: 7, school: "transmutation", castingTime: "1-minute", actionCost: "action", range: 5, target: "ally", duration: "1-hour", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a prayer wheel and holy water" }, effects: [] } },
    { reference: resurrection, name: "Resurrection", description: "Restores a dead creature that has been dead no longer than a century to life with full hit points.", tags: ["srd-5.1", "level-7", "metadata-only", "bard", "cleric"], mechanics: { level: 7, school: "necromancy", castingTime: "1-hour", actionCost: "action", range: 5, target: "ally", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a diamond worth at least 1,000 gp, which the spell consumes" }, effects: [] } },
    { reference: reverseGravity, name: "Reverse Gravity", description: "Reverses gravity in a 50-foot radius cylinder, causing creatures and objects to fall upward while you concentrate.", tags: ["srd-5.1", "level-7", "metadata-only", "druid", "sorcerer", "wizard"], mechanics: { level: 7, school: "transmutation", castingTime: "action", actionCost: "action", range: 100, target: "area", duration: "concentration", attackType: "none", saveType: "dexterity", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a lodestone and iron filings" }, effects: [] } },
    { reference: sequester, name: "Sequester", description: "Turns a willing creature or object invisible and places it in a state of suspended animation until the spell ends.", tags: ["srd-5.1", "level-7", "metadata-only", "wizard"], mechanics: { level: 7, school: "transmutation", castingTime: "action", actionCost: "action", range: 5, target: "ally", duration: "8-hours", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a powder of diamond, emerald, ruby, and sapphire dust worth at least 5,000 gp, which the spell consumes" }, effects: [] } },
    { reference: simulacrum, name: "Simulacrum", description: "Creates a partially real duplicate of a beast or humanoid that obeys your commands.", tags: ["srd-5.1", "level-7", "metadata-only", "wizard"], mechanics: { level: 7, school: "illusion", castingTime: "1-hour", actionCost: "action", range: 5, target: "single", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "snow or ice to make a life-size copy of the creature; a piece of the creature placed inside; and powdered ruby worth 1,500 gp, consumed by the spell" }, effects: [] } },
    { reference: symbol, name: "Symbol", description: "Inscribes a glyph that triggers a chosen magical effect when a creature enters its area or interacts with it.", tags: ["srd-5.1", "level-7", "metadata-only", "bard", "cleric", "wizard"], mechanics: { level: 7, school: "abjuration", castingTime: "1-minute", actionCost: "action", range: 5, target: "area", duration: "8-hours", attackType: "none", saveType: "wisdom", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "mercury, phosphorus, and powdered diamond and opal with a total value of at least 1,000 gp, which the spell consumes" }, effects: [] } },
    { reference: teleport, name: "Teleport", description: "Instantly transports you and up to eight willing creatures to a destination you are familiar with.", tags: ["srd-5.1", "level-7", "metadata-only", "bard", "sorcerer", "wizard"], mechanics: { level: 7, school: "conjuration", castingTime: "action", actionCost: "action", range: 10, target: "self", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: false }, effects: [] } },
  ];
}
