import type { StarterReferences } from "../references.js";

/**
 * SRD 5.1 5th-level spells. Each file under `spells/` owns one level band.
 * Definitions are bounded metadata only: every `effects` array is empty and
 * spell execution is not implemented for this band.
 */
export function buildLevel5Spells(refs: StarterReferences) {
  const spell = (slug: string) => refs.ref("spell", `srd-5.1:spell:${slug}`);
  return [
    { reference: spell("animate-objects"), name: "Animate Objects", description: "Objects within range come to life and fight under the caster's command while the caster concentrates.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "sorcerer", "wizard"], mechanics: { level: 5, school: "transmutation", castingTime: "action", actionCost: "action", range: 120, target: "area", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: spell("antilife-shell"), name: "Antilife Shell", description: "A shimmering barrier moves with the caster and hedges out creatures other than undead and constructs while the caster concentrates.", tags: ["srd-5.1", "level-5", "metadata-only", "druid"], mechanics: { level: 5, school: "abjuration", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: spell("arcane-hand"), name: "Arcane Hand", description: "A large hand of force appears at the caster's command and can strike, push, grapple, or interpose.", tags: ["srd-5.1", "level-5", "metadata-only", "wizard"], mechanics: { level: 5, school: "evocation", castingTime: "action", actionCost: "action", range: 120, target: "single", duration: "concentration", attackType: "melee", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "an eggshell and a snakeskin glove" }, effects: [] } },
    { reference: spell("awaken"), name: "Awaken", description: "After a long ritual, a beast or plant gains an Intelligence of 10 and the ability to speak one language the caster knows.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "druid"], mechanics: { level: 5, school: "transmutation", actionCost: "action", range: 5, target: "single", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "an agate worth at least 1,000 gp, which the spell consumes" }, effects: [] } },
    { reference: spell("cloudkill"), name: "Cloudkill", description: "A 20-foot-radius sphere of poisonous fog deals 5d8 poison damage to creatures that enter it or start their turn there.", tags: ["srd-5.1", "level-5", "metadata-only", "sorcerer", "wizard"], mechanics: { level: 5, school: "conjuration", castingTime: "action", actionCost: "action", range: 120, target: "area", duration: "concentration", attackType: "none", saveType: "constitution", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: spell("commune"), name: "Commune", description: "The caster contacts a divine proxy and asks up to three questions answerable with a yes or no.", tags: ["srd-5.1", "level-5", "metadata-only", "cleric"], mechanics: { level: 5, school: "divination", castingTime: "1-minute", actionCost: "action", range: 0, target: "self", duration: "1-minute", attackType: "none", saveType: "none", concentration: false, ritual: true, components: { verbal: true, somatic: true, material: true, materialDescription: "incense and a vial of holy or unholy water" }, effects: [] } },
    { reference: spell("commune-with-nature"), name: "Commune with Nature", description: "The caster gains knowledge of the surrounding terrain within 3 miles outdoors or 300 feet underground.", tags: ["srd-5.1", "level-5", "metadata-only", "druid", "ranger"], mechanics: { level: 5, school: "divination", castingTime: "1-minute", actionCost: "action", range: 0, target: "self", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: true, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: spell("cone-of-cold"), name: "Cone of Cold", description: "A 60-foot cone of cold deals 8d8 cold damage to creatures that fail a Constitution saving throw.", tags: ["srd-5.1", "level-5", "metadata-only", "sorcerer", "wizard"], mechanics: { level: 5, school: "evocation", castingTime: "action", actionCost: "action", range: 0, target: "area", duration: "instantaneous", attackType: "none", saveType: "constitution", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a small crystal or glass cone" }, effects: [] } },
    { reference: spell("conjure-elemental"), name: "Conjure Elemental", description: "An elemental of challenge rating 5 or lower appears and obeys the caster's verbal commands while the caster concentrates.", tags: ["srd-5.1", "level-5", "metadata-only", "druid", "wizard"], mechanics: { level: 5, school: "conjuration", castingTime: "1-minute", actionCost: "action", range: 90, target: "area", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "burning incense for air, soft clay for earth, sulfur and phosphorus for fire, or water and sand for water" }, effects: [] } },
    { reference: spell("contact-other-plane"), name: "Contact Other Plane", description: "The caster contacts an extraplanar intelligence and, on a successful Intelligence save, can ask up to five questions.", tags: ["srd-5.1", "level-5", "metadata-only", "warlock", "wizard"], mechanics: { level: 5, school: "divination", castingTime: "1-minute", actionCost: "action", range: 0, target: "self", duration: "1-minute", attackType: "none", saveType: "intelligence", concentration: false, ritual: true, components: { verbal: true, somatic: false, material: false }, effects: [] } },
    { reference: spell("contagion"), name: "Contagion", description: "A melee spell attack infects a creature with a disease that imposes a lasting debilitation.", tags: ["srd-5.1", "level-5", "metadata-only", "cleric", "druid"], mechanics: { level: 5, school: "necromancy", castingTime: "action", actionCost: "action", range: 5, target: "enemy", attackType: "melee", saveType: "constitution", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: spell("creation"), name: "Creation", description: "The caster shapes shadow material into a nonliving object no larger than a 5-foot cube whose duration depends on its material.", tags: ["srd-5.1", "level-5", "metadata-only", "sorcerer", "wizard"], mechanics: { level: 5, school: "illusion", castingTime: "1-minute", actionCost: "action", range: 30, target: "single", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a tiny piece of matter of the same type of the item you plan to create" }, effects: [] } },
    { reference: spell("dispel-evil-and-good"), name: "Dispel Evil and Good", description: "The caster is protected from fey, undead, and extraplanar creatures and can break enchantments or dismiss such a creature.", tags: ["srd-5.1", "level-5", "metadata-only", "cleric", "paladin"], mechanics: { level: 5, school: "abjuration", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "concentration", attackType: "none", saveType: "charisma", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "holy water or powdered silver and iron" }, effects: [] } },
    { reference: spell("dominate-person"), name: "Dominate Person", description: "A humanoid that fails a Wisdom save is charmed and obeys the caster's telepathic commands while the caster concentrates.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "sorcerer", "wizard"], mechanics: { level: 5, school: "enchantment", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "concentration", attackType: "none", saveType: "wisdom", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: spell("dream"), name: "Dream", description: "A messenger enters a known creature's dreams and can deliver a nightmare that deals 3d6 psychic damage and denies rest.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "warlock", "wizard"], mechanics: { level: 5, school: "illusion", castingTime: "1-minute", actionCost: "action", range: 0, target: "single", duration: "8-hours", attackType: "none", saveType: "wisdom", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a handful of sand, a dab of ink, and a writing quill plucked from a sleeping bird" }, effects: [] } },
    { reference: spell("flame-strike"), name: "Flame Strike", description: "A divine column of fire deals 4d6 fire damage and 4d6 radiant damage to creatures in a 10-foot-radius, 40-foot-high cylinder.", tags: ["srd-5.1", "level-5", "metadata-only", "cleric"], mechanics: { level: 5, school: "evocation", castingTime: "action", actionCost: "action", range: 60, target: "area", duration: "instantaneous", attackType: "none", saveType: "dexterity", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a pinch of sulfur" }, effects: [] } },
    { reference: spell("geas"), name: "Geas", description: "A creature that fails a Wisdom save is charmed into carrying out or refraining from a course of action.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "cleric", "druid", "paladin", "wizard"], mechanics: { level: 5, school: "enchantment", castingTime: "1-minute", actionCost: "action", range: 60, target: "enemy", attackType: "none", saveType: "wisdom", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: false }, effects: [] } },
    { reference: spell("greater-restoration"), name: "Greater Restoration", description: "The caster touches a creature to reduce its exhaustion by one or end a charm, curse, petrification, or ability reduction effect.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "cleric", "druid"], mechanics: { level: 5, school: "abjuration", castingTime: "action", actionCost: "action", range: 5, target: "ally", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "diamond dust worth at least 100 gp, which the spell consumes" }, effects: [] } },
    { reference: spell("hallow"), name: "Hallow", description: "The caster infuses an area up to 60 feet in radius with holy or unholy power and one bound extra effect.", tags: ["srd-5.1", "level-5", "metadata-only", "cleric"], mechanics: { level: 5, school: "evocation", actionCost: "action", range: 5, target: "area", attackType: "none", saveType: "charisma", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "herbs, oils, and incense worth at least 1,000 gp, which the spell consumes" }, effects: [] } },
    { reference: spell("hold-monster"), name: "Hold Monster", description: "A creature that fails a Wisdom save is paralyzed for the duration while the caster concentrates.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "sorcerer", "warlock", "wizard"], mechanics: { level: 5, school: "enchantment", castingTime: "action", actionCost: "action", range: 90, target: "enemy", duration: "concentration", attackType: "none", saveType: "wisdom", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a small piece of iron" }, effects: [] } },
    { reference: spell("insect-plague"), name: "Insect Plague", description: "A 20-foot-radius sphere of biting locusts deals 4d10 piercing damage to creatures in the area.", tags: ["srd-5.1", "level-5", "metadata-only", "cleric", "druid", "sorcerer"], mechanics: { level: 5, school: "conjuration", castingTime: "action", actionCost: "action", range: 300, target: "area", duration: "concentration", attackType: "none", saveType: "constitution", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a few grains of sugar, some kernels of grain, and a smear of fat" }, effects: [] } },
    { reference: spell("legend-lore"), name: "Legend Lore", description: "The caster learns legends and secrets about a person, place, or object of importance.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "cleric", "wizard"], mechanics: { level: 5, school: "divination", castingTime: "10-minutes", actionCost: "action", range: 0, target: "self", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "incense worth 250 gp that the spell consumes and four ivory strips worth 50 gp each" }, effects: [] } },
    { reference: spell("mass-cure-wounds"), name: "Mass Cure Wounds", description: "Up to six creatures in a 30-foot-radius sphere regain 3d8 plus the caster's spellcasting ability modifier hit points.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "cleric", "druid"], mechanics: { level: 5, school: "conjuration", castingTime: "action", actionCost: "action", range: 60, target: "ally", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: spell("mislead"), name: "Mislead", description: "The caster turns invisible and projects an illusory double that can move and speak while the caster concentrates.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "wizard"], mechanics: { level: 5, school: "illusion", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: false, somatic: true, material: false }, effects: [] } },
    { reference: spell("modify-memory"), name: "Modify Memory", description: "A creature that fails a Wisdom save has up to 10 minutes of memory altered while the caster concentrates.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "wizard"], mechanics: { level: 5, school: "enchantment", castingTime: "action", actionCost: "action", range: 30, target: "enemy", duration: "concentration", attackType: "none", saveType: "wisdom", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: spell("passwall"), name: "Passwall", description: "The caster creates a passage through wood, plaster, or stone that lasts for the duration.", tags: ["srd-5.1", "level-5", "metadata-only", "wizard"], mechanics: { level: 5, school: "transmutation", castingTime: "action", actionCost: "action", range: 30, target: "single", duration: "1-hour", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a pinch of sesame seeds" }, effects: [] } },
    { reference: spell("planar-binding"), name: "Planar Binding", description: "A celestial, elemental, fey, or fiend must succeed on a Charisma save or serve the caster for the duration.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "cleric", "druid", "wizard"], mechanics: { level: 5, school: "abjuration", castingTime: "1-hour", actionCost: "action", range: 60, target: "enemy", attackType: "none", saveType: "charisma", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a jewel worth at least 1,000 gp, which the spell consumes" }, effects: [] } },
    { reference: spell("raise-dead"), name: "Raise Dead", description: "The caster returns a dead creature that has been dead no longer than 10 days to life with 1 hit point.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "cleric", "paladin"], mechanics: { level: 5, school: "necromancy", castingTime: "1-hour", actionCost: "action", range: 5, target: "ally", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a diamond worth at least 500 gp, which the spell consumes" }, effects: [] } },
    { reference: spell("reincarnate"), name: "Reincarnate", description: "The caster forms a new adult body for a dead creature and reincarnates it with a random race.", tags: ["srd-5.1", "level-5", "metadata-only", "druid"], mechanics: { level: 5, school: "transmutation", castingTime: "1-hour", actionCost: "action", range: 5, target: "ally", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "rare oils and unguents worth at least 1,000 gp, which the spell consumes" }, effects: [] } },
    { reference: spell("scrying"), name: "Scrying", description: "The caster can see and hear a chosen creature or location on the same plane while concentrating.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "cleric", "druid", "warlock", "wizard"], mechanics: { level: 5, school: "divination", castingTime: "10-minutes", actionCost: "action", range: 0, target: "single", duration: "concentration", attackType: "none", saveType: "wisdom", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a focus worth at least 1,000 gp, such as a crystal ball, a silver mirror, or a font filled with holy water" }, effects: [] } },
    { reference: spell("seeming"), name: "Seeming", description: "The caster changes the appearance of any number of creatures within range for the duration.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "sorcerer", "wizard"], mechanics: { level: 5, school: "illusion", castingTime: "action", actionCost: "action", range: 30, target: "area", duration: "8-hours", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: spell("telekinesis"), name: "Telekinesis", description: "The caster moves or manipulates a creature or object by thought while concentrating.", tags: ["srd-5.1", "level-5", "metadata-only", "sorcerer", "wizard"], mechanics: { level: 5, school: "transmutation", castingTime: "action", actionCost: "action", range: 60, target: "single", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: spell("telepathic-bond"), name: "Telepathic Bond", description: "Up to eight willing creatures within range are linked by telepathy across any distance for the duration.", tags: ["srd-5.1", "level-5", "metadata-only", "wizard"], mechanics: { level: 5, school: "divination", castingTime: "action", actionCost: "action", range: 30, target: "ally", duration: "1-hour", attackType: "none", saveType: "none", concentration: false, ritual: true, components: { verbal: true, somatic: true, material: true, materialDescription: "pieces of eggshell from two different kinds of creatures" }, effects: [] } },
    { reference: spell("teleportation-circle"), name: "Teleportation Circle", description: "The caster draws a circle that opens a short-lived portal to a permanent teleportation circle on the same plane.", tags: ["srd-5.1", "level-5", "metadata-only", "bard", "sorcerer", "wizard"], mechanics: { level: 5, school: "conjuration", castingTime: "1-minute", actionCost: "action", range: 10, target: "area", duration: "1-round", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: true, materialDescription: "rare chalks and inks infused with precious gems worth 50 gp, which the spell consumes" }, effects: [] } },
    { reference: spell("tree-stride"), name: "Tree Stride", description: "The caster moves from one tree to another of the same kind within 500 feet while concentrating.", tags: ["srd-5.1", "level-5", "metadata-only", "druid", "ranger"], mechanics: { level: 5, school: "conjuration", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: spell("wall-of-force"), name: "Wall of Force", description: "An invisible wall of force springs into existence and is immune to most damage and spells while the caster concentrates.", tags: ["srd-5.1", "level-5", "metadata-only", "wizard"], mechanics: { level: 5, school: "evocation", castingTime: "action", actionCost: "action", range: 120, target: "area", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a pinch of powder made by crushing a clear gemstone" }, effects: [] } },
    { reference: spell("wall-of-stone"), name: "Wall of Stone", description: "A wall of stone springs into existence and can be shaped into panels, with creatures in its path able to dodge with a Dexterity save.", tags: ["srd-5.1", "level-5", "metadata-only", "druid", "sorcerer", "wizard"], mechanics: { level: 5, school: "evocation", castingTime: "action", actionCost: "action", range: 120, target: "area", duration: "concentration", attackType: "none", saveType: "dexterity", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a small block of granite" }, effects: [] } },
  ];
}
