import type { StarterReferences } from "../references.js";

/** SRD cantrips (spell level 0). Each file under `spells/` owns one level band. */
export function buildLevel0Spells(refs: StarterReferences) {
  const { light, wizardCantrip, rayOfFrost, mageHand, sacredFlame } = refs;
  return [
    { reference: light, name: "Light", description: "Catalog coverage marker only; casting and spell effects are not implemented.", tags: ["srd-5.1", "unsupported-runtime"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 0, target: "single", duration: "1-hour", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: true, materialDescription: "a firefly or phosphorescent moss" }, effects: [] } },
    { reference: wizardCantrip, name: "Fire Bolt", description: "A level-zero Wizard cantrip reference; casting and damage are not executable in this bounded pack.", tags: ["srd-5.1", "wizard-1", "unsupported-runtime"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 120, target: "enemy", duration: "instantaneous", attackType: "ranged", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "damage", damageType: "fire", dice: { count: 1, sides: 10, modifier: 0 } }] } },
    { reference: rayOfFrost, name: "Ray of Frost", description: "A level-zero Wizard cantrip reference; casting and slowing are not executable in this bounded pack.", tags: ["srd-5.1", "wizard-1", "unsupported-runtime"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "instantaneous", attackType: "ranged", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "damage", damageType: "frost", dice: { count: 1, sides: 8, modifier: 0 } }] } },
    { reference: mageHand, name: "Mage Hand", description: "A level-zero Wizard cantrip reference; its interaction and carrying rules are metadata-only.", tags: ["srd-5.1", "cantrip", "metadata-only"], mechanics: { level: 0, school: "conjuration", castingTime: "action", actionCost: "action", range: 30, target: "single", duration: "1-minute", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a bit of fleece" }, effects: [] } },
    { reference: sacredFlame, name: "Sacred Flame", description: "A level-zero Cleric cantrip reference; saving throw and radiant damage execution are unsupported.", tags: ["srd-5.1", "cantrip", "metadata-only"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "instantaneous", attackType: "none", saveType: "dexterity", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "damage", damageType: "radiant", dice: { count: 1, sides: 8, modifier: 0 } }] } },
  ];
}
