import type { StarterReferences } from "../references.js";

/** SRD 5.1 8th-level spells. Each file under `spells/` owns one level band. */
export function buildLevel8Spells(refs: StarterReferences) {
  const { ref } = refs;
  return [
    { reference: ref("spell", "srd-5.1:spell:animal-shapes"), name: "Animal Shapes", description: "The caster transforms willing creatures within range into beasts of the caster's choice for the duration.", tags: ["srd-5.1", "level-8", "metadata-only", "druid"], mechanics: { level: 8, school: "transmutation", castingTime: "action", actionCost: "action", range: 30, target: "ally", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:antimagic-field"), name: "Antimagic Field", description: "A 10-foot-radius invisible sphere around the caster suppresses magic and magical effects within it.", tags: ["srd-5.1", "level-8", "metadata-only", "cleric", "wizard"], mechanics: { level: 8, school: "abjuration", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a pinch of powdered iron or iron filings" }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:antipathy-sympathy"), name: "Antipathy/Sympathy", description: "The caster marks a creature or object to repel or attract chosen kinds of creatures for the duration.", tags: ["srd-5.1", "level-8", "metadata-only", "druid", "wizard"], mechanics: { level: 8, school: "enchantment", castingTime: "1-hour", actionCost: "action", range: 60, target: "single", duration: "8-hours", attackType: "none", saveType: "wisdom", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a lump of alum soaked in vinegar or a drop of honey" }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:clone"), name: "Clone", description: "The caster grows an inert duplicate of a living creature that can receive its soul if the original dies.", tags: ["srd-5.1", "level-8", "metadata-only", "wizard"], mechanics: { level: 8, school: "necromancy", castingTime: "1-hour", actionCost: "action", range: 5, target: "single", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a diamond worth at least 1,000 gp and a vessel worth at least 2,000 gp" }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:control-weather"), name: "Control Weather", description: "The caster takes control of the weather within a five-mile radius for the duration.", tags: ["srd-5.1", "level-8", "metadata-only", "cleric", "druid", "wizard"], mechanics: { level: 8, school: "transmutation", castingTime: "10-minutes", actionCost: "action", range: 0, target: "area", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "burning incense and bits of earth and wood mixed in water" }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:demiplane"), name: "Demiplane", description: "The caster creates a shadowy door on a flat surface that opens into a 30-foot demiplane.", tags: ["srd-5.1", "level-8", "metadata-only", "warlock", "wizard"], mechanics: { level: 8, school: "conjuration", castingTime: "action", actionCost: "action", range: 60, target: "area", duration: "1-hour", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: false, somatic: true, material: false }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:dominate-monster"), name: "Dominate Monster", description: "The caster charms one creature of any type, controlling its actions while the spell lasts.", tags: ["srd-5.1", "level-8", "metadata-only", "bard", "sorcerer", "warlock", "wizard"], mechanics: { level: 8, school: "enchantment", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "concentration", attackType: "none", saveType: "wisdom", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:earthquake"), name: "Earthquake", description: "The caster shakes the ground in a 100-foot radius, knocking creatures prone and damaging structures.", tags: ["srd-5.1", "level-8", "metadata-only", "cleric", "druid", "sorcerer"], mechanics: { level: 8, school: "evocation", castingTime: "action", actionCost: "action", range: 500, target: "area", duration: "concentration", attackType: "none", saveType: "dexterity", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a pinch of dirt, a piece of rock, and a lump of clay" }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:feeblemind"), name: "Feeblemind", description: "The caster blasts the mind of one creature, reducing its Intelligence and Charisma scores to 1 on a failed save.", tags: ["srd-5.1", "level-8", "metadata-only", "bard", "druid", "warlock", "wizard"], mechanics: { level: 8, school: "enchantment", castingTime: "action", actionCost: "action", range: 150, target: "enemy", duration: "instantaneous", attackType: "none", saveType: "intelligence", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a handful of clay, crystal, glass, or mineral spheres" }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:glibness"), name: "Glibness", description: "The caster's speech becomes magically persuasive, and Charisma checks can be replaced with a flat 15 result.", tags: ["srd-5.1", "level-8", "metadata-only", "bard", "warlock"], mechanics: { level: 8, school: "transmutation", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "1-hour", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:holy-aura"), name: "Holy Aura", description: "Divine light surrounds the caster, protecting allies and blinding fiends and undead that strike them.", tags: ["srd-5.1", "level-8", "metadata-only", "cleric"], mechanics: { level: 8, school: "abjuration", castingTime: "action", actionCost: "action", range: 0, target: "area", duration: "concentration", attackType: "none", saveType: "constitution", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a tiny reliquary worth at least 1,000 gp containing a sacred relic" }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:incendiary-cloud"), name: "Incendiary Cloud", description: "A swirling cloud of embers fills a 20-foot radius and burns creatures that start their turn inside it.", tags: ["srd-5.1", "level-8", "metadata-only", "sorcerer", "wizard"], mechanics: { level: 8, school: "conjuration", castingTime: "action", actionCost: "action", range: 150, target: "area", duration: "concentration", attackType: "none", saveType: "dexterity", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:maze"), name: "Maze", description: "The caster banishes a creature into a labyrinthine demiplane, where it remains until it escapes.", tags: ["srd-5.1", "level-8", "metadata-only", "wizard"], mechanics: { level: 8, school: "conjuration", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:mind-blank"), name: "Mind Blank", description: "The caster wards a creature's mind against psychic damage, mind reading, and divination for a day.", tags: ["srd-5.1", "level-8", "metadata-only", "bard", "wizard"], mechanics: { level: 8, school: "abjuration", castingTime: "action", actionCost: "action", range: 5, target: "ally", duration: "8-hours", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:power-word-stun"), name: "Power Word Stun", description: "The caster speaks a word of power that stuns one creature with 150 hit points or fewer.", tags: ["srd-5.1", "level-8", "metadata-only", "bard", "sorcerer", "warlock", "wizard"], mechanics: { level: 8, school: "enchantment", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: false }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:sunburst"), name: "Sunburst", description: "A burst of brilliant light fills a 60-foot radius, damaging and blinding creatures that fail a Constitution save.", tags: ["srd-5.1", "level-8", "metadata-only", "druid", "sorcerer", "wizard"], mechanics: { level: 8, school: "evocation", castingTime: "action", actionCost: "action", range: 150, target: "area", duration: "instantaneous", attackType: "none", saveType: "constitution", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a piece of sunstone" }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:telepathy"), name: "Telepathy", description: "The caster forges a telepathic link with a willing creature, allowing silent communication across any distance.", tags: ["srd-5.1", "level-8", "metadata-only", "wizard"], mechanics: { level: 8, school: "evocation", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "8-hours", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("spell", "srd-5.1:spell:tsunami"), name: "Tsunami", description: "The caster conjures a towering wall of water that sweeps across the area, crushing and carrying creatures.", tags: ["srd-5.1", "level-8", "metadata-only", "druid", "sorcerer"], mechanics: { level: 8, school: "conjuration", castingTime: "1-minute", actionCost: "action", range: 0, target: "area", duration: "concentration", attackType: "none", saveType: "strength", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
  ];
}
