import type { StarterReferences } from "../references.js";

/** SRD cantrips (spell level 0). Each file under `spells/` owns one level band. */
export function buildLevel0Spells(refs: StarterReferences) {
  const { light, wizardCantrip, rayOfFrost, mageHand, sacredFlame } = refs;
  const ref = (slug: string) => refs.ref("spell", `srd-5.1:spell:${slug}`);
  return [
    { reference: light, name: "Light", description: "Catalog coverage marker only; casting and spell effects are not implemented.", tags: ["srd-5.1", "unsupported-runtime"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 0, target: "single", duration: "1-hour", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: true, materialDescription: "a firefly or phosphorescent moss" }, effects: [] } },
    { reference: wizardCantrip, name: "Fire Bolt", description: "A level-zero Wizard cantrip reference; casting and damage are not executable in this bounded pack.", tags: ["srd-5.1", "wizard-1", "unsupported-runtime"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 120, target: "enemy", duration: "instantaneous", attackType: "ranged", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "damage", damageType: "fire", dice: { count: 1, sides: 10, modifier: 0 } }] } },
    { reference: rayOfFrost, name: "Ray of Frost", description: "A level-zero Wizard cantrip reference; casting and slowing are not executable in this bounded pack.", tags: ["srd-5.1", "wizard-1", "unsupported-runtime"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "instantaneous", attackType: "ranged", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "damage", damageType: "frost", dice: { count: 1, sides: 8, modifier: 0 } }] } },
    { reference: mageHand, name: "Mage Hand", description: "A level-zero Wizard cantrip reference; its interaction and carrying rules are metadata-only.", tags: ["srd-5.1", "cantrip", "metadata-only"], mechanics: { level: 0, school: "conjuration", castingTime: "action", actionCost: "action", range: 30, target: "single", duration: "1-minute", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a bit of fleece" }, effects: [] } },
    { reference: sacredFlame, name: "Sacred Flame", description: "A level-zero Cleric cantrip reference; saving throw and radiant damage execution are unsupported.", tags: ["srd-5.1", "cantrip", "metadata-only"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "instantaneous", attackType: "none", saveType: "dexterity", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "damage", damageType: "radiant", dice: { count: 1, sides: 8, modifier: 0 } }] } },
    { reference: ref("acid-splash"), name: "Acid Splash", description: "You hurl a bubble of acid at one creature, or two creatures within 5 feet of each other, forcing a Dexterity saving throw or 1d6 acid damage.", tags: ["srd-5.1", "cantrip", "metadata-only", "sorcerer", "wizard"], mechanics: { level: 0, school: "conjuration", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "instantaneous", attackType: "none", saveType: "dexterity", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("blade-ward"), name: "Blade Ward", description: "You trace a sigil of warding to gain resistance against bludgeoning, piercing, and slashing damage from weapon attacks until the end of your next turn.", tags: ["srd-5.1", "cantrip", "metadata-only", "bard", "sorcerer", "warlock", "wizard"], mechanics: { level: 0, school: "abjuration", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "1-round", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("chill-touch"), name: "Chill Touch", description: "A ghostly skeletal hand makes a ranged spell attack for 1d8 necrotic damage and prevents the target from regaining hit points until the start of your next turn.", tags: ["srd-5.1", "cantrip", "metadata-only", "sorcerer", "warlock", "wizard"], mechanics: { level: 0, school: "necromancy", castingTime: "action", actionCost: "action", range: 120, target: "enemy", duration: "1-round", attackType: "ranged", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("dancing-lights"), name: "Dancing Lights", description: "You create up to four torch-sized lights that hover and can be moved within range for the duration.", tags: ["srd-5.1", "cantrip", "metadata-only", "bard", "sorcerer", "wizard"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 120, target: "area", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a bit of phosphorus or wychwood, or a glowworm" }, effects: [] } },
    { reference: ref("druidcraft"), name: "Druidcraft", description: "Whispering to the spirits of nature, you create a minor sensory or weather effect within range.", tags: ["srd-5.1", "cantrip", "metadata-only", "druid"], mechanics: { level: 0, school: "transmutation", castingTime: "action", actionCost: "action", range: 30, target: "area", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("eldritch-blast"), name: "Eldritch Blast", description: "A beam of crackling energy streaks toward a creature, making a ranged spell attack that deals 1d10 force damage on a hit.", tags: ["srd-5.1", "cantrip", "metadata-only", "warlock"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 120, target: "enemy", duration: "instantaneous", attackType: "ranged", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("friends"), name: "Friends", description: "You gain advantage on Charisma checks against one nonhostile creature for the duration, after which it becomes hostile toward you.", tags: ["srd-5.1", "cantrip", "metadata-only", "bard", "sorcerer", "warlock", "wizard"], mechanics: { level: 0, school: "enchantment", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: false, somatic: true, material: true, materialDescription: "a small amount of makeup applied to the face as this spell is cast" }, effects: [] } },
    { reference: ref("guidance"), name: "Guidance", description: "You touch a willing creature that can then roll a d4 and add it to one ability check of its choice before the spell ends.", tags: ["srd-5.1", "cantrip", "metadata-only", "cleric", "druid"], mechanics: { level: 0, school: "divination", castingTime: "action", actionCost: "action", range: 5, target: "ally", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("mending"), name: "Mending", description: "This spell repairs a single break or tear in an object you touch, such as a broken chain link, a torn cloak, or a leaking wineskin.", tags: ["srd-5.1", "cantrip", "metadata-only", "bard", "cleric", "druid", "sorcerer", "warlock", "wizard"], mechanics: { level: 0, school: "transmutation", castingTime: "1-minute", actionCost: "action", range: 5, target: "single", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "two lodestones" }, effects: [] } },
    { reference: ref("message"), name: "Message", description: "You point at a creature and whisper a message that only the target hears, and it can reply in a whisper only you can hear.", tags: ["srd-5.1", "cantrip", "metadata-only", "bard", "sorcerer", "wizard"], mechanics: { level: 0, school: "transmutation", castingTime: "action", actionCost: "action", range: 120, target: "single", duration: "1-round", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a short piece of copper wire" }, effects: [] } },
    { reference: ref("minor-illusion"), name: "Minor Illusion", description: "You create a sound or an image of an object within range that lasts for the duration.", tags: ["srd-5.1", "cantrip", "metadata-only", "bard", "sorcerer", "warlock", "wizard"], mechanics: { level: 0, school: "illusion", castingTime: "action", actionCost: "action", range: 30, target: "area", duration: "1-minute", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: false, somatic: true, material: true, materialDescription: "a bit of fleece" }, effects: [] } },
    { reference: ref("poison-spray"), name: "Poison Spray", description: "You project a puff of noxious gas at a creature within range that must succeed on a Constitution saving throw or take 1d12 poison damage.", tags: ["srd-5.1", "cantrip", "metadata-only", "druid", "sorcerer", "warlock", "wizard"], mechanics: { level: 0, school: "conjuration", castingTime: "action", actionCost: "action", range: 10, target: "enemy", duration: "instantaneous", attackType: "none", saveType: "constitution", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("prestidigitation"), name: "Prestidigitation", description: "You perform a minor magical trick that creates one of several small sensory or utility effects within range for the duration.", tags: ["srd-5.1", "cantrip", "metadata-only", "bard", "sorcerer", "warlock", "wizard"], mechanics: { level: 0, school: "transmutation", castingTime: "action", actionCost: "action", range: 10, target: "area", duration: "1-hour", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("produce-flame"), name: "Produce Flame", description: "A flickering flame appears in your hand and can be hurled at a creature as a ranged spell attack for 1d8 fire damage, ending the spell.", tags: ["srd-5.1", "cantrip", "metadata-only", "druid"], mechanics: { level: 0, school: "conjuration", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "10-minutes", attackType: "ranged", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("resistance"), name: "Resistance", description: "You touch a willing creature that can then roll a d4 and add it to one saving throw of its choice before the spell ends.", tags: ["srd-5.1", "cantrip", "metadata-only", "cleric", "druid"], mechanics: { level: 0, school: "abjuration", castingTime: "action", actionCost: "action", range: 5, target: "ally", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a miniature cloak" }, effects: [] } },
    { reference: ref("shillelagh"), name: "Shillelagh", description: "The wood of a club or quarterstaff you hold becomes magical, letting you use your spellcasting ability and a d8 damage die for its attacks.", tags: ["srd-5.1", "cantrip", "metadata-only", "druid"], mechanics: { level: 0, school: "transmutation", castingTime: "bonus-action", actionCost: "bonus-action", range: 5, target: "single", duration: "1-minute", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "mistletoe, a shamrock leaf, and a club or quarterstaff" }, effects: [] } },
    { reference: ref("shocking-grasp"), name: "Shocking Grasp", description: "Lightning springs from your hand in a melee spell attack that deals 1d8 lightning damage and prevents the target from taking reactions until its next turn.", tags: ["srd-5.1", "cantrip", "metadata-only", "sorcerer", "wizard"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 5, target: "enemy", duration: "instantaneous", attackType: "melee", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("spare-the-dying"), name: "Spare the Dying", description: "You touch a living creature at 0 hit points and it becomes stable.", tags: ["srd-5.1", "cantrip", "metadata-only", "cleric"], mechanics: { level: 0, school: "necromancy", castingTime: "action", actionCost: "action", range: 5, target: "ally", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: ref("thaumaturgy"), name: "Thaumaturgy", description: "You manifest a minor wonder, a sign of supernatural power, within range for the duration.", tags: ["srd-5.1", "cantrip", "metadata-only", "cleric"], mechanics: { level: 0, school: "transmutation", castingTime: "action", actionCost: "action", range: 30, target: "area", duration: "1-minute", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: false }, effects: [] } },
    { reference: ref("thorn-whip"), name: "Thorn Whip", description: "A vine-like whip makes a melee spell attack for 1d6 piercing damage and pulls a Large or smaller target up to 10 feet closer.", tags: ["srd-5.1", "cantrip", "metadata-only", "druid"], mechanics: { level: 0, school: "transmutation", castingTime: "action", actionCost: "action", range: 30, target: "enemy", duration: "instantaneous", attackType: "melee", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "the stem of a plant with thorns" }, effects: [] } },
    { reference: ref("true-strike"), name: "True Strike", description: "Your magic grants you advantage on your first attack roll against a target in range on your next turn, provided the spell hasn't ended.", tags: ["srd-5.1", "cantrip", "metadata-only", "bard", "sorcerer", "warlock", "wizard"], mechanics: { level: 0, school: "divination", castingTime: "action", actionCost: "action", range: 30, target: "enemy", duration: "1-round", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: false, somatic: true, material: false }, effects: [] } },
    { reference: ref("vicious-mockery"), name: "Vicious Mockery", description: "A creature that can hear your insults must make a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on its next attack roll.", tags: ["srd-5.1", "cantrip", "metadata-only", "bard"], mechanics: { level: 0, school: "enchantment", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "instantaneous", attackType: "none", saveType: "wisdom", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: false }, effects: [] } },
  ];
}
