import type { StarterReferences } from "../references.js";

/**
 * SRD 5.1 9th-level spells. Bounded metadata only: every definition carries
 * authoritative level, school, casting, range, target, and component facts but
 * an intentional empty `effects` array. Each file under `spells/` owns one band.
 */
export function buildLevel9Spells(refs: StarterReferences) {
  return [
    { reference: refs.ref("spell", "srd-5.1:spell:astral-projection"), name: "Astral Projection", description: "You and up to eight willing creatures project your astral bodies onto the Astral Plane while your material bodies remain in suspended animation.", tags: ["srd-5.1", "level-9", "metadata-only", "cleric", "warlock", "wizard"], mechanics: { level: 9, school: "necromancy", castingTime: "1-hour", actionCost: "action", range: 10, target: "ally", duration: "8-hours", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "for each creature you affect with this spell, you must provide one jacinth worth at least 1,000 gp and one ornately carved bar of silver worth at least 100 gp, all of which the spell consumes" }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:foresight"), name: "Foresight", description: "You touch a willing creature and grant it advantage on attack rolls, ability checks, and saving throws while other creatures have disadvantage on attacks against it.", tags: ["srd-5.1", "level-9", "metadata-only", "bard", "druid", "wizard"], mechanics: { level: 9, school: "divination", castingTime: "1-minute", actionCost: "action", range: 5, target: "ally", duration: "8-hours", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a hummingbird feather" }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:gate"), name: "Gate", description: "You conjure a portal linking an unoccupied space you can see to a precise location on a different plane of existence.", tags: ["srd-5.1", "level-9", "metadata-only", "cleric", "sorcerer", "wizard"], mechanics: { level: 9, school: "conjuration", castingTime: "action", actionCost: "action", range: 60, target: "area", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a diamond worth at least 5,000 gp" }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:imprisonment"), name: "Imprisonment", description: "You create a magical restraint to hold a creature that you can see within range, choosing from one of several binding forms.", tags: ["srd-5.1", "level-9", "metadata-only", "warlock", "wizard"], mechanics: { level: 9, school: "abjuration", castingTime: "1-minute", actionCost: "action", range: 30, target: "enemy", duration: "8-hours", attackType: "none", saveType: "wisdom", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a vellum depiction or a carved statuette in ivory, jade, or a similar material, of the target, and a special component that varies according to the version of the spell you choose, worth at least 500 gp per Hit Die of the target" }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:mass-heal"), name: "Mass Heal", description: "A flood of healing energy restores up to 700 hit points divided among any number of creatures you can see and ends diseases, blindness, and deafness on them.", tags: ["srd-5.1", "level-9", "metadata-only", "cleric"], mechanics: { level: 9, school: "evocation", castingTime: "action", actionCost: "action", range: 60, target: "area", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:meteor-swarm"), name: "Meteor Swarm", description: "Blazing orbs of fire plummet to four points you can see within range, each exploding in a 40-foot-radius sphere.", tags: ["srd-5.1", "level-9", "metadata-only", "sorcerer", "wizard"], mechanics: { level: 9, school: "evocation", castingTime: "action", actionCost: "action", range: 5280, target: "area", duration: "instantaneous", attackType: "none", saveType: "dexterity", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:power-word-heal"), name: "Power Word Heal", description: "A wave of healing energy restores all hit points to one creature you touch and ends its charmed, frightened, paralyzed, and stunned conditions.", tags: ["srd-5.1", "level-9", "metadata-only", "bard", "cleric"], mechanics: { level: 9, school: "evocation", castingTime: "action", actionCost: "action", range: 5, target: "ally", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:power-word-kill"), name: "Power Word Kill", description: "You utter a word of power that instantly slays one creature you can see within range that has 100 hit points or fewer.", tags: ["srd-5.1", "level-9", "metadata-only", "bard", "sorcerer", "warlock", "wizard"], mechanics: { level: 9, school: "enchantment", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: false }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:prismatic-wall"), name: "Prismatic Wall", description: "A shimmering, multicolored plane of light forms a vertical opaque wall with seven layers, each imposing a different effect.", tags: ["srd-5.1", "level-9", "metadata-only", "wizard"], mechanics: { level: 9, school: "abjuration", castingTime: "action", actionCost: "action", range: 60, target: "area", duration: "10-minutes", attackType: "none", saveType: "dexterity", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:shapechange"), name: "Shapechange", description: "You assume the form of a different creature of your choice with a challenge rating no higher than your level, retaining your game statistics except as noted.", tags: ["srd-5.1", "level-9", "metadata-only", "druid", "wizard"], mechanics: { level: 9, school: "transmutation", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a jade circlet worth at least 1,500 gp, which you must place on your head before you cast the spell" }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:storm-of-vengeance"), name: "Storm of Vengeance", description: "You create a churning storm cloud centered on a point you can see, unleashing thunder, acid rain, lightning, and hail over successive rounds.", tags: ["srd-5.1", "level-9", "metadata-only", "druid"], mechanics: { level: 9, school: "conjuration", castingTime: "action", actionCost: "action", range: 10000, target: "area", duration: "concentration", attackType: "none", saveType: "constitution", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:time-stop"), name: "Time Stop", description: "You briefly stop the flow of time for everyone but yourself, taking 1d4+1 turns in a row while other creatures are frozen.", tags: ["srd-5.1", "level-9", "metadata-only", "sorcerer", "wizard"], mechanics: { level: 9, school: "transmutation", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: false }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:true-polymorph"), name: "True Polymorph", description: "You transform a creature or nonmagical object that you can see into a different kind of creature or object, replacing its game statistics.", tags: ["srd-5.1", "level-9", "metadata-only", "bard", "warlock", "wizard"], mechanics: { level: 9, school: "transmutation", castingTime: "action", actionCost: "action", range: 30, target: "single", duration: "concentration", attackType: "none", saveType: "wisdom", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a caterpillar cocoon" }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:true-resurrection"), name: "True Resurrection", description: "You touch a creature that has been dead for no longer than 200 years and that died for any reason except old age, restoring it to life with all its hit points.", tags: ["srd-5.1", "level-9", "metadata-only", "cleric", "druid"], mechanics: { level: 9, school: "necromancy", castingTime: "1-hour", actionCost: "action", range: 5, target: "ally", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a sprinkle of holy water and diamonds worth at least 25,000 gp, which the spell consumes" }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:weird"), name: "Weird", description: "You create illusory horrors in the minds of creatures within a 30-foot-radius sphere, frightening them and dealing psychic damage each turn.", tags: ["srd-5.1", "level-9", "metadata-only", "wizard"], mechanics: { level: 9, school: "illusion", castingTime: "action", actionCost: "action", range: 120, target: "area", duration: "concentration", attackType: "none", saveType: "wisdom", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [] } },
    { reference: refs.ref("spell", "srd-5.1:spell:wish"), name: "Wish", description: "You alter reality itself by speaking your wish aloud, duplicating any spell of 8th level or lower or producing one of several listed effects.", tags: ["srd-5.1", "level-9", "metadata-only", "sorcerer", "wizard"], mechanics: { level: 9, school: "conjuration", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: false }, effects: [] } },
  ];
}
