import type { StarterReferences } from "../references.js";

/** SRD 1st-level spells. Each file under `spells/` owns one level band. */
export function buildLevel1Spells(refs: StarterReferences) {
  const { bless, cureWounds, magicMissile, shield, healingWord, guidingBolt, falseLife } = refs;
  return [
    { reference: bless, name: "Bless", description: "A level-one Cleric spell. Creatures in the area gain a +1 bonus to attack rolls and saving throws while the caster concentrates.", tags: ["srd-5.1", "cleric-1", "spellcasting"], mechanics: { level: 1, school: "enchantment", castingTime: "action", actionCost: "action", range: 30, target: "area", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a sprinkling of holy water" }, effects: [{ type: "modifier", statistic: "attack", amount: 1, duration: "encounter" }] } },
    { reference: cureWounds, name: "Cure Wounds", description: "A level-one Cleric spell that restores 1d8 hit points to a touched ally.", tags: ["srd-5.1", "cleric-1", "spellcasting"], mechanics: { level: 1, school: "evocation", castingTime: "action", actionCost: "action", range: 5, target: "ally", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "healing", dice: { count: 1, sides: 8, modifier: 0 } }] } },
    { reference: magicMissile, name: "Magic Missile", description: "A first-level Wizard spell with automatic-hit force darts, authoritative range, components, slot use, and replay-safe execution.", tags: ["srd-5.1", "level-1", "spellcasting"], mechanics: { level: 1, school: "evocation", castingTime: "action", actionCost: "action", range: 120, target: "enemy", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a tiny ball of bat guano and sulfur" }, effects: [{ type: "damage", damageType: "force", dice: { count: 3, sides: 4, modifier: 3 } }] } },
    { reference: shield, name: "Shield", description: "A first-level Wizard reaction spell that grants the caster a +5 bonus to armor class until the start of their next turn.", tags: ["srd-5.1", "level-1", "spellcasting"], mechanics: { level: 1, school: "abjuration", castingTime: "reaction", actionCost: "reaction", range: 0, target: "self", duration: "1-round", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "modifier", statistic: "defense", amount: 5, duration: "round" }] } },
    { reference: healingWord, name: "Healing Word", description: "A first-level Cleric healing spell with authoritative 60-foot range, ally targeting, slot use, and replay-safe execution.", tags: ["srd-5.1", "level-1", "spellcasting"], mechanics: { level: 1, school: "evocation", castingTime: "bonus-action", actionCost: "bonus-action", range: 60, target: "ally", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: false }, effects: [{ type: "healing", dice: { count: 1, sides: 4, modifier: 0 } }] } },
    { reference: guidingBolt, name: "Guiding Bolt", description: "A first-level Cleric spell reference with exact 120-foot range; radiant damage and advantage rider are unsupported.", tags: ["srd-5.1", "level-1", "metadata-only"], mechanics: { level: 1, school: "evocation", castingTime: "action", actionCost: "action", range: 120, target: "enemy", duration: "instantaneous", attackType: "ranged", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "damage", damageType: "radiant", dice: { count: 4, sides: 6, modifier: 0 } }] } },
    { reference: falseLife, name: "False Life", description: "A first-level Wizard spell that grants the caster 1d4+4 temporary hit points with replay-safe execution.", tags: ["srd-5.1", "level-1", "spellcasting"], mechanics: { level: 1, school: "necromancy", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "1-hour", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a small amount of alcohol or distilled spirits" }, effects: [{ type: "temporary-hit-points", dice: { count: 1, sides: 4, modifier: 4 } }] } },
  ];
}
