import type { StarterReferences } from "./references.js";

export function buildClasses(refs: StarterReferences) {
  const { klass, cleric, barbarian, rogue, wizard, paladin, ranger, level, levelTwo, levelThree, clericOne, barbarianOne, rogueOne, wizardOne, paladinOne, rangerOne, levelRefs } = refs;
  return [
    { reference: klass, name: "Fighter", description: "Bounded SRD Fighter progression supports levels 1-2 only. Level 3 Martial Archetype is deliberately not executable.", tags: ["srd-5.1", "fighter-1-2"], mechanics: { hitDie: 10, primaryAttribute: "strength", savingAttributes: ["strength", "constitution"], levelRefs: [level, levelTwo, levelThree] } },
    { reference: cleric, name: "Cleric", description: "Bounded SRD Cleric progression includes levels 1-3 as metadata; spell execution and domain choices remain unsupported.", tags: ["srd-5.1", "cleric-1-3", "prepared-spells"], mechanics: { hitDie: 8, primaryAttribute: "wisdom", savingAttributes: ["wisdom", "charisma"], levelRefs: [clericOne, levelRefs.clericTwo, levelRefs.clericThree] } },
    { reference: barbarian, name: "Barbarian", description: "Bounded SRD Barbarian progression includes levels 1-3 as metadata; rage and primal-path execution remain unsupported.", tags: ["srd-5.1", "barbarian-1-3", "unsupported-runtime"], mechanics: { hitDie: 12, primaryAttribute: "strength", savingAttributes: ["strength", "constitution"], levelRefs: [barbarianOne, levelRefs.barbarianTwo, levelRefs.barbarianThree] } },
    { reference: rogue, name: "Rogue", description: "Bounded SRD Rogue progression includes levels 1-3 as metadata; expertise and archetype execution remain unsupported.", tags: ["srd-5.1", "rogue-1-3", "unsupported-runtime"], mechanics: { hitDie: 8, primaryAttribute: "dexterity", savingAttributes: ["dexterity", "intelligence"], levelRefs: [rogueOne, levelRefs.rogueTwo, levelRefs.rogueThree] } },
    { reference: wizard, name: "Wizard", description: "Bounded SRD Wizard progression includes levels 1-3 as metadata; spell execution and Arcane Tradition remain unsupported.", tags: ["srd-5.1", "wizard-1-3", "unsupported-runtime"], mechanics: { hitDie: 6, primaryAttribute: "intelligence", savingAttributes: ["intelligence", "wisdom"], levelRefs: [wizardOne, levelRefs.wizardTwo, levelRefs.wizardThree] } },
    { reference: paladin, name: "Paladin", description: "Bounded SRD Paladin progression includes levels 1-3 as metadata; oath and smite execution remain unsupported.", tags: ["srd-5.1", "paladin-1-3", "unsupported-runtime"], mechanics: { hitDie: 10, primaryAttribute: "charisma", savingAttributes: ["wisdom", "charisma"], levelRefs: [paladinOne, levelRefs.paladinTwo, levelRefs.paladinThree] } },
    { reference: ranger, name: "Ranger", description: "Bounded SRD Ranger progression includes levels 1-3 as metadata; favored terrain and archetype execution remain unsupported.", tags: ["srd-5.1", "ranger-1-3", "unsupported-runtime"], mechanics: { hitDie: 10, primaryAttribute: "dexterity", savingAttributes: ["strength", "dexterity"], levelRefs: [rangerOne, levelRefs.rangerTwo, levelRefs.rangerThree] } },
  ];
}
