import type { StarterReferences } from "./references.js";

export function buildEnemies(refs: StarterReferences) {
  const { ref, attack, goblinAttack, goblinNimbleEscape, banditAttack, wolfAttack, wolfPackTactics, wolfKnockdown } = refs;
  return [
    { reference: ref("enemy-template", "velvet:test-fixture:enemy-template:training-dummy"), name: "Training Dummy", description: "An original Velvet deterministic integration target; not SRD content.", tags: ["velvet:test-fixture", "original", "non-srd"], mechanics: { tier: 1, maxHp: 8, defense: 10, speed: 0 + 1, abilityRefs: [attack], resistances: [], vulnerabilities: [], immunities: [], combatProfile: { kind: "dnd-5e-pinned-basic-attack-v1", proficiencyBonus: 0, attack: { abilityRef: attack, attackBonus: 0 } } }, private: { tactics: "Use only as a stationary basic-attack integration target.", gmNotes: "Original Velvet test fixture, not an SRD monster.", hiddenAbilityRefs: [] } },
    { reference: ref("enemy-template", "srd-5.1:enemy-template:goblin"), name: "Goblin", description: "A bounded SRD Goblin profile with a pinned scimitar attack and Nimble Escape policy.", tags: ["srd-5.1", "enemy-basic-attack", "enemy-trait", "bounded"], mechanics: { tier: 1, maxHp: 7, defense: 15, speed: 30, abilityRefs: [goblinAttack, goblinNimbleEscape], resistances: [], vulnerabilities: [], immunities: [], combatProfile: { kind: "dnd-5e-pinned-basic-attack-v1", proficiencyBonus: 2, attack: { abilityRef: goblinAttack, attackBonus: 4 } } }, private: { tactics: "Use the pinned scimitar attack against the deterministic legal target; retain a short Nimble Escape reposition state.", gmNotes: "SRD 5.1 Goblin attack and Nimble Escape policy are catalog-pinned. Grid movement is not modeled.", hiddenAbilityRefs: [] } },
    { reference: ref("enemy-template", "srd-5.1:enemy-template:bandit"), name: "Bandit", description: "A bounded SRD Bandit profile with only its scimitar attack executable.", tags: ["srd-5.1", "enemy-basic-attack", "bounded"], mechanics: { tier: 1, maxHp: 11, defense: 12, speed: 30, abilityRefs: [banditAttack], resistances: [], vulnerabilities: [], immunities: [], combatProfile: { kind: "dnd-5e-pinned-basic-attack-v1", proficiencyBonus: 2, attack: { abilityRef: banditAttack, attackBonus: 3 } } }, private: { tactics: "Use the pinned scimitar attack against the deterministic legal target.", gmNotes: "SRD 5.1 Bandit basic attack only; other actions are not executable.", hiddenAbilityRefs: [] } },
    { reference: ref("enemy-template", "srd-5.1:enemy-template:wolf"), name: "Wolf", description: "A bounded SRD Wolf profile with bite, Pack Tactics, and a hit-confirmed knockdown rider.", tags: ["srd-5.1", "enemy-basic-attack", "enemy-trait", "bounded"], mechanics: { tier: 1, maxHp: 11, defense: 13, speed: 40, abilityRefs: [wolfAttack, wolfPackTactics, wolfKnockdown], resistances: [], vulnerabilities: [], immunities: [], combatProfile: { kind: "dnd-5e-pinned-basic-attack-v1", proficiencyBonus: 2, attack: { abilityRef: wolfAttack, attackBonus: 4 } } }, private: { tactics: "Use the pinned bite attack against the deterministic legal target; apply Pack Tactics and knockdown only through server-derived evidence.", gmNotes: "SRD 5.1 Wolf bite, Pack Tactics, and the hit-confirmed rider are catalog-pinned.", hiddenAbilityRefs: [] } },
  ];
}
