import type { StarterReference, StarterReferences } from "./references.js";

/**
 * The complete SRD 5.1 feat list as bounded catalog definitions. Feats grant no
 * executable abilities in this pack (`grantedAbilityRefs` is always empty);
 * ability-score increases and numeric effects are carried as closed mechanics,
 * and SRD prerequisites are recorded where the schema can express them.
 */
export function buildFeats(refs: StarterReferences) {
  const { ref } = refs;
  const tags = ["srd-5.1", "feat"];
  /** Feats intentionally grant no executable abilities in this pack. */
  const grantedAbilityRefs: StarterReference[] = [];
  return [
    { reference: ref("feat", "srd-5.1:feat:grappler"), name: "Grappler", description: "Prerequisite: Strength 13. You have advantage on attack rolls against a creature you are grappling, and you can use an action to try to pin a grappled creature.", tags, mechanics: { grantedAbilityRefs, prerequisites: { minimumAttribute: { attribute: "strength", value: 13 } } } },
    { reference: ref("feat", "srd-5.1:feat:great-weapon-master"), name: "Great Weapon Master", description: "On a critical hit or when you reduce a creature to 0 hit points with a melee weapon, you can make one melee weapon attack as a bonus action; before an attack with a heavy weapon you are proficient with, you can take a -5 penalty to hit for +10 damage.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:sharpshooter"), name: "Sharpshooter", description: "Attacking at long range does not impose disadvantage, your ranged weapon attacks ignore half and three-quarters cover, and before an attack with a ranged weapon you are proficient with you can take a -5 penalty to hit for +10 damage.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:sentinel"), name: "Sentinel", description: "When you hit a creature with an opportunity attack its speed becomes 0 for the rest of the turn, creatures provoke opportunity attacks even if they Disengage, and you can use your reaction to attack a creature within 5 feet that attacks a target other than you.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:war-caster"), name: "War Caster", description: "Prerequisite: The ability to cast at least one spell. You have advantage on Constitution saving throws to maintain concentration, can perform somatic components while wielding weapons and a shield, and can cast a spell in place of an opportunity attack.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:lucky"), name: "Lucky", description: "You have 3 luck points. You can spend one to roll an additional d20 on an attack roll, ability check, or saving throw, or when an attack roll is made against you; you choose which roll to use. Luck points return after a long rest.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:mobile"), name: "Mobile", description: "Your speed increases by 10 feet, difficult terrain does not cost extra movement when you Dash, and you do not provoke opportunity attacks from a creature you attacked this turn.", tags, mechanics: { grantedAbilityRefs, modifiers: [{ type: "modifier", statistic: "speed", amount: 10, duration: "permanent" }] } },
    { reference: ref("feat", "srd-5.1:feat:tough"), name: "Tough", description: "Your hit point maximum increases by 2 for every level you have.", tags, mechanics: { grantedAbilityRefs, modifiers: [{ type: "modifier", statistic: "max-hp", amount: 2, duration: "permanent" }] } },
    { reference: ref("feat", "srd-5.1:feat:alert"), name: "Alert", description: "You gain a +5 bonus to initiative, you cannot be surprised while conscious, and other creatures do not gain advantage on attack rolls against you as a result of being hidden from you.", tags, mechanics: { grantedAbilityRefs, modifiers: [{ type: "modifier", statistic: "check", amount: 5, duration: "permanent" }] } },
    { reference: ref("feat", "srd-5.1:feat:athlete"), name: "Athlete", description: "Increase your Strength or Dexterity score by 1, to a maximum of 20. You can stand up from prone using only 5 feet of movement, climbing does not cost extra movement, and you can make a running jump after moving only 5 feet.", tags, mechanics: { grantedAbilityRefs, abilityBonuses: { strength: 1 } } },
    { reference: ref("feat", "srd-5.1:feat:actor"), name: "Actor", description: "Increase your Charisma score by 1, to a maximum of 20. You have advantage on Charisma (Deception) and Charisma (Performance) checks when pretending to be a different person, and you can mimic the speech of a person or the sounds of a creature.", tags, mechanics: { grantedAbilityRefs, abilityBonuses: { charisma: 1 } } },
    { reference: ref("feat", "srd-5.1:feat:charger"), name: "Charger", description: "When you use your action to Dash, you can use a bonus action to make one melee weapon attack or to shove a creature; moving at least 10 feet in a straight line before the attack grants +5 damage or 10 feet of shove distance.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:crossbow-expert"), name: "Crossbow Expert", description: "You ignore the loading quality of crossbows you are proficient with, being within 5 feet of a hostile creature does not impose disadvantage on your ranged attack rolls, and when you use the Attack action with a one-handed weapon you can make a bonus-action hand crossbow attack.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:defensive-duelist"), name: "Defensive Duelist", description: "Prerequisite: Dexterity 13. When you are wielding a finesse weapon you are proficient with and are hit by a melee attack, you can use your reaction to add your proficiency bonus to your AC for that attack, potentially causing it to miss.", tags, mechanics: { grantedAbilityRefs, prerequisites: { minimumAttribute: { attribute: "dexterity", value: 13 } } } },
    { reference: ref("feat", "srd-5.1:feat:dual-wielder"), name: "Dual Wielder", description: "You gain a +1 bonus to AC while wielding a separate melee weapon in each hand, you can use two-weapon fighting even when the one-handed weapons are not light, and you can draw or stow two one-handed weapons when you could normally draw or stow one.", tags, mechanics: { grantedAbilityRefs, modifiers: [{ type: "modifier", statistic: "defense", amount: 1, duration: "permanent" }] } },
    { reference: ref("feat", "srd-5.1:feat:dungeon-delver"), name: "Dungeon Delver", description: "You have advantage on Wisdom (Perception) and Intelligence (Investigation) checks made to detect secret doors, advantage on saving throws against traps, resistance to trap damage, and you can search for traps while traveling at a normal pace.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:durable"), name: "Durable", description: "Increase your Constitution score by 1, to a maximum of 20. When you roll a Hit Die to regain hit points, the minimum number of hit points you regain equals twice your Constitution modifier (minimum of 2).", tags, mechanics: { grantedAbilityRefs, abilityBonuses: { constitution: 1 } } },
    { reference: ref("feat", "srd-5.1:feat:elemental-adept"), name: "Elemental Adept", description: "Choose a damage type (acid, cold, fire, lightning, or thunder): spells you cast ignore resistance to that type, and when you roll damage for such a spell you can treat any 1 on a damage die as a 2.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:heavily-armored"), name: "Heavily Armored", description: "Prerequisite: Proficiency with medium armor. Increase your Strength score by 1, to a maximum of 20, and you gain proficiency with heavy armor.", tags, mechanics: { grantedAbilityRefs, abilityBonuses: { strength: 1 } } },
    { reference: ref("feat", "srd-5.1:feat:heavy-armor-master"), name: "Heavy Armor Master", description: "Prerequisite: Proficiency with heavy armor. Increase your Strength score by 1, to a maximum of 20, and while you are wearing heavy armor bludgeoning, piercing, and slashing damage you take is reduced by 3.", tags, mechanics: { grantedAbilityRefs, abilityBonuses: { strength: 1 } } },
    { reference: ref("feat", "srd-5.1:feat:inspiring-leader"), name: "Inspiring Leader", description: "Prerequisite: Charisma 13. You can spend 10 minutes to inspire up to six friendly creatures that can see or hear you, granting each temporary hit points equal to your level plus your Charisma modifier.", tags, mechanics: { grantedAbilityRefs, prerequisites: { minimumAttribute: { attribute: "charisma", value: 13 } } } },
    { reference: ref("feat", "srd-5.1:feat:keen-mind"), name: "Keen Mind", description: "Increase your Intelligence score by 1, to a maximum of 20. You always know which way is north, you know how many hours remain before the next sunrise or sunset, and you can accurately recall anything you have seen or heard within the past month.", tags, mechanics: { grantedAbilityRefs, abilityBonuses: { intelligence: 1 } } },
    { reference: ref("feat", "srd-5.1:feat:lightly-armored"), name: "Lightly Armored", description: "Increase your Strength or Dexterity score by 1, to a maximum of 20, and you gain proficiency with light armor.", tags, mechanics: { grantedAbilityRefs, abilityBonuses: { dexterity: 1 } } },
    { reference: ref("feat", "srd-5.1:feat:linguist"), name: "Linguist", description: "Increase your Intelligence score by 1, to a maximum of 20. You learn three languages of your choice, and you can ably create written ciphers that others cannot decipher unless you teach them or they succeed on an Intelligence check.", tags, mechanics: { grantedAbilityRefs, abilityBonuses: { intelligence: 1 } } },
    { reference: ref("feat", "srd-5.1:feat:mage-slayer"), name: "Mage Slayer", description: "When a creature within 5 feet of you casts a spell, you can use your reaction to make a melee weapon attack against it; when you damage a creature that is concentrating on a spell it has disadvantage on the saving throw; and you have advantage on saving throws against spells cast by creatures within 5 feet of you.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:magic-initiate"), name: "Magic Initiate", description: "Choose a class: you learn two cantrips and one 1st-level spell from that class's spell list, and you can cast the 1st-level spell at its lowest level once per long rest.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:medium-armor-master"), name: "Medium Armor Master", description: "Prerequisite: Proficiency with medium armor. Wearing medium armor does not impose disadvantage on Dexterity (Stealth) checks, and you can add 3 rather than 2 to your AC when wearing medium armor with a Dexterity of 16 or higher.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:mounted-combatant"), name: "Mounted Combatant", description: "You have advantage on melee attack rolls against unmounted creatures smaller than your mount, you can force an attack targeting your mount to target you instead, and when your mount succeeds on a Dexterity saving throw it takes no damage.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:observant"), name: "Observant", description: "Increase your Intelligence or Wisdom score by 1, to a maximum of 20. You can read lips of creatures speaking a language you know, and you gain a +5 bonus to your passive Wisdom (Perception) and passive Intelligence (Investigation) scores.", tags, mechanics: { grantedAbilityRefs, abilityBonuses: { intelligence: 1 } } },
    { reference: ref("feat", "srd-5.1:feat:polearm-master"), name: "Polearm Master", description: "When you take the Attack action with a glaive, halberd, quarterstaff, or spear you can make a bonus-action attack with the opposite end, and while wielding such a weapon you can use your reaction to make an opportunity attack against a creature that enters your reach.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:resilient"), name: "Resilient", description: "Choose one ability score in which you are not already proficient: increase it by 1, to a maximum of 20, and gain proficiency in saving throws using that ability.", tags, mechanics: { grantedAbilityRefs, abilityBonuses: { constitution: 1 } } },
    { reference: ref("feat", "srd-5.1:feat:ritual-caster"), name: "Ritual Caster", description: "Prerequisite: Intelligence or Wisdom 13. You acquire a ritual book with two 1st-level ritual spells of your choice and can cast them as rituals; you can add further ritual spells you find.", tags, mechanics: { grantedAbilityRefs, prerequisites: { minimumAttribute: { attribute: "intelligence", value: 13 } } } },
    { reference: ref("feat", "srd-5.1:feat:savage-attacker"), name: "Savage Attacker", description: "Once per turn when you roll damage for a melee weapon attack, you can reroll the weapon's damage dice and use either total.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:shield-master"), name: "Shield Master", description: "If you take the Attack action you can use a bonus action to shove a creature within 5 feet with your shield, and when you are subjected to an effect that allows a Dexterity saving throw you can use your reaction to take no damage on a success.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:skilled"), name: "Skilled", description: "You gain proficiency in any combination of three skills or tools of your choice.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:skulker"), name: "Skulker", description: "You can try to hide when lightly obscured, being hidden from a creature does not impose disadvantage on your ranged attacks against it, and remaining hidden after a missed ranged attack does not reveal your position.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:spell-sniper"), name: "Spell Sniper", description: "Prerequisite: The ability to cast at least one spell. When you cast a spell that requires an attack roll its range is doubled, your ranged spell attacks ignore half and three-quarters cover, and you learn one cantrip that requires an attack roll.", tags, mechanics: { grantedAbilityRefs } },
    { reference: ref("feat", "srd-5.1:feat:tavern-brawler"), name: "Tavern Brawler", description: "Increase your Strength or Constitution score by 1, to a maximum of 20. You are proficient with improvised weapons, your unarmed strike deals 1d4 bludgeoning damage, and when you hit with an unarmed strike or improvised weapon you can use a bonus action to grapple the target.", tags, mechanics: { grantedAbilityRefs, abilityBonuses: { strength: 1 } } },
    { reference: ref("feat", "srd-5.1:feat:weapon-master"), name: "Weapon Master", description: "Increase your Strength or Dexterity score by 1, to a maximum of 20, and you gain proficiency with four weapons of your choice.", tags, mechanics: { grantedAbilityRefs, abilityBonuses: { strength: 1 } } },
  ];
}
