import type { StarterReferences } from "./references.js";

export function buildItems(refs: StarterReferences) {
  const { ref, currency, sword, pack, acolyteEquipment } = refs;
  const weapon = (id: string, name: string, description: string, price: number, weightPounds: number, proficiency: "simple" | "martial", attackType: "melee" | "ranged", damageType: "bludgeoning" | "piercing" | "slashing", sides: 4 | 6 | 8 | 10 | 12, properties: unknown[]) => ({
    reference: ref("item", `srd-5.1:item:${id}`), name, description, tags: ["srd-5.1", "equipment"],
    mechanics: { category: "weapon", stackable: false, slot: "hand", price: { currency, amount: price }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds, equipmentProfile: { kind: "weapon", proficiency, attackType, damage: { type: damageType, die: { count: 1, sides } }, properties } } },
  });
  const armor = (id: string, name: string, description: string, price: number, weightPounds: number, category: "light" | "medium" | "heavy", baseArmorClass: number, dexterity: unknown, strengthRequirement: number | null, stealthDisadvantage: boolean) => ({
    reference: ref("item", `srd-5.1:item:${id}`), name, description, tags: ["srd-5.1", "equipment"],
    mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: price }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds, equipmentProfile: { kind: "armor", category, baseArmorClass, dexterity, strengthRequirement, stealthDisadvantage, shieldBonus: 0 } } },
  });
  const tool = (id: string, name: string, description: string, price: number, weightPounds: number, proficiency: string) => ({
    reference: ref("item", `srd-5.1:item:${id}`), name, description, tags: ["srd-5.1", "equipment", "tool"],
    mechanics: { category: "tool", stackable: false, slot: null, price: { currency, amount: price }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds, equipmentProfile: { kind: "tool", proficiency } } },
  });
  const ammunition = (id: string, name: string, description: string, price: number, weightPounds: number, weaponCategory: "simple" | "martial") => ({
    reference: ref("item", `srd-5.1:item:${id}`), name, description, tags: ["srd-5.1", "equipment", "ammunition"],
    mechanics: { category: "gear", stackable: true, slot: null, price: { currency, amount: price }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds, equipmentProfile: { kind: "ammunition", weaponCategory } } },
  });
  const gear = (id: string, name: string, description: string, price: number, weightPounds: number, stackable = false) => ({
    reference: ref("item", `srd-5.1:item:${id}`), name, description, tags: ["srd-5.1", "equipment", "gear"],
    mechanics: { category: "gear", stackable, slot: null, price: { currency, amount: price }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds, equipmentProfile: null } },
  });
  return [
    { reference: sword, name: "Longsword", description: "A martial melee weapon dealing 1d8 slashing damage, or 1d10 when wielded with two hands.", tags: ["srd-5.1"], mechanics: { category: "weapon", stackable: false, slot: "hand", price: { currency, amount: 15 }, effects: [{ type: "damage", damageType: "physical", dice: { count: 1, sides: 8, modifier: 0 } }], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 3, equipmentProfile: { kind: "weapon", proficiency: "martial", attackType: "melee", damage: { type: "slashing", die: { count: 1, sides: 8 } }, properties: [{ property: "versatile", damageDie: { count: 1, sides: 10 } }] } } } },
    { reference: ref("item", "srd-5.1:item:leather-armor"), name: "Leather Armor", description: "Light armor with base AC 11 and full Dexterity contribution.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 10 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 10, equipmentProfile: { kind: "armor", category: "light", baseArmorClass: 11, dexterity: { policy: "full" }, strengthRequirement: null, stealthDisadvantage: false, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:chain-shirt"), name: "Chain Shirt", description: "Medium armor with base AC 13 and Dexterity contribution capped at +2.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 50 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 20, equipmentProfile: { kind: "armor", category: "medium", baseArmorClass: 13, dexterity: { policy: "capped", maxBonus: 2 }, strengthRequirement: null, stealthDisadvantage: false, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:chain-mail"), name: "Chain Mail", description: "Heavy armor with AC 16, Strength 13 requirement, and stealth disadvantage.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 75 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 55, equipmentProfile: { kind: "armor", category: "heavy", baseArmorClass: 16, dexterity: { policy: "none" }, strengthRequirement: 13, stealthDisadvantage: true, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:hide-armor"), name: "Hide Armor", description: "Medium armor with AC 12 and Dexterity capped at +2.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 10 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 12, equipmentProfile: { kind: "armor", category: "medium", baseArmorClass: 12, dexterity: { policy: "capped", maxBonus: 2 }, strengthRequirement: null, stealthDisadvantage: false, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:scale-mail"), name: "Scale Mail", description: "Medium armor with AC 14, Dexterity capped at +2, and stealth disadvantage.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 50 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 45, equipmentProfile: { kind: "armor", category: "medium", baseArmorClass: 14, dexterity: { policy: "capped", maxBonus: 2 }, strengthRequirement: null, stealthDisadvantage: true, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:breastplate"), name: "Breastplate", description: "Medium armor with AC 14 and Dexterity capped at +2.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 400 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 20, equipmentProfile: { kind: "armor", category: "medium", baseArmorClass: 14, dexterity: { policy: "capped", maxBonus: 2 }, strengthRequirement: null, stealthDisadvantage: false, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:plate"), name: "Plate", description: "Heavy armor with AC 18, Strength 15 requirement, and stealth disadvantage.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 1500 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 65, equipmentProfile: { kind: "armor", category: "heavy", baseArmorClass: 18, dexterity: { policy: "none" }, strengthRequirement: 15, stealthDisadvantage: true, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:shield"), name: "Shield", description: "A wielded shield granting a +2 armor class bonus.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "hand", price: { currency, amount: 10 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 6, equipmentProfile: { kind: "armor", category: "shield", baseArmorClass: null, dexterity: { policy: "none" }, strengthRequirement: null, stealthDisadvantage: false, shieldBonus: 2 } } } },
    { reference: pack, name: "Explorer's Pack", description: "A single bounded starter-gear entry; individual contents are not modeled.", tags: ["srd-5.1"], mechanics: { category: "gear", stackable: false, slot: null, price: { currency, amount: 10 }, effects: [] } },
    { reference: acolyteEquipment, name: "Acolyte Equipment", description: "One grant-only entry representing a holy symbol, prayer book, five sticks of incense, vestments, and common clothes.", tags: ["srd-5.1", "bounded-aggregate", "grant-only"], mechanics: { category: "gear", stackable: false, slot: null, price: { currency, amount: 0 }, effects: [] } },
    weapon("dagger", "Dagger", "A simple finesse and light melee weapon.", 2, 1, "simple", "melee", "piercing", 4, [{ property: "finesse" }, { property: "light" }, { property: "thrown", range: { normalFeet: 20, longFeet: 60 } }]),
    weapon("club", "Club", "A simple light bludgeoning weapon.", 0, 2, "simple", "melee", "bludgeoning", 4, [{ property: "light" }]),
    weapon("handaxe", "Handaxe", "A simple light and thrown slashing weapon.", 5, 2, "simple", "melee", "slashing", 6, [{ property: "light" }, { property: "thrown", range: { normalFeet: 20, longFeet: 60 } }]),
    weapon("mace", "Mace", "A simple bludgeoning weapon.", 5, 4, "simple", "melee", "bludgeoning", 6, []),
    weapon("quarterstaff", "Quarterstaff", "A simple versatile bludgeoning weapon.", 0, 4, "simple", "melee", "bludgeoning", 6, [{ property: "versatile", damageDie: { count: 1, sides: 8 } }]),
    weapon("spear", "Spear", "A simple versatile and thrown piercing weapon.", 1, 3, "simple", "melee", "piercing", 6, [{ property: "thrown", range: { normalFeet: 20, longFeet: 60 } }, { property: "versatile", damageDie: { count: 1, sides: 8 } }]),
    weapon("shortbow", "Shortbow", "A simple ranged piercing weapon.", 25, 2, "simple", "ranged", "piercing", 6, [{ property: "ammunition", range: { normalFeet: 80, longFeet: 320 } }, { property: "two-handed" }]),
    weapon("light-crossbow", "Light Crossbow", "A simple loading ranged piercing weapon.", 25, 5, "simple", "ranged", "piercing", 8, [{ property: "ammunition", range: { normalFeet: 80, longFeet: 320 } }, { property: "loading" }, { property: "two-handed" }]),
    weapon("rapier", "Rapier", "A martial finesse piercing weapon.", 25, 2, "martial", "melee", "piercing", 8, [{ property: "finesse" }]),
    weapon("battleaxe", "Battleaxe", "A martial versatile slashing weapon.", 10, 4, "martial", "melee", "slashing", 8, [{ property: "versatile", damageDie: { count: 1, sides: 10 } }]),
    weapon("greatsword", "Greatsword", "A martial heavy two-handed slashing weapon.", 50, 6, "martial", "melee", "slashing", 6, [{ property: "heavy" }, { property: "two-handed" }]),
    armor("padded-armor", "Padded Armor", "Light armor with base AC 11 and stealth disadvantage.", 5, 8, "light", 11, { policy: "full" }, null, true),
    armor("studded-leather-armor", "Studded Leather Armor", "Light armor with base AC 12 and full Dexterity contribution.", 45, 13, "light", 12, { policy: "full" }, null, false),
    armor("splint", "Splint", "Heavy armor with AC 17, Strength 15 requirement, and stealth disadvantage.", 200, 60, "heavy", 17, { policy: "none" }, 15, true),
    armor("ring-mail", "Ring Mail", "Heavy armor with AC 14, Strength 13 requirement, and stealth disadvantage.", 30, 40, "heavy", 14, { policy: "none" }, 13, true),
    tool("artisans-tools-alchemists", "Alchemist's Supplies", "Artisan's tools for crafting alchemical items and identifying potions.", 50, 8, "Alchemist's supplies"),
    tool("artisans-tools-brewers", "Brewer's Supplies", "Artisan's tools for brewing beer, wine, and spirits.", 20, 9, "Brewer's supplies"),
    tool("artisans-tools-calligraphers", "Calligrapher's Supplies", "Artisan's tools for fine writing and illumination.", 10, 5, "Calligrapher's supplies"),
    tool("artisans-tools-carpenters", "Carpenter's Tools", "Artisan's tools for working wood.", 8, 6, "Carpenter's tools"),
    tool("artisans-tools-cartographers", "Cartographer's Tools", "Artisan's tools for drafting maps.", 15, 6, "Cartographer's tools"),
    tool("artisans-tools-cobblers", "Cobbler's Tools", "Artisan's tools for making and repairing footwear.", 5, 5, "Cobbler's tools"),
    tool("artisans-tools-cooks", "Cook's Utensils", "Artisan's tools for preparing meals.", 1, 8, "Cook's utensils"),
    tool("artisans-tools-glassblowers", "Glassblower's Tools", "Artisan's tools for shaping glass.", 30, 5, "Glassblower's tools"),
    tool("artisans-tools-jewelers", "Jeweler's Tools", "Artisan's tools for cutting gems and crafting jewelry.", 25, 2, "Jeweler's tools"),
    tool("artisans-tools-leatherworkers", "Leatherworker's Tools", "Artisan's tools for working leather.", 5, 5, "Leatherworker's tools"),
    tool("artisans-tools-masons", "Mason's Tools", "Artisan's tools for cutting stone and building.", 10, 8, "Mason's tools"),
    tool("artisans-tools-painters", "Painter's Supplies", "Artisan's tools for painting and drawing.", 10, 5, "Painter's supplies"),
    tool("artisans-tools-potters", "Potter's Tools", "Artisan's tools for shaping clay.", 10, 3, "Potter's tools"),
    tool("artisans-tools-smiths", "Smith's Tools", "Artisan's tools for forging metal.", 20, 8, "Smith's tools"),
    tool("artisans-tools-tinkers", "Tinker's Tools", "Artisan's tools for repairing and assembling small mechanisms.", 50, 10, "Tinker's tools"),
    tool("artisans-tools-weavers", "Weaver's Tools", "Artisan's tools for spinning and weaving cloth.", 1, 5, "Weaver's tools"),
    tool("artisans-tools-woodcarvers", "Woodcarver's Tools", "Artisan's tools for carving wood.", 1, 5, "Woodcarver's tools"),
    tool("disguise-kit", "Disguise Kit", "A kit for creating disguises.", 25, 3, "Disguise kit"),
    tool("forgery-kit", "Forgery Kit", "A kit for duplicating documents and seals.", 15, 5, "Forgery kit"),
    tool("gaming-set-dice", "Dice Set", "A gaming set of dice; SRD cost 1 sp, represented as 0 gp under integer-gold pricing.", 0, 0, "Dice set"),
    tool("gaming-set-dragonchess", "Dragonchess Set", "A gaming set for dragonchess.", 1, 0, "Dragonchess set"),
    tool("gaming-set-playing-cards", "Playing Card Set", "A gaming set of playing cards; SRD cost 5 sp, represented as 0 gp under integer-gold pricing.", 0, 0, "Playing card set"),
    tool("gaming-set-three-dragon-ante", "Three-Dragon Ante Set", "A gaming set for Three-Dragon Ante.", 1, 0, "Three-Dragon Ante set"),
    tool("herbalism-kit", "Herbalism Kit", "A kit for identifying and preparing herbs.", 5, 3, "Herbalism kit"),
    tool("navigators-tools", "Navigator's Tools", "Tools for plotting a course at sea.", 25, 2, "Navigator's tools"),
    tool("poisoners-kit", "Poisoner's Kit", "A kit for brewing and applying poisons.", 50, 2, "Poisoner's kit"),
    tool("thieves-tools", "Thieves' Tools", "Tools for picking locks and disarming traps.", 25, 1, "Thieves' tools"),
    tool("vehicles-land", "Vehicles (Land)", "Proficiency with land vehicles.", 0, 0, "Vehicles (land)"),
    tool("vehicles-water", "Vehicles (Water)", "Proficiency with waterborne vehicles.", 0, 0, "Vehicles (water)"),
    tool("musical-instrument-bagpipes", "Bagpipes", "A musical instrument.", 30, 6, "Bagpipes"),
    tool("musical-instrument-drum", "Drum", "A musical instrument.", 6, 3, "Drum"),
    tool("musical-instrument-dulcimer", "Dulcimer", "A musical instrument.", 25, 10, "Dulcimer"),
    tool("musical-instrument-flute", "Flute", "A musical instrument.", 2, 1, "Flute"),
    tool("musical-instrument-horn", "Horn", "A musical instrument.", 3, 2, "Horn"),
    tool("musical-instrument-lute", "Lute", "A musical instrument.", 35, 2, "Lute"),
    tool("musical-instrument-lyre", "Lyre", "A musical instrument.", 30, 2, "Lyre"),
    tool("musical-instrument-pan-flute", "Pan Flute", "A musical instrument.", 12, 2, "Pan flute"),
    tool("musical-instrument-shawm", "Shawm", "A musical instrument.", 2, 1, "Shawm"),
    tool("musical-instrument-viol", "Viol", "A musical instrument.", 30, 1, "Viol"),
    ammunition("arrows", "Arrows (20)", "A bundle of twenty arrows for a bow.", 1, 1, "simple"),
    ammunition("crossbow-bolts", "Crossbow Bolts (20)", "A bundle of twenty bolts for a crossbow.", 1, 1.5, "simple"),
    ammunition("blowgun-needles", "Blowgun Needles (50)", "A bundle of fifty needles for a blowgun.", 1, 1, "martial"),
    ammunition("sling-bullets", "Sling Bullets (20)", "A bundle of twenty bullets for a sling; SRD cost 4 cp, represented as 0 gp under integer-gold pricing.", 0, 1.5, "simple"),
    gear("abacus", "Abacus", "A counting frame for arithmetic.", 2, 2),
    gear("acid-vial", "Acid (vial)", "A vial of corrosive acid.", 25, 1),
    gear("alchemists-fire", "Alchemist's Fire (flask)", "A flask of sticky, flammable liquid.", 50, 1),
    gear("antitoxin", "Antitoxin (vial)", "A vial that helps a creature resist poison.", 50, 0),
    gear("backpack", "Backpack", "A sturdy pack for carrying gear.", 2, 5),
    gear("ball-bearings", "Ball Bearings (bag of 1,000)", "A bag of one thousand tiny metal balls.", 1, 2, true),
    gear("barrel", "Barrel", "A wooden barrel holding forty gallons.", 2, 70),
    gear("basket", "Basket", "A woven basket; SRD cost 4 sp, represented as 0 gp under integer-gold pricing.", 0, 2),
    gear("bedroll", "Bedroll", "A roll of bedding for sleeping outdoors.", 1, 7),
    gear("bell", "Bell", "A small metal bell.", 1, 0),
    gear("blanket", "Blanket", "A thick wool blanket; SRD cost 5 sp, represented as 0 gp under integer-gold pricing.", 0, 3),
    gear("block-and-tackle", "Block and Tackle", "A pulley system for lifting heavy loads.", 1, 5),
    gear("book", "Book", "A bound volume of lore or records.", 25, 5),
    gear("bottle-glass", "Bottle, Glass", "A glass bottle holding one and a half pints.", 2, 2),
    gear("bucket", "Bucket", "A wooden bucket; SRD cost 5 cp, represented as 0 gp under integer-gold pricing.", 0, 2),
    gear("caltrops", "Caltrops (bag of 20)", "A bag of twenty caltrops.", 1, 2, true),
    gear("candle", "Candle", "A candle that sheds light; SRD cost 1 cp, represented as 0 gp under integer-gold pricing.", 0, 0, true),
    gear("case-crossbow-bolt", "Case, Crossbow Bolt", "A case for holding twenty crossbow bolts.", 1, 1),
    gear("case-map-scroll", "Case, Map or Scroll", "A cylindrical case for maps or scrolls.", 1, 1),
    gear("chain", "Chain (10 feet)", "A ten-foot length of metal chain.", 5, 10),
    gear("chalk", "Chalk (1 piece)", "A piece of chalk; SRD cost 1 cp, represented as 0 gp under integer-gold pricing.", 0, 0, true),
    gear("chest", "Chest", "A sturdy wooden chest.", 5, 25),
    gear("climbers-kit", "Climber's Kit", "Pitons, boot tips, gloves, and a harness for climbing.", 25, 12),
    gear("clothes-common", "Clothes, Common", "Simple everyday clothing; SRD cost 5 cp, represented as 0 gp under integer-gold pricing.", 0, 3),
    gear("clothes-costume", "Clothes, Costume", "A costume for performances or disguise.", 5, 4),
    gear("clothes-fine", "Clothes, Fine", "Fine clothing suited to nobility.", 15, 6),
    gear("clothes-travelers", "Clothes, Traveler's", "Durable clothing suited to travel.", 2, 4),
    gear("component-pouch", "Component Pouch", "A belt pouch holding spell components.", 25, 2),
    gear("crowbar", "Crowbar", "An iron bar for prying doors open.", 2, 5),
    gear("fishing-tackle", "Fishing Tackle", "A rod, line, hooks, and bait.", 1, 4),
    gear("flask-or-tankard", "Flask or Tankard", "A flask or tankard holding one pint; SRD cost 2 cp, represented as 0 gp under integer-gold pricing.", 0, 1),
    gear("grappling-hook", "Grappling Hook", "A hooked iron spike for anchoring a rope.", 2, 4),
    gear("hammer", "Hammer", "A small hammer for pitons and routine work.", 1, 3),
    gear("hammer-sledge", "Hammer, Sledge", "A heavy sledgehammer.", 2, 10),
    gear("healers-kit", "Healer's Kit", "A kit of bandages and salves for stabilizing wounds.", 5, 3),
    gear("holy-symbol", "Holy Symbol", "A sacred symbol of a deity.", 5, 1),
    gear("holy-water", "Holy Water (flask)", "A flask of blessed water harmful to fiends and undead.", 25, 1),
    gear("hourglass", "Hourglass", "A glass hourglass for measuring time.", 25, 1),
    gear("hunting-trap", "Hunting Trap", "A spring-loaded toothed trap for game.", 5, 25),
    gear("ink", "Ink (1 ounce bottle)", "A one-ounce bottle of writing ink.", 10, 0),
    gear("ink-pen", "Ink Pen", "A pen for writing; SRD cost 2 cp, represented as 0 gp under integer-gold pricing.", 0, 0),
    gear("jug-or-pitcher", "Jug or Pitcher", "A jug or pitcher holding one gallon; SRD cost 2 cp, represented as 0 gp under integer-gold pricing.", 0, 4),
    gear("ladder", "Ladder (10-foot)", "A ten-foot wooden ladder; SRD cost 1 sp, represented as 0 gp under integer-gold pricing.", 0, 25),
    gear("lamp", "Lamp", "An oil lamp shedding bright light; SRD cost 5 sp, represented as 0 gp under integer-gold pricing.", 0, 1),
    gear("lantern-bullseye", "Lantern, Bullseye", "A lantern casting a focused beam of light.", 10, 2),
    gear("lantern-hooded", "Lantern, Hooded", "A lantern with a hood to dim or hide its light.", 5, 2),
    gear("lock", "Lock", "A metal lock for doors and chests.", 10, 1),
    gear("magnifying-glass", "Magnifying Glass", "A lens for examining fine detail.", 100, 0),
    gear("manacles", "Manacles", "Iron shackles for restraining a creature.", 2, 6),
    gear("mess-kit", "Mess Kit", "A tin cup, cutlery, and cookware; SRD cost 2 sp, represented as 0 gp under integer-gold pricing.", 0, 1),
    gear("mirror-steel", "Mirror, Steel", "A small polished steel mirror.", 5, 0.5),
    gear("net", "Net", "A weighted net for entangling a creature.", 1, 3),
    gear("oil-flask", "Oil (flask)", "A flask of lamp oil; SRD cost 1 sp, represented as 0 gp under integer-gold pricing.", 0, 1, true),
    gear("paper", "Paper (one sheet)", "A single sheet of paper; SRD cost 2 sp, represented as 0 gp under integer-gold pricing.", 0, 0, true),
    gear("parchment", "Parchment (one sheet)", "A single sheet of parchment; SRD cost 1 sp, represented as 0 gp under integer-gold pricing.", 0, 0, true),
    gear("perfume", "Perfume (vial)", "A vial of fragrant perfume.", 5, 0),
    gear("pick-miners", "Pick, Miner's", "A miner's pick for breaking rock.", 2, 10),
    gear("piton", "Piton", "A metal spike for anchoring ropes; SRD cost 5 cp, represented as 0 gp under integer-gold pricing.", 0, 0.25, true),
    gear("poison-basic", "Poison, Basic (vial)", "A vial of basic poison.", 100, 0),
    gear("pole", "Pole (10-foot)", "A ten-foot wooden pole; SRD cost 5 cp, represented as 0 gp under integer-gold pricing.", 0, 7),
    gear("pot-iron", "Pot, Iron", "A heavy iron cooking pot.", 2, 10),
    gear("pouch", "Pouch", "A small cloth pouch; SRD cost 5 sp, represented as 0 gp under integer-gold pricing.", 0, 1),
    gear("quiver", "Quiver", "A quiver holding twenty arrows.", 1, 1),
    gear("ram-portable", "Ram, Portable", "A portable battering ram.", 4, 35),
    gear("rations", "Rations (1 day)", "One day of dry travel food; SRD cost 5 sp, represented as 0 gp under integer-gold pricing.", 0, 2, true),
    gear("robes", "Robes", "Loose ceremonial robes.", 1, 4),
    gear("rope-hempen", "Rope, Hempen (50 feet)", "A fifty-foot hempen rope.", 1, 10),
    gear("rope-silk", "Rope, Silk (50 feet)", "A fifty-foot silk rope.", 10, 5),
    gear("sack", "Sack", "A cloth sack holding thirty pounds; SRD cost 1 cp, represented as 0 gp under integer-gold pricing.", 0, 0.5),
    gear("saddle-exotic", "Saddle, Exotic", "A saddle for an exotic mount.", 60, 40),
    gear("saddle-military", "Saddle, Military", "A saddle that keeps a rider seated at a +5 bonus.", 20, 30),
    gear("saddle-pack", "Saddle, Pack", "A saddle built for carrying cargo.", 5, 15),
    gear("saddle-riding", "Saddle, Riding", "A standard saddle for a riding mount.", 10, 25),
    gear("saddlebags", "Saddlebags", "A pair of bags that hang from a saddle.", 4, 8),
    gear("scale-merchants", "Scale, Merchant's", "A small balance for weighing merchandise.", 5, 3),
    gear("sealing-wax", "Sealing Wax", "A stick of wax for sealing documents; SRD cost 5 sp, represented as 0 gp under integer-gold pricing.", 0, 0),
    gear("shovel", "Shovel", "A shovel for digging.", 2, 5),
    gear("signal-whistle", "Signal Whistle", "A whistle audible at long range; SRD cost 5 cp, represented as 0 gp under integer-gold pricing.", 0, 0),
    gear("signet-ring", "Signet Ring", "A ring bearing a personal seal.", 5, 0),
    gear("soap", "Soap", "A bar of soap; SRD cost 2 cp, represented as 0 gp under integer-gold pricing.", 0, 0),
    gear("spellbook", "Spellbook", "A wizard's leather-bound spellbook.", 50, 3),
    gear("spikes-iron", "Spikes, Iron (10)", "Ten iron spikes for securing doors.", 1, 5, true),
    gear("spyglass", "Spyglass", "A lens for viewing distant objects.", 1000, 1),
    gear("tent-two-person", "Tent, Two-Person", "A simple two-person tent.", 2, 20),
    gear("tinderbox", "Tinderbox", "Flint, fire steel, and tinder; SRD cost 5 sp, represented as 0 gp under integer-gold pricing.", 0, 1),
    gear("torch", "Torch", "A torch burning for one hour; SRD cost 1 cp, represented as 0 gp under integer-gold pricing.", 0, 1, true),
    gear("vial", "Vial", "A glass vial holding four ounces.", 1, 0),
    gear("waterskin", "Waterskin", "A full waterskin; SRD cost 2 sp, represented as 0 gp under integer-gold pricing.", 0, 5),
    gear("whetstone", "Whetstone", "A stone for sharpening blades; SRD cost 1 cp, represented as 0 gp under integer-gold pricing.", 0, 1, true),
    gear("riding-horse", "Riding Horse", "A Medium horse that serves as a mount; SRD speed and carrying capacity are not representable.", 75, 0),
    gear("draft-horse", "Draft Horse", "A Large horse bred for labor; SRD speed and carrying capacity are not representable.", 50, 0),
    gear("pony", "Pony", "A Small mount; SRD speed and carrying capacity are not representable.", 30, 0),
    gear("mule", "Mule", "A sure-footed pack animal; SRD speed and carrying capacity are not representable.", 8, 0),
    gear("donkey", "Donkey", "A small pack animal; SRD speed and carrying capacity are not representable.", 8, 0),
    gear("camel", "Camel", "A desert mount; SRD speed and carrying capacity are not representable.", 50, 0),
    gear("elephant", "Elephant", "A Huge beast that can serve as a mount; SRD speed and carrying capacity are not representable.", 200, 0),
    gear("warhorse", "Warhorse", "A horse trained for war; SRD speed and carrying capacity are not representable.", 400, 0),
    gear("mastiff", "Mastiff", "A Medium dog trained for riding or guarding; SRD speed and carrying capacity are not representable.", 25, 0),
    gear("chariot", "Chariot", "A two-wheeled vehicle drawn by horses.", 250, 0),
    gear("carriage", "Carriage", "A four-wheeled passenger vehicle.", 100, 0),
    gear("cart", "Cart", "A simple two-wheeled vehicle.", 15, 0),
    gear("wagon", "Wagon", "A four-wheeled cargo vehicle.", 35, 0),
    gear("rowboat", "Rowboat", "A small oared waterborne vehicle.", 50, 0),
    gear("keelboat", "Keelboat", "A river or coastal waterborne vehicle.", 3000, 0),
    gear("longship", "Longship", "A fast waterborne vessel.", 10000, 0),
    gear("sailing-ship", "Sailing Ship", "A large wind-driven waterborne vessel.", 10000, 0),
    gear("galley", "Galley", "A large oared waterborne vessel.", 30000, 0),
    gear("warship", "Warship", "A heavily armed waterborne vessel.", 25000, 0),
    gear("barding-chain-mail", "Warhorse Barding (Chain Mail)", "Mount armor equivalent to chain mail; SRD barding costs four times the armor price and weighs twice as much, but the mount armor slot is not representable.", 300, 110),
  ];
}
