import type { StarterReferences } from "./references.js";

export function buildItems(refs: StarterReferences) {
  const { ref, currency, sword, pack, acolyteEquipment } = refs;
  const weapon = (id: string, name: string, description: string, price: number, weightPounds: number, proficiency: "simple" | "martial", attackType: "melee" | "ranged", damageType: "bludgeoning" | "piercing" | "slashing", sides: 4 | 6 | 8 | 10 | 12, properties: unknown[]) => ({
    reference: ref("item", `srd-5.1:item:${id}`), name, description, tags: ["srd-5.1", "equipment"],
    mechanics: { category: "weapon", stackable: false, slot: "hand", price: { currency, amount: price }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds, equipmentProfile: { kind: "weapon", proficiency, attackType, damage: { type: damageType, die: { count: 1, sides } }, properties } } },
  });
  const armor = (id: string, name: string, description: string, price: number, weightPounds: number, category: "light" | "medium" | "heavy", baseArmorClass: number, dexterity: unknown, strengthRequirement: number | null, stealthDisadvantage: boolean) => ({
    reference: ref("item", `srd-5.1:item:${id}`), name, description, tags: ["srd-5.1", "equipment"],
    mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: price }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds, equipmentProfile: { kind: "armor", category, baseArmorClass, dexterity, strengthRequirement, stealthDisadvantage, shieldBonus: 0 } } },
  });
  return [
    { reference: sword, name: "Longsword", description: "A martial melee weapon dealing 1d8 slashing damage, or 1d10 when wielded with two hands.", tags: ["srd-5.1"], mechanics: { category: "weapon", stackable: false, slot: "hand", price: { currency, amount: 15 }, effects: [{ type: "damage", damageType: "physical", dice: { count: 1, sides: 8, modifier: 0 } }], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 3, equipmentProfile: { kind: "weapon", proficiency: "martial", attackType: "melee", damage: { type: "slashing", die: { count: 1, sides: 8 } }, properties: [{ property: "versatile", damageDie: { count: 1, sides: 10 } }] } } } },
    { reference: ref("item", "srd-5.1:item:leather-armor"), name: "Leather Armor", description: "Light armor with base AC 11 and full Dexterity contribution.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 10 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 10, equipmentProfile: { kind: "armor", category: "light", baseArmorClass: 11, dexterity: { policy: "full" }, strengthRequirement: null, stealthDisadvantage: false, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:chain-shirt"), name: "Chain Shirt", description: "Medium armor with base AC 13 and Dexterity contribution capped at +2.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 50 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 20, equipmentProfile: { kind: "armor", category: "medium", baseArmorClass: 13, dexterity: { policy: "capped", maxBonus: 2 }, strengthRequirement: null, stealthDisadvantage: false, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:chain-mail"), name: "Chain Mail", description: "Heavy armor with AC 16, Strength 13 requirement, and stealth disadvantage.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 75 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 55, equipmentProfile: { kind: "armor", category: "heavy", baseArmorClass: 16, dexterity: { policy: "none" }, strengthRequirement: 13, stealthDisadvantage: true, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:hide-armor"), name: "Hide Armor", description: "Medium armor with AC 12 and Dexterity capped at +2.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 10 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 12, equipmentProfile: { kind: "armor", category: "medium", baseArmorClass: 12, dexterity: { policy: "capped", maxBonus: 2 }, strengthRequirement: null, stealthDisadvantage: false, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:scale-mail"), name: "Scale Mail", description: "Medium armor with AC 14, Dexterity capped at +2, and stealth disadvantage.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 50 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 45, equipmentProfile: { kind: "armor", category: "medium", baseArmorClass: 14, dexterity: { policy: "capped", maxBonus: 2 }, strengthRequirement: null, stealthDisadvantage: true, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:breastplate"), name: "Breastplate", description: "Medium armor with AC 14 and Dexterity capped at +2.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 400 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 20, equipmentProfile: { kind: "armor", category: "medium", baseArmorClass: 14, dexterity: { policy: "capped", maxBonus: 2 }, strengthRequirement: null, stealthDisadvantage: false, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:plate"), name: "Plate", description: "Heavy armor with AC 18, Strength 15 requirement, and stealth disadvantage.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "body", price: { currency, amount: 1500 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 65, equipmentProfile: { kind: "armor", category: "heavy", baseArmorClass: 18, dexterity: { policy: "none" }, strengthRequirement: 15, stealthDisadvantage: true, shieldBonus: 0 } } } },
    { reference: ref("item", "srd-5.1:item:shield"), name: "Shield", description: "A wielded shield granting a +2 armor class bonus.", tags: ["srd-5.1"], mechanics: { category: "armor", stackable: false, slot: "hand", price: { currency, amount: 10 }, effects: [], engineDetails: { rulesEngine: "dnd-5e", weightPounds: 6, equipmentProfile: { kind: "armor", category: "shield", baseArmorClass: null, dexterity: { policy: "none" }, strengthRequirement: null, stealthDisadvantage: false, shieldBonus: 2 } } } },
    { reference: pack, name: "Explorer's Pack", description: "A single bounded starter-gear entry; individual contents are not modeled.", tags: ["srd-5.1"], mechanics: { category: "gear", stackable: false, slot: null, price: { currency, amount: 10 }, effects: [] } },
    { reference: acolyteEquipment, name: "Acolyte Equipment", description: "One grant-only entry representing a holy symbol, prayer book, five sticks of incense, vestments, and common clothes.", tags: ["srd-5.1", "bounded-aggregate", "grant-only"], mechanics: { category: "gear", stackable: false, slot: null, price: { currency, amount: 0 }, effects: [] } },
    weapon("dagger", "Dagger", "A simple finesse and light melee weapon.", 2, 1, "simple", "melee", "piercing", 4, [{ property: "finesse" }, { property: "light" }, { property: "thrown", range: { normalFeet: 20, longFeet: 60 } }]),
    weapon("club", "Club", "A simple light bludgeoning weapon.", 0, 2, "simple", "melee", "bludgeoning", 4, [{ property: "light" }]),
    weapon("handaxe", "Handaxe", "A simple light and thrown slashing weapon.", 5, 2, "simple", "melee", "slashing", 6, [{ property: "light" }, { property: "thrown", range: { normalFeet: 20, longFeet: 60 } }]),
    weapon("mace", "Mace", "A simple bludgeoning weapon.", 5, 4, "simple", "melee", "bludgeoning", 6, []),
    weapon("quarterstaff", "Quarterstaff", "A simple versatile bludgeoning weapon.", 0, 4, "simple", "melee", "bludgeoning", 6, [{ property: "versatile", damageDie: { count: 1, sides: 8 } }]),
    weapon("spear", "Spear", "A simple versatile and thrown piercing weapon.", 1, 3, "simple", "melee", "piercing", 6, [{ property: "thrown", range: { normalFeet: 20, longFeet: 60 } }, { property: "versatile", damageDie: { count: 1, sides: 8 } }]),
    weapon("shortbow", "Shortbow", "A simple ranged piercing weapon.", 25, 2, "simple", "ranged", "piercing", 6, [{ property: "ammunition", range: { normalFeet: 80, longFeet: 320 } }, { property: "two-handed" }]),
    weapon("light-crossbow", "Light Crossbow", "A simple loading ranged piercing weapon.", 25, 5, "simple", "ranged", "piercing", 8, [{ property: "ammunition", range: { normalFeet: 80, longFeet: 320 } }, { property: "loading" }, { property: "two-handed" }]),
    weapon("rapier", "Rapier", "A martial finesse piercing weapon.", 25, 2, "martial", "melee", "piercing", 8, [{ property: "finesse" }]),
    weapon("battleaxe", "Battleaxe", "A martial versatile slashing weapon.", 10, 4, "martial", "melee", "slashing", 8, [{ property: "versatile", damageDie: { count: 1, sides: 10 } }]),
    weapon("greatsword", "Greatsword", "A martial heavy two-handed slashing weapon.", 50, 6, "martial", "melee", "slashing", 6, [{ property: "heavy" }, { property: "two-handed" }]),
    armor("padded-armor", "Padded Armor", "Light armor with base AC 11 and stealth disadvantage.", 5, 8, "light", 11, { policy: "full" }, null, true),
    armor("studded-leather-armor", "Studded Leather Armor", "Light armor with base AC 12 and full Dexterity contribution.", 45, 13, "light", 12, { policy: "full" }, null, false),
    armor("splint", "Splint", "Heavy armor with AC 17, Strength 15 requirement, and stealth disadvantage.", 200, 60, "heavy", 17, { policy: "none" }, 15, true),
    armor("ring-mail", "Ring Mail", "Heavy armor with AC 14, Strength 13 requirement, and stealth disadvantage.", 30, 40, "heavy", 14, { policy: "none" }, 13, true),
  ];
}
