import type { StarterReferences } from "./references.js";

export function buildRaces(refs: StarterReferences) {
  const { ref } = refs;
  return [
    { reference: ref("race", "srd-5.1:race:human"), name: "Human", description: "A level-one development ancestry with a +1 increase to each ability score.", tags: ["srd-5.1"], mechanics: { size: "Medium", speed: 30, attributeBonuses: { strength: 1, dexterity: 1, constitution: 1, intelligence: 1, wisdom: 1, charisma: 1 }, abilityRefs: [], languages: ["Common", "one language of choice"], proficiencies: [], damageResistances: [], senses: [] } },
    { reference: ref("race", "srd-5.1:race:dwarf"), name: "Dwarf", description: "A sturdy SRD ancestry with Constitution training and resilient stonecraft traditions.", tags: ["srd-5.1", "metadata-only"], mechanics: { size: "Medium", speed: 25, attributeBonuses: { constitution: 2 }, abilityRefs: [refs.dwarfResilience, refs.dwarfStonecunning], languages: ["Common", "Dwarvish"], proficiencies: ["battleaxe", "handaxe", "light hammer", "warhammer"], damageResistances: ["poison"], senses: [{ kind: "darkvision", rangeFeet: 60 }] } },
    { reference: ref("race", "srd-5.1:race:elf"), name: "Elf", description: "An SRD ancestry with Dexterity training, keen senses, and fey heritage.", tags: ["srd-5.1", "metadata-only"], mechanics: { size: "Medium", speed: 30, attributeBonuses: { dexterity: 2 }, abilityRefs: [refs.elfDarkvision, refs.elfKeenSenses], languages: ["Common", "Elvish"], proficiencies: ["Perception"], damageResistances: [], senses: [{ kind: "darkvision", rangeFeet: 60 }] } },
    { reference: ref("race", "srd-5.1:race:halfling"), name: "Halfling", description: "A nimble SRD ancestry known for luck and courage.", tags: ["srd-5.1", "metadata-only"], mechanics: { size: "Small", speed: 25, attributeBonuses: { dexterity: 2 }, abilityRefs: [refs.halflingLucky, refs.halflingBrave], languages: ["Common", "Halfling"], proficiencies: [], damageResistances: [], senses: [] } },
    { reference: ref("race", "srd-5.1:race:dragonborn"), name: "Dragonborn", description: "A draconic SRD ancestry with Strength, Charisma, ancestry, and breath-weapon metadata.", tags: ["srd-5.1", "metadata-only"], mechanics: { size: "Medium", speed: 30, attributeBonuses: { strength: 2, charisma: 1 }, abilityRefs: [refs.dragonbornAncestry, refs.dragonbornBreath], languages: ["Common", "Draconic"], proficiencies: [], damageResistances: [], senses: [] } },
    { reference: ref("race", "srd-5.1:race:gnome"), name: "Gnome", description: "A small SRD ancestry with Intelligence training and innate cunning.", tags: ["srd-5.1", "metadata-only"], mechanics: { size: "Small", speed: 25, attributeBonuses: { intelligence: 2 }, abilityRefs: [refs.gnomeCunning], languages: ["Common", "Gnomish"], proficiencies: [], damageResistances: [], senses: [{ kind: "darkvision", rangeFeet: 60 }] } },
    { reference: ref("race", "srd-5.1:race:half-orc"), name: "Half-Orc", description: "An SRD ancestry with Strength, Constitution, endurance, and savage-attack metadata.", tags: ["srd-5.1", "metadata-only"], mechanics: { size: "Medium", speed: 30, attributeBonuses: { strength: 2, constitution: 1 }, abilityRefs: [refs.halfOrcEndurance, refs.halfOrcSavage], languages: ["Common", "Orc"], proficiencies: ["Intimidation"], damageResistances: [], senses: [{ kind: "darkvision", rangeFeet: 60 }] } },
    { reference: ref("race", "srd-5.1:race:half-elf"), name: "Half-Elf", description: "A versatile SRD ancestry with Charisma training, fey heritage, darkvision, and two chosen skill proficiencies. The SRD's two floating +1 ability increases and two skill choices are recorded as bounded metadata because this closed catalog cannot accept character-selected bonuses.", tags: ["srd-5.1", "metadata-only", "choice:ability-plus-1-two", "choice:two-skills"], mechanics: { size: "Medium", speed: 30, attributeBonuses: { charisma: 2 }, abilityRefs: [ref("ability", "srd-5.1:ability:half-elf-fey-ancestry"), ref("ability", "srd-5.1:ability:half-elf-skill-versatility"), ref("ability", "srd-5.1:ability:half-elf-darkvision")], languages: ["Common", "Elvish", "one language of choice"], proficiencies: [], damageResistances: [], senses: [{ kind: "darkvision", rangeFeet: 60 }] } },
    { reference: ref("race", "srd-5.1:race:tiefling"), name: "Tiefling", description: "An infernal SRD ancestry with Charisma and Intelligence training, darkvision, fire resistance, and Infernal Legacy spell traits recorded as bounded metadata.", tags: ["srd-5.1", "metadata-only"], mechanics: { size: "Medium", speed: 30, attributeBonuses: { charisma: 2, intelligence: 1 }, abilityRefs: [ref("ability", "srd-5.1:ability:tiefling-hellish-resistance"), ref("ability", "srd-5.1:ability:tiefling-infernal-legacy"), ref("ability", "srd-5.1:ability:tiefling-darkvision")], languages: ["Common", "Infernal"], proficiencies: [], damageResistances: ["fire"], senses: [{ kind: "darkvision", rangeFeet: 60 }] } },
  ];
}
