import type { StarterReferences } from "./references.js";

export function buildSpells(refs: StarterReferences) {
  const { light, bless, cureWounds, wizardCantrip, rayOfFrost, mageHand, sacredFlame, magicMissile, shield, healingWord, guidingBolt, falseLife } = refs;
  return [
    { reference: light, name: "Light", description: "Catalog coverage marker only; casting and spell effects are not implemented.", tags: ["srd-5.1", "unsupported-runtime"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 0, target: "single", duration: "1-hour", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: true, materialDescription: "a firefly or phosphorescent moss" }, effects: [] } },
    { reference: bless, name: "Bless", description: "A level-one Cleric spell. Creatures in the area gain a +1 bonus to attack rolls and saving throws while the caster concentrates.", tags: ["srd-5.1", "cleric-1", "spellcasting"], mechanics: { level: 1, school: "enchantment", castingTime: "action", actionCost: "action", range: 30, target: "area", duration: "concentration", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a sprinkling of holy water" }, effects: [{ type: "modifier", statistic: "attack", amount: 1, duration: "encounter" }] } },
    { reference: cureWounds, name: "Cure Wounds", description: "A level-one Cleric spell that restores 1d8 hit points to a touched ally.", tags: ["srd-5.1", "cleric-1", "spellcasting"], mechanics: { level: 1, school: "evocation", castingTime: "action", actionCost: "action", range: 5, target: "ally", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "healing", dice: { count: 1, sides: 8, modifier: 0 } }] } },
    { reference: wizardCantrip, name: "Fire Bolt", description: "A level-zero Wizard cantrip reference; casting and damage are not executable in this bounded pack.", tags: ["srd-5.1", "wizard-1", "unsupported-runtime"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 120, target: "enemy", duration: "instantaneous", attackType: "ranged", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "damage", damageType: "fire", dice: { count: 1, sides: 10, modifier: 0 } }] } },
    { reference: rayOfFrost, name: "Ray of Frost", description: "A level-zero Wizard cantrip reference; casting and slowing are not executable in this bounded pack.", tags: ["srd-5.1", "wizard-1", "unsupported-runtime"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "instantaneous", attackType: "ranged", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "damage", damageType: "frost", dice: { count: 1, sides: 8, modifier: 0 } }] } },
    { reference: mageHand, name: "Mage Hand", description: "A level-zero Wizard cantrip reference; its interaction and carrying rules are metadata-only.", tags: ["srd-5.1", "cantrip", "metadata-only"], mechanics: { level: 0, school: "conjuration", castingTime: "action", actionCost: "action", range: 30, target: "single", duration: "1-minute", attackType: "none", saveType: "none", concentration: true, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a bit of fleece" }, effects: [] } },
    { reference: sacredFlame, name: "Sacred Flame", description: "A level-zero Cleric cantrip reference; saving throw and radiant damage execution are unsupported.", tags: ["srd-5.1", "cantrip", "metadata-only"], mechanics: { level: 0, school: "evocation", castingTime: "action", actionCost: "action", range: 60, target: "enemy", duration: "instantaneous", attackType: "none", saveType: "dexterity", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "damage", damageType: "radiant", dice: { count: 1, sides: 8, modifier: 0 } }] } },
    { reference: magicMissile, name: "Magic Missile", description: "A first-level Wizard spell with automatic-hit force darts, authoritative range, components, slot use, and replay-safe execution.", tags: ["srd-5.1", "level-1", "spellcasting"], mechanics: { level: 1, school: "evocation", castingTime: "action", actionCost: "action", range: 120, target: "enemy", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a tiny ball of bat guano and sulfur" }, effects: [{ type: "damage", damageType: "force", dice: { count: 3, sides: 4, modifier: 3 } }] } },
    { reference: shield, name: "Shield", description: "A first-level Wizard reaction spell that grants the caster a +5 bonus to armor class until the start of their next turn.", tags: ["srd-5.1", "level-1", "spellcasting"], mechanics: { level: 1, school: "abjuration", castingTime: "reaction", actionCost: "reaction", range: 0, target: "self", duration: "1-round", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "modifier", statistic: "defense", amount: 5, duration: "round" }] } },
    { reference: healingWord, name: "Healing Word", description: "A first-level Cleric healing spell with authoritative 60-foot range, ally targeting, slot use, and replay-safe execution.", tags: ["srd-5.1", "level-1", "spellcasting"], mechanics: { level: 1, school: "evocation", castingTime: "bonus-action", actionCost: "bonus-action", range: 60, target: "ally", duration: "instantaneous", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: false, material: false }, effects: [{ type: "healing", dice: { count: 1, sides: 4, modifier: 0 } }] } },
    { reference: guidingBolt, name: "Guiding Bolt", description: "A first-level Cleric spell reference with exact 120-foot range; radiant damage and advantage rider are unsupported.", tags: ["srd-5.1", "level-1", "metadata-only"], mechanics: { level: 1, school: "evocation", castingTime: "action", actionCost: "action", range: 120, target: "enemy", duration: "instantaneous", attackType: "ranged", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: false }, effects: [{ type: "damage", damageType: "radiant", dice: { count: 4, sides: 6, modifier: 0 } }] } },
    { reference: falseLife, name: "False Life", description: "A first-level Wizard spell that grants the caster 1d4+4 temporary hit points with replay-safe execution.", tags: ["srd-5.1", "level-1", "spellcasting"], mechanics: { level: 1, school: "necromancy", castingTime: "action", actionCost: "action", range: 0, target: "self", duration: "1-hour", attackType: "none", saveType: "none", concentration: false, ritual: false, components: { verbal: true, somatic: true, material: true, materialDescription: "a small amount of alcohol or distilled spirits" }, effects: [{ type: "temporary-hit-points", dice: { count: 1, sides: 4, modifier: 4 } }] } },
  ];
}
