import { FormEvent, useEffect, useState } from "react";
import { ApiError, Character, LoreEntry, LoreInput, createLore, deleteLore, listLore, updateLore } from "../api";

const blank: LoreInput = { characterIds: [], keys: [], content: "", enabled: true, insertionOrder: 100 };

export function LoreManager({ characters, onClose }: { characters: Character[]; onClose: () => void }) {
  const [entries, setEntries] = useState<LoreEntry[]>([]); const [editing, setEditing] = useState<LoreEntry | null>(null); const [form, setForm] = useState<LoreInput>(blank); const [keysText, setKeysText] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function reload() { try { setEntries((await listLore()).lore); setError(null); } catch (err) { setError(err instanceof ApiError ? err.message : "Could not load lore."); } }
  useEffect(() => { void reload(); }, []);
  function begin(entry?: LoreEntry) { setEditing(entry ?? null); setForm(entry ? { characterIds: entry.characterIds, keys: entry.keys, content: entry.content, enabled: entry.enabled, insertionOrder: entry.insertionOrder } : blank); setKeysText(entry?.keys.join(", ") ?? ""); }
  async function save(event: FormEvent) { event.preventDefault(); if (!form.content.trim()) return; setBusy(true); try { const input = { ...form, content: form.content.trim(), keys: keysText.split(",").map((key) => key.trim()).filter(Boolean) }; if (editing) await updateLore(editing.id, input); else await createLore(input); begin(); await reload(); } catch (err) { setError(err instanceof ApiError ? err.message : "Could not save lore."); } finally { setBusy(false); } }
  async function remove(id: string) { if (!confirm("Delete this lore entry?")) return; try { await deleteLore(id); await reload(); } catch (err) { setError(err instanceof ApiError ? err.message : "Could not delete lore."); } }
  return <section className="card manager-card lore-manager"><div className="section-heading-row"><div><p className="eyebrow">WORLD LORE</p><h1 className="title">Lore library</h1></div><button className="ghost" onClick={onClose}>Back to library</button></div>
    <p className="subtitle">Global entries apply everywhere. Scoped entries apply when any selected character joins a session.</p>
    <form className="form lore-editor" onSubmit={save}><h2>{editing ? "Edit lore" : "New lore entry"}</h2><label className="field"><span>Trigger keys (comma-separated; blank = always available)</span><input value={keysText} onChange={(e) => setKeysText(e.target.value)} placeholder="moon gate, old harbor" /></label><label className="field"><span>Content</span><textarea value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} rows={4} placeholder="World details, places, rules, or shared history…" /></label><div className="lore-options"><label className="field"><span>Insertion order</span><input type="number" value={form.insertionOrder} onChange={(e) => setForm({ ...form, insertionOrder: Number(e.target.value) })} /></label><label className="checkbox"><input type="checkbox" checked={form.enabled} onChange={(e) => setForm({ ...form, enabled: e.target.checked })} /><span>Enabled</span></label></div><fieldset className="scope-picker"><legend>Character scope <span>({form.characterIds.length === 0 ? "global" : `${form.characterIds.length} selected`})</span></legend><label className="checkbox"><input type="checkbox" checked={form.characterIds.length === 0} onChange={() => setForm({ ...form, characterIds: [] })} /><span>Global — all characters</span></label>{characters.map((character) => <label className="checkbox" key={character.id}><input type="checkbox" checked={form.characterIds.includes(character.id)} onChange={(e) => setForm({ ...form, characterIds: e.target.checked ? [...form.characterIds, character.id] : form.characterIds.filter((id) => id !== character.id) })} /><span>{character.name}</span></label>)}</fieldset>{error && <p className="error" role="alert">{error}</p>}<div className="button-row"><button className="primary" disabled={busy || !form.content.trim()}>{busy ? "Saving…" : editing ? "Save lore" : "Add lore"}</button>{editing && <button type="button" className="ghost" onClick={() => begin()}>Cancel edit</button>}</div></form>
    <div className="manager-list lore-list">{entries.length === 0 && <p className="empty-state">No lore yet.</p>}{entries.map((entry) => <article className={`manager-item ${!entry.enabled ? "is-muted" : ""}`} key={entry.id}><div className="manager-item-head"><span className={`status-pill ${entry.enabled ? "active" : "forgotten"}`}>{entry.enabled ? "enabled" : "disabled"}</span><span className="meta-text">order {entry.insertionOrder} · {entry.characterIds.length ? entry.characterIds.map((id) => characters.find((c) => c.id === id)?.name ?? "Missing character").join(", ") : "global"}</span></div><p>{entry.content}</p><p className="meta-text">Keys: {entry.keys.length ? entry.keys.join(", ") : "always"}</p><div className="item-actions"><button className="ghost small" onClick={() => begin(entry)}>Edit</button><button className="ghost small" onClick={() => void updateLore(entry.id, { enabled: !entry.enabled }).then(reload).catch((err) => setError(err instanceof ApiError ? err.message : "Could not update lore."))}>{entry.enabled ? "Disable" : "Enable"}</button><button className="danger subtle small" onClick={() => void remove(entry.id)}>Delete</button></div></article>)}</div>
  </section>;
}
